### ISSUE TITLE
Core: severe performance problem while reading sdf file

### ISSUE THREAD

**Issue by iFeofilaktov** [datagrok-ai/public#100]
Attempt to load local file with sdf format leads to gatagrok performing unknown procedure on it. Supposedly gatagrok tries to read it as some sort of html document. 
![image](https://user-images.githubusercontent.com/89513337/131592401-77997d70-8f74-44aa-ab82-1d492c687198.png)

**Comment by skalkin** [comment]
Looks like this has been fixed a while ago
