### ISSUE TITLE
Charts: Trellis plot: category slider width is suboptimal sometimes when rendering molecules

### ISSUE THREAD

**Issue by sasha-tsepilova** [datagrok-ai/public#101]
When there aren't enough items to show the scrollbar, their preview on the sidebar becomes small.
![image](https://user-images.githubusercontent.com/75687119/131676238-6541aade-e685-4c0a-a953-e1ee21b64ffe.png)
![image](https://user-images.githubusercontent.com/75687119/131676255-bfd0b8bb-927c-4981-95a0-98efaa7a1786.png)

**Comment by skalkin** [comment]
Fixed it.
