### ISSUE TITLE
#1028: Test action doesn't work for shared subfolders within a file share

### ISSUE THREAD

**Issue by lbankurova** [datagrok-ai/public#1028]
@alex-aprm 
**Test** action fails for shared subfolders with the following error message: "[shared folder name]": failed to connect: FileSystemException: Directory listing failed, path = '_____________/' (OS Error: No such file or directory, errno = 2))

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14826

**Comment by KiK0S** [comment]
Just seems to work for me now.. Probably was fixed earlier but not mirrored.
