### ISSUE TITLE
#1036: Downloaded files doubled after Extract Selected Rows

### ISSUE THREAD

**Issue by tanas80** [datagrok-ai/public#1036]
Steps to reproduce:

- Select a few rows in opened TableView
- In the top menu, click Select / Extract Selected Rows (the second TableView will be created)
- In the top menu, click Download / As CSV
- Two identical files simultaneously will be downloaded (or blocked by the browser by default)

![error-extract-selected-rows-download-as-csv](https://user-images.githubusercontent.com/3798326/190386890-683a2cc9-98c3-486c-a920-a160a44a0708.gif)

**Comment by skalkin** [comment]
@tanas80 , @osakhniuk  I can't reproduce it - can you?

**Comment by osakhniuk** [comment]
@skalkin , this is reproducible assuming the table was opened from local storage by a drag-and-drop

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14828

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

Ok on release 1.19. download 1 file
