### ISSUE TITLE
BsV: enable mol* at the platform molstar

### ISSUE THREAD

**Issue by StLeonidas** [datagrok-ai/public#1052]
- [ ] create JsViewer derived wrapper for molstar viewer
- [ ] highlight the part of protein/single molecule
- [ ] switch molecule representation (cartoon, balls and sticks)

https://www.npmjs.com/package/molstar
https://www.npmjs.com/package/@rcsb/rcsb-molstar

npmjs @rcsb packages (saguaro)
https://www.npmjs.com/search?q=%40rcsb

RCSB PDB stands for Research Collaboratory for Structural Bioinformatics PDB

Sample data PDB file [3BJ1.pdb](https://files.rcsb.org/view/3BJ1.pdb)

**Comment by tanas80** [comment]
![Image](https://user-images.githubusercontent.com/3798326/199954758-186c3bb8-cf69-4a0f-a4ec-9413b9c3c251.png)
