### ISSUE TITLE
Bio: Sequence Renderer: different rendering modes

### ISSUE THREAD

**Issue by skalkin** [datagrok-ai/public#1057]
Similarly to Chem, let's provide "Render" panel ("Chem" in Chem) that would appear in context panel when user clicks on a column header. The following options should be editable there:

- [x] "Color code" checkbox
- [x] Monomer width: [`short` / `long`]. In `short` mode, only the first character should be visible, followed by `..` if there are more characters
- [x] Reference sequence text box: when defined, all sequences should be rendered in the "diff" mode to the specified sequence
- [x] "Compare with current" check box: when on, all sequences get rendered in the "diff" mode, with the current sequence treated as the reference sequence. This should be on by default.

**Comment by simpleprofi** [comment]
Can you describe the behavior in diff mode in more detail, are there any examples of this rendering?

**Comment by skalkin** [comment]
I think we already have the "Macromolecule Difference" renderer, the same (or similar) mechanism should be used (similar monomers should be semi-transparent, different ones opaque).

Specifying the reference sequence should set corresponding column's 'referenceSequence` tag. Then, the renderer should check whether this tag exists, and if it does, then the sequence should be rendered in the "difference" mode.

**Comment by skalkin** [comment]
> What behavior expected from WebLogo with the color Code On/ Off parameter?

We are not talking about WebLogo, this is all in-grid rendering

**Comment by skalkin** [comment]
Also, note that I've added another feature to the list:

[ ] "Compare with current" check box: when on, all sequences get rendered in the "diff" mode, with the current sequence treated as the reference sequence. This should be on by default.
