### ISSUE TITLE
A way to indicate current viewer

### ISSUE THREAD

**Issue by dionissqq** [datagrok-ai/public#1063]
Implement viewer visual indication for the Context Panel

**Comment by ahadzhanian** [comment]
The **Gear** icon remains visible to the viewer that has the **Context Panel** open.
DG 1.17.0

![Image](https://github.com/datagrok-ai/public/assets/111368431/eff07a32-3e11-4b26-9ed6-e5d8089e691b)

**Comment by katerina-stepanova** [comment]
v1.17.3

Gear icon is not highlighted if properties panel was opened using context menu (instead of clicking the icon itself).
![2023-11-13_18-09-46 (1)](https://github.com/datagrok-ai/public/assets/15780643/ca5bf6c5-3350-4a04-83cb-ebd57ba73c88)

**Comment by ahadzhanian** [comment]
This feature works for all viewers except for the grid
1.17.4
