### ISSUE TITLE
Line chart is not updated on selecting/deselecting rows when Row source = Selected

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1075]
v 1.5.1, 1.6.11
**Steps to reproduce:**
1. Open a table, e.g. SPGI
2. Add a line chart
3. Configure line chart's Row source = Selected
4. Select/deselect some rows in the table

**Expected results:** Line chart is updated when rows selection is changed.
**Actual results:** When Row source is changed from default 'Filtered' to 'Selected', line chart is updated according to current selection. When rows are selected/deselected after that, line chart is no longer updated.
Issue does not depend on how exactly rows are selected/deselected (individual row selection, shift-drag, using bar chart to select rows etc.)
![2022-09-28_16-31-47 (1)](https://user-images.githubusercontent.com/15780643/192792061-6fdea6b1-aaf2-42cc-9239-42be549d9fc2.gif)

**Comment by dionissqq** [comment]
Fixen in v1.6.12
