### ISSUE TITLE
Grid: Popup Dialog from hamburger menu stays after the column is deleted

### ISSUE THREAD

**Issue by dgosi** [datagrok-ai/public#1083]
After removing a column using Hamburger menu's popup dialog, the dialog is not closed and subsequent clicking on any of the links in the "Actions" section produces exception. Separate issue: initially clicking on "the Rename" column link opens a second dialog which is hidden behind the primary one. The solution to both issues is to close the primary dialog after clicking on any of the "Actions" links.

![hambbug](https://user-images.githubusercontent.com/96437636/193319100-0a5a045b-a1c2-4e3d-8d93-ce6b9ee15008.png)

**Comment by skalkin** [comment]
Fixed in Datagrok 1.8.3
