### ISSUE TITLE
#1092: Multiple Issues with Conditional Color Dialog

### ISSUE THREAD

**Issue by dgosi** [datagrok-ai/public#1092]
There are multiple issues with Conditional Color dialog (see the attached image).
1. Editing ranges doesn't update the  Grid viewer on the fly
2. Choosing a color from the Color picker doesn't update the Grid viewer on the fly
3. Clicking on the same or different color buttons opens multiple copies of color editors. Instead the should be just one instance of editor shared across all the numerical ranges
4. Color editor doesn't have a title to identify the numerical range it belongs to
5. Closing the main Conditional Color Dialog doesn't close the opened color editors
6. The color editor child dialog should have a "Close" titled button instead of "Cancel"

![conditional_color_bugs](https://user-images.githubusercontent.com/96437636/193640549-3428d3aa-b548-4c21-a4ca-29b6bf97363c.png)

**Comment by katerina-stepanova** [comment]
v1.13.10
Following points are still reproduced:
- (3) Clicking on the same or different color buttons opens multiple copies of color editors. Instead the should be just one instance of editor shared across all the numerical ranges
- (4) Color editor doesn't have a title to identify the numerical range it belongs to
- (5) Closing the main Conditional Color Dialog doesn't close the opened color editors

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14582

**Comment by ahadzhanian** [comment]
DG1.19.0
