### ISSUE TITLE
Filters on/off checkboxes state is inconsistent in specific cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1103]
DG 1.6.11 with #953 hotfix

**Case 1: after layout with disabled filters was applied**
1. Open a table
2. Open filters
3. Set-up some filtering
4. Disable all filters (uncheck 'Turn filters on/off')
5. Save layout
6. Re-apply layout
7. Enable all filters (check 'Turn filters on/off')
8. See 'Turn on/off' checkboxes for individual filters
**Expected:** 'Turn on/off' checkboxes for individual filters are checked.
**Actual:** filters are active, but  'Turn on/off' checkboxes for individual filters are unchecked:
<img width="251" alt="image" src="https://user-images.githubusercontent.com/15780643/194582002-b85ddf25-ae68-4548-b952-84e64038fc70.png">

**Case 2: adding new filter column when all filters are disabled**
1. Open a table
2. Open filters
3. Disable all filters (uncheck 'Turn filters on/off')
4. Add one more column to filters
5. See 'Turn filters on/off' checkbox
**Expected:** 'Turn filters on/off' checkbox status should be consistent with filters.
**Actual:** Newly added filter is active, but 'Turn filters on/off' marking 'disabled' state of all filters is unchecked:
<img width="252" alt="image" src="https://user-images.githubusercontent.com/15780643/194582688-6e9f0635-943e-4f30-9002-a6e7466235dd.png">

**Comment by dionissqq** [comment]
Fixed in v1.7.1
