### ISSUE TITLE
Viewers: legend cannot be resized again after it was resized once if legend contains long values

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1110]
v.1.6.12
**Steps to reproduce:**
1. Open a table
2. Configure a viewer so that legend is displayed, and some items in it are **partially hidden** e.g.
<img width="499" alt="image" src="https://user-images.githubusercontent.com/15780643/195353094-5da8dd9b-4c7b-439c-9e15-c3c24fed2f12.png">

3. Make legend wider so that values are fully visible
4. Change legend width again

**Expected results:** Legend should be resizable after it was resized once.
**Actual results:** Legend cannot be resized for the 2nd time. Issue can be reproduced for any viewer with resizable legend (scatter plot, bar chart etc.)

**Comment by dionissqq** [comment]
Fixed in v1.8.1
