### ISSUE TITLE
Peptides: incorrect multiple selection behavior

### ISSUE THREAD

**Issue by vdyma** [datagrok-ai/public#1114]
Clicking a cell in SAR viewer should initialize selection with only monomer-position that was clicked and remove any other and add a monomer-position to selection if clicked with shift. However it doesn't clear selection when clicked without shift

**Comment by skalkin** [comment]
@vdyma , any updates?

**Comment by vdyma** [comment]
Fixed in https://github.com/datagrok-ai/public/commit/032d08e124c0e7e58a0f3aa0e1ec7856da4a881c
