### ISSUE TITLE
JS API: add hints to UI methods

### ISSUE THREAD

**Issue by onuf** [datagrok-ai/public#1124]
```ts
export namespace hints {
  export function addHint(el: HTMLElement): HTMLElement {}
  export function addTextHint(el: HTMLElement, text: string): HTMLElement {}
  export function remove(el: HTMLElement): HTMLElement {}
}
```

**Comment by skalkin** [comment]
```
export function addHint(el: HTMLElement): HTMLElement {}
```

I don't get it, what is this function supposed to do?

**Comment by onuf** [comment]
@skalkin we discussed these methods a few weeks ago. The purpose is to attach interactive hints, close to what happens in tutorials, to elements. Application authors can then use these methods in the app code to introduce a new feature to the user, etc.

**Comment by skalkin** [comment]
Right, but I still can't figure out what this function is supposed to do.

```export function addHint(el: HTMLElement): HTMLElement {}
```

**Comment by onuf** [comment]
Updated the wizard design based on the following mock-ups:
![image](https://user-images.githubusercontent.com/56073962/222446540-1d81fd03-5a2e-4288-b2fd-986496968ca2.png)
![image](https://user-images.githubusercontent.com/56073962/222446576-8c4edc63-2876-4d86-a9e3-21cade02512d.png)
