### ISSUE TITLE
Order and hide columns dialog isues

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1128]
**Case 1: Move to the top/bottom**
1. Open 'Order or hide' columns dialog
2. Search for some columns > filtered list of columns is shown
3. Select some columns and click 'Move to the top' or 'Move to the bottom'
**Expected results:** column is moved to the top/bottom of all columns.
**Actual results:** column is moved to the top/bottom of the filtered list of columns which means it ends up somewhere in the middle of the table.

**Case 2: inconsistency between dialog and table**
1. Open 'Order or hide' columns dialog
2. Select some column and click 'Move to the top' or 'Move to the bottom'
3. Search for some columns > filtered list of columns is shown
4. Clear the search
5. Compare order of columns in the table and in the dialog
**Expected results:** columns are shown in the same order in the table and in the dialog.
**Actual results:** different order of columns in the table and in the dialog:
![image](https://user-images.githubusercontent.com/15780643/196478023-79ca7ad2-e6b0-449e-a04b-0673d59e41b5.png)

**Case 3: no scrolling while dragging**
1. Open 'Order or hide' columns dialog
2. Select some columns
3. Drag columns up or down
**Expected results:** list of columns in the dialog is scrolled automatically when dragged columns reach top or bottom of the part of the list currently in view.
**Actual results:** dialog is not scrolled automatically during dragging selected columns:
![2022-10-11_16-10-31 (1)](https://user-images.githubusercontent.com/15780643/196478636-527f6ee4-24f4-483d-9d36-36f58027f4cc.gif)

**Comment by JianmeiFan** [comment]
**Case 4: inconsistency of selection indication**
1. Open 'Order or hide' columns dialog
2. Select some columns at the bottom
**Expected results**: The right side should has yellow selection indication. 
**Actual results**: Below certain columns at the bottom, yellow selection indication doesn't show any more
3. Select some columns and move up or down
**Expected results**: The right side yellow selection indication should reflect current selection columns' position. 
**Actual results**: It doesn't change. Only when I close this dialog and reopen it, it will reflect the real position.

It seems another bug similar to **Case 2**. If I close this dialog and reopen, then it is OK. Sync is off a bit.

https://user-images.githubusercontent.com/100243033/197582131-5ebbe329-a45a-4cb2-bcc3-0f25da8f55e1.mp4

**Comment by onuf** [comment]
Relates to https://github.com/datagrok-ai/public/issues/1157

**Comment by katerina-stepanova** [comment]
DG 1.8.3
There are remaining issues with order/hide columns dialog:
**1. Column position in dialog and table inconsistency:**
When column is moved up/down/top/bottom using the buttons on the right, column's position is not changed in the dialog, but is changed in the table, which results in inconsistency:
<img width="852" alt="image" src="https://user-images.githubusercontent.com/15780643/200867795-5de78b61-94c1-497a-b8e3-3aa1816231c1.png">
Note: column position in the dialog is synced with table if 'show or hide all/selected' checkbox is toggled.

**2. Column position is changed unexpectedly after unchecking and checking it in some case.** (probably a consequence of case 1)
- Open the dialog
- Move some column up or down > column position is changed in the table, but not in the dialog (case 1)
- Uncheck this column
- Check it again
Expected: column position in the table does not change when it is checked/unchecked.
Actual: column position is reverted to a state before it was moved.

**3. Wrong column is checked/unchecked in specific case:** (possibly a consequence of case 1)
- Open the dialog
- Search for columns, so that there are only a few left
- Move one of the columns up or down using buttons on the right
- Check/uncheck one of the columns
- Check/uncheck one more column
Expected: the same column checked/unchecked in the dialog should be shown/hidden in the table.
Actual: wrong column is shown/hidden:
![2022-11-09_18-29-03 (1)](https://user-images.githubusercontent.com/15780643/200871762-2c535970-83ab-499e-806c-4e23057b7a64.gif)

**Comment by dionissqq** [comment]
Fixed in v1.8.4
