### ISSUE TITLE
Trellis Plot > Scatter Plot Pack and Zoom by the filter is not functioning

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1135]
**Steps to reproduce:**
1. Open a table, e.g. SPGI
2. Open Trellis plot> switch to Scatterplot > Configure axis with any categorical column
3. Properties>select> Misc> Zoom and Filter> choose "pack and zoom by the filter"

**Expected results:**  The categorical axis label should be updated based on a filter.
**Actual results:** The categorical axis label is not packed based on the filter:
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/15780643/196927233-4a4c63b1-a8f7-4d74-a2bd-6f7713d686f8.png">

**Comment by dionissqq** [comment]
We currently do not option for trellis plot to pack categories. The option on the photo is related to scatterplot and packs categories inside scatterplot viewers. Though we will try to implement it in future.

**Comment by skalkin** [comment]
@katerina-stepanova , @DanTkachev , let's discuss it on our next meeting - this one is not trivial at all

**Comment by DanTkachev** [comment]
@skalkin JFYI, this is not a high priority for us - we just noticed an inconsistency in a new functionality which we thought would easy to fix. Please don't spend much time if you see that is something beyond the current implementation. Thanks!
