### ISSUE TITLE
#1139: Bio: monomer works refactoring

### ISSUE THREAD

**Issue by StLeonidas** [datagrok-ai/public#1139]
- [x] export single monomer structures
- [ ] export and calculate color palletes
- [x] export atomic level representations

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14832

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16087
