### ISSUE TITLE
Columns/rows sorting

### ISSUE THREAD

**Issue by StLeonidas** [datagrok-ai/public#1143]
Implement a dialog similar to column ordering to:
- [ ] Allow columns move left, move right, move first, move last. 
- [ ] Add the ability to select highlight several columns and move them all first/last, etc. 
- [ ] Same for rows, up, down, first, last.

**Comment by skalkin** [comment]
@StLeonidas , we already have "order or hide columns" that lets you easily rearrange columns

**Comment by StLeonidas** [comment]
Yes, this feature is present
![Column reordering](https://user-images.githubusercontent.com/57249456/200247293-2c1b119a-2403-4483-8048-95c55442b1d6.gif)
