### ISSUE TITLE
Filter tags set through code are ignored for structure columns

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1146]
**Steps to reproduce:**
1. Create a dataframe containing structure column
2. Set tags on it, so that categorical filter would be used:
.ignore-custom-filter = true
.structure-filter-type = Categorical
3. Open filters and add this structure column to filters

*Code example TBD.*

**Expected results:** filter is categorical for a column with these tags set.
**Actual results:** tags are ignored, filter with molecule sketcher is used.
If tags are set manually through 'Column properties' dialog, filter is categorical as expected.

**Comment by katerina-stepanova** [comment]
The reason was that we're setting .ignore-custom-filter = true value as boolean instead of string.

**Comment by skalkin** [comment]
We should probably throw an error when anything other than the string gets
assigned as a tag value

**Comment by dionissqq** [comment]
Closing as not longer a problem
