### ISSUE TITLE
Tag .color-coding-categorical is missing on a column if default categorical colours are used

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1147]
**Steps to reproduce:**
1. Open a table
2. Apply categorical colouring to some column
3. Go to column properties and see tags

**Expected results:** .color-coding-categorical and .color-coding-type tags are present
**Actual results:** only .color-coding-type is present. Tag .color-coding-categorical is added only if colours are customised.

**Comment by skalkin** [comment]
Is it a bug though?

**Comment by skalkin** [comment]
@onuf will provide a way to retrieve the default palette, in case `.color-coding-categorical` is not specified (this is an optimization, not a bug)

**Comment by onuf** [comment]
Here it is: https://datagrok.ai/js-api/classes/dg.Color#categoricalPalette

**Comment by madmurdok** [comment]
@onuf So, if there is no .color-coding-categorical tag, but .color-coding-type means that we use categorical colors => we can use categoricalPalette for getting default colors?

**Comment by skalkin** [comment]
Closing this issue, please reopen if more assistance is needed
