### ISSUE TITLE
Extended color picker (hex/RGB codes, common/corporative/recent colors)

### ISSUE THREAD

**Issue by DanTkachev** [datagrok-ai/public#1148]
**Color Picker**

Color Picker box appears in a new dialog (this behavior should be consistent for all data types - numeric, string, etc.).

Users can choose from six different color sources:

_**Standard colors: (must)**_
- Blue #73AFF5
- Yellow #FFDF5B
- Red #FF5140
- Green #50AF28
- Gray #D9D9D9

**_Corporate colors: (optional)_**
- See screenshot attached to the ticket

_**Color box (must)**_

_**Eyedropper tool (optional)**_

_**Hex-code entry (must) and RGB entry (optional):**_ 
- Hex code is default. Users can switch to RGB.

_**Recent colors: (must)**_
- Colors selected from either the color box, eyedropper or by hex-code/RGB entry are displayed in a "Recent" section
- Max 6 recent colors (could also be 5 if we go with Standard colors only) can be displayed until they will get overwritten again
- Recent colors should be available on application level
- For all color sources, the color hex-code of the selected color is displayed.

**Pick Up/Apply Coloring**

Add ability to copy existing colour-coding (conditional and catagorical) from one column to another or to more than one.

Our proposal: Pick Up/Apply allows users to pick up the whole configuration (colors and formatting) of one column and apply it again to one or multi-selected columns.

**Designs** 
![Handoff Corporate Colors](https://user-images.githubusercontent.com/114074888/197972948-e471ea45-8d0d-4963-b33d-c50f632225d6.png)
![Design Handoff](https://user-images.githubusercontent.com/114074888/197972954-d66f55c1-9f99-4d79-9918-d83c3acc0b3d.png)

https://www.figma.com/file/XWM13t9bG4vkEBgQJovUHa/Color-Picker-Dialog?node-id=71%3A2346

**Comment by onuf** [comment]
Wiki for the new context menu commands: https://github.com/datagrok-ai/public/blob/master/help/visualize/viewers/grid.md#column-color-coding (they are currently tested and will be part of `v1.8.3`)

**Comment by onuf** [comment]
Comes with `v1.10.0`
