### ISSUE TITLE
Chem: multiple substructure filters all have "Structure" caption

### ISSUE THREAD

**Issue by skalkin** [datagrok-ai/public#1158]
To reproduce:
1. Open the SPGI dataset (it has multiple molecule columns)
2. Add filters

Expected: captions should correspond to column names
Actual: all captions are "Structure"

![image](https://user-images.githubusercontent.com/943403/199513435-87713332-8278-4b3b-bbb0-048fb769ae7d.png)

**Comment by MariaDolotova** [comment]
Hi @skalkin ! Could you please specify Datagrok version on which this bug occurrs.

**Comment by dionissqq** [comment]
Fixed in Datagrok v1.9.0
