### ISSUE TITLE
Grid: Pinned columns: column header and sorting missing functionality

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1159]
PowerGrid 1.1.6

**Sorting:**
1. 'No sorting' option is missing for pinned columns, double click on column header can only sort asc/desc
2. Sorting indicator is not shown in pinned column header (small up/down arrow in non-pinned columns)

**Column header:**
1. Right click on pinned column header is showing grid context menu instead of column header context menu
2. There is no way to change column width for a pinned column

**Comment by dgosi** [comment]
Thank you for the feedback. This functionality will be added within next several days.

**Comment by dgosi** [comment]
All the issues have been addressed in the Core v1.8.4 and PowerGrid v1.1.8

**Comment by osakhniuk** [comment]
@dgosi, context menu called for the pinned column continues to be displayed for the entire grid

![image](https://user-images.githubusercontent.com/57458471/201905069-f41dfdee-b782-4152-9034-b47d7602e8f0.png)

Another case related to this issue:
After clicking on the pinned column header, it does not become the current object.

I reproduced it on Datagrok v1.8.4 and PowerGrid v1.1.8

**Comment by onuf** [comment]
@osakhniuk please check the option 'Current Column' in the context menu dispalyed for a pinned column. As I recall, we discussed this as a potential workaround to reach column properties/color coding/formatting, etc.
@katerina-stepanova could you follow up with your team to decide whether such workaround would be sufficient?

**Comment by katerina-stepanova** [comment]
@onuf thanks for the hint, I'll check with the team if that would be sufficient.

There is an issue however in PowerGrid 1.1.8:
'Current column' options are applied for a wrong column, if there is more than 1 column pinned. It can happen for colouring, sorting, format, opening column properties. Example for colouring:
![2022-11-16_11-55-55 (1)](https://user-images.githubusercontent.com/15780643/202138846-fa943a18-52d2-4d82-91fd-c1d386804821.gif)


Issue can be reproduced on SPGI dataset.

**Comment by katerina-stepanova** [comment]
@onuf I've confirmed with the team that this is fine, once the bug ^^ is fixed.

**Comment by onuf** [comment]
@katerina-stepanova Great, thanks!

**Comment by dgosi** [comment]
Thank you for reporting, it's been taken care of.

**Comment by onuf** [comment]
The bug should be fixed in DG v1.8.3, PowerGrid 1.1.8

**Comment by dgosi** [comment]
The problem could not be reproduced. Could you please specify the column names you pin from SPGI file and on which column you make a right click to invoke the context menu. This should be of help to reproduce.

**Comment by katerina-stepanova** [comment]
@dgosi 
I've checked behaviour in a bit more detail, and it looks like the menu on the first right click is usually wrong, but the second right click on the same column is showing the correct menu.
1. Pinned 3 columns: ID, Structure, Last published date
2. Right click on ID > I've noticed that on first right click there is no 'Current column' option:
<img width="234" alt="image" src="https://user-images.githubusercontent.com/15780643/205591893-62e7c9f4-c445-4520-a8af-7de3d6ab0c7a.png">
3. Right click ID again > choose categorical colour > this time colour was set correctly on ID column
4. Right click 'Last published date' > **it's context menu is wrong**, showing ID column's context menu > thus all changes will be applied on ID column

Can be reproduced on Chrome, Mac OS.

**Comment by katerina-stepanova** [comment]
Cannot reproduce it on Windows, public.datagrok.ai

**Comment by dgosi** [comment]
On Win this issue cannot be reproduced. Is this Mac specific or it is present on both systems?

**Comment by katerina-stepanova** [comment]
@dgosi I think it's Mac-specific.

**Comment by onuf** [comment]
Seems like a Mac-specific problem, tested on https://public.datagrok.ai/ [DG 1.9.1, PowerGrid 1.1.9] & on the sandbox server [DG 1.9.1, PowerGrid 1.1.10]. Works as expected on Windows

**Comment by onuf** [comment]
@katerina-stepanova could you please follow up with the team to understand how critical is it to fix the context menu issue on Mac OS?

**Comment by katerina-stepanova** [comment]
@onuf it's a major issue, but not a blocker for the nearest release.

**Comment by dgosi** [comment]
The topic for pinned column selection was moved to a separate ticket https://github.com/datagrok-ai/public/issues/1631
