### ISSUE TITLE
PowerGrid: Pinned columns: some row selection features are missing

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1160]
PowerGrid 1.1.6
**Missing row selection features on pinned columns area:**
1. Row cannot be selected with Ctrl-Click (Cmd-Click on Mac) in the pinned columns area
2. Row is not selected on clicking row number at the left of the table if there are pinned columns

**Comment by dgosi** [comment]
Thank you for the feedback. This feature is already available in PowerGrid 1.1.8

**Comment by dgosi** [comment]
Added support for Macs, command key (Ctrl Windows) and fixed pinned rows column selection on regular click. The fix is available in PowerGrid v 1.1.9

**Comment by katerina-stepanova** [comment]
DG 1.9.1, PowerGrid 1.1.9, MacOS (not tested on Win)

Row cannot be deselected by cmd-click on pinned columns area, if some sorting or filtering is on:
1. Open some table, e.g. SPGI
2. Pin some columns
3. Enable some sorting or filtering
4. Select some rows
5. Cmd-click on a selected row in pinned columns area
for case with sorting: any row
for case with filtering: row that was originally below one of the filtered out ones

**Expected:** cmd-click on selected row deselects it.
**Actual:** nothing happens.

**Comment by dgosi** [comment]
The fix is available in PowerGrid 1.1.10. Please give it a try.
