### ISSUE TITLE
Order or hide columns dialog: columns cannot be shown/hidden after searching for column

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1162]
DG 1.8.2

**Steps to reproduce:** 
1. Open a table
2. Open 'Order or hide columns' dialog
3. Search for some column within the dialog
4. Check/uncheck one of the columns found

**Expected results:** Column is shown/hidden when checked/unchecked in 'Order or hide columns' dialog.
**Actual results:** When something is searched in 'Order or hide columns' dialog, checking/unchecking a column in the results does not show/hide it.
![2022-11-03_14-49-46 (1)](https://user-images.githubusercontent.com/15780643/199713512-1fb112f2-76b8-46a0-a656-5598810c5c90.gif)

**Comment by dionissqq** [comment]
Seems like some bug on 1.8.2 version, it is already fixed in 1.8.3

**Comment by skalkin** [comment]
@dionissqq , probably it would make sense to close it if it is no longer reproduced on dev

**Comment by dionissqq** [comment]
Closing as no longer reproducible
