### ISSUE TITLE
Zoom slider is not working for numerical columns with specific data distribution

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1167]
**Preconditions:**
Open a table with column having specific distribution of values.
Some examples:
- Files > demo_files > smiles.csv > FractionCSP3 column
- Calculated column with sigmoid-like function: open SPGI, create a calculated column with following formula:
    if(${Average Mass} == null, 0.00001,1/(1+Exp(-0.01*(${Average Mass}-680))))

**Steps to reproduce:**
1. Add a scatter plot
2. Set up a column prepared earlier as one of the axes
3. Try to use zoom slider for this column

**Expected results:** Scatter plot can be zoomed using the slider.
**Actual results:** Nothing happens on attempt to use zoom slider.

Issue can be reproduced in v1.8.2, it first appeared in 1.6.13 or earlier.

**Comment by dionissqq** [comment]
Fixed in v1.8.3
