### ISSUE TITLE
Significant figures should be rounded properly

### ISSUE THREAD

**Issue by JianmeiFan** [datagrok-ai/public#1173]
**Steps to reproduce:** 
1 open this file in datagrok 2 Change the format of 2nd column logP to 3 Significant digits
**Expected results:** 
The significant figures should be rounded as user expected.
**Actual results:** 
It doesn't round up a number. For example, user would expect that 4.3083 should be rounded as 4.31 instead of 4.30. Please see attached screenshot
![image](https://user-images.githubusercontent.com/100243033/200424261-fddb2c8a-4ee4-416a-91f7-d17423e6eb66.png)

[DDIS-4157.csv](https://github.com/datagrok-ai/public/files/9955805/DDIS-4157.csv)

**Comment by osakhniuk** [comment]
@skalkin, look at this please, it's something wrong with rounds. 

@JianmeiFan, thanks for the report!

**Comment by skalkin** [comment]
Good catch. That was due to our heavily customized (NIBR-requested) formatter that formats to max N significant digits, but always leaves the whole part intact.

Fixed in Datagrok 1.8.4
