### ISSUE TITLE
Can not select empty value colored data points in scatterplot 

### ISSUE THREAD

**Issue by JianmeiFan** [datagrok-ai/public#1174]
**Steps to reproduce:** 

1. Make a scatterplot 
2. Use a column that has empty value to color the plot 
3. Do some selection on these non-colored data point.

**Expected results:** 
User can select any data point in the scatterplot

**Actual results:** 
These colored by empty values are not selectable by pressing Shift Mouse Drag, user can only do Ctrl + Mouse Click selects individual missing value data. 
Please see video
https://user-images.githubusercontent.com/100243033/200426757-b7420030-1a9f-4990-a8b2-71cb9145bf6c.mp4

**Comment by osakhniuk** [comment]
Hello! Thanks for the report. I think @dionissqq needs to look at this

**Comment by dionissqq** [comment]
Fixed in 1.8.4
