### ISSUE TITLE
Calculated columns dialog is too large in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1186]
PowerPack 1.0.5

**Steps to reproduce:**
1. Open a table, e.g. SPGI
2. Open calculated column dialog

**Expected:** calculated column dialog is not too large.
**Actual:** calculated columns dialog is too large in some cases. Can be reproduced in native DG with dev tools panel opened:
![2022-11-09_13-19-16 (1)](https://user-images.githubusercontent.com/15780643/200891405-14abf7ce-49a1-43a6-a792-6072e6a5d1c7.gif)
And in the NX application.

**Comment by dionissqq** [comment]
Fixed in PowerPack v1.0.6
