### ISSUE TITLE
Viewer legend is not synchronised with in-viewer filter in a specific case

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1209]
**Steps to reproduce:**
1. Open a table
2. Add a viewer that supports in-viewer filtering (scatter plot, bar chart, line chart)
3. Configure viewer so that showing legend is applicable (e.g. color by column for scatter plot, or split by column for line chart)
4. Set-up in-viewer filter so that there are no data shown in viewer
5. Change in-viewer filter so that there is some data shown in viewer
**Expected results:** Legend should be shown.
**Actual results:** Legend is still hidden.
6. Save layout
7. Close and open the same table and re-apply layout
**Expected results:** Legend is shown, legend is synchronised with in-viewer filter and is not showing categories that are hidden on the plot.
**Actual results:** Legend is shown, but it is not synchronised with in-viewer filter. All existing categories are shown instead.

**Comment by dionissqq** [comment]
Fixed in 1.9.1

**Comment by katerina-stepanova** [comment]
v1.9.2: issue is reproduced as described above

v1.10.2 (public):
1. Cases described above fixed.
2. New case (not reproduced in 1.9.2): legend is not updated when in-viewer filter is removed
![2022-12-09_13-46-48 (1)](https://user-images.githubusercontent.com/15780643/206685376-f4ca2fe1-9dba-4673-a896-4ee2a1b2874f.gif)

**Comment by dionissqq** [comment]
Fixed in v.1.10.3

**Comment by katerina-stepanova** [comment]
v1.11.1

1. Original case fixed
2. Legend update when filter is removed is fixed

**New case discovered - legend disappears when specific filter is applied:**
1. Open SPGI
2. Add a scatter plot: CAST Idea ID/Chemical Space Y, coloured by Stereo Category
3. Add in-viewer filter: ${Stereo Category} in "S_PART"

**Expected results:** legend is still shown.
**Actual results:** legend disappears.
Issue can be reproduced if filter contains "S_ACHIR", "S_PART", "S_UNKN", but not for "R_ONE" and "S_ABS" values.

**Comment by ahadzhanian** [comment]
DG v. 1.14.0
