### ISSUE TITLE
#1216: Chem: Structure Filter for Current Molecule Value

### ISSUE THREAD

**Issue by dgosi** [datagrok-ai/public#1216]
When current value is used as a molecule for structure search (see the screen shot) the search is performed on a first found Molecular column. Is this the expected behavior? What if there are multiple compound columns in the data set?  Should it be the same molecule column the current value belongs to? Here is the code snippet.

//name: Use as filter
//description: Adds this structure as a substructure filter
//meta.action: Use as filter
//input: string mol { semType: Molecule }
export function useAsSubstructureFilter(mol: string): void {
  const tv = grok.shell.tv;
  if (tv == null)
    throw 'Requires an open table view.';

  const molCol = tv.dataFrame.columns.bySemType(DG.SEMTYPE.MOLECULE);

<img width="200" alt="current_value" src="https://user-images.githubusercontent.com/96437636/203140619-7bf8343f-fc4e-4b29-82fe-fbb15a58e198.png">

**Comment by skalkin** [comment]
>  Is this the expected behavior?

Of course it's not, it's a bug clearly

**Comment by dgosi** [comment]
To fix this, SemanticValue has to be used as the parameter from which the column would be available. However, using semantic_type as input doesn't register the function. There is an issue in the whole registration chain somewhere. Are there any obvious reasons?

//name: Use as filter
//description: Adds this structure as a substructure filter
//meta.action: Use as filter
//input: semantic_value value
export function useAsSubstructureFilter(value: SemanticValue): void {}

**Comment by skalkin** [comment]
Yes indeed we need to make sure we can pass semantic values.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16089
