### ISSUE TITLE
JS API: ability to disable column renaming

### ISSUE THREAD

**Issue by onuf** [datagrok-ai/public#1220]
Add a hidden column tag (e.g., '.allow-rename', default is true), which, when set to false, will hide or disable renaming in the UI for the corresponding columns (from property panel actions, column context menu, etc.).

**Comment by onuf** [comment]
Implemented as part of next release (`v1.10.0`)

**Comment by skalkin** [comment]
Would be nice to set the disabled (greyed-out) style to the input field as well

**Comment by onuf** [comment]
Done.
