### ISSUE TITLE
Grid resize after pinning columns

### ISSUE THREAD

**Issue by dgosi** [datagrok-ai/public#1231]
Once some columns are pinned we don’t correctly update the horizontal scrollbar data so you can no longer scroll to the end of the columns – by the exact width of the pinned columns.To reproduce:

    Open DG and open the demog dataset.
    Make your browser window width small enough so not all columns are visible
    Pin some columns
    Resize the browser window by a very small amount (just to trigger a re-render event)
    Scroll to the end of the Grid, the final columns will not be displayed, how much is missing is determined by the width columns that are pinned.

**Comment by katerina-stepanova** [comment]
Same issue happens when viewer is added to the right side of the screen, or properties panel is opened (instead of resizing browser window).

**Comment by dgosi** [comment]
we will try to provide a fix through the PowerGrid package in 2-3 days.
