### ISSUE TITLE
Make the 'Reset filters' icon less similar to the 'Refresh data' icon

### ISSUE THREAD

**Issue by DanTkachev** [datagrok-ai/public#1235]
Currently, the icons for resetting filters in the Filter panel and for refreshing the data in the analysis look very similar. It would be great to replace the icon 'Reset filters' with a different but convenient icon, i.e.:

https://fontawesome.com/icons/arrow-rotate-left?s=regular&f=classic

**Comment by dionissqq** [comment]
Fixed in v1.10.0
