### ISSUE TITLE
Color coding: ability to invert colors for linear color coding

### ISSUE THREAD

**Issue by dionissqq** [datagrok-ai/public#1236]
- [ ] invert colours in continuous color coding
- [ ] color coding behavior in case of data extremities changes

**Comment by onuf** [comment]
Added in `v1.11.0`.
Details for testing:

1. Histogram, bar chart, scatter plot (property `invertColorScheme` is editable when the colorColumn is selected)
2. Grid - on the column level. In API, inverted color scheme gets saved as any other custom color scheme (DG.TAGS.COLOR_CODING_LINEAR). In UI, the inverted scheme won't be duplicated in the popup list.
