### ISSUE TITLE
Scatter plot tooltip

### ISSUE THREAD

**Issue by dionissqq** [datagrok-ai/public#1237]
- [x] show only 5 columns instead of 10 ?
- [x] show x and y columns ?

**Comment by dionissqq** [comment]
Done in v1.10.3

**Comment by onuf** [comment]
We also discussed addition of the tooltip editor to the property panel.

**Comment by onuf** [comment]
@dionissqq please close the issue. I believe it's implemented in `v1.11.1` (next release). Just mentioning you to confirm

**Comment by dionissqq** [comment]
Fixed and added tooltip editor in v1.11.1

**Comment by dnillovna** [comment]
Changes will be included in the release 1.12.0
