### ISSUE TITLE
Chem: Marvin sketcher doesn't set molecule after repeated opening via burger filter

### ISSUE THREAD

**Issue by StLeonidas** [datagrok-ai/public#1239]
The bug is valid for Marvin 
Steps to reproduce:
- open Marvin sketcher in burger menu of molecule column, set any molecule
- close burger panel
- open burger panel again, the molecule will be missing

**Comment by MariaDolotova** [comment]
Duplicate of https://github.com/datagrok-ai/public/issues/1226
