### ISSUE TITLE
#1240: Top menus panel dissapear 

### ISSUE THREAD

**Issue by StLeonidas** [datagrok-ai/public#1240]
All top menus dissapear after 'menu' is of
![image](https://user-images.githubusercontent.com/57249456/204776950-8c5809b6-afc7-4875-b8a8-8b373ca72a61.png)
![image](https://user-images.githubusercontent.com/57249456/204777097-2e8db346-fbc2-4054-b82e-701501e7011b.png)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16090
