### ISSUE TITLE
Chem: Current value -> Use as filter adds an empty filter

### ISSUE THREAD

**Issue by MariaDolotova** [datagrok-ai/public#1244]

**Comment by MariaDolotova** [comment]
applyState() is called 2 times on filter (assume this occurrs in api.grok_FilterGroup_Add) - first is correct one, second contains previous value.

**Comment by ahadzhanian** [comment]
Now **Current Value** > **Use As Filter** adds a molecule to the filter in a different orientation (compared to the cell)
