### ISSUE TITLE
Chem: Sketcher filter is added to filter panel in incorrect mode if using 'Add filter' from burger menu or property panel

### ISSUE THREAD

**Issue by MariaDolotova** [datagrok-ai/public#1260]

**Comment by MariaDolotova** [comment]
Steps to reproduce:
- open dataset with molecular column
- choose molecular column and go to property panel (or burger menu). Expand filter on property panel
- click 'Add filter' one or several more times

**Comment by skalkin** [comment]
Fixed in v1.10
