### ISSUE TITLE
Chem: Recent molecules in sketcher are not drawn

### ISSUE THREAD

**Issue by MariaDolotova** [datagrok-ai/public#1265]

**Comment by MariaDolotova** [comment]
- open any dataset with molecule column
- open sketcher (by dbl clicking on any molecule cell)
- draw any structure or modify existing and click OK
- repeat several times
- open sketcher and go to 'Recent' via sketcher popup menu
- all molecules you drawn shoul be available in the list

**Comment by ahadzhanian** [comment]
Top menu Sketcher doesn't show **Recent** and **Favourites**

Platform: Release Version: 1.11.0
Data smiles.csv

1. Open smiles.csv 
2. Go to  **Chem > Sketcher**
3. Draw an arbitrary structure
4. Expand the **Actions** tab on the **Property Pane** and click the **Add to Favorites** item 
5. From the Sketcher hamburger menu select Recent and than Favorites
 Expected: the molecule you draw is shown in Recent and in Favourites
Actual: nothing is shown in Recent and in Favourites


![Image](https://user-images.githubusercontent.com/111368431/208730218-2d66a77c-7eb6-4a4a-9d00-9592948df1bb.gif)

**Comment by MariaDolotova** [comment]
@skalkin , @dionissqq , it seems that 'Add to favorites' button on property panel doesn't call addFavorite() method of Sketcher class. And handler of this button is not in Chem package. Is it called from core?

**Comment by dionissqq** [comment]
Will take a look

**Comment by StLeonidas** [comment]
not valid since add to favorites in property panel is not related to favorites in sketcher
