### ISSUE TITLE
Chem: R-Groups Analysis doesn't work on SPGI

### ISSUE THREAD

**Issue by AnnaMuza** [datagrok-ai/public#1266]
R-Groups Analysis does not work on SPGI
_public_

**Comment by ahadzhanian** [comment]
When clicking MCS on the R-Group Analysis dialog, red balloon shows
 " NoSuchMethodError: method not found: 'b9'
Receiver: Instance of 'd8S'
Arguments: [Closure 'c4f'] "

Occurs on any data, not only SPGI
