### ISSUE TITLE
Scatterplot: improvements to retire iGPS

### ISSUE THREAD

**Issue by DanTkachev** [datagrok-ai/public#1279]
Hi team! Please find the changes in the Scatterplot that we find important for retiring iGPS on our end.

1. Let users manually set axes limits by entering exact values (including values that are not on the data set now) and save the settings to the layout - it can be added simply to the property panel
2. Zooming issues:
- when filtering the plot by dragging the axis, the buffer is filtered out 
- when dragging the axis range down to the initial state, not all filtering is undone

**Comment by dionissqq** [comment]
could you specify what you mean in Zooming issues. Preferably with steps to reproduce?

**Comment by katerina-stepanova** [comment]
I've filed zooming issue as #1302

**Comment by dionissqq** [comment]
Fixed in v1.10.3
