### ISSUE TITLE
Chem: similarity/diversity - remove context menus

### ISSUE THREAD

**Issue by StLeonidas** [datagrok-ai/public#1285]
![Image](https://user-images.githubusercontent.com/57249456/205724141-edf6afcb-cb73-4972-9d53-9f052d624f6a.png)

**Comment by MariaDolotova** [comment]
Commit https://github.com/datagrok-ai/public/commit/43140da1ff9dbe214bc38d2f498fe636d990706c

**Comment by skalkin** [comment]
What exactly got removed?
