### ISSUE TITLE
Chem: Sketcher: Favorites: do not show/save empty structures and duplicates

### ISSUE THREAD

**Issue by skalkin** [datagrok-ai/public#1288]
![image](https://user-images.githubusercontent.com/943403/205746448-4a4813e4-f044-4269-b802-c4896432d26b.png)

**Comment by MariaDolotova** [comment]
Commits https://github.com/datagrok-ai/public/commit/2e77ffb3286e47f131deae2ed08929ccd3b5285f and https://github.com/datagrok-ai/public/commit/a9b610956df1f05e1fa0d8f86db04415174b3419
