### ISSUE TITLE
Line chart is showing less data than expected if table is filtered

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1292]
DG 1.9.1

**Steps to reproduce:**
1. Open SPGI
2. Add a Line chart with following config: 'Average Mass' on X axis, 'Chemical space X' on Y axis, row source = filtered. Everything else: default.
3. Open filters and set following filtering:
'Stereo Category': only 'S_PART' value is selected
'Chemist521': only 'Chemist 13' is selected
Notice that there are 28 rows left in the table, and columns used in line chart are non-empty
4. See Line chart.

Expected: line chart should show some points.
Actual: line chart is completely empty.

Note: it was working fine in DG 1.6.13

**Comment by dionissqq** [comment]
Fixed in v1.9.2
