### ISSUE TITLE
Pubchem: panel is not working

### ISSUE THREAD

**Issue by StLeonidas** [datagrok-ai/public#1294]
Platform: public
Data: mol1k
Steps to reproduce: open the panel 'Pubchem' item
Actual results: shows an error
Expected results: provide Pubchem features

![Image](https://user-images.githubusercontent.com/57249456/205959200-639ace4d-7604-4997-bf66-f86d7fd681af.png)

**Comment by vdyma** [comment]
The issue was fixed in version 1.1.3
