### ISSUE TITLE
Bio: Macromolecule sem type detectors: false positives

### ISSUE THREAD

**Issue by skalkin** [datagrok-ai/public#1295]
To reproduce:
* open SPGI dataset

Expected: `Cblood nM` column is string
Actual: `Cblood nM` column gets detected as a macromolecule

Here's a sample cell value:

```
54.0

43.3









90.9



687.0```

**Comment by tanas80** [comment]
In detector tests, perform multiple attempts on the same sample data (due to the non-deterministic nature of detectors).
