### ISSUE TITLE
Chem: Ketcher and Open Chem Sketcher don't work with Mol V3000

### ISSUE THREAD

**Issue by AnnaMuza** [datagrok-ai/public#1305]
_Public 1.10.0_

Steps to reproduce:

- open dataset with mol v3000 column (v3000_sample for example)
- Top Menu | Chem | Sketcher | hamburger menu => select any from mentioned sketchers
- double-click on any molecule

Expected result:
Editable molecule's structure in sketcher

Actual result:
Blank field

![Image](https://user-images.githubusercontent.com/70022930/206194822-c9e3f05b-76be-4cea-b96a-c6ba24e4d733.gif)

**Comment by MariaDolotova** [comment]
OCL doesn't work with structures from v3000_sample because molecules contain R groups. OCL sketcher doesn't support R groups.
As for Ketcher - it works correctly.


![Image](https://user-images.githubusercontent.com/44060410/211823757-4d365e63-e832-4fa0-a726-a1d4066731ed.gif)
