### ISSUE TITLE
Core: histogram legend doesn't show category colors represented with rgb string

### ISSUE THREAD

**Issue by vdyma** [datagrok-ai/public#131]
If category colors were set with a rgb string, histogram doesn't show the category colors in legend properly.
Consider the following code:
```
let df = grok.data.demo.demog();
let view = grok.shell.addTableView(df);

view.grid.col('sex').categoryColors = {
  'M': 'rgb(211,211,211)',
  'F': 0xFF800080
};
```
M category color is set with rgb string and F color is set using hex-number. This results in legend not being able to get the M category color properly:
![image](https://user-images.githubusercontent.com/25188402/135272295-d873420d-1a23-4a3a-b056-dd7b443c8e11.png)

**Comment by skalkin** [comment]
Fixed.

**Comment by skalkin** [comment]
Apologies, closed it by a mistake, I meant to close the neighboring #131 :)
