### ISSUE TITLE
Chem: error in hamburger menu after switching  sketcher to Marvin

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#1323]
Platform: public "Version":"1.10.2"
Data: any data with molecules
To reproduce:

1. Open the substructure filter via the column hamburger menu.
2. Switch to the Marvin sketcher. 
Actual: hamburger menu closes. If open the menu again, it shows an ‘error’ in the filter section
Expected: sketcher switches to Marvin 

![Image](https://user-images.githubusercontent.com/111368431/206678475-1cffc62a-f5e8-4e6e-8226-9f0d44c1a530.gif)

**Comment by MariaDolotova** [comment]
Fixed in PR #1349  and PR#4(labs repository)
