### ISSUE TITLE
Chem | Top menu Sketcher: doesn't work on molV2000, molV3000

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#1324]
Platform: public "Version":"1.10.2"
Data: 

- molV2000, for example [mol1K](https://public.datagrok.ai/mol1K)
- molV3000, for example [ApprovedDrugs2015](https://public.datagrok.ai/ApprovedDrugs2015)

To reproduce:

1. Go to Chem > Sketcher.
2. Draw cyclohexane. 
Actual: empty dataframe
Expected: filtered data 

![Image](https://user-images.githubusercontent.com/111368431/206695334-204fdff1-4d5e-40cc-a283-bff74cd0484c.gif)

**Comment by MariaDolotova** [comment]
@dionissqq , could you please check if the Sketcher from top-menu is created somewhere in core. Cannot find it in Chem package. 


![Image](https://user-images.githubusercontent.com/44060410/209160944-c7195a5e-fad8-415e-8c87-ac1084401533.png)


When clicking on 'Filter' button substructure filter is not created.

**Comment by MariaDolotova** [comment]
Not relevant any more
