### ISSUE TITLE
Chem: сlosing the Sketcher changes orientation for some molecules

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#1328]
Platform: public "Version":"1.10.2"
Data: [smiles](https://public.datagrok.ai/f/System.AppData/Chem/smiles.csv)

To reproduce:

1. Go to the molecule in the 47th row.
2. Double-click the cell. 
3. Click OK 

Actual: the molecule’s orientation is changed
Expected: molecule doesn’t change the orientation

![Image](https://user-images.githubusercontent.com/111368431/206721436-ad98a350-8678-4042-8455-bea3766e45a7.gif)

**Comment by ahadzhanian** [comment]
![Image](https://user-images.githubusercontent.com/111368431/209334603-6ad1c8e0-0f02-492b-a848-186db40074c4.gif)

**Comment by ahadzhanian** [comment]
Sketcher in Mutate dialog has the same issue

**Comment by MariaDolotova** [comment]
Fixed in PR #1349

**Comment by MariaDolotova** [comment]
As for mutate dialog - molecule is set to sketcher in the core. @StLeonidas , can you help with that?

**Comment by StLeonidas** [comment]
@MariaDolotova , yes

**Comment by MariaDolotova** [comment]
@ahadzhanian , issue with mutate dialog cannot be fixed at this point since OCL sketcher itself returns modified smiles when you select 'Copy as smiles'. And this leads to different coordinates.
