### ISSUE TITLE
Chem | Activity Cliffs: molecules orientation issue

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#1333]
Platform: public "Version":"1.10.2"
Data: [activity_cliffs](https://public.datagrok.ai/f/System.AppData/Chem/activity_cliffs.csv)

To reproduce:

1. Open the Property Pane.
2. Go to Chem > Activity Cliffs…. A scatter plot appears.
3. On the scatter plot, click the number of cliffs. An Activity Cliffs table appears.
4. In the table, click the first pair of cliffs. 

Actual: the molecules have a different orientation on the Property Pane and in the tooltip on the scatter plot compared to the orientation in the cell.
Expected: the molecules have the same orientation in the cell, on the Property Pane, and in the tooltip on the scatter plot.

![Image](https://user-images.githubusercontent.com/111368431/207048059-adcdcbae-f6b3-4669-b84a-154c6553ab01.png)

**Comment by vdyma** [comment]
I just want to mention that my commits https://github.com/datagrok-ai/public/commit/a147fbb2ad6cf825951e06d569bc9ff18d82371c and https://github.com/datagrok-ai/public/commit/8a9236925bcf248154299610016ce4d24470fc5e actually belong to #1339.
