### ISSUE TITLE
Chem | Activity Cliffs | Chemical Space: not enough data points error in UMAP

### ISSUE THREAD

**Issue by AnnaMuza** [datagrok-ai/public#1341]
_Public 1.10.2_

Steps to reproduce:

- open dataset with molecular column and small number of rows ([small_empty_vals.csv](https://public.datagrok.ai/f/System.AppData/Chem/tests/sar-small_empty_vals.csv) for example)
- remove the molecules so that there are less than 15 left
- run Top Menu | Chem | Chemical Space with UMAP method and random metric

Expected result:
balloon with warning/error

Actual result:
error log in console and infinite task execution

![Image](https://user-images.githubusercontent.com/70022930/207180482-9bc2a626-3f78-484f-813e-5672a0bf028c.gif)

**Comment by MariaDolotova** [comment]
Instead of warning message, number of required data points will be automatically adjusted
