### ISSUE TITLE
Chem | Activity Cliffs: slider on scatter plot overlaps categories for color coding

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#1342]
Platform: public "Version": "1.10.2"
 Dev "Version": "1.10.3"

Data: [approveddrugs2015](https://public.datagrok.ai/files/system.appdata/chem/approveddrugs2015.sdf)

To reproduce:

1. Go to **Chem** > **Activity Cliffs**
 
Actual: the **Show only cliffs** slider on the scatter plot overlaps categories for color coding.
Expected: UI elements don't overlap each other.

![Image](https://user-images.githubusercontent.com/111368431/207359269-79c2eebb-3633-46fc-bea3-4b092cfc2cfb.png)

**Comment by MariaDolotova** [comment]
The legend should not appear in activity cliffs viewer. This was caused by incorrect type of column selected for Activity (only numeric columns should be used). Will implement check for input column type.

**Comment by ahadzhanian** [comment]
For this dataset the 'molecule' column was selected for Actitvity cliffs. No legend was added manually

**Comment by ahadzhanian** [comment]
Can't reproduce
