### ISSUE TITLE
Formula lines issues

### ISSUE THREAD

**Issue by dionissqq** [datagrok-ai/public#1345]
- [x]  partly renders in log mod 
- [x]  tooltip inconsistencies.
- [x] line labels

**Comment by onuf** [comment]
Regarding the line labels, the line title will be on the plot, both title and description will be in the tooltip.

**Comment by dionissqq** [comment]
Done in v1.11.1

**Comment by dnillovna** [comment]
Changes will be included in the release 1.12.0
