### ISSUE TITLE
PowerGrid: Summary columns: normalization of bars

### ISSUE THREAD

**Issue by dionissqq** [datagrok-ai/public#1346]

**Comment by skalkin** [comment]
Should have the same "global scale" property as Sparkline

**Comment by skalkin** [comment]
package: PowerGrid
file: bar-chart.ts
example of the global scale: sparklines-lines.ts

**Comment by onuf** [comment]
@AnnaMuza once it's tested, please publish a new version to npm, mention its number here in a comment, and close the ticket. Thanks in advance!

**Comment by AnnaMuza** [comment]
added in version 1.1.11

**Comment by AnnaMuza** [comment]
fixed area of the tooltip trigger in version 1.1.12 of PowerGrid
