### ISSUE TITLE
Minimised scatter plot issues: some rows are unexpectedly filtered out, scatter plot shown incorrectly when brought back

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1348]
1.9.2, 1.10.2

**Steps to reproduce:**
1. Open SPGI table
2. Open Filters panel
3. Add a scatter plot: 'Chemical Space Y' as Y axis, 'Whole blood assay 1' on X axis
4. Minimise scatter plot so that it is almost completely hidden:
<img width="415" alt="image" src="https://user-images.githubusercontent.com/15780643/207564302-cf09db53-4fd7-439b-8ed5-4611ba3f47b6.png">

5. Reset filters
**Expected results:** filters are reset, all rows are displayed.
**Actual results:** some rows are filtered after clicking Reset filters:
![2022-12-14_12-58-15 (1)](https://user-images.githubusercontent.com/15780643/207564905-c100835d-8ff3-4868-b8ff-1239aff2bc5b.gif)

6. Bring back scatter plot from minimised state
**Expected results:** scatter plot should show some data.
**Actual results:** scatter plot is empty:
<img width="744" alt="image" src="https://user-images.githubusercontent.com/15780643/207565298-0fa4556d-b2b2-4058-94c7-12a8f0f56fdb.png">

**Comment by dionissqq** [comment]
Fixed in v1.11.1
