### ISSUE TITLE
Chem | R-Groups Analysis: ‘Cannot read properties of undefined (reading 'gpM')’  error

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#1351]
Platform: dev "Version": "1.10.3"

Data: [sar-small_empty_vals](https://dev.datagrok.ai/f/System.AppData/Chem/tests/sar-small_empty_vals.csv)

To reproduce:

1. Go to **Chem** > **R-Groups Analysis…**.
2. On the R-Groups Analysis dialog, click **MCS**.
3. Click OK.

**Actual result**: 
````
TypeError: Cannot read properties of undefined (reading 'gpM')
````

**Expected result**: R-group Analysis result

![Image](https://user-images.githubusercontent.com/111368431/207846641-08486c2e-1d13-4fa6-9d8e-851160e3f46e.gif)

**Comment by StLeonidas** [comment]
@dionissqq is it relevant?
