### ISSUE TITLE
#1352: Chem | R-Groups Analysis: viewer resizing issue

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#1352]
Platform: dev "Version": "1.10.3"

Data: [spgi-100](https://dev.datagrok.ai/f/System.AppData/Chem/tests/spgi-100.csv)
To reproduce:

1. Go to **Chem** > **R-Groups Analysis…**.
2. On R-Groups Analysis dialog, click **MCS**.
3. Change **Column prefix** and click OK.
4. Use range sliders to increase the number of elements on the viewer.
5. Resize the viewer (make it smaller).

**Actual result**: red numbers appear on the plot. 
Note: do not appear on the usual trellis plot viewer.
**Expected result**: viewer resizing without artifacts

![Image](https://user-images.githubusercontent.com/111368431/207858753-47eab8cc-afe4-4025-88f5-92f99c557671.gif)

**Comment by MariaDolotova** [comment]
@ahadzhanian , I guess this is expected behaviour of trellis plot. Max 250 categories can be displayed at once. @dionissqq , is it correct? Are we going to change or not?

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14842
