### ISSUE TITLE
Trellis plot: ‘Full screen’  doesn’t work

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#1356]
Platform: dev "Version": "1.10.3"
Data: any data 

To reproduce:

1. Open **Trellis plot*.
2. On the viewer, hover over an element. A **Full screen** icon appears.
3. Click the **Full screen** icon.

**Actual result**: nothing happens
**Expected result**:  a viewer for the element opens in a full-screen mode 
![full screen](https://user-images.githubusercontent.com/111368431/207865292-5401c32f-1f46-4505-b0f1-2355b29407fd.gif)

**Comment by dionissqq** [comment]
Issue appeared while using v3000 mols as dialog title
Fixed in 1.11.1
