### ISSUE TITLE
#1362: #1362: Chem: RDKit minimal lib - R-groups

### ISSUE THREAD

**Issue by StLeonidas** [datagrok-ai/public#1362]
Datagrok uses [RDKit minimal lib](https://github.com/rdkit/rdkit/tree/master/Code/MinimalLib) for cheminformatics related calculations. Minimal lib is limited to a subset of features presented in [RDKit](https://www.rdkit.org/) which is usually wrapped and used in Python. Some more features will be useful in the minimal lib. One of them are features essential for R-groups analysis. In Python RDKit they are used as:
[Chem.ReplaceCore](https://www.rdkit.org/docs/source/rdkit.Chem.rdmolops.html#rdkit.Chem.rdmolops.ReplaceCore)
[Chem.GetMolFrags](https://www.rdkit.org/docs/source/rdkit.Chem.rdmolops.html#rdkit.Chem.rdmolops.GetMolFrags)

Implement these both functions RDKit minimal lib using c++

Add this functionality to [JS wrapper](https://github.com/rdkit/rdkit/blob/master/Code/MinimalLib/jswrapper.cpp) and to [CFFI wrapper](https://github.com/rdkit/rdkit/blob/5d0be00f8dee7d2098944b83c3bb08adb01504ec/Code/MinimalLib/cffiwrapper.cpp)

**Comment by StLeonidas** [comment]
Implement RDKit Python functions
[Chem.ReplaceCore](https://www.rdkit.org/docs/source/rdkit.Chem.rdmolops.html#rdkit.Chem.rdmolops.ReplaceCore)
[Chem.GetMolFrags](https://www.rdkit.org/docs/source/rdkit.Chem.rdmolops.html#rdkit.Chem.rdmolops.GetMolFrags)
in [RDKit minimal lib](https://github.com/rdkit/rdkit/tree/master/Code/MinimalLib)
This functionality has to be added to JS Minimal Lib and needs to be implemented in [CFFI library](https://github.com/rdkit/rdkit/blob/5d0be00f8dee7d2098944b83c3bb08adb01504ec/Code/MinimalLib/cffiwrapper.cpp)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14844
