### ISSUE TITLE
Chem | Property Pane: errors in  DragBank: Substructure Search and DragBank: Similarity Search info panels

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#1366]
Platform: Release Version: 1.11.0

Data smiles.csv

To reproduce:

1. Click the cell with molecule
2. Go to Property Pane  and expand DragBank: Substructure Search and DragBank: Similarity Search info panels

**Expected result:** results of  DragBank: Substructure Search and DragBank: Similarity Search

**Actual result**: errors

![Image](https://user-images.githubusercontent.com/111368431/208701797-473c1c6b-21c9-474f-876c-95bab24a61dd.png)

**Comment by ahadzhanian** [comment]
1.0.1 is set as the latest

**Comment by vdyma** [comment]
Latest DrugBank version is 1.0.5. I will check if the problem is still present in the latest version.

**Comment by vdyma** [comment]
I couldn't confirm this bug with the latest version.
