### ISSUE TITLE
Scatter plot: context menu harmonization

### ISSUE THREAD

**Issue by AnnaMuza** [datagrok-ai/public#1375]
- [x] rename Drop Lines (add Show)
- [x] rename Regression Line (add Show)
- [x] Rectangle/Lasso select
- [x] add "Label Color As Marker" to Context menu | Markers
- [x] hide/disable marker type when marker axis is defined

**Comment by onuf** [comment]
Comes with version `1.14.0`

**Comment by Recca-Gottschall** [comment]
For the Bar chart context-menu, you renamed "Visibility" to "Controls" (see here: https://github.com/datagrok-ai/public/issues/1376).  I noticed that Scatter plot context-menu also has a menu with the name "Visibility" with similar properties. Should they be named consistently?

**Comment by ahadzhanian** [comment]
DG 1.16.0
