### ISSUE TITLE
#1380: PC Plot: Show Min Max display bug

### ISSUE THREAD

**Issue by AnnaMuza** [datagrok-ai/public#1380]
- [x] handle long column names
- [x] hide/format min/max value if it is overlaid

![safdfds](https://user-images.githubusercontent.com/70022930/208795176-aa46c013-591b-4b23-adb8-8493dfe53461.png)

**Comment by skalkin** [comment]
Hi @AnnaMuza , ticket descriptions should be a bit more... descriptive :) There are a few things going wrong in this picture

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14848

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16101
