### ISSUE TITLE
#1381: Line Chart: context menu harmonization

### ISSUE THREAD

**Issue by AnnaMuza** [datagrok-ai/public#1381]
- [x] add new menu Selection/Active Row with entries:
- Show Current Row Line
- Show Mouse Over Row Line
- Show Mouse Over Category
- [ ] add Segments... (will open column select dialog) entry to Misc
- [x] rename Left menu to Left Bar Chart and move to Misc
- [x] move Filter menu to Misc
- [x] add (to Misc) menu Lines with entries:
- Interpolation
- Spline Tension
- Line Width
- [x] add new menu Controls with entries:
- Show X Axis
- Show Y Axis
- Show Aggr Selectors
- Show X Selector
- Show Y Selectors
- Show Split Selector
- Multi Axis
- [ ] add menu Y axis (show number of columns as summary: for example, 10 columns (like in Spotfire)) with entries:
- Show Y Axis
- Y Axis Type
- Y Global Scale
- [x] add menu X axis (Zoom Slider with context-menu) with entries:
- Show X Axis
- X Axis Type
- Invert X Axis

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14583

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16102
