### ISSUE TITLE
Chem | Elemental Analysis: save to layout functionality

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#1390]
Saving to layout functionality should be applicable to Elemental Analysis

**Comment by skalkin** [comment]
@ahadzhanian , so what exactly is the issue?

**Comment by Aleksashka11** [comment]
@skalkin, for some reason when doing manually View -> Layout -> Save to gallery, the layout isn’t saving. Or it was not applicable to other similar datasets.
When I tested it today, it was saved sometimes from the first attempt, sometimes from the second/third.
I don’t think that it is elemental analysis fault. However, the behavior is not right.

**Comment by ahadzhanian** [comment]
Saving to layout functionality is applicable to Elemental Analysis on v. 1.11.1
