### ISSUE TITLE
Chem | Curate: changes molecules orientation

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#1391]
Platform: Dev Version: 1.10.3 Chem 1.4.8

Data: SPGI

to reproduce:
1. Go to **Chem** > **Curate**
2. Set **Molecules** to `Structure`
3. Check all checkboxes and click Ok

**Expected result**: the same molecules in the **Structure** and **curated_molecule** columns have the same orientation 
**Actual result**:  the same molecules have different orientation in the **Structure** and **curated_molecule** columns

**Comment by skalkin** [comment]
This is very minor (also it will inevitably change the format from smiles to molblock), I don't think it's worth our time
