### ISSUE TITLE
#1400: Chem: RDKit minimal lib - reactions

### ISSUE THREAD

**Issue by StLeonidas** [datagrok-ai/public#1400]
Datagrok uses [RDKit minimal lib](https://github.com/rdkit/rdkit/tree/master/Code/MinimalLib) for cheminformatics related calculations. Minimal lib is limited to a subset of features presented in [RDKit](https://www.rdkit.org/) which is usually wrapped and used in Python. Some more features will be useful in the minimal lib. One of them are features essential for reactions handling. In Python RDKit they are used in [rdChemReactions](https://www.rdkit.org/docs/source/rdkit.Chem.rdChemReactions.html) module:
ReactionFromSmarts();
runReactants();

Implement these both functions RDKit minimal lib using c++

Add this functionality to [JS wrapper](https://github.com/rdkit/rdkit/blob/master/Code/MinimalLib/jswrapper.cpp) and to [CFFI wrapper](https://github.com/rdkit/rdkit/blob/5d0be00f8dee7d2098944b83c3bb08adb01504ec/Code/MinimalLib/cffiwrapper.cpp)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14849

**Comment by StLeonidas** [comment]
Was supposed as external ticket - not relevant now
