### ISSUE TITLE
Chem | Widgets: handling empty values issue

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#1405]
Platform: Public Version: 1.11.1 Chem 1.4.8

Data: any
[ApprovedDrugs2015](https://public.datagrok.ai/f/Demo.TestJobs.Files.DemoFiles/chem/ApprovedDrugs2015.csv)
To reproduce:

1. Delete a molecule in the first row
2. Click the empty cell
3. Go to  the **Property Pane**

**Expected result**: widgets don’t work with empty data
**Actual result**:  Chembl Similarity Search, Chembl Substructure Search, ChemblAPI Substructure
Search Widget, ChemblAPI Similarity Search Widget, Chem Descriptors, and PubChem are processing empty value

![Image](https://user-images.githubusercontent.com/111368431/209653515-45a2f2d4-dc28-4e69-bde2-f66d823504bc.gif)

**Comment by vdyma** [comment]
What is wrong with this though? There are indeed no matches for empty values. Should I handle empty values in some other way?

**Comment by ahadzhanian** [comment]
If the data is empty, we shouldn't even search for a match
