### ISSUE TITLE
Scatter plot coloured by numerical or date column: some data is missing after re-applying saved layout

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1411]
**Steps to reproduce:**
1. Open a table
2. Add a scatter plot
3. Use numerical or date column for colouring:
- either column used for colouring is not coloured itself on the table
- or linear colour is applied
4. Save layout
5. Re-apply saved layout

**Expected results:** everything looks the same after re-applying saved layout.
**Actual results:** data on scatter plot coloured by numerical or date column is missing:
![image](https://user-images.githubusercontent.com/15780643/209691200-cd48682f-102d-4a6e-b17b-823ed35c2d6d.png)

**Comment by dionissqq** [comment]
closing as not more reproducible. Issue was on v1.11.1.
