### ISSUE TITLE
Viewers properties: column choosing dropdown is positioned so that some columns are hidden in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1412]
**Steps to reproduce:** 
1. Open a table with large number of columns, e.g. SPGI
2. Add a viewer that allows to choose columns, e.g. for axes (Scatter plot, histogram)
3. Open properties panel
4. Scroll properties panel
5. Open column choosing dropdown (e.g. for scatter plot Y axis)

**Expected results:** Position of the column chooser should not depend on how properties panel is scrolled.
**Actual results:** Column chooser is moved up together with properties panel contents on scrolling, hiding some of the topmost columns:
![2022-12-26_16-46-34 (1)](https://user-images.githubusercontent.com/15780643/209691606-af593947-9ec9-405f-a4b7-db37c6cda250.gif)

Issue was already present in 1.9.2, but did not cause much trouble because most column selections were at the top of properties panel.
In 1.11.1 issue is much more noticeable because of properties panel re-arrangement.

**Comment by dionissqq** [comment]
Fixed in v.1.12.0
