### ISSUE TITLE
Colour coding checkboxes in columns context menu behave inconsistently

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1455]
Found on v1.11.2, probably reproduced on v1.12.0 too

Colour coding options checkboxes in columns context menu behaviour is following:
1. Checkbox state is changed on every click
2. However unchecking the checkbox does not disable selected colouring option

As a result, colouring checkboxes are inconsistent with actual colouring:
1. Multiple options can be checked at once:
![изображение](https://user-images.githubusercontent.com/15780643/210820415-b40b9611-dc26-446a-8db5-167a72f86140.png)
2. Checkboxes state can be inconsistent with actual colouring in table (e.g. everything unchecked, but there is some coloring applied):
![изображение](https://user-images.githubusercontent.com/15780643/210820694-95d0e87a-7e9c-489b-8968-b10e21b25c65.png)

**Expected:** Colouring options should be mutually exclusive: only one should be enabled at a time, if no colouring is set, 'Off' should be enabled.

**Comment by skalkin** [comment]
Fixed in 1.12.0

**Comment by ahadzhanian** [comment]
The issue can be reproduced in Sketcher menu
![ChemDraw](https://user-images.githubusercontent.com/111368431/212740364-7e9d4126-a51d-427d-90ef-901fcd64ff61.gif)

**Comment by onuf** [comment]
@ahadzhanian please post this to https://github.com/datagrok-ai/public/issues/1474 (the Sketcher dialog is constructed via API, I'll investigate if this is an issue with the method itself or with the specific API usage)
