### ISSUE TITLE
Turning off filters does not disable filtering if another view contains same column in filters panel

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1460]
v.1.9.2, 1.11.3

**Steps to reproduce:**
1. Open a table
2. Open filters
3. Make sure there are some columns added to filters
4. Clone current view
5. Set up filtering so that some rows are filtered out
6. Turn off all filters
**Expected results:** all filtering is turned off, all rows are displayed.
**Actual results:** turning off filters has no effect on rows displayed.
7. Turn on filters again
8. Turn off some individual filter
**Expected results:** rows filtered out by this individual filter should be shown again.
**Actual results:** turning off individual filter has no effect on rows displayed.

Issue happens only for columns present in both views.

This issue looks like a synchronisation bug. Syncing state of on/off checkboxes for all filters and for individual filters across views should probably solve it.

**Comment by DanTkachev** [comment]
@dionissqq Please postpone this fix until we define the consolidated behavior for filters on different tabs. Thanks!

**Comment by ahadzhanian** [comment]
implemented in DG 1.14.0 as a part of https://github.com/datagrok-ai/public/issues/1589
