### ISSUE TITLE
Date in histograms: numerical values are shown for min/max instead of dates in a tooltip

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1467]
v1.11.3

**Steps to reproduce:**
1. Open a table
2. Find some date column, e.g. 'Competition assay Date' in SPGI
3. See tooltips for min/max/current range values

**Expected results:** date values should be shown in tooltips.
**Actual results:** numerical values are shown in tooltips instead of dates:
Histogram viewer:
<img width="738" alt="image" src="https://user-images.githubusercontent.com/15780643/211589513-2861de08-88c6-4aaa-87d6-51bc719771b7.png">
Filter panel:
<img width="423" alt="image" src="https://user-images.githubusercontent.com/15780643/211589602-8dc0bdaf-fea7-4a7d-b80f-d28ea3a5d386.png">
Column header filter:
<img width="395" alt="image" src="https://user-images.githubusercontent.com/15780643/211589679-e84f4748-ec4d-460a-bc5d-1764bba82bad.png">

**Comment by onuf** [comment]
@dionissqq please see [GROK-8482](https://reddata.atlassian.net/browse/GROK-8482), it makes something similar to show formatted datetime in a tooltip over histogram bins.
