### ISSUE TITLE
Reuse 'Pick up style' functionality for JsViewers

### ISSUE THREAD

**Issue by onuf** [datagrok-ai/public#1472]
Investigate possibility to reuse context menu options 'Pick up style' and 'Apply style' on custom viewers.

**Comment by DanTkachev** [comment]
Acceptance criteria:

- expose native Datagrok "pick/apply" API to JS-API
   - custom viewer should be able to use this API
   - custom viewer should be able to react on this API and react on the passed configuration
- provide examples on how to use and integrate this API into custom JS viewer implementations

**Comment by onuf** [comment]
@DanTkachev as you were interested in the status of this task, here is a summary:

For these commands to work on custom viewers we need a few things: to be able to distinguish between different types of custom viewers in the core (e.g., datagrid or radar chart, etc.) and to properly copy & apply custom viewer settings. The first point works out of the box, the second one (saving and applying) doesn't work uniformly as it is for native viewers, so this part is being improved and I think will be included into the next release. 

A few questions about the API:

1. Would a flag for enabling/disabling this group of commands on a custom viewer be a preferred way for you? If so, should it work for the entire group, or do you need a more specific selection (let's say you want to show only one of the three Apply options (out of Apply, Apply data settings, Apply style settings) or configure it in any other way)
2. Regarding configuration, will it be enough if the programmer can access it, or is there a need for events (something's been picked up / applied).

We can discuss this next time, I'm leaving these questions in case you already have some ideas on the API design you'd prefer.

**Comment by gasserandreas** [comment]
Some input from my end. Hopefully this helps to answer your questions:
1. Some sort of a flag and having control about what is shown is always preferred. For us it's fine if we can set this on viewer level only (I assume similar to how we can configure other viewers).
2. For us it's important that our viewer is can create and provide a custom configuration which then can be applied to another viewer. If this can/should be done via events or direct api calls (which we probably should be able to override/inherit from) does not matter. It's more important that we are able to share larger set of configuration including (some examples, not completed list): selected columns, column relationship, height, width, etc...

I hope this makes sense, let me know otherwise. I am happy to have a focused session/call to further clarify if needed.

**Comment by onuf** [comment]
@gasserandreas I believe we have everything ready for `v1.13`
We've added short descriptions for every context menu command in the UI (tooltips for users). We also have information on the topic in a wiki page: https://datagrok.ai/help/visualize/viewers/#common-actions.
Here is a [sample code snippet](https://github.com/datagrok-ai/public/blob/master/packages/ApiSamples/scripts/ui/viewers/style-settings.js):
```js
const df = grok.data.demo.demog();
const view = grok.shell.addTableView(df);

const sp = view.scatterPlot({
  colorColumnName: 'sex',
  backColor: DG.Color.lightBlue,
});

// Sets the current state of viewer properties as the default configuration
// used to create new viewer instances of this type (works both for native and custom viewers).
// Corresponds to the "Pick Up / Apply | Set as Default"
// Takes optional arguments to specify whether [data] and [style] settings should be copied.
// By default, copies only style settings: setDefault() is the same as setDefault(false, true)
sp.props.setDefault(true, true);

// Clears the previously remembered default settings.
// Note that the reset method can be invoked on any instance of this viewer type.
// Corresponds to "Pick Up / Apply | Reset Default"
const sp1 = view.scatterPlot();
sp1.props.resetDefault();
```
So, for the Datagrid case, all style-related commands will be shown in the context menu by default (I will also add a way to disable them by setting a special `allowDynamicMenus` option to false). And if you have a desired default configuration (likely with data properties), you can do as follows:
```js
datagrid.setOptions(config);
datagrid.props.setDefault(true, true);
```
