### ISSUE TITLE
JS API: add radioGroup to Menu.item

### ISSUE THREAD

**Issue by onuf** [datagrok-ai/public#1474]

**Comment by ahadzhanian** [comment]
The issue can be reproduced in the Sketcher menu:
![ChemDraw](https://user-images.githubusercontent.com/111368431/212838198-c0623c55-21ed-48b4-85be-b072e6e5d97e.gif)

**Comment by onuf** [comment]
@ahadzhanian please check if everything works as expected:

![sketcher-selector](https://user-images.githubusercontent.com/56073962/216057422-2c578683-f3bc-44a8-82b9-4a39e4451c27.gif)
