### ISSUE TITLE
Chem | Filtering: Filter Panel has to be reopened to display the molecule after Current value>Use as filter action

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#1475]
Platform: dev v. 1.11.3 

Data: [SPGI](https://dev.datagrok.ai/f/System.AppData/Chem/SPGI.csv)
To reproduce:

1. Open SPGI.csv 
2. Go to Tables and click the Filter icon. A Filter Panel opens
3. Right-click a cell in the `Structure` column 
4. Select Current value > Use as filter from the context menu. 

**Expected result**:  the Filter Panel displays the molecule 
**Actual result**:  the Filter Panel has to be reopened to display the molecule

![Image](https://user-images.githubusercontent.com/111368431/212035843-8c725307-029e-419f-a908-50de9c168dc4.gif)

**Comment by dionissqq** [comment]
Fixed in 1.3.0
