### ISSUE TITLE
Chem | Structural Alerts: error

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#1477]
dev v. 1.11.3
Data: SPGI
To reproduce: click a cell with a molecule
**Expected**: Property Pane > Structural Alerts are shown
**Actuall**: Property Pane > Structural Alerts error

![Image](https://user-images.githubusercontent.com/111368431/212067302-f87f6bcf-88fe-458a-8b73-0528956a4b72.png)

**Comment by vdyma** [comment]
@ahadzhanian Is this issue outdated? The newer one #1487 proves the panel is working.

**Comment by ahadzhanian** [comment]
Yes, can't reproduce anymore
