### ISSUE TITLE
Chem | Top menu functionality: malformed data in dataset and malformed inputs handling

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#1491]
**Expected**: Malformed data is not used for Top menu functionality. The malformed row should not produce any result
**Actual**: Malformed data in the dataset and inputs is used (and has to be handled according to the expected result) for the following functionality:
**Malformed data in dataset handling:**
- [ ]  Diversity Search
- [ ] Sketcher
- [ ] Chemical Space
- [ ] R-Groups Analysis

**Malformed inputs handling:**
- [ ] R-Groups Analysis
- [ ] Sketcher

**Comment by MariaDolotova** [comment]
moved to Jira
