### ISSUE TITLE
Chem | Elemental analysis: malformed data in dataset handling

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#1492]
Expected: The malformed row should not produce the Elemental Analysis result
Actual: The malformed row produces zeros and a radar chart with zeros.
Implement malformed data in dataset handling in Elemental analysis.

**Comment by Aleksashka11** [comment]
Can you please provide the dataset to check and test on? 
Or just steps to reproduce the issue?

**Comment by ahadzhanian** [comment]
[smiles_malformed.csv](https://github.com/datagrok-ai/public/files/10434237/smiles_malformed.csv)
How to malform, an example:
![malformed data](https://user-images.githubusercontent.com/111368431/212882574-5701a934-3545-4f1b-81ff-f9deef0d6231.gif)

**Comment by ahadzhanian** [comment]
![malformed data](https://user-images.githubusercontent.com/111368431/212883660-74509812-c8b8-479c-a91f-b921ab00af8f.gif)

**Comment by ahadzhanian** [comment]
[Test_smiles_malformed.csv](https://github.com/datagrok-ai/public/files/11019586/Test_smiles_malformed.csv)

**Comment by ahadzhanian** [comment]
[Test_smiles_malformed.csv](https://github.com/datagrok-ai/public/files/11027264/Test_smiles_malformed.csv)

**Comment by ahadzhanian** [comment]
Chem 1.6.7
