### ISSUE TITLE
Chem | Map Identifiers: malformed and empty data in dataset handling

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#1495]
Implement malformed and empty  data in dataset handling in Map Identifiers functionality

**Comment by ahadzhanian** [comment]
**case 1**
To reproduce:
1 .Add an empty row
2. Run Chem | Map Identifiers
An error occurs:
`Invalid type identifier: 8508
	null`
![Map_Identifiers_case1](https://user-images.githubusercontent.com/111368431/226337733-27698984-475e-42d3-bd8d-ae4935d4a2d9.gif)

**Comment by tcarolan** [comment]
Olena, thanks for triaging. Case 2 is what I am still experiencing with Chem Package 1.5.10, exactly as you describe.  Also, this behavior occurs for Chem | Descriptors.  When trying to add Molecular Weight I have gotten it to work once. But most times it fails, even after closing and reopening the Project.

**Comment by ahadzhanian** [comment]
@tcarolan We've recently fixed [Chem | Descriptors](https://github.com/datagrok-ai/public/issues/1417). Fixes will be in the nearest Grok Compute version.

**Comment by tcarolan** [comment]
Thank you. I will request an upgrade for Grok Compute.
