### ISSUE TITLE
Line chart coloring should be able to scale to visible range of data

### ISSUE THREAD

**Issue by DanTkachev** [datagrok-ai/public#1500]
The line chart should be able to scale the axes to the range of visible (plotted) data and not to the entire range of data in the table, in order to be able to look at the data in it's full size.

![image-2022-12-30-12-53-00-629](https://user-images.githubusercontent.com/114074888/213732364-cfabf962-1d9a-4300-9a66-f0b494496bd4.png)

**Comment by dionissqq** [comment]
This one is not reproducible on other data, could you provide the dataset or list of actions that lead to such behavior?

**Comment by dionissqq** [comment]
Bug was present in case no aggregations were applied to data.

There are still cases to get similar behavior

1) when x is null, y number is largest and row is not filtered
eg:
col1, col2, col3
a1, 10, 20
a1, 20, 40
a1, , 100

we see table with 100 as max, though max visible value is 40
2)
when some categories have only one point, row is still included in data (though dot might be not displayed in case of large datasets)
eg:
col1, col2, col3
a1, 10, 20
a1, 20, 40
a2, 10, 100
split by col1

**Comment by DanTkachev** [comment]
@dionissqq  Could you please move the corner cases to a separate ticket with a lower priority and proceed with the current fix (covering the main case) in 1.13? Thanks!

**Comment by AnnaMuza** [comment]
#1561
