### ISSUE TITLE
Line Chart: ability to customize the tooltip

### ISSUE THREAD

**Issue by onuf** [datagrok-ai/public#1516]
Add an option to create a custom tooltip on line chart and add a description in tooltip for users (so that it is clear in which cases, e.g. data aggregation) the custom tooltip will not be applied).

**Comment by ahadzhanian** [comment]
Implemented earlier

![Image](https://github.com/datagrok-ai/public/assets/111368431/b3e375e0-e1e4-49a7-b549-038e02fdee84)
