### ISSUE TITLE
#1534: redkit-cell-renderer doesn't correctly render structures with aromatic bonds

### ISSUE THREAD

**Issue by dgosi** [datagrok-ai/public#1534]
The structure produced by a sketcher with one aromatic bond looses the bond in rdkit-cell-renderer, see the image below

![image](https://user-images.githubusercontent.com/96437636/214922200-97b2d965-eb8e-4f14-ab2f-af91f7b3bc6e.png)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14861

**Comment by StLeonidas** [comment]
This issue is solved
