### ISSUE TITLE
Scatter plot legend: min/max are displayed incorrectly when plot is coloured by date column

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1539]
v1.12.2

**Steps to reproduce:**
1. Open SPGI
2. Add scatter plot
3. Colour it by 'Competition assay Date'

**Expected results:** min/max values are shown on legend as dates.
**Actual results:** min/max dates are not formatted correctly:
<img width="191" alt="image" src="https://user-images.githubusercontent.com/15780643/215430727-032f5e39-b5d8-4930-9a8f-14786941f69c.png">

**Comment by onuf** [comment]
@AnnaMuza please double-check, I think this one is already fixed (works correctly on dev `v1.12.2`, but not public `v1.12.0`). Dev version 1.12.2 includes latest changes (all of it will definitely be in major release of `v1.13`)
![image](https://user-images.githubusercontent.com/56073962/215468141-73e99fc1-1f54-4334-98ce-9905ae571226.png)
