### ISSUE TITLE
PC Plot: density is not recalculated on normalisation or switching columns to log scale

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1546]
**Steps to reproduce:** 
1. Open SPGI table
2. Add a PC Plot
3. Enable columns normalisation or change some columns to log scale

**Expected results:** Densities are re-calculated accordingly.

**Actual results:** Densities are not recalculated. See example for normalisation:
![2023-01-06_15-12-20 (1)](https://user-images.githubusercontent.com/15780643/215600969-ab818345-deb6-4e0b-890d-8ec46ee3a942.gif)

**Comment by ahadzhanian** [comment]
DG 1.14.1
