### ISSUE TITLE
#1562: Chem: R-groups (c++ to JS)

### ISSUE THREAD

**Issue by StLeonidas** [datagrok-ai/public#1562]
Datagrok uses [RDKit minimal lib](https://github.com/rdkit/rdkit/tree/master/Code/MinimalLib) for cheminformatics related calculations. Minimal lib is limited to a subset of features presented in [RDKit](https://www.rdkit.org/) which is usually wrapped and used in Python. Some more features will be useful in the minimal lib. 
Implement R-groups analysis in RDKit minimal lib using c++. 
In Python RDKit we implemented it as:
[find R-group](https://github.com/datagrok-ai/public/blob/master/packages/Chem/scripts/find_rgroups.py)

Expected JS signature is:
find_rgroups(molecules: string[], core: string): { [fragment: string] : string[]; }(see line 73 in Python script)

Add this functionality to [JS wrapper](https://github.com/rdkit/rdkit/blob/master/Code/MinimalLib/jswrapper.cpp) and to [CFFI wrapper](https://github.com/rdkit/rdkit/blob/5d0be00f8dee7d2098944b83c3bb08adb01504ec/Code/MinimalLib/cffiwrapper.cpp)

Example of usage:
![Image](https://user-images.githubusercontent.com/57249456/216430708-d0a5c68a-b5f3-4eee-8a48-22ecdd1b8818.gif)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14863
