### ISSUE TITLE
#1563: Chem: most common structure (c++ to JS)

### ISSUE THREAD

**Issue by StLeonidas** [datagrok-ai/public#1563]
Datagrok uses [RDKit minimal lib](https://github.com/rdkit/rdkit/tree/master/Code/MinimalLib) for cheminformatics related calculations. Minimal lib is limited to a subset of features presented in [RDKit](https://www.rdkit.org/) which is usually wrapped and used in Python. Some more features will be useful in the minimal lib. 

Implement finding the most common substructure for the whole dataset in RDKit minimal lib using c++. 

In Python RDKit we implemented it as:
[MCS](https://github.com/datagrok-ai/public/blob/master/packages/Chem/scripts/find_mcs.py)

Expected JS signature is:
find_mcs(molecules: string[]): string 

Add this functionality to [JS wrapper](https://github.com/rdkit/rdkit/blob/master/Code/MinimalLib/jswrapper.cpp) and to [CFFI wrapper](https://github.com/rdkit/rdkit/blob/5d0be00f8dee7d2098944b83c3bb08adb01504ec/Code/MinimalLib/cffiwrapper.cpp)

Example of usage:
It is an additional feature used in different Datagrok features (like in sketchers):
![Image](https://user-images.githubusercontent.com/57249456/216432093-59904e7d-e31f-44e0-8721-67b58c045de3.gif)

**Comment by tcarolan** [comment]
Bump +1. Users have asked for MCS because they found the documentation on Datagrok website but the feature is not currently available. They've expressed interest because its a great feature.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14864
