### ISSUE TITLE
#1565: Chem: RDKit minimal lib - FromInchI

### ISSUE THREAD

**Issue by StLeonidas** [datagrok-ai/public#1565]
Datagrok uses [RDKit minimal lib](https://github.com/rdkit/rdkit/tree/master/Code/MinimalLib) for cheminformatics related calculations. Minimal lib is limited to a subset of features presented in [RDKit](https://www.rdkit.org/) which is usually wrapped and used in Python. 
Implement the conversion from InchI to molecule in RDKit minimal lib using c++.
 In Python RDKit it is  used as:
[MolFromInchi](https://www.rdkit.org/docs/source/rdkit.Chem.inchi.html)

Expected JS signature is:
get_mol_from_inchi(inchi: string, sanitize: boolean = true, removeHs: boolean = true): string

Add this functionality to [JS wrapper](https://github.com/rdkit/rdkit/blob/master/Code/MinimalLib/jswrapper.cpp) and to [CFFI wrapper]https://github.com/rdkit/rdkit/blob/5d0be00f8dee7d2098944b83c3bb08adb01504ec/Code/MinimalLib/cffiwrapper.cpp)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14866

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16116
