### ISSUE TITLE
Charts: SankeyViewer tests fail

### ISSUE THREAD

**Issue by onuf** [datagrok-ai/public#1570]
_Test result : Failed : 3526 : Charts.Viewers.SankeyViewer : Error: cannot load viewer from layout_
_Charts 1.0.16_ 
Sankey Viewer does not work with empty data

![Recording 2023-02-06 at 16 38 15](https://user-images.githubusercontent.com/70022930/217000653-fc3a6569-6846-4862-94a1-056355e982bf.gif)

**Comment by LaykDimon** [comment]
done
