### ISSUE TITLE
Charts: GroupAnalysisViewer tests fail

### ISSUE THREAD

**Issue by onuf** [datagrok-ai/public#1572]
_Test result : Failed : 219 : Charts.Viewers.GroupAnalysisViewer : Converting object to an encodable object failed.
Charts 1.0.16_
GroupAnalysisViewer does not support serialization

![Recording 2023-02-06 at 16 43 27](https://user-images.githubusercontent.com/70022930/217001916-6304a2e0-55ba-47cf-a625-88670552ca40.gif)

**Comment by LaykDimon** [comment]
done

**Comment by LaykDimon** [comment]
done
