### ISSUE TITLE
Compute: Outliers detector

### ISSUE THREAD

**Issue by dskatov** [datagrok-ai/public#158]
[Sketch](https://user-images.githubusercontent.com/67762377/137735009-ee9bbd27-46aa-49c5-97d4-98f348b7be87.png)

**Comment by AufarZakiev** [comment]
Should we close this issue since https://github.com/datagrok-ai/public/commit/ba3a3ce35fa1332f75bce55d73b1c7041f1ad276 was approved as good enough?
