### ISSUE TITLE
Viewers: render structures in the legend component

### ISSUE THREAD

**Issue by onuf** [datagrok-ai/public#1581]
In core viewers that have a legend, if a categorical column contains molecules, render them in the legend.
Add a marker to indicate the corresponding color.

**Comment by katerina-stepanova** [comment]
1.14.1
Structures are rendered, but cropped at the right:
<img width="499" alt="image" src="https://user-images.githubusercontent.com/15780643/234228574-6ce71cde-445a-479b-acc4-9ca9090dc6f8.png">
