### ISSUE TITLE
Consolidate filters across different tabs

### ISSUE THREAD

**Issue by DanTkachev** [datagrok-ai/public#1589]
The purpose of this improvement is to consolidate filters application across different tabs so that the behavior is intuitive to users.

Acceptance criteria:

- The 'Reset' button resets all filters in the analysis:
   - turns all filters on
   - clears all selected options
   - clears visualization filters (e.g. scatterplot color label or "filter by zoom")
- Turning on / off a filter makes it turned on /off across all tabs
- Turning off a filter makes the filter inactive but its selection remains set (but not applied)

**Comment by onuf** [comment]
Relates to https://github.com/datagrok-ai/public/issues/1460
