### ISSUE TITLE
Peptides: Integration with Multi-Sequence Alignment

### ISSUE THREAD

**Issue by StLeonidas** [datagrok-ai/public#159]
Implement an algorithm for multy-sequence alignement in wasm same to Clustal-omega.

- [x] Find candidate for porting.
- [x] Is its license permit commercial use?
- [x] Plug in to the package.
- [x] Implement as a web worker.
- [x] Perform tests to ensure it is ready for production.
- [x] Add MSA into property panel.
- [x] Fix multiple runs issue. 
- [x] Test which sizes of inputs can be processed.

**Comment by nikolay-alemasov** [comment]
Is it useful for us to consider https://github.com/DinikaSen/clustal-omega-wrapper ?

**Comment by nikolay-alemasov** [comment]
One more package for MSA: https://www.npmjs.com/package/biomsa

**Comment by nikolay-alemasov** [comment]
Just the link Andrew found before: https://github.com/Merck/PepSeA

**Comment by nikolay-alemasov** [comment]
Suggest to consider [kalign](https://github.com/TimoLassmann/kalign).

**Comment by nikolay-alemasov** [comment]
Andrew would like to have this integration is done rather via [biowasm](https://github.com/biowasm/biowasm).

**Comment by nikolay-alemasov** [comment]
Issues now in the license of kalign and webpack of .wasm into a package.

**Comment by nikolay-alemasov** [comment]
Moved to biowasm.

**Comment by nikolay-alemasov** [comment]
The kalign cannot be run more than once without exceptions. Opened the [biowasm issue](https://github.com/biowasm/biowasm/issues/60) on that.
