### ISSUE TITLE
Excessive memory usage on applying several layouts with scatter plots having log scale axes (possibly a memory leak)

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1591]
**Steps to reproduce:**
1. Open a table that has several numerical columns (e.g. SPGI)
2. Add a scatter plot
3. Switch one or both axes to log scale
4. Right click > Prick up / Apply > Set as Default
5. Add more scatter plots (20-30)
6. Save layout
7. Add a few more viewers (e.g. open filters) and save layout once more
8. Switch quickly between two saved layouts several times in a row

**Expected results:** no memory leaks, layouts should be applied quickly without unexpectedly high memory consumption.

**Actual results:** Memory usage starts going up after switching between layouts multiple times. If browser page is left open for a while, memory consumption is still going up. Sometimes browser tab crashes after a while.
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/15780643/218758387-35e9efe6-a353-4aaf-9076-2c0ae21ce0e3.png">

Similar issue occurs in our app during loading sequence, in some cases crashing browser tab.

**Comment by ahadzhanian** [comment]
Couldn't reproduce on v. 1.15.x
