### ISSUE TITLE
Chem: Render a structure in a tooltip for the sketch box in the filters panel if the depicted substructure is large

### ISSUE THREAD

**Issue by onuf** [datagrok-ai/public#1608]
Dynamically determine if a substructure in the filter is large. If this is the case, add a tooltip above the sketch box rendering this structure. 
Use case: R group filters (sometimes it's hard to see the molecule in the sketch box in the filters panel). 
For now, decided to add a tooltip and not box resizing (though, it resizes up to the point when the filters start to form two columns in the panel).
![image](https://user-images.githubusercontent.com/56073962/220472646-e4a696ff-3901-4c35-bd54-57e6e2e805a7.png)
![image](https://user-images.githubusercontent.com/56073962/220473276-cfe5434a-3567-41ed-b387-4c4d48e7abaa.png)

**Comment by katerina-stepanova** [comment]
Example:
<img width="553" alt="image" src="https://user-images.githubusercontent.com/15780643/221186962-f033661d-b12e-4157-b8c0-4ba12e71b17a.png">

Some examples can be found in this file:
[PubChem_compound_text_covid-19.csv](https://github.com/datagrok-ai/public/files/10824370/PubChem_compound_text_covid-19.csv)
