### ISSUE TITLE
Pinned columns are blank in specific case

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1610]
Pinned columns are blank for a specific dataframe in NX application.
It happens for a table linked to another one, with applied layout.

Error:
`html_dart2js.dart:3558 Cannot read properties of null (reading 'name')
	https://gnfgrok.dev.nibr.novartis.net/api/packages/published/files/PowerGrid/1.1.13/XaqtOHIDTpx8ZVlktZJ69sWfdvqrPv4t/1/dist/package.js 947:35  PinnedColumn.paint
	https://gnfgrok.dev.nibr.novartis.net/api/packages/published/files/PowerGrid/1.1.13/XaqtOHIDTpx8ZVlktZJ69sWfdvqrPv4t/1/dist/package.js 255:47  <fn>
	aq_	@	html_dart2js.dart:3558
cB	@	log.dart:146
dart.dCt.$2	@	log.dart:110
fS	@	js_helper.dart:1521
dart.dhF	@	js_helper.dart:1489
(anonymous)	@	js_dart2js.dart:667
(anonymous)	@	dg.ts:44`

**Comment by dgosi** [comment]
Diana, Is there a way for you to get access to that specific data frame to reproduce the error?

**Comment by onuf** [comment]
@dgosi I'll check and post an update

**Comment by dgosi** [comment]
Perfect, thank you!

**Comment by onuf** [comment]
Found an analysis where the issue is reproduced, I'm getting the same error as in the ticket description. It's on the prod instance (DG v1.12.2)

**Comment by katerina-stepanova** [comment]
Found a way to reproduce blank pinned columns in native DG, however i'm not 100% sure it's exactly same issue:
1. Open a table
2. Pin a few columns
3. Add scatter plot and stack it over the table with pinned columns
4. Save layout
5. Re-apply saved layout
6. Pin ome more column

![image](https://user-images.githubusercontent.com/15780643/221801460-bc5526df-406e-4e0f-864c-bfa84926182f.png)

**Comment by dgosi** [comment]
The fix for all these pinned columns related issues is the version 1.1.15 of the PowGrid package.
