### ISSUE TITLE
Scatter plot: zoom slider behaviour is inconsistent for inverted axes

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1616]
**Steps to reproduce:** 
1. Open a table
2. Add scatter plot
3. Invert one of the axes
4. Zoom using slider

**Expected results:** Zoom slider behaviour should be consistent with axis direction.
**Actual results:** Zoom slider does not take into account 'invert axis' setting: wrong part of the plot is zoomed.

**Comment by dionissqq** [comment]
Fixed in 1.14

**Comment by ahadzhanian** [comment]
Case 2

1. Open table: [scatter plot broken.csv](https://github.com/datagrok-ai/public/files/10824294/scatter.plot.broken.csv)
2. Add scatter plot 
3. Switch an axis to log scale and invert it
4. Zoom using slider
An error occurs

![Image](https://user-images.githubusercontent.com/111368431/224296805-6383d094-b741-460f-894f-3399e950983f.gif)

**Comment by ahadzhanian** [comment]
Wrong range.
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1772:17      Object.u
	packages/d4/src/widgets/range_selector/range_selector.dart 83:44       pU.fk
	packages/d4/src/widgets/range_selector/range_selector.dart 208:13      cz5.
	packages/$sdk/lib/html/dart2js/html_dart2js.dart 42920:48              db5.
	packages/$sdk/lib/async/zone.dart 1132:12                              aYc
	packages/$sdk/lib/async/zone.dart 1012:12                              d8O.Ae
	packages/$sdk/lib/async/zone.dart 909:14                               d8O.Hq
	packages/$sdk/lib/async/zone.dart 936:23                               d8R.
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:48      fF2.
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 474:16  O0.LE
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 59:16   Object.FY
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:14      fF0
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2476:14      HTMLDocument.<fn>

**Comment by ahadzhanian** [comment]
DG v1.14.0

**Comment by ahadzhanian** [comment]
Also fixed in 1.13.15
