### ISSUE TITLE
Pinned columns are displayed incorrectly after applying layout with viewer stacked over the table

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1625]
**Steps to reproduce:**
1. Open SPGI
2. Pin ID and structure
3. Add scatter plot and stack it over the table
4. Save layout
5. Re-apply layout

**Expected results:** Pinned columns should be displayed properly after re-applying layout when something is stacked over the table.
**Actual results:** Structure overlaps ID:
![image](https://user-images.githubusercontent.com/15780643/222413211-0ce8a09e-f7e3-40ab-afe2-ff0fe03a46cd.png)
If one more column is pinned, it is empty (might be related to #1610)

**Comment by dgosi** [comment]
Yes, most likely the error is related to #1610, where the fix was provided

**Comment by onuf** [comment]
Tried locally with the new version of PowerGrid, seems to work as expected now. Let's double-check it on ID side along with #1610, though.

**Comment by ahadzhanian** [comment]
@dgosi It seems that the 'Pin columns' action is missing in the context menu
![Pinned_columns_are_missing](https://user-images.githubusercontent.com/111368431/223114475-0cc58841-a7bd-40c5-8640-b098baae35cb.gif)

**Comment by ahadzhanian** [comment]
Re-applying the layout is really slow.
![Pinned_columns_after_layout](https://user-images.githubusercontent.com/111368431/223114974-027cb463-cab8-4b96-a31f-1183d723f6c3.gif)

**Comment by onuf** [comment]
'Pin column**s**' is missing (I think there was an option to pin selected columns in one action), isn't it so?

**Comment by dgosi** [comment]
We never had this functionality

**Comment by onuf** [comment]
Oh, I see, sorry. I thought we had it and then the option disappeared

**Comment by ahadzhanian** [comment]
"Which server you are testing on?"
I'm testing on dev. I'll check it once more

**Comment by ahadzhanian** [comment]
I still reproduce slow layout re-applying. @onuf can you please check it?

**Comment by onuf** [comment]
@dgosi Unfortunately, it is slow on my machine too (even without additional charts, only the grid with two pinned columns):
```js 
let l = grok.shell.v.saveLayout();
console.time('Layout application');
grok.events.onViewLayoutApplied.subscribe(() => console.timeEnd('Layout application'));
grok.shell.v.loadLayout(l);
// Layout application: 7604.821044921875 ms
```
Works way faster without pinned columns.

**Comment by onuf** [comment]
I think the "Structure" column is to blame, layout applies fast if pinned columns list doesn't include molecular data

**Comment by onuf** [comment]
Structure columns will be pinned most likely, so the performance issue is critical.

**Comment by dgosi** [comment]
Slow pinned molecule columns issue was reproduced and the fix is available in the version 1.1.18 of PowerGrid package

**Comment by onuf** [comment]
@dgosi there's still the overlap bug if we use `DG.DOCK_TYPE.FILL`:

![image](https://user-images.githubusercontent.com/56073962/224712884-ce0f65e0-be30-4d7a-903e-5df914f70e4f.png)

![image](https://user-images.githubusercontent.com/56073962/224712640-ba118d60-c39b-414c-8091-c16d91361fe8.png)

**Comment by dgosi** [comment]
@onuf , the overlapping pinned columns bug has been addressed. The fix in v. 1.1.19 of PowerGrid package
