### ISSUE TITLE
Scaffold Tree: filtering enhancements

### ISSUE THREAD

**Issue by onuf** [datagrok-ai/public#1627]
AND, OR, NOT operators:

- [x] a switch to search for structure / absence of the structure (NOT implementation on the node level)
- [x] allow a combination of operations (AND, OR, NOT), currently achievable via two viewers side by side)
- [x] the ability to add Scaffold Tree as an individual filter in a filter group

**Comment by onuf** [comment]
"NOT" operation is top priority

**Comment by dgosi** [comment]
Bitwise operations AND and OR for hits filtering are available as properties of ScaffoldTree. NOT option is provided for each node of a tree. This functionality is available in version 1.5.9 of Chem package.

**Comment by onuf** [comment]
@ahadzhanian I think these steps should be repeated for testing:

1. Open a table, e.g., https://dev.datagrok.ai/f/Demo.Files/chem/sar_small.csv
2. Add a "Scaffold Tree" viewer and wait for tree generation to complete
3. Switch AND/OR via the "Bit Operation" property 
4. To switch bitwise NOT, select a substructure in the checkbox and click on the icon 
![scaffold-tree-filtering](https://user-images.githubusercontent.com/56073962/224307855-38b2ce03-b025-4214-966c-8c0845369501.gif)

**Comment by ahadzhanian** [comment]
Chem v 1.5.14

**Comment by ahadzhanian** [comment]
Change the icon for "Not" on click (both red and blue can be seen as enabled, change the icon appearance instead of color)

**Comment by dgosi** [comment]
The behavior of the NOT icon has been changed

**Comment by ahadzhanian** [comment]
The ability to add Scaffold Tree as an individual filter in a filter group is available in Chem 1.6.16
