### ISSUE TITLE
Wrong data is shown on line chart

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1628]
v1.13.2
**Case 1: row source = selected**
**Steps to reproduce:**
1. Open SPGI table
2. Add a line chart: 'Chemist 521' on X, 'Competition assay' on Y, split by 'Scaffold Names'
3. Set row source = selected
4. Start selecting some rows

**Expected results:** line chart is showing data according to selection.
**Actual results:** wrong data is shown (some points can be missing, some added unexpectedly). Some points do not have a dot marker:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/15780643/223071333-6f67a372-737d-4a73-8273-962484c32e5a.png">
<img width="600" alt="image" src="https://user-images.githubusercontent.com/15780643/223071628-0dd0c5b2-a565-4f96-832b-09d97548ba35.png">

**Comment by katerina-stepanova** [comment]
**Case 2: row source = filtered**
**Steps to reproduce:**
1. Open SPGI and configure line chart similar to the case above
2. Set row source = filtered
3. Open filter panel and add 'Id' as filtering column
4. Select only a few Ids

**Actual results:** some data is missing on the line chart, e.g. no point with 'chemist 21' on the image:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/15780643/223073661-fc26c287-903d-469b-928e-858de19c8e1c.png">

**Comment by katerina-stepanova** [comment]
Issue is not reproduced if 'Split by' is configured **after** selecting some rows:
1. Open SPGI table
2. Add a line chart: 'Chemist 521' on X, 'Competition assay' on Y
3. Set row source = selected
4. Select some rows
5. Configure line chart split by 'Scaffold Names' when some rows are already selected

**Comment by ahadzhanian** [comment]
DG v1.13.8
