### ISSUE TITLE
Selecting Pinned Columns

### ISSUE THREAD

**Issue by dgosi** [datagrok-ai/public#1631]
Adding the ability to select pinned columns like any regular column with Ctrl mouse click.

**Comment by onuf** [comment]
One more use case to cover -- users should be able to copy the selected data to the clipboard (select some pinned columns & some rows) . This doesn't seem to work with pinned columns (tried the same selection on pinned/regular columns, copy-paste works only on regular columns)

**Comment by dgosi** [comment]
The functionality to copy values from pinned columns was added in the version 1.1.17 of PowerGrid package

**Comment by ahadzhanian** [comment]
@dgosi please take a look! Can't properly select and copy data on pinned column. I'm testing on PowerGrid package 1.1.19
![Copy_pin_col](https://user-images.githubusercontent.com/111368431/224995740-f2c928f7-90da-4a0b-b263-59d3bd8172be.gif)
