### ISSUE TITLE
Filters re-ordering dialog is not opened if a custom filter was added to filters panel

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1637]
Filters re-ordering dialog is not opened if a custom filter was added to filters panel.
Error in console:
`html_dart2js.dart:3558 Cannot read properties of null (reading 'gj')
	https://gnfgrok.dev.nibr.novartis.net/packages/d4/src/common/column_grid.dart 600:21                         biW.
	https://gnfgrok.dev.nibr.novartis.net/packages/ddt/src/data_frame/column_types/string_column.dart 230:20     bT.zn
	https://gnfgrok.dev.nibr.novartis.net/packages/d4/src/common/column_grid.dart 374:5                          m..YM
	https://gnfgrok.dev.nibr.novartis.net/packages/d4/src/common/column_grid.dart 126:18                         m..ayo
	https://gnfgrok.dev.nibr.novartis.net/packages/$sdk/lib/async/stream_controller.dart 169:49                  Object.aKm
	https://gnfgrok.dev.nibr.novartis.net/packages/d4/src/filters/filters_core.dart 171:5                        pt.aXf
	https://gnfgrok.dev.nibr.novartis.net/packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2799:14      Up.eval
	https://gnfgrok.dev.nibr.novartis.net/packages/d4/src/events.dart 499:7                                      Object.yQ
	https://gnfgrok.dev.nibr.novartis.net/packages/d4/src/widgets/menu/menu.dart 112:7                           rU.a8s
	https://gnfgrok.dev.nibr.novartis.net/packages/d4/src/widgets/menu/menu.dart 165:33                          cf3.
	https://gnfgrok.dev.nibr.novartis.net/packages/$sdk/lib/html/dart2js/html_dart2js.dart 42920:48              d92.
	https://gnfgrok.dev.nibr.novartis.net/packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:48      fAJ.
	https://gnfgrok.dev.nibr.novartis.net/packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 474:16  NI.L9
	https://gnfgrok.dev.nibr.novartis.net/packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 59:16   Object.FP
	https://gnfgrok.dev.nibr.novartis.net/packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:14      fAH
	https://gnfgrok.dev.nibr.novartis.net/packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2476:14      HTMLDivElement.<fn>`

Same issue can be reproduced for 'Free text filter'.

**Comment by ahadzhanian** [comment]
DG v 1.14.0

**Comment by onuf** [comment]
Decided to include in patch `v1.13.9`
