### ISSUE TITLE
Structure is very small and not centered in the structure filter

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1642]
**Steps to reproduce:** 

1. Open a table
2. Open filter panel
3. Add some structure filter
4. Draw a structure, e.g. benzene ring

**Expected results:** Structure is centered and not too small.
**Actual results:** Structure is not at the center, it does not use all available space and is very small:
![image](https://user-images.githubusercontent.com/15780643/224318250-67c60a60-3083-4e7a-9d15-ce6a3f257394.png)

**Comment by onuf** [comment]
Chem version 1.5.1

**Comment by dionissqq** [comment]
@MariaDolotova can you look at this one?

**Comment by katerina-stepanova** [comment]
Structure size is increased slightly, but there is a lot of blank space left unused:
![2023-03-16_18-35-06 (1)](https://user-images.githubusercontent.com/15780643/225670388-eca5bddc-5916-44aa-a77c-524d3f8d28a3.gif)

**Comment by onuf** [comment]
@MariaDolotova please post the version of Chem where this behavior is fixed (I think it works fine in v1.5.18, but probably it comes from one of earlier versions)

**Comment by onuf** [comment]
Chem v1.5.17
