### ISSUE TITLE
Scaffold Tree fails on large dataset

### ISSUE THREAD

**Issue by tcarolan** [datagrok-ai/public#1675]
I wanted to bring to your attention an error I encountered when using the new Scaffold Tree. I am happy to provide more information if that helps debug. I am using Chem Package 1.5.11

Stacktrace from Console:

Chem:scaffoldTreeViewer()
result: Instance of ‘aOx’
Exception: IndexError: list index out of range
---------------------------------------------------------------------------IndexError Traceback (most recent call last)Cell In[3], line 125
116 return json_list
117 tree = sg.ScaffoldTree.from_dataframe(
118 data,
119 smiles_column=smilesColumn,
(…)
123 discharge_and_deradicalize=dischargeAndDeradicalize,
124 )
–> 125 res = get_json_representation(tree)
126 json_result = json.dumps(res)
127 result = json_result.replace("\n", “\n”)
Cell In[3], line 115, in get_json_representation(tree)
113 json_list = []
114 for scaffold in first_scaffolds:
–> 115 json_list.append(get_tree(tree, scaffold[0]))
116 return json_list
Cell In[3], line 108, in get_tree(tree, scaffold_1)
106 else:
107 parent = parent_lookup(sorted_scaffolds[i], sorted_scaffolds, hierarchies)
–> 108 recurs_append_nodes(‘smiles’, parent, hierarchy_dict, json_list[0])
109 return json_list[0]
Cell In[3], line 30, in recurs_append_nodes(key, value, node, obj)
28 for k, v in obj.items():
29 if type(v) == list:
—> 30 result = recurs_append_nodes(key, value, node, v[0])
Cell In[3], line 30, in recurs_append_nodes(key, value, node, obj)
28 for k, v in obj.items():
29 if type(v) == list:
—> 30 result = recurs_append_nodes(key, value, node, v[0])
[… skipping similar frames: recurs_append_nodes at line 30 (2 times)]
Cell In[3], line 30, in recurs_append_nodes(key, value, node, obj)
28 for k, v in obj.items():
29 if type(v) == list:
—> 30 result = recurs_append_nodes(key, value, node, v[0])
IndexError: list index out of range

![385bffe9ecfb157d134328ef9b254da54d901454](https://user-images.githubusercontent.com/6126004/225407602-e64188ad-8710-41a4-81c3-9ff3cbacef7f.png)

**Comment by skalkin** [comment]
Hi @dgosi , any updates on that? It really shouldn't depend on the size of the dataset since we are doing sampling when the dataset is too large.

**Comment by dgosi** [comment]
It doesn't depend on the size, it just fails on a particular data set unrelated to size.

**Comment by dgosi** [comment]
The issue was reproduced. @Aleksashka11, will debug the python package causing this error.

**Comment by dgosi** [comment]
Thank you, @Aleksashka11, for the help! The issue has been addressed. The fix is available in v.1.5.16 of Chem package.
