### ISSUE TITLE
'Extract Selected Rows' creates table with exact same table name

### ISSUE THREAD

**Issue by tcarolan** [datagrok-ai/public#1676]
Under the 'Select' menu when choosing 'Extract Selected Rows' the new table that is created is given the exact same table name. This causes problems when distinguishing between the different tables. Particularly when using the 'Chemical Space' tool. There is no way to differentiate and the Chemical Space values are always added to the first table, not the extracted table.

**Comment by skalkin** [comment]
Hi @tcarolan , how do I reproduce it? When I do "Extract Selected Rows", a postfix gets added that lets you differentiate between tables. I.e., "smiles" becomes "smiles (2)", then "smiles (3)", etc

**Comment by tcarolan** [comment]
Hi Andrew, Please see the attached video. This must be a case when the postfix is not added. The data is loaded from a DB query. Oddly, if I execute the 'Extract Selected Rows' a second time the postfix is added "(2)" but the first two duplicate tables remain. 

https://user-images.githubusercontent.com/6126004/228627315-2c4581f6-8b19-492d-90c0-c9a4608f1543.mp4

**Comment by tcarolan** [comment]
I'm not sure if this was fixed but it appears to not be a problem in my current 1.14.1 version. 
![image](https://user-images.githubusercontent.com/6126004/235794882-9433f958-05d9-4843-94c5-0ada3e3f148d.png)
