### ISSUE TITLE
Snowflake Doubles interpreted at Integers

### ISSUE THREAD

**Issue by tcarolan** [datagrok-ai/public#1678]
Tables with column types of 'Double' are interpreted by Datagrok as type 'int'. 

I can work with the developer to show the error if that will help.

**Comment by PavloPolovyi** [comment]
https://reddata.atlassian.net/browse/GROK-12510

**Comment by PavloPolovyi** [comment]
Please tell me which version of the Grok Connect you are using?

**Comment by tcarolan** [comment]
Hi Pavlo, The column in Snowflake is defined as a FLOAT. Datagrok server was recently upgraded to 1.13.7. I am not sure what version of Grok Connect I have. Please let me know how to find this information and I will provide it. 
![Screenshot 2023-03-16 100242](https://user-images.githubusercontent.com/6126004/225710768-43665266-7c8c-4202-8b0a-d391adcd6cf6.png)
![Screenshot 2023-03-16 100308](https://user-images.githubusercontent.com/6126004/225710777-05291474-9568-4dbd-bbb8-137f555fdfeb.png)

**Comment by PavloPolovyi** [comment]
Could you please provide creational script of this table? SELECT GET_DDL('TABLE', 'schema.TABLE_NAME');

**Comment by tcarolan** [comment]
> Could you please provide creational script of this table? SELECT GET_DDL('TABLE', 'schema.TABLE_NAME');

create or replace TABLE SCREENS (
	NAME VARCHAR(16777216),
	SMILES VARCHAR(16777216),
	MOLECULAR_WEIGHT FLOAT,
	LOG_P NUMBER(20,3),
	NUM_H_BOND_DONORS NUMBER(38,0),
	NUM_RULE_OF_5_VIOLATIONS NUMBER(38,0),
	HEAVY_ATOM_COUNT NUMBER(38,0),
	NUM_ROTATABLE_BONDS NUMBER(38,0),
	IUPAC_NAME VARCHAR(16777216),
	INCHI_KEY VARCHAR(16777216),
	OWNER VARCHAR(16777216),
	CREATED_AT TIMESTAMP_NTZ(9),
	BATCHES ARRAY
);

**Comment by tcarolan** [comment]
> And please, try to clear cache of connection if possible and run again query.

I cleared the cache for the connection, but get the same result.

**Comment by PavloPolovyi** [comment]
Hi, Tom. I have made some investigations and it turned out that you use the older version of Grok Conne - 1.3.1. Support for Snowflake was corrected in newer versions of GC. Please contact Sofia Podolskaya to update your Grok Connect.

**Comment by tcarolan** [comment]
Thank you Pavlo for investigating. I will have Grok Connect upgraded.

**Comment by tcarolan** [comment]
Hi Pavlo, Confirming that the upgrade to the latest Grok Connect fixed this issue. Thanks!
