### ISSUE TITLE
#168: Core: settings icon is not shown in panel widgets

### ISSUE THREAD

**Issue by vdyma** [datagrok-ai/public#168]
In property panel widgets there is no settings icon which makes it impossible to hide that specific widget.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14763

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16023

**Comment by skalkin** [comment]
Now you can hide each panel
