### ISSUE TITLE
Table is not rendered properly after switching dataframe if it was sorted

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1724]
v.1.13.*

**Steps to reproduce:**
1. Open two different tables with different rows/columns: simple table from attached file: [ForDG.csv](https://github.com/datagrok-ai/public/files/11018221/ForDG.csv) and SPGI
2. Sort SPGI table on some column that is not present in the 2nd table
3. Click the cog icon to open currently shown table's properties
4. Switch dataframe to another tabble

**Expected results:** data from the selected dataframe is shown, no rendering issues.
**Actual results:** Wrong number of rows is shown, data is not rendered properly (red crosses):
![2023-03-20_16-15-40 (1)](https://user-images.githubusercontent.com/15780643/226351164-6b057945-fb4d-4857-b966-963ca25546d4.gif)

Issue is not reproduced if no sorting was set before switching dataframe.

**Comment by onuf** [comment]
Decided to include in patch `v1.13.9`
