### ISSUE TITLE
Pinned Columns: Id link is not clickable

### ISSUE THREAD

**Issue by onuf** [datagrok-ai/public#1726]
Id link is not clickable if column is pinned.
**Steps to reproduce:** 

1. Open an analysis
2. Pin Id column
3. Click some Id link

**Expected results**: Link should be clickable in the pinned column.
**Actual results:** Id link is not clickable if column is pinned (nothing happens on click, no errors in console).

**Comment by dgosi** [comment]
The fix is available in v. 1.1.21 of PowerGrid package
