### ISSUE TITLE
Grok Connect: Snowflake handling of doubles, infinity, -infinity, NaN, and large scale floating point numbers

### ISSUE THREAD

**Issue by tcarolan** [datagrok-ai/public#1732]
There are a few issues with Grok Connect handling of floating point numbers from Snowflake driver. To reproduce I created a test table with a FLOAT, INTEGER, and DESCRIPTION columns. Then populated it with large, small, infinity, -infinity, NaN, and large scale floating points. The results from a Datagrok query show problems with large scale floating points and very large negative floating points. Everything else seemed to interpret correctly. 

However, some visualizations fail because of misinterpreting numbers as NaN. Visualizations like the 'PC Plot' and 'Correlation Plot' do not handle the NaN case and will fail with Javascript errors. Please see screen video.  

Please let me know if doing a screenshare meeting will help expediate the fixes. Thanks and best regards,

Test Table:
create or replace TABLE NEOMORPH.NEODATA.TEST_TABLE_FLOAT (
	BIG_NUMBER FLOAT,
	BIG_INTEGER NUMBER(38,0),
	DESCRIPTION VARCHAR(16777216),
	constraint TEST_TABLE_FLOAT_pk primary key (DESCRIPTION)
);

INSERT INTO NEOMORPH.NEODATA.TEST_TABLE_FLOAT (BIG_NUMBER, BIG_INTEGER, DESCRIPTION) VALUES (-17.0000121231235, -17, 'neg_scale');
INSERT INTO NEOMORPH.NEODATA.TEST_TABLE_FLOAT (BIG_NUMBER, BIG_INTEGER, DESCRIPTION) VALUES (100000000000000000000000000000000000000, 99999999999999999999999999999999999999, 'high');
INSERT INTO NEOMORPH.NEODATA.TEST_TABLE_FLOAT (BIG_NUMBER, BIG_INTEGER, DESCRIPTION) VALUES (-100000000000000000000000000000000000000, -99999999999999999999999999999999999999, 'low');
INSERT INTO NEOMORPH.NEODATA.TEST_TABLE_FLOAT (BIG_NUMBER, BIG_INTEGER, DESCRIPTION) VALUES (17.1564654654654, 17, 'pos_scale');
INSERT INTO NEOMORPH.NEODATA.TEST_TABLE_FLOAT (BIG_NUMBER, BIG_INTEGER, DESCRIPTION) VALUES ('NaN', null, 'NaN');
INSERT INTO NEOMORPH.NEODATA.TEST_TABLE_FLOAT (BIG_NUMBER, BIG_INTEGER, DESCRIPTION) VALUES ('Infinity', null, 'inf');
INSERT INTO NEOMORPH.NEODATA.TEST_TABLE_FLOAT (BIG_NUMBER, BIG_INTEGER, DESCRIPTION) VALUES ('-Infinity', null, '-inf');

![Screenshot 2023-03-21 175944](https://user-images.githubusercontent.com/6126004/226775400-59bec13e-f7c1-4513-8a7e-5cb69dc4c831.png)
![Screenshot 2023-03-21 180058](https://user-images.githubusercontent.com/6126004/226775404-87fe3591-c817-4f0d-910e-8f97c0e5dfe3.png)

https://user-images.githubusercontent.com/6126004/226775898-4800b35f-64b7-4087-b100-c20d94b2be13.mp4

**Comment by PavloPolovyi** [comment]
Hi, Tom, sorry for this trouble. Problem with incorrect display of doubles will be fixed in the 1.14.0 version of Datagrok. Another problem with Visualizations is more complex and we think about how it can be fixed.

**Comment by ahadzhanian** [comment]
DG v.1.14.0

**Comment by tcarolan** [comment]
I'm using DG 1.14.1 and the issues with large/small, NaN, +/-Infinity appear to be fixed, at least on the driver support level. Fixing all the viewers is a different issue. Thank you for addressing this.

**Comment by tcarolan** [comment]
![Screenshot 2023-05-02 144052](https://user-images.githubusercontent.com/6126004/235793171-cabb0655-4137-4644-9958-08ba2887aeea.png)

**Comment by ahadzhanian** [comment]
Hello Tom! Thank you for giving your feedback.
