### ISSUE TITLE
Table is unexpectedly filtered if scatter plot has 'filter by zoom' setting and empty column on log scale axis

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1744]
**Steps to reproduce:** 
1. Open a table that has a numerical column with no values
2. Add scatter plot
3. Set zoom and filter = 'filter by zoom'
4. Switch one of the axes to the log scale and select numerical column with no values for it

**Expected results:** No data on scatter plot, but table is not filtered.
**Actual results:** All table values are unexpectedly filtered out:
![2023-03-22_18-05-21 (1)](https://user-images.githubusercontent.com/15780643/228271840-b71dab96-f8d1-4c51-9f05-4e303967bd5e.gif)
Issue does not happen for linear axes.

**Comment by ahadzhanian** [comment]
Reproduce this bug with errors

![1744](https://user-images.githubusercontent.com/111368431/229764561-9912f696-8c82-46b9-abc0-c78392641d05.gif)

Viewport can't be infinite: (NaN, 6.050000000000003, NaN, 20.899999999999995)
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1772:17                   Object.u
	packages/d4/src/viewer_base/canvas_viewport_mixin.dart 48:20                        k4.shm
	packages/d4/src/scatterplot/scatterplot_core.dart 907:5                             [k4.ke](http://k4.ke/)
	packages/d4/src/scatterplot/scatterplot_core.dart 137:7                             k4.dF
	packages/d4/src/viewer_base/viewer_base.dart 107:9                                  d5C.
	packages/$sdk/lib/async/zone.dart 1132:12                                           aYA
	packages/$sdk/lib/async/zone.dart 1012:12                                           dag.Al
	packages/$sdk/lib/async/zone.dart 909:14                                            dag.Hy
	packages/$sdk/lib/async/stream_impl.dart 330:5                                      [d9H.aw](http://d9h.aw/)
	packages/$sdk/lib/async/stream_impl.dart 257:7                                      o7.lg
	packages/$sdk/lib/async/broadcast_stream_controller.dart 387:7                      djf.
	packages/$sdk/lib/async/broadcast_stream_controller.dart 328:9                      x.a6Z
	packages/$sdk/lib/async/broadcast_stream_controller.dart 386:5                      [x.aw](http://x.aw/)
	packages/$sdk/lib/async/broadcast_stream_controller.dart 254:5                      Aw.a0W
	packages/prop_gen/property.dart 149:11                                              cyV.
	packages/xamgle/src/property_grid/prop_grid.dart 127:39                             e3Q.
	packages/xamgle/src/property_grid/prop_grid.dart 98:16                              e3T.
	packages/xamgle/src/property_grid/editors/property_view_column_selector.dart 16:20  cy2.
	packages/$sdk/lib/async/zone.dart 1128:37                                           aYA
	packages/$sdk/lib/async/zone.dart 1012:12                                           dag.Al
	packages/$sdk/lib/async/zone.dart 909:14                                            dag.Hy
	packages/$sdk/lib/async/stream_impl.dart 330:5                                      [d9H.aw](http://d9h.aw/)
	packages/$sdk/lib/async/stream_impl.dart 257:7                                      o7.lg
	packages/$sdk/lib/async/broadcast_stream_controller.dart 379:7                      [x.aw](http://x.aw/)
	packages/$sdk/lib/async/broadcast_stream_controller.dart 254:5                      xJ.u
	packages/ddt/src/events/event_bus.dart 69:7                                         C.a6
	packages/d4/src/common/column_combo_box.dart 67:9                                   [rJ.IN](http://rj.in/)
	packages/d4/src/common/column_combo_box.dart 53:36                                  bju.
	packages/$sdk/lib/async/zone.dart 1116:37                                           aYy
	packages/$sdk/lib/async/zone.dart 1001:12                                           dag.fC
	packages/$sdk/lib/async/zone.dart 901:14                                            dag.Hx
	packages/$sdk/lib/async/zone.dart 926:20                                            dah.
	packages/$sdk/lib/async/zone.dart 1120:12                                           aYy
	packages/$sdk/lib/async/zone.dart 1001:12                                           dag.fC
	packages/$sdk/lib/async/zone.dart 901:14                                            dag.Hx
	packages/$sdk/lib/async/zone.dart 926:20                                            dah.
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 1393:9               cW2.
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2454:48                   fHq.
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 474:16               [O9.LK](http://o9.lk/)
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 59:16                Object.G1
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2454:14                   fHp
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2476:14                   <fn>
	
aqM @ logging.dart:95
cB @ log.dart:89
dart.Lu.any @ log.dart:131
dart.Lu.any @ log.dart:131
(anonymous) @ login.dart:173
(anonymous) @ async_patch.dart:213
dart.e0F.$2 @ login.dart.js?30987:4012
dart.dkG.$1 @ login.dart.js?30987:4008
Al @ login.dart.js?30987:5794
$0 @ future_impl.dart:637
xL @ zone.dart:632
dart.ddt.$0 @ login.dart.js?30987:4432
dYI @ login.dart.js?30987:3836
dart.h3d @ schedule_microtask.dart:53
dart.d91.$1 @ login.dart.js?30987:3994
$0 @ login.dart.js?30987:3109
LK @ isolate_helper.dart:475
G1 @ isolate_helper.dart:61
dart.fHp @ js_helper.dart:2458
(anonymous) @ js_helper.dart:2489
childList (async)
$1 @ login.dart.js?30987:4000
aYF @ login.dart.js?30987:3844
dart.a2R @ login.dart.js?30987:3945
ys @ zone.dart:1395
Tc @ future_impl.dart:348
a8l @ future_impl.dart:252
a2d @ async_patch.dart:212
o @ login.dart.js?30987:3755
dart.fI9.$2 @ login.dart.js?30987:18142
dart.aYz @ zone.dart:1144
a33 @ zone.dart:1380
dart.fO0.$5 @ zone.dart:1445
aof @ zone.dart:669
dart.fO0.$5 @ login.dart.js?30987:5820
vB @ zone.dart:985
Hy @ zone.dart:911
aw @ stream_impl.dart:331
dart.o7.lg @ stream_impl.dart:577
$1 @ login.dart.js?30987:4171
a6Z @ broadcast_stream_controller.dart:328
aw @ broadcast_stream_controller.dart:391
a0W @ prop_gen_annotation.dart:649
dart.cyV.$2 @ login.dart.js?30987:15917
km @ login.dart.js?30987:15904
J.bV @ login.dart.js?30987:18820
$1 @ login.dart.js_1.part.js?30987:157423
dart.e3T.$1 @ login.dart.js_1.part.js?30987:157401
dart.cy2.$1 @ property_view_ellipsis_editor.dart:18
dart.aYA @ zone.dart:621
Al @ zone.dart:1016
Hy @ zone.dart:909
aw @ stream_impl.dart:331
dart.o7.lg @ stream_impl.dart:577
aw @ broadcast_stream_controller.dart:379
dart.xJ.u @ broadcast_stream_controller.dart:257
[J.ae](http://j.ae/) @ login.dart.js?30987:18234
a6 @ event_bus.dart:83
IN @ column_combo_box.dart:67
h2 @ login.dart.js_1.part.js?30987:14880
dart.bju.$0 @ column_combo_box.dart:53
dart.aYy @ zone.dart:621
dart.dag.fC @ zone.dart:1005
Hx @ zone.dart:901
dart.dah.$0 @ login.dart.js?30987:5727
dart.aYy @ zone.dart:1120
dart.dag.fC @ zone.dart:1005
Hx @ zone.dart:901
dart.dah.$0 @ login.dart.js?30987:5727
dart.cW2.$0 @ login.dart.js?30987:2067
$0 @ login.dart.js?30987:3107
LK @ isolate_helper.dart:475
G1 @ isolate_helper.dart:61
dart.fHp @ js_helper.dart:2456
(anonymous) @ js_helper.dart:2489
setTimeout (async)
aD_ @ login.dart.js?30987:2054
cVZ @ isolate_helper.dart:1369
a0f @ async_patch.dart:125
dart.h30 @ zone.dart:1193
Cb @ zone.dart:1087
cc @ timer.dart:71
dart.bjv.$1 @ column_combo_box.dart:353
dart.aYA @ zone.dart:621
Al @ zone.dart:1016
Hy @ zone.dart:909
aw @ stream_impl.dart:331
dart.o7.lg @ stream_impl.dart:577
$1 @ login.dart.js?30987:4171
a6Z @ broadcast_stream_controller.dart:328
aw @ broadcast_stream_controller.dart:391
dart.xJ.u @ broadcast_stream_controller.dart:257
[J.ae](http://j.ae/) @ login.dart.js?30987:18234
a6 @ event_bus.dart:83
bI @ event_bus.dart:83
soG @ notifier.dart:32
dart.eD.ai2 @ data_frame_viewer.dart:123
eval @ VM3344:3
dart.aYA @ zone.dart:621
Al @ zone.dart:1016
Hy @ zone.dart:909
aw @ stream_impl.dart:331
dart.o7.lg @ stream_impl.dart:577
lg @ stream_pipe.dart:135
Bv @ login.dart.js?30987:5462
dart.O4.aG8 @ stream_pipe.dart:168
eval @ VM3215:3
dart.dcy.$1 @ login.dart.js?30987:13057
dart.aYA @ zone.dart:1132
Al @ zone.dart:1016
Hy @ zone.dart:909
dart.daj.$1 @ login.dart.js?30987:5731
$0 @ login.dart.js?30987:3109
LK @ isolate_helper.dart:475
G1 @ isolate_helper.dart:61
dart.fHp @ js_helper.dart:2458
(anonymous) @ js_helper.dart:2489
logging.dart:95 Unsupported operation: NaN.ceil()
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1772:17      Object.u
	packages/d4/src/axes/axis.dart 240:53                                  Object.J.
	packages/d4/src/axes/axis.dart 39:21                                   Object.rG
	packages/d4/src/scatterplot/scatterplot_core.dart 1105:7               k4.a7l
	packages/d4/src/scatterplot/scatterplot_core.dart 1175:7               k4.ji
	packages/d4/src/viewer_base/canvas_viewer_mixin.dart 169:7             k4.a8.
	packages/d4/src/viewer_base/canvas_viewer_mixin.dart 106:9             beN.
	packages/$sdk/lib/async/zone.dart 1132:12                              aYA
	packages/$sdk/lib/async/zone.dart 1012:12                              dag.Al
	packages/$sdk/lib/async/zone.dart 909:14                               dag.Hy
	packages/$sdk/lib/async/zone.dart 936:23                               daj.
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:48      fHr.
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 474:16  [O9.LK](http://o9.lk/)
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 59:16   Object.G1
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:14      fHp
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2476:14      <fn>
```

**Comment by ahadzhanian** [comment]
The dataset for testing
[fruits_.csv](https://github.com/datagrok-ai/public/files/11147804/fruits_.csv)

**Comment by ahadzhanian** [comment]
@dionissqq new error occurs:
```
html_dart2js.dart:3558 Wrong range: -0.5 <= NaN <= 0.55 <= 0.55}
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1772:17                   Object.u
	packages/d4/src/widgets/range_selector/range_selector.dart 84:45                    pY.f9
	packages/d4/src/viewer_base/canvas_viewport_mixin.dart 76:19                        k4.shG
	packages/d4/src/scatterplot/scatterplot_core.dart 921:5                             k4.kf
	packages/d4/src/scatterplot/scatterplot_core.dart 137:7                             k4.dF
	packages/d4/src/viewer_base/viewer_base.dart 107:9                                  d5L.
	packages/$sdk/lib/async/zone.dart 1132:12                                           aYD
	packages/$sdk/lib/async/zone.dart 1012:12                                           dap.Al
	packages/$sdk/lib/async/zone.dart 909:14                                            dap.Hz
	packages/$sdk/lib/async/stream_impl.dart 330:5                                      d9Q.aw
	packages/$sdk/lib/async/stream_impl.dart 257:7                                      o7.li
	packages/$sdk/lib/async/broadcast_stream_controller.dart 387:7                      djq.
	packages/$sdk/lib/async/broadcast_stream_controller.dart 328:9                      y.a70
	packages/$sdk/lib/async/broadcast_stream_controller.dart 386:5                      y.aw
	packages/$sdk/lib/async/broadcast_stream_controller.dart 254:5                      xj.a0V
	packages/prop_gen/property.dart 149:11                                              cz3.
	packages/xamgle/src/property_grid/prop_grid.dart 127:39                             e4b.
	packages/xamgle/src/property_grid/prop_grid.dart 98:16                              e4e.
	packages/xamgle/src/property_grid/editors/property_view_column_selector.dart 16:20  cyb.
	packages/$sdk/lib/async/zone.dart 1128:37                                           aYD
	packages/$sdk/lib/async/zone.dart 1012:12                                           dap.Al
	packages/$sdk/lib/async/zone.dart 909:14                                            dap.Hz
	packages/$sdk/lib/async/stream_impl.dart 330:5                                      d9Q.aw
	packages/$sdk/lib/async/stream_impl.dart 257:7                                      o7.li
	packages/$sdk/lib/async/broadcast_stream_controller.dart 379:7                      y.aw
	packages/$sdk/lib/async/broadcast_stream_controller.dart 254:5                      xM.u
	packages/ddt/src/events/event_bus.dart 69:7                                         C.a6
	packages/d4/src/common/column_combo_box.dart 67:9                                   rJ.IN
	packages/d4/src/common/column_combo_box.dart 53:36                                  bjx.
	packages/$sdk/lib/async/zone.dart 1116:37                                           aYB
	packages/$sdk/lib/async/zone.dart 1001:12                                           dap.fC
	packages/$sdk/lib/async/zone.dart 901:14                                            dap.Hy
	packages/$sdk/lib/async/zone.dart 926:20                                            daq.
	packages/$sdk/lib/async/zone.dart 1120:12                                           aYB
	packages/$sdk/lib/async/zone.dart 1001:12                                           dap.fC
	packages/$sdk/lib/async/zone.dart 901:14                                            dap.Hy
	packages/$sdk/lib/async/zone.dart 926:20                                            daq.
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 1393:9               cWb.
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2454:48                   fHS.
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 474:16               O9.LJ
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 59:16                Object.G1
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2454:14                   fHR
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2476:14                   <fn>
```

**Comment by ahadzhanian** [comment]
DG 1.14.1
