### ISSUE TITLE
Floating viewer appears unexpectedly on applying layout in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1745]
**Steps to reproduce:** 
1. Open table, e.g. SPGI
2. Add some viewer and stack it over the table (dock type fill)
3. Click 'x' either for the stacked viewer or for the table
4. Save layout
5. Re-apply saved layout

**Expected results:** No floating viewers appearing unexpectedly.
**Actual results:** Floating viewer (the one removed on step 3) appears on applying layout:
![2023-03-22_16-48-54 (1)](https://user-images.githubusercontent.com/15780643/228272566-bf441345-332e-4972-a0ca-77af952a131a.gif)

**Comment by alex-aprm** [comment]
Fixed in 1.14.1
