### ISSUE TITLE
PowerPack: Add new column dialog fails to execute some function calls

### ISSUE THREAD

**Issue by onuf** [datagrok-ai/public#1748]
![image](https://user-images.githubusercontent.com/56073962/228323017-a4ab5334-a02a-4eba-bbb1-fbdeb645d749.png)

**Comment by ahadzhanian** [comment]
The Date() function doesn't parse strings like `03` as numbers `3`.



![Image](https://user-images.githubusercontent.com/111368431/228842495-99027ece-11c9-4915-b84a-3d27947e582f.png)

**Comment by onuf** [comment]
@ahadzhanian I think it's okay as long as it is consistent with the DG console behavior (such expression won't work from the console either)
