### ISSUE TITLE
Out of memory on adding viewer with specific data

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1761]
v1.13.10

**Steps to reproduce:**
1. Open table from this file: 
[OOMscatter plot small.csv](https://github.com/datagrok-ai/public/files/11146965/OOMscatter.plot.small.csv)
2. Add scatter plot or histogram

**Expected results:** viewer is added without issues.
**Actual results:** browser tab freezes and crashes with 'out of memory' error after a while.

**Comment by ahadzhanian** [comment]
DG v. 1.14.1
