### ISSUE TITLE
Error loading scatter plot for specific data and log scale axes on applying layout

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1764]
v.1.13.10

**Steps to reproduce:** 
1. Load table from attached file in DG:
[BrokenScatterPlots.csv](https://github.com/datagrok-ai/public/files/11160898/BrokenScatterPlots.csv)
2. Add scatter plots:
 -Categorical column on one axis, one of the two numerical columns on another axis
 -Numerical columns on both axes
3. Switch axes with numerical columns to log scale
4. Save layout
5. Re-apply saved layout

**Expected results:** Scatter plots are displayed after applying layout.

**Actual results:** Error loading scatter plots:
`html_dart2js.dart:41505 Error: <circle> attribute cy: Expected length, "NaN".
adB @ html_dart2js.dart:41505
qp @ range_selector.dart:228
ff @ range_selector.dart:98
shb @ canvas_viewport_mixin.dart:47
dart.lq.kR @ scatterplot_core.dart:870
dE @ scatterplot_core.dart:134
fm @ login.dart.js_1.part.js?5151:35393
y5 @ viewer_base.dart:43
a9D @ viewer_descriptor.dart:87
Lu @ login.dart.js_1.part.js?5151:17256
J.b5S @ login.dart.js?5151:18496
$2 @ table_view.dart:971
aAH @ panel_dock_container.dart:74
YH @ panel_dock_container.dart:63
aDL @ dock_graph_deserializer.dart:62
afX @ dock_graph_deserializer.dart:38
dart.bBz.$1 @ dock_graph_deserializer.dart:33
ao @ js_array.dart:252
J.co @ login.dart.js?5151:18226
afX @ dock_graph_deserializer.dart:32
tv @ dock_graph_deserializer.dart:13
tV @ dock_manager.dart:388
ZZ @ table_view.dart:990
yJ @ table_view.dart:949
$1 @ viewer_suggestions.dart:103
dart.d9k.$1 @ html_dart2js.dart:42920
dart.aXo @ zone.dart:1132
zZ @ zone.dart:1012
H4 @ zone.dart:909
dart.d75.$1 @ zone.dart:936
$0 @ js_helper.dart:2456
Lb @ isolate_helper.dart:474
FR @ isolate_helper.dart:59
dart.fB3 @ js_helper.dart:2456
(anonymous) @ js_helper.dart:2476
19:18:11.316 html_dart2js.dart:3558 Unsupported operation: NaN.round()
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1772:17      Object.u
	packages/d4/src/common/svg_viewer_mixin.dart 72:28                     pP.qp
	packages/d4/src/widgets/range_selector/range_selector.dart 98:5        pP.ff
	packages/d4/src/viewer_base/canvas_viewport_mixin.dart 47:19           lq.shb
	packages/d4/src/scatterplot/scatterplot_core.dart 870:5                lq.kR
	packages/d4/src/scatterplot/scatterplot_core.dart 134:7                lq.dE
	packages/d4/src/viewer_base/viewer_base.dart 43:5                      lq.y5
	packages/d4/src/common/viewer_descriptor.dart 87:7                     cC4.a9D
	packages/xamgle/src/views/table_view.dart 971:29                       cQ..
	packages/dock_spawn/containers/panel_dock_container.dart 74:29         je.aAH
	packages/dock_spawn/containers/panel_dock_container.dart 63:3          Object.YH
	packages/dock_spawn/serialization/dock_graph_deserializer.dart 62:19   bBy.aDL
	packages/dock_spawn/serialization/dock_graph_deserializer.dart 38:32   bBy.afX
	packages/dock_spawn/serialization/dock_graph_deserializer.dart 33:28   bBz.
	packages/$sdk/lib/_internal/js_runtime/lib/js_array.dart 252:7         av.ao
	packages/dock_spawn/serialization/dock_graph_deserializer.dart 32:5    bBy.afX
	packages/dock_spawn/serialization/dock_graph_deserializer.dart 13:22   bBy.tv
	packages/dock_spawn/dock/dock_manager.dart 388:17                      nF.tV
	packages/xamgle/src/views/table_view.dart 990:5                        bt.ZZ
	packages/xamgle/src/views/table_view.dart 949:86                       bt.yJ
	packages/xamgle/src/features/viewer_suggestions.dart 103:5             c6..
	packages/$sdk/lib/html/dart2js/html_dart2js.dart 42920:48              d9k.
	packages/$sdk/lib/async/zone.dart 1132:12                              aXo
	packages/$sdk/lib/async/zone.dart 1012:12                              d72.zZ
	packages/$sdk/lib/async/zone.dart 909:14                               d72.H4
	packages/$sdk/lib/async/zone.dart 936:23                               d75.
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:48      fB5.
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 474:16  NJ.Lb
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 59:16   Object.FR
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:14      fB3
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2476:14      HTMLDivElement.<fn>
	`

This case could be related to #1613

**Comment by ahadzhanian** [comment]
DG 1.14.1
