### ISSUE TITLE
Viewers: Organize properties consistently in the context panel

### ISSUE THREAD

**Issue by onuf** [datagrok-ai/public#1778]
- [x] Move Label orientation to Style (PC Plot; the same applies for other viewers with this property)
- [x] Move Segments Font to Style (Line Chart)
- [x] Move tooltip properties from Misc to Tooltip and column properties from Misc to Columns (Heatmap, Table)
- [x] Rename 'Point' to 'Line' (PC Plot)
- [ ] Use the same order of categories for different viewers (see the slide)

**Comment by onuf** [comment]
![image](https://user-images.githubusercontent.com/56073962/231217815-66562880-4ab5-4656-8862-6fd6d7e48019.png)
![image](https://user-images.githubusercontent.com/56073962/231217837-594fd598-cf31-430b-9879-09f792430004.png)

**Comment by ahadzhanian** [comment]
DG 1.14.1

**Comment by Recca-Gottschall** [comment]
On the property panel harmonization = First screenshot. During our meeting in April, we agreed together to move "Label Orientation" to the Styles category across all chart types, where applicable. It's strange, on the Miro board it was documented but your screenshot doesn't capture it. For PC Plot the change was changed, but for Heatmap&Table this property still needs to be moved to "Style".
![image](https://github.com/datagrok-ai/public/assets/108325558/5f59d10c-f209-4a22-99e3-1b10b21ef91f)

**Comment by ahadzhanian** [comment]
Moved "Col Label Orientation" to the Styles category for heatmap and grid
Fixed in 1.15.3
