### ISSUE TITLE
Line chart with logarithmic Y axis is rendering data points incorrectly

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1808]
v.1.13.* (regression)

**Steps to reproduce:**
1. Open the table: 
[LineChartIssue.csv](https://github.com/datagrok-ai/public/files/11259152/LineChartIssue.csv)
2. Add line chart: Sample Time on X axis, another column on Y axis
3. Switch Y axis to log scale

**Expected results:** Line chart should correlate with data in the table, i.e. higher sample time corresponds to lower Does-Normalised values.
**Actual results:** Line chart does not correspond to actual data:
<img width="533" alt="image" src="https://user-images.githubusercontent.com/15780643/232707126-266f626d-9850-4f1f-8732-7c46f124a71e.png">

**Comment by ahadzhanian** [comment]
DG 1.13.13
