### ISSUE TITLE
Filters cannot be enabled if all filters were disabled in another view

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1837]
DG 1.14.1

**Steps to reproduce:**
1. Open a table
2. Open filters
3. Add another view for the same table
4. Open filters in 2nd view too
5. Disable all filters in view1
6. Switch to view2 > filters are disabled
7. Re-enable filters in view2

**Expected results:** filters are re-enabled, filter state stays consistent across all views after switching them on/off in any view.

**Actual results:** it's not possible to re-enable filters from view2 if they were disabled in view1.

This is a follow-up ticket for #1460 and #1589

**Comment by ahadzhanian** [comment]
DG 1.14.4
