### ISSUE TITLE
Compute: function parameter editor

### ISSUE THREAD

**Issue by skalkin** [datagrok-ai/public#184]
A tool for visual annotation of the  function parameters that would be especially useful for the auto-generated UI. 

- guided editing with suggestions
- immediate preview of the auto-generated UI

**Comment by dskatov** [comment]
@AufarZakiev please instruct what's left to get done on the Function Editor.
(I would consider tests, documentation, video)

**Comment by AufarZakiev** [comment]
@dskatov all info is stored here: https://github.com/datagrok-ai/public/issues/208

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14919

**Comment by AufarZakiev** [comment]
Closing as #208 is closed
