### ISSUE TITLE
Calculated columns: errors on missing values

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1840]
**Steps to reproduce:**
1. Open a table that has column with qualifiers, e.g. 
[ForDGWithSigns.csv](https://github.com/datagrok-ai/public/files/11324437/ForDGWithSigns.csv)
2. Add a calculated formula

**Actual results:**
The Qnum() function generates errors on missing values:

Qnum((100-${withSigns2})/100, if(qualifier(${withSigns2})==">", "<", "="))
returns "NullError: method not found: 'toString' on null" on missing values

Qnum((100-${withSigns2})/100, if(isnotempty("${withSigns2}"), if(qualifier(${withSigns2})==">", "<", "="), null))
returns "NullError: method not found: 'toString' on null" on missing values

**Comment by ahadzhanian** [comment]
DG 1.15.0
