### ISSUE TITLE
Line chart with splitting with specific data is making Datagrok slow (row selection, interaction with line chart)

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1852]
**Steps to reproduce:**
1. Open a table with 7-8K rows
2. Add a line chart with numerical columns on X and Y axes
3. Split line chart by a column with ~1-2K categories
4. Other properties leave defaults

**Expected results:** Line chart and table are responsive.
**Actual results:** row selection in the table becomes slow. Interaction with line chart itself is also slow (e.g. zooming).

Issue can be reproduce on specific data (non-public).

**Comment by skalkin** [comment]
Correction: we are still looking for ways to improve the rendering performance in this case.
