### ISSUE TITLE
"Pack and zoom by filter": some data is missing

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1855]
**Steps to reproduce:**
1. Open SPGI table
2. Add a scatter plot
3. Set 'Chemical Space Y' as an Y axis
4. Switch scatter plot to 'pack and zoom by filter'
5. Change X axis to a categorical one, e.g. 'Stereo Category'
6. Change X axis 'Chemical Space X'
7. Compare data shown with 'pack and zoom by filter' and other options

**Expected results:** All available data should be shown on the scatter plot.
**Actual results:** Some data is missing with "Pack and zoom by filter" option.
Issue happens after switching column on one of the axes.
![image](https://user-images.githubusercontent.com/15780643/235437482-54ff71d8-db4b-47b5-b1a6-23e60e15a15c.png)

**Comment by ahadzhanian** [comment]
DG 1.13.14

**Comment by ahadzhanian** [comment]
DG 1.14.4
