### ISSUE TITLE
Scatter plot with specific data and log scale axis failed to load on applying layout

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1858]
**Steps to reproduce:**
1. Open a table: 
[scatter.plot.broken2.csv](https://github.com/datagrok-ai/public/files/11370777/scatter.plot.broken2.csv)
2. Add scatter plot
3. Switch axes to log scale
4. Save layout
5. Re-apply layout

**Expected results:** scatter plot is shown after applying layout.
**Actual results:** Error loading scatter plot.
023-05-02 10:34:29.230 Wrong range.
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1772:17      Object.u
	packages/d4/src/widgets/range_selector/range_selector.dart 83:44       pP.f6
	packages/d4/src/viewer_base/canvas_viewport_mixin.dart 60:19           lq.shx
	packages/d4/src/scatterplot/scatterplot_core.dart 906:5                lq.km
	packages/d4/src/scatterplot/scatterplot_core.dart 137:7                lq.dE
	packages/d4/src/viewer_base/viewer_base.dart 43:5                      lq.y5
	packages/d4/src/common/viewer_descriptor.dart 87:7                     cC4.a9C
	packages/xamgle/src/views/table_view.dart 971:29                       cQ..
	packages/dock_spawn/containers/panel_dock_container.dart 74:29         je.aAH
	packages/dock_spawn/containers/panel_dock_container.dart 63:3          Object.YH
	packages/dock_spawn/serialization/dock_graph_deserializer.dart 62:19   bBy.aDL
	packages/dock_spawn/serialization/dock_graph_deserializer.dart 38:32   bBy.afW
	packages/dock_spawn/serialization/dock_graph_deserializer.dart 33:28   bBz.
	packages/$sdk/lib/_internal/js_runtime/lib/js_array.dart 252:7         av.ao
	packages/dock_spawn/serialization/dock_graph_deserializer.dart 32:5    bBy.afW
	packages/dock_spawn/serialization/dock_graph_deserializer.dart 13:22   bBy.tx
	packages/dock_spawn/dock/dock_manager.dart 388:17                      nF.tX
	packages/xamgle/src/views/table_view.dart 990:5                        bt.ZX
	packages/xamgle/src/views/table_view.dart 949:86                       bt.yJ
	packages/xamgle/src/features/viewer_suggestions.dart 103:5             c6..
	packages/$sdk/lib/html/dart2js/html_dart2js.dart 42920:48              d9k.
	packages/$sdk/lib/async/zone.dart 1132:12                              aXo
	packages/$sdk/lib/async/zone.dart 1012:12                              d72.zZ
	packages/$sdk/lib/async/zone.dart 909:14                               d72.H4
	packages/$sdk/lib/async/zone.dart 936:23                               d75.
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:48      fB5.
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 474:16  NJ.La
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 59:16   Object.FS
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:14      fB3
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2476:14      HTMLDivElement.<fn>
	

Issue looks exactly like #1613 but is reproduced with other data.

**Comment by ahadzhanian** [comment]
DG 1.13.14

**Comment by ahadzhanian** [comment]
DG 1.14.4
