### ISSUE TITLE
Legends in the stack viewers are not saved properly

### ISSUE THREAD

**Issue by JianmeiFan** [datagrok-ai/public#1866]
**Steps to reproduce:** 

1 Stack a couple of viewers that has color legend, for example, barchart, pie chart, line chart, scatterplot etc. 2. Make all legend visibility as always 3 Make sure all legends are shown 4 Save the layout 5 Reopen the layout

**Expected results:** 

All the legend color should show

**Actual results:** 

Only one of legend in one of the stack viewers is shown, the rest legends are all gone. But user can get the legend back again by moving the line between legend and viewer.

Single viewer doesn't have the problem.

**
https://user-images.githubusercontent.com/100243033/236017716-ad3f6d7d-fcbf-4970-abf5-b97e3b5d861b.mp4
**

**Comment by ahadzhanian** [comment]
DG 1.15.0
