### ISSUE TITLE
#188: Adding a little delay for opening toolbar and menus will be useful  

### ISSUE THREAD

**Issue by umid-shahmaliyev** [datagrok-ai/public#188]
Sidebar and menus reacts too fast for mouse over events to auto show/hide toolbar or menus. It will be useful to add some delay (ex 250ms) to avoid accident mouse overs.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14767

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16028

**Comment by skalkin** [comment]
Done
