### ISSUE TITLE
#1887: Grid: Implement 'Pick Up / Apply To' for style

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#1887]
Note: Apply color-coding (apply style) should work if you pick up style from a different dataframe

**Comment by ahadzhanian** [comment]
public 1.15.3
Pick Up \ Apply works incorrectly:
1. Style in the template table disappears after being applied to another table
2. After editing, color coding is not updated immediately
![PickUp_Apply_style](https://github.com/datagrok-ai/public/assets/111368431/80b91c9e-4bbd-485e-bb0a-79d5c026f08f)

**Comment by ahadzhanian** [comment]
After the style is applied, the linear and categorical color coding can't be applied.


![Image](https://github.com/datagrok-ai/public/assets/111368431/60498f1b-c4e7-43b3-8d0c-765ddafd8609)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14604

**Comment by skalkin** [comment]
I'm trying to reproduce but failing. Too much is happening on the gif, can you please list the minimal steps to reproduce?

**Comment by ahadzhanian** [comment]
'Pick Up / Apply To' for style works for columns with the same name
dev 1.18
1. Open demog.csv twice
2. For HEIGHT set a new format and coloring
3. For HEIGHT, use Pick Up / Apply > Pick Up
4. For WEIGHT, try to use Pick Up / Apply > Apply  **- it doesn't work**
5. Go to the second demog table
6.  For HEIGHT, use Pick Up / Apply > Apply  - **it works (apparently because of the same column name)**
![1887](https://github.com/datagrok-ai/public/assets/111368431/41d08238-089c-4e2a-b07a-487ccc9d0adf)
