### ISSUE TITLE
#1888: Context Pane: add visibility of the column names

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#1888]
1. Context Pane should resize the values when resizing (add max-width for values)
2. Add a tooltip to the columns in the column selector used on the Context Pane

![Image](https://github.com/datagrok-ai/public/assets/111368431/5bc10878-53c1-4d64-bc1d-084ed237fcd9)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14605
