### ISSUE TITLE
PowerGrid: can't edit values in pinned column

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#1912]
dev 1.15.0
PowerGrid: 1.1.21
To reproduce, pin a column and try to edit a value
**Expected**: values in pinned column are editable
**Actual**: can't edit values in pinned column
![PinnedColumns](https://github.com/datagrok-ai/public/assets/111368431/47f87b34-5441-4e3d-8a7e-1ffc585bad32)

**Comment by dgosi** [comment]
Editing cells was added to PowerGrid v. 1.1.23
