### ISSUE TITLE
Viewers do not support hex colours set in categorical colouring

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1929]
**Steps to reproduce:**
1. Open SPGI
2. Set following tags on 'Stereo Category' column:
    .color-coding-type = Categorical
    .color-coding-categorical={"R_ONE":"#73aff5","S_ABS":"#ffa500","S_ACHIR":"#50af28","S_PART":"#ff5140","S_UNKN":"#d9d9d9"}
3. Add Bar chart stacked by 'Stereo Category'
4. Add scatter plot coloured by 'Stereo Category'
5. Add line chart split by 'Stereo Category'
6. Add pie chart by 'Stereo Category'
7. Add histogram split by 'Stereo Category'

**Expected:** hex colours should be supported not only by table, but by viewers as well. Colouring is applied to the chart and is displayed properly in legend.
**Actual:** Colour is not shown in legend. Colour is not applied to bar chart, line chart, pie chart:
<img width="1044" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/fe151487-1840-416b-a121-52f640bb59f0">
Histogram does not show data:
<img width="875" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/700718ce-0427-405f-ab97-b0d1e2438205">

**Comment by ahadzhanian** [comment]
DG 1.15.1
