### ISSUE TITLE
Peptides: additional features

### ISSUE THREAD

**Issue by StLeonidas** [datagrok-ai/public#193]
- [x]  alignedSequence property panel: add NGL view
- [x]  alignedSequence property panel: add distributions of non-transformed and transformed data
- [x]  SAR table: Benjamini Yekutieli FDR for multiple hypothsis
- [x] Grouping AARs when SAR analysis is performed
- [ ] #298

**Comment by nikolay-alemasov** [comment]
I am going here to tackle:
1. alignedSequence property panel: add NGL view
2. SAR table: Benjamini Yekutieli FDR for multiple hypothsis

**Comment by nikolay-alemasov** [comment]
Only left:

1. alignedSequence property panel: add NGL view
