### ISSUE TITLE
Trellis plot: Exclude empty categories

### ISSUE THREAD

**Issue by DanTkachev** [datagrok-ai/public#1952]
It would be good to have the option to exclude empty categories from the Trellis plot.

**Comment by DanTkachev** [comment]
Acceptance criteria:
- A row where all cells do not contain any data is not shown
- A column where all cells do not contain any data is not shown

**Comment by ahadzhanian** [comment]
Related to https://reddata.atlassian.net/browse/GROK-13187

**Comment by ahadzhanian** [comment]
DG 1.16.0
