### ISSUE TITLE
Trellis plot: cannot be added in specific case, error on setting structure column as X axis

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1957]
**Steps to reproduce:**
1. Open SPGI (or any other table that has a column with molecules
2. Add trellis plot
3. Set up column with no molecules as Y axis
4. Set up column with molecules as X axis

**Expected results:** Trellis plot configuration is updated, no errors.
**Actual results:** Trellis plot configuration is not updated, error in console:
    html_dart2js.dart:3558 NullError: method not found: 'gpS' on null
    	packages/d4/src/trellis_plot/trellis_plot_core.dart 327:73             MI.fe
	packages/d4/src/trellis_plot/trellis_plot_core.dart 240:5              MI.IX
	packages/d4/src/trellis_plot/trellis_plot_core.dart 224:9              cTv.
	packages/$sdk/lib/html/dart2js/html_dart2js.dart 42920:48              d7W.
	packages/$sdk/lib/async/zone.dart 1132:12                              aWR
	packages/$sdk/lib/async/zone.dart 1012:12                              d5E.zX
	packages/$sdk/lib/async/zone.dart 909:14                               d5E.GX
	packages/$sdk/lib/async/zone.dart 936:23                               d5H.
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:48      fz1.
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 474:16  Ny.L5
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 59:16   Object.FI
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:14      fz.
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2476:14      HTMLSelectElement.<fn>

For some datasets Trellis plot cannot be added at all (it happens if structure column gets into default trellis plot's configurations)

**Comment by ahadzhanian** [comment]
Can be reproduced on smiles.csv
![1957](https://github.com/datagrok-ai/public/assets/111368431/f12f4529-2899-4c7e-b5ff-9c193738f448)

**Comment by ahadzhanian** [comment]
1.16.0
