### ISSUE TITLE
Cannot adjust legend width for a Trellis plot

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1959]
**Steps to reproduce:** 

1. Open a table
2. Add and configure Trellis plot so that legend is shown (e.g. inner viewer is scatter plot coloured by a categorical column)

**Expected results:** Legend width should be adjustable.
**Actual results:** Legend width cannot be changed.

**Comment by ahadzhanian** [comment]
DG 1.16.0
DG 1.15.3
