### ISSUE TITLE
Implement fuzzy filter

### ISSUE THREAD

**Issue by dionissqq** [datagrok-ai/public#1972]

**Comment by onuf** [comment]
Possible enhancements:
- [ ] Add the ability to delete or rename searches
- [ ] Add three modes for search:
       - In one column. The filter header corresponds to the column name.
       - In a column subset. The filter header name is "Search text in {n} columns" (on hover, show a tooltip with the names of all columns in the subset)
       - Across all columns. The filter header name is "Search text".
- [ ] Combine with free-text filter
- [ ] Save to layout typical searches / search patterns

**Comment by ahadzhanian** [comment]
Fuzzy filter is implemented in 1.16.0
For enhancements , I've created the #[2185](https://github.com/datagrok-ai/public/issues/2185) ticket

**Comment by ahadzhanian** [comment]
Implemented in 1.16.0
https://datagrok.ai/help/visualize/viewers/filters#text-filter
