### ISSUE TITLE
#198: tableView: Documentation does not match the implementation

### ISSUE THREAD

**Issue by nikolay-alemasov** [datagrok-ai/public#198]
datagrok-api/src/shell.ts:234 says that the **tableView** returns null if there is no view with the name specified:
```
  /** Returns a first TableView for the specified [tableName], or null if there
   *  are no such views. */
  tableView(tableName: string): TableView {
    return this.getTableView(tableName);
  }
```
while datagrok-api/src/shell.ts:192 states that **getTableView** opens a new view if necessary:
```
/**
   * Returns {@link TableView} for the specified table if it exists, opens a new view if necessary.
   * Search is case-insensitive.
   * @param {string} tableName
   * @returns {TableView} */
  //Obsolete
  getTableView(tableName: string): TableView {
    return new TableView(api.grok_GetTableView(tableName));
  }
```
So it seems that there is no case when **tableView** returns null.

**Comment by skalkin** [comment]
Thanks - feel free to adjust the implementation!

**Comment by skalkin** [comment]
I meant, adjust the documentation :)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14768

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16031
