### ISSUE TITLE
Categorical colouring colours cannot be changed

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1983]
**Steps to reproduce:** 
1. Open a table
2. Set categorical colouring for a column with small number of categories
3. Change default colours to something else for some of the categories
4. Close the colouring dialog

**Expected results:** Colours are updated.
**Actual results:** Colours changes are not applied:
![2023-05-30_11-18-12 (1)](https://github.com/datagrok-ai/public/assets/15780643/60e8e0de-1191-470c-a3fe-0da75341d33c)

**Comment by ahadzhanian** [comment]
DG 1.16.0
DG 1.15.3
