### ISSUE TITLE
Filter's missing values settings are not properly synced between different tabs/views

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1984]
**Case 1:** 
1. Open a table, e.g. SPGI
2. Add another view in the same table
3. Open filters in both views
4. View 1: add numerical column, and set one of the following options:
'filter out missing values'
'show only missing values'
5. View 2: add the same numerical column to filters
**Expected results:** Adding the same column to filters in another view should not change filters state.
**Actual results:** missing values settings are reset:
If 'show only missing values' was selected > filter is reset completely.
If 'filter out missing values' was selected > only range set is kept, missing values are not filtered out anymore.

**Case 2:**
1. Two views are opened
2. Same numerical filter is present in both views
3. Filter is switched from 'show only missing values' to 'Keep missing values' on one of the views
**Expected results:** filter is updated in the 2nd view too.
**Actual results:** in some cases, the range filter is not updated in another view if the setting was changed from 'show only missing values' to 'Keep missing values' on one of the views

**Comment by AnnaMuza** [comment]
Reopened because the first case was not fixed
