### ISSUE TITLE
Dragging a column to filter panel moves it to the beginning of the table

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1986]
**Steps to reproduce:**
1. Open a table
2. Open filters
3. Drag some column to filters by its header

**Expected results:** Dragged column is added to filters, column position in the table is not changed.
**Actual results:** Column is unexpectedly moved to the beginning of the table on dragging it to filters.

**Comment by ahadzhanian** [comment]
DG 1.16.0
DG 1.15.3
