### ISSUE TITLE
Tooltip from the wrong column is shown in filters in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1987]
v1.15.1

**Steps to reproduce:**
1. Open SPGI v2
2. Open filters
3. Add 'CAST Idea ID' to filters
4. Move slider to filter out some rows
5. Hover the icon near filter title and notice tooltip
<img width="278" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/d180c9a4-53a6-43c6-b5aa-1005f08a828a">
6. Add 'Average Mass' to filters
7. Hover the icon near filter title for 'Average Mass' filter

**Expected results:** 'Average Mass' filter's range is shown in tooltip.
**Actual results:** 'CAST Idea ID' filter's range is shown in tooltip:
<img width="293" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/6d56b7b0-d2bd-4549-9b00-fa278a88385b">

Issue is reproduced for some of the columns, but not all.

**Comment by ahadzhanian** [comment]
DG 1.16.0
DG 1.15.3
