### ISSUE TITLE
#1988: Trellis Plot: Enhancements

### ISSUE THREAD

**Issue by onuf** [datagrok-ai/public#1988]
- [x] Add a column filter to the properties for column selection. X and Y axes accept categorical columns only, however, in the context panel we currently see all column types.
- [x] Hide the "Viewer Type" property from the context panel (users can switch it via the dropdown in the chart itself)
- [x] Check that the filtered-out data is rendered in Trellis after filters reset (in some cases, it appers to be missing)
- [x] Add the ability to resize a legend for Trellis
- [x] Adjust labels apprearance on the Y axis. Labels aren’t fitting, even if we change the label orientation
- [x] When inner viewer type is bar chart, show labels inside the bars to save some space

**Comment by onuf** [comment]
There are a few additional tasks:

- [ ] Adjust labels apprearance on the Y axis. Use ellipsis for long names (labels are currently overflowing)
- [ ] Add `ShowBorders` property (when enabled, makes the inner viewer borders visible)
- [ ] Inner viewer axes: categories should be shown just once on the left (do not show on every inner plot)

**Comment by ahadzhanian** [comment]
- [ ] extract global scales for all viewers 
- [ ]  add the ability to visualize just one category

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14586

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16122
