### ISSUE TITLE
Correlation Plot shows wrong axises

### ISSUE THREAD

**Issue by tcarolan** [datagrok-ai/public#2009]
1) Hovering over a Correlation Plot, each scatter plot shows the incorrect axis. Is the data correct? In the attached example the axis should be EC50/Tmax but the hovering scatter plot will only show the Dmax/Tmax.  

2) Double-click the Correlation Plot to view a fullsize scatter plot. The scatter plot that is shown also has the wrong axis selections. Is the data correct. It's hard to tell because normal selection seems to not reset the scatter plot. 

![Screenshot 2023-06-05 171049](https://github.com/datagrok-ai/public/assets/6126004/203bd1de-d75a-4ce7-9edd-10e7244ba4fa)

**Comment by dionissqq** [comment]
Thanks for finding! Fixed in v16.0

**Comment by tcarolan** [comment]
Great, thanks.

**Comment by ahadzhanian** [comment]
Included fix in 1.15.3
