### ISSUE TITLE
Trellis plot: scatterplot, bar chart, boxplot should not allow zooming by default

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2054]
Add a property **Allow Zoom** (false by default)

**Comment by ahadzhanian** [comment]
- [x] Scatterplot - added **Allow zoom**, false by default
- [x] Bar chart - zooming is forbidden
- [ ]  Box plot - zooming is forbidden

**Comment by ahadzhanian** [comment]
DG 1.16.0

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14587

**Comment by dnillovna** [comment]
@ahadzhanian , it looks like this issue was resolved. Could you check?
