### ISSUE TITLE
Projects:  the tabs order is changed from the original uploaded project state

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2060]
Copied from [GROK-13303 Projects: the tabs order is changed from the original uploaded project state](https://reddata.atlassian.net/browse/GROK-13303)

public: 1.15.2
Data: any

1. Open four tables
2. Rename them and upload them to the project
3. Close All
4. Open the uploaded project

**Expected**: the tabs order is saved

**Actual**: the tabs order is changed from the original uploaded project state

![Tabs_order](https://github.com/datagrok-ai/public/assets/111368431/6cc05899-1a75-4de7-9a33-cdb1eb4e8549)

**Comment by tcarolan** [comment]
This is an issue from a data analytics perspective.  Dashboards with multiple views are delivered in random order.

**Comment by skalkin** [comment]
@alex-aprm Let's fix it in the upcoming 1.17
