### ISSUE TITLE
#208: DevTools: add the FunctionEditor feature

### ISSUE THREAD

**Issue by AufarZakiev** [datagrok-ai/public#208]
### TaskList

- [x] Highlight code in code preview
- [x] Generated UI preview
- [x] Bug: default value removal has no effect
- [ ] arbitrary metaparams addition (e.g., `meta.key: value`)
- [x] Bug: type choosing combobox dissapears
- [x] Add the semantic type choice
- [x] Remove CodeMirror & RxJS from dependencies
- [x] Bug: when the language is changed, the text is doubled
- [ ] Replace view creation by view changing
- [x] UI fixes
- [ ] Interactive CodePreview
- [ ] Docs
- [ ] Tests
- [ ] Blog post 

### Context

The only way to create DG script now is to copy-paste it into the editor and add the DG headers with all the metadata.

### Problem

It is important to give an opportunity to edit the DG headers visually. The visual way is more intuitive and makes the experimenting easier.

### Proposal 

Add the visual DG headers editor that covers effectively all the combinations of headers. The FunctionEditor should generate DG headers with no internal conflicts.

It can be visualized as something like this:
![sketch drawio](https://user-images.githubusercontent.com/5558521/142421203-7f029219-0690-4595-94a0-f0ada19aa00d.png)

This view must be available from any script editor.

**Comment by AufarZakiev** [comment]
More sketches from Dima:
![изображение](https://user-images.githubusercontent.com/5558521/143460249-b2b4f907-887b-44a5-8d53-baac7d4cb09d.png)
![изображение](https://user-images.githubusercontent.com/5558521/143460274-b9a5acbe-21e7-4abf-a54b-522c30305d25.png)

**Comment by AufarZakiev** [comment]
MVP deployed: https://github.com/datagrok-ai/public/commit/f3ca420cf981801653956a7f2f1cd8d754c731a7

Moved from Compute to DevTools.

**Comment by AufarZakiev** [comment]
### TaskList

- [ ] Highlight code in code preview
- [ ] Generated UI preview
- [ ] Bug: default value removal has no effect
- [ ] arbitrary metaparams addition (e.g., `meta.key: value`)
- [ ] Bug: type choosing combobox dissapears
- [ ] Add the semantic type choice

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14770

**Comment by AufarZakiev** [comment]
Done with `DevTools` package
