### ISSUE TITLE
Charts | Sunburst: Add different click types, highlighting, selection

### ISSUE THREAD

**Issue by LaykDimon** [datagrok-ai/public#2096]
- [x] Implement highlighting (in order to sync with other viewers)
- [x] Implement ctrl + click for selecting specific parts of the plot
- [x] Implement shift + click for adding selection on the plot
- [x] Implement ctrl + shift + click for removing selection
- [ ] Turn off animations or make them shorter (especially, remove animation in ctrl + click)
- [x] Remove delays from animations
- [ ] Fix selection - if selecting from the grid or viewer - select only a segment or part of the chart

**Comment by ahadzhanian** [comment]
Animation and selection improvements are related to the changes in the ECharts library - moved them to a separate ticket:
https://github.com/datagrok-ai/public/issues/2262
