### ISSUE TITLE
Charts | Sunburst: UI/UX improvements

### ISSUE THREAD

**Issue by LaykDimon** [datagrok-ai/public#2098]
- [x] If color coding - render sunburst sectors color-coded
- [x] If the text doesn't fit - remove it
- [x] Add tooltips
- [x] Check that the molecule renderer will work properly on the sunburst plot
- [x] Verify that the hierarchy column order is persisted properly if we reopen the "hierarchy" dialog
- [x] Fix wrong behavior - second-level classes are not aggregated (more - https://community.datagrok.ai/t/sunburst-plot/746/5)

**Comment by ahadzhanian** [comment]
@Aleksashka11 please check the molecule rendering

Data: sar_small (the first six rows)


![Image](https://github.com/datagrok-ai/public/assets/111368431/a2bfd44b-fb5e-4edb-853e-acfd5c211e2b)

**Comment by ahadzhanian** [comment]
@Aleksashka11 Please check this issue: an error occurs when clicking the root node with 0 rows


![Image](https://github.com/datagrok-ai/public/assets/111368431/622b4347-ba16-4791-b865-4de56a11388b)


```
html_dart2js.dart:3558 2023-08-03 15:04:39.892 Cannot read properties of undefined (reading 'split')
	api/packages/published/files/Charts/1.1.1/2eIQ9gMFytrC5zuSwkxPy7IH9iRaACuh/4/dist/package.js 214515:43  ECharts.<fn>
	api/packages/published/files/Charts/1.1.1/2eIQ9gMFytrC5zuSwkxPy7IH9iRaACuh/4/dist/package.js 221923:33  Eventful.trigger
	api/packages/published/files/Charts/1.1.1/2eIQ9gMFytrC5zuSwkxPy7IH9iRaACuh/4/dist/package.js 162865:17  ECharts.handler
	api/packages/published/files/Charts/1.1.1/2eIQ9gMFytrC5zuSwkxPy7IH9iRaACuh/4/dist/package.js 221923:33  Eventful.trigger
	api/packages/published/files/Charts/1.1.1/2eIQ9gMFytrC5zuSwkxPy7IH9iRaACuh/4/dist/package.js 217450:18  Handler.dispatchToElement
	api/packages/published/files/Charts/1.1.1/2eIQ9gMFytrC5zuSwkxPy7IH9iRaACuh/4/dist/package.js 217550:14  Handler.<computed>
	api/packages/published/files/Charts/1.1.1/2eIQ9gMFytrC5zuSwkxPy7IH9iRaACuh/4/dist/package.js 221923:33  Eventful.trigger
	api/packages/published/files/Charts/1.1.1/2eIQ9gMFytrC5zuSwkxPy7IH9iRaACuh/4/dist/package.js 226154:14  localDOMHandlers.<computed>
	api/packages/published/files/Charts/1.1.1/2eIQ9gMFytrC5zuSwkxPy7IH9iRaACuh/4/dist/package.js 226201:50  HTMLDivElement.<fn>
```

**Comment by ahadzhanian** [comment]
Please, note that it is possible to change the order of hierarchy levels. However, during the next configuration of the **Hierarchy** setting, the order of levels is restored according to the order of columns in the table. This limitation is inherent in the ECharts library.

![Image](https://github.com/datagrok-ai/public/assets/111368431/5f8760c4-1f6c-40fa-9e29-e3071269ed69)

**Comment by ahadzhanian** [comment]
Charts 1.2.0
