### ISSUE TITLE
#2105: Curves: Outliers and curves colors changes

### ISSUE THREAD

**Issue by LaykDimon** [datagrok-ai/public#2105]
- [x] Make outliers red color and much bigger size (TBD)
- [x] Add option for the outlier color
- [x] Make curves by default as a Datagrok categorical color, and if needed user can set his own color

**Comment by LaykDimon** [comment]
@skalkin, as we spoke with @dgosi it turned out, that Neomorph used to see outliers as much bigger and red-color outliers
do we need to make this change for our Curves package?
also, @dgosi stated, that Neomorph doesn't use color settings in their curves, so I suggest to make by default different categorical colors, and if the user picks a color, he will use it

**Comment by skalkin** [comment]
I'm ok if the outliers are red (this could be an option) and bigger. Will need to see how it looks though.

**Comment by skalkin** [comment]
Regarding line colors - isn't that how it works already? We have a default color, then if there are multiple series we start adding colors from the categorical palette.

**Comment by LaykDimon** [comment]
if I remember correctly, it will just render the same color, but I will check this and fix if it's working like that

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14877
