### ISSUE TITLE
'Select all search results' in the 'Order and hide columns' dialog

### ISSUE THREAD

**Issue by DanTkachev** [datagrok-ai/public#2107]
Currently, when a user searches for some columns in the 'Order and hide columns' dialog and then clicks the checkbox to 'Select all', the selection applies to all columns.

Acceptance criteria:
- Change the function (and, maybe, title/hint?) for the checkbox to 'Select all search results' once any search is applied

To consider:
- Adding the third state for the checkbox for consistency? Or just stop keeping the box checked if at least one column has been deselected?
- What would be selected if a user selects something within the search results?
- Selecting all makes it impossible to go back to your previous columns set. Does it make sense to apply the changes in the dialog only after clicking 'Save' or 'Apply' to avoid accidental setting loss?
- Currently, the checkbox is close to the dropdown 'All' so it looks like it's the name of the checkbox - maybe, it makes sense to change their relative position?

**Comment by ahadzhanian** [comment]
- [ ] Changed the function and the tooltip for the checkbox to 'Select all search results' once any search is applied.
 - [ ] Added the third state for the checkbox for consistency.
 - [ ] If a user selects something within the search results, the function is applied to the selected items only.
Available in v1.16.0
