### ISSUE TITLE
Improve behavior of 'Dot' marker type on Scatter plot

### ISSUE THREAD

**Issue by DanTkachev** [datagrok-ai/public#2108]
The 'Dot' marker type has the following issues that may prevent analyzing big data sets:

o	It shows markers for where there is no data (e.g. if for some compounds do not have data for the Y axis, they still appear on the plot, but just on the zero line of the Y axis)
o	The grid lines disappear

https://github.com/datagrok-ai/public/assets/114074888/2a0e3f98-7c8a-4d59-92ea-6b3062c100f5

**Comment by ahadzhanian** [comment]
Fixed in v 1.16.0
