### ISSUE TITLE
#2116: Column settings are connected on two Trellis plots after settings are picked up/applied

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2116]
**Steps to reproduce:** 
1. Open a table
2. Add two trellis plots
3. Right click one of the trellis plots > Pick up/Apply > Pick up
4. Apply on another trellis plot
5. Change X or Y column on the 1st trellis plot
6. Move zoom slider on the 2nd plot

**Expected results:** Configuration/style should be only applied once, when user does it explicitly. After that trellis plots configurations should be completely independent.

**Actual results:** data configuration changes of the 1st trellis plot are applied on the 2nd one after settings were picked up/applied.
![2023-07-04_15-09-43 (1)](https://github.com/datagrok-ai/public/assets/15780643/56ca89c7-6f63-48bc-ad79-1da339ac9aa4)

**Comment by ahadzhanian** [comment]
1.16.0

**Comment by ahadzhanian** [comment]
1.18.5
![2116](https://github.com/datagrok-ai/public/assets/111368431/0e00bbc6-f1e8-4619-89f4-9fc343ed8a07)
`Viewer "viewer" cannot draw trellis axes
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1772:17      wrapException
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1807:25      throwExpression
	packages/d4/src/viewer_base/viewer_base.dart 299:103                   ViewerBase.renderTrellisAxes
	packages/d4/src/rect.dart 173:54                                       Rect.inflate
	packages/d4/src/trellis_plot/trellis_plot_core.dart 1169:5             TrellisPlotCore._render
	packages/d4/src/trellis_plot/trellis_plot_core.dart 482:5              TrellisPlotCore._refresh
	packages/d4/src/trellis_plot/trellis_plot_core.dart 306:5              TrellisPlotCore.onLookChanged
	packages/d4/src/viewer_base/viewer_base.dart 110:9                     ViewerBase.initViewer.<anonymous function>
	packages/$sdk/lib/async/zone.dart 1132:12                              _rootRunUnary
	packages/$sdk/lib/async/zone.dart 1012:12                              _CustomZone.runUnary
	packages/$sdk/lib/async/zone.dart 909:14                               _CustomZone.runUnaryGuarded
	packages/$sdk/lib/async/stream_impl.dart 330:5                         _BufferingStreamSubscription._sendData
	packages/$sdk/lib/async/stream_impl.dart 257:7                         _BufferingStreamSubscription._add
	packages/$sdk/lib/async/broadcast_stream_controller.dart 387:7         _SyncBroadcastStreamController._sendData.<anonymous function>
	packages/$sdk/lib/async/broadcast_stream_controller.dart 328:9         _BroadcastStreamController._forEachListener
	packages/$sdk/lib/async/broadcast_stream_controller.dart 386:5         _SyncBroadcastStreamController._sendData
	packages/$sdk/lib/async/broadcast_stream_controller.dart 254:5         _BroadcastStreamController.add
	packages/d4/src/viewer_base/look_and_feel.dart 121:7                   LookAndFeel.copyFrom
	packages/xamgle/src/features/themes.dart 45:11                         _initThemes.regApplyStyle.<anonymous function>
	packages/d4/src/command.dart 298:9                                     ParamCommand.reg.<anonymous function>
	packages/xamgle/src/commands_param/viewer_context_commands.dart 14:52  _initViewerContextCommands.<anonymous function>.<anonymous function>
	packages/d4/src/events.dart 527:7                                      AppEvents.contextRun
	packages/d4/src/widgets/menu/menu.dart 121:7                           MenuItem.click
	packages/d4/src/widgets/menu/menu.dart 183:33                          MenuItem._init.<anonymous function>
	packages/$sdk/lib/html/dart2js/html_dart2js.dart 42920:48              _EventStreamSubscription.<anonymous function>
	packages/$sdk/lib/async/zone.dart 1132:12                              _rootRunUnary
	packages/$sdk/lib/async/zone.dart 1012:12                              _CustomZone.runUnary
	packages/$sdk/lib/async/zone.dart 909:14                               _CustomZone.runUnaryGuarded
	packages/$sdk/lib/async/zone.dart 936:23                               _CustomZone.bindUnaryCallback.<anonymous function>
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:48      invokeClosure.<anonymous function>
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 474:16  _IsolateContext.eval
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 59:16   _callInIsolate
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:14      invokeClosure
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2476:14      convertDartClosureToJS`

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15494

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

Pick up/Apply > Apply causes errors:


```
2024-05-13 12:36:26.062 RangeError (index): Index out of range: index should be less than 2: 4
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1772:17      wrapException
	packages/d4/src/trellis_plot/trellis_plot_core.dart 999:89             TrellisPlotCore._refreshCharts._createInnerViewer.<anonymous function>
	packages/$sdk/lib/internal/iterable.dart 391:18                        MappedIterator.moveNext
	packages/$sdk/lib/_internal/js_runtime/lib/core_patch.dart 375:5       List.from
	packages/$sdk/lib/core/iterable.dart 347:12                            Iterable.toList
	packages/d4/src/trellis_plot/trellis_plot_core.dart 1099:23            TrellisPlotCore._refreshCharts.<anonymous function>
	packages/d4/src/html_utils.dart 380:21                                 htmlCellGrid
	packages/d4/src/trellis_plot/trellis_plot_core.dart 1098:17            TrellisPlotCore._refreshCharts
	packages/d4/src/trellis_plot/trellis_plot_core.dart 1167:7             TrellisPlotCore._render
	packages/d4/src/trellis_plot/trellis_plot_core.dart 484:5              TrellisPlotCore._refresh
	packages/d4/src/trellis_plot/trellis_plot_core.dart 282:7              TrellisPlotCore.sourceRowsChanged
	packages/d4/src/viewer_base/data_frame_viewer.dart 93:7                DataFrameViewer.onCombinedFilterSubs
	packages/$sdk/lib/async/zone.dart 1132:12                              _rootRunUnary
	packages/$sdk/lib/async/zone.dart 1012:12                              _CustomZone.runUnary
	packages/$sdk/lib/async/zone.dart 909:14                               _CustomZone.runUnaryGuarded
	packages/$sdk/lib/async/stream_impl.dart 330:5                         _BufferingStreamSubscription._sendData
	packages/$sdk/lib/async/stream_impl.dart 257:7                         _BufferingStreamSubscription._add
	packages/$sdk/lib/async/broadcast_stream_controller.dart 387:7         _SyncBroadcastStreamController._sendData.<anonymous function>
	packages/$sdk/lib/async/broadcast_stream_controller.dart 328:9         _BroadcastStreamController._forEachListener
	packages/$sdk/lib/async/broadcast_stream_controller.dart 386:5         _SyncBroadcastStreamController._sendData
	packages/$sdk/lib/async/broadcast_stream_controller.dart 254:5         _BroadcastStreamController.add
	packages/d4/src/viewer_base/look_and_feel.dart 121:7                   LookAndFeel.copyFrom
	packages/d4/src/viewer_base/viewer_base.dart 44:5                      ViewerBase.setLook
	packages/xamgle/src/features/themes.dart 46:11                         _initThemes.regApplyStyle.<anonymous function>
	packages/d4/src/command.dart 298:9                                     ParamCommand.reg.<anonymous function>
	packages/xamgle/src/commands_param/viewer_context_commands.dart 14:52  _initViewerContextCommands.<anonymous function>.<anonymous function>
	packages/d4/src/events.dart 531:7                                      AppEvents.contextRun
	packages/d4/src/widgets/menu/menu.dart 122:7                           MenuItem.click
	packages/d4/src/widgets/menu/menu.dart 184:33                          MenuItem._init.<anonymous function>
	packages/$sdk/lib/html/dart2js/html_dart2js.dart 42920:48              _EventStreamSubscription.<anonymous function>
	packages/$sdk/lib/async/zone.dart 1132:12                              _rootRunUnary
	packages/$sdk/lib/async/zone.dart 1012:12                              _CustomZone.runUnary
	packages/$sdk/lib/async/zone.dart 909:14                               _CustomZone.runUnaryGuarded
	packages/$sdk/lib/async/zone.dart 936:23                               _CustomZone.bindUnaryCallback.<anonymous function>
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:48      invokeClosure.<anonymous function>
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 474:16  _IsolateContext.eval
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 59:16   _callInIsolate
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:14      invokeClosure
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2476:14      convertDartClosureToJS
```

[file id="e51c68e6-69a4-4d21-8dcb-c7541e041faa"]

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

Pick up/Apply > Apply causes errors
