### ISSUE TITLE
API configuration to define layout import settings

### ISSUE THREAD

**Issue by DanTkachev** [datagrok-ai/public#2118]
As a user, when I import a page layout to my analysis, I'd like to define which layout settings shall be applied (all vs viewers only) so that unnecessary options (e.g. coloring) are not applied to the entire analysis.

**Comment by ahadzhanian** [comment]
To test:

1. Creare a layout (add viewers, color coding, change format for some columns, use Order and Hide columns)
2. To save a layout,  in console run `let l = grok.shell.tv.saveLayout()`
Expected: 

- when applying layout `grok.shell.tv.loadLayout(l)`, color coding is applied
- when applying layout  `grok.shell.tv.loadLayout(l, false)`, formatting is not applied

**Comment by ahadzhanian** [comment]
DG 1.16.0
