### ISSUE TITLE
Pie chart: auto layout

### ISSUE THREAD

**Issue by dionissqq** [datagrok-ai/public#2124]

**Comment by ahadzhanian** [comment]
When resizing the viewers, it is possible to achieve a result where the pie chart is displayed in three different ways on viewers of the same size.


![Image](https://github.com/datagrok-ai/public/assets/111368431/d65eae44-d898-4d9a-ba6f-e508127a88d2)

**Comment by ahadzhanian** [comment]
1.16.0
