### ISSUE TITLE
ScaffoldTree in filter panel issues

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2135]
- [x] The structure rendering is too small, and you cannot easily recognize the individual atoms. Expected:  molecules should occupy most of the free space
- [x] The counts and controls are partially hidden (same problem on the ScaffoldTree visualization)
- [x] When I change the drawing of a scaffold, then selection (checkbox) of all other scaffolds gets reset (to unchecked).

**Comment by ahadzhanian** [comment]
Chem 1.6.23

**Comment by katerina-stepanova** [comment]
Chem 1.7.0

Structures rendered in Scaffold tree filter are still too small:
<img width="252" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/ba85a24c-d699-4689-aaa7-f74dd5975f6d">
Image size is slightly increased when panel is made wider, but it's still not large enough:
<img width="529" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/3dc362fd-e396-4121-af5a-44c693d1c815">
