### ISSUE TITLE
Scaffold tree stops working after adding an invalid structure

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2139]
**Steps to reproduce:**
1. Open a table
2. Add scaffold tree
3. Add new root structure
4. Start drawing some valid structure > table is filtered, drawn structure is highlighted
5. Edit structure to make it invalid > invalid parts are highlighted in editor
6. Fix the structure so that it is valid again

**Expected results:** user can fix invalid structure and continue working with scaffold tree.
**Actual results:** Editing structure no longer affects filtering and highlighting in the table. The scaffold tree doesn't function right any more - User can not edit any structure; the substructure search doesn't work

**Comment by ahadzhanian** [comment]
Chem 1.6.20
