### ISSUE TITLE
#215: JS API: `DG.TagEditor`'s `onChanged` method accepts callback as parameter

### ISSUE THREAD

**Issue by AufarZakiev** [datagrok-ai/public#215]
### Description

`DG.TagEditor`'s `onChanged` method accepts callback as parameter. Instead of this, `onChanged` method should return RxJS observable with `subscribe` option. Example of this approach can be found here: https://public.datagrok.ai/js/samples/data-frame/events/events

### Demo script:
```
//language: javascript
//name: Template
const v = grok.shell.newView('demo: tag editor');

const editor = DG.TagEditor.create();
editor.addTag('demo');
editor.addTag('test');
editor.addTag(1234);
editor.onChanged(() => console.log('tags changed'));

v.append(editor.root);
```
### Steps to reproduce

Run the script

### Expected

We use `subscribe` by RxJS to react on events
### Actual

Callback is accepted as a parameter

### Additional info:
Same situation is in `DG.InputBase.onInput()` and `DG.InputBase.onChanged()` methods.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14771

**Comment by AufarZakiev** [comment]
Won't fix until major release in very far future
