### ISSUE TITLE
Line chart lines are displayed incorrectly in some cases (drop below the X axis)

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2163]
**Steps to reproduce:**
1. Open SPGI
2. Add a line chart
3. Configure line chart: R3 on X, 'Whole blood assay 1' or 'Cellular assay 1' on Y, split by Series
4. Check the lines displayed

**Expected results:** lines should not be interrupted unexpectedly.
**Actual results:** Lines are unexpectedly interrupted in some places (as if some part of it should be below X axis):
![image](https://github.com/datagrok-ai/public/assets/15780643/522ddb05-96fd-4e85-9921-95cff9857f33)

Issue becomes more noticeable when dots on the plot are visible, e.g. when data is filtered by Chemist521='Chemist20':
![image](https://github.com/datagrok-ai/public/assets/15780643/90cb1759-54e0-4cf0-97cf-0cde0261d674)

**Comment by ahadzhanian** [comment]
See also Histogram, when:
- showXAxis: false,
- showRangeSlider: false,

**Comment by ahadzhanian** [comment]
When setting X to R3 an error occurs


![Image](https://github.com/datagrok-ai/public/assets/111368431/12396557-cc56-4f7d-b8dc-74c669ad2042)


```
2023-07-18 16:14:46.583 Unsupported operation: NaN.round()
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1772:17      Object.u
	packages/d4/src/common/painter.dart 222:9                              Object.hR
	packages/d4/src/axes/axis.dart 207:11                                  bdg.
	packages/d4/src/axes/axis.dart 219:9                                   Object.oL
	packages/d4/src/line_chart/line_chart_core.dart 910:12                 An.a9i
	packages/d4/src/line_chart/line_chart_core.dart 857:7                  An.akM
	packages/d4/src/line_chart/line_chart_core.dart 943:7                  An.jU
	packages/d4/src/viewer_base/canvas_viewer_mixin.dart 169:7             An.a8K
	packages/d4/src/viewer_base/canvas_viewer_mixin.dart 106:9             bgG.
	packages/$sdk/lib/async/zone.dart 1132:12                              b.A
	packages/$sdk/lib/async/zone.dart 1012:12                              deS.AJ
	packages/$sdk/lib/async/zone.dart 909:14                               deS.I.
	packages/$sdk/lib/async/zone.dart 936:23                               deV.
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:48      fPl.
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 474:16  Os.Mu
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 59:16   Object.G5
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:14      fPj
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2476:14      <fn>
```

**Comment by ahadzhanian** [comment]
DG 1.16.0

**Comment by katerina-stepanova** [comment]
1.16.3

Issue is fixed for SPGI examples, but still reproduced on some user data:
<img width="213" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/f717c106-9484-4ebb-88e9-1822b273afe1">

**Comment by katerina-stepanova** [comment]
Issue can be reproduced with following data:
[2163.csv](https://github.com/datagrok-ai/public/files/12429543/2163.csv)
1. Add line chart
2. 'X axis' as X axis
3. 'Y axis' as Y axis
4. Split by 'Split' column

![2023-08-24_15-41-51 (1)](https://github.com/datagrok-ai/public/assets/15780643/24233252-1ce7-4739-b701-e709ae8ac1ed)

**Comment by ahadzhanian** [comment]
DG 1.16.4
