### ISSUE TITLE
Filter Panel: Always add new filters to the top 

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2165]
Always add new filters to the top (now, in some cases, it’s added to the bottom):
- [x] Context action > Add External (e.g. Scaffold tree filter)
- [x] Context action > Add Free Text Filter
- [x] Context action > Select Column
- [x] Add custom filter
- [x] Column's header > Hamburger menu > Filter > Add filter
- [x] Current Value > Use as filter (in case there is no corresponding filter tab)

**Comment by ahadzhanian** [comment]
DG 1.16.1

**Comment by dnillovna** [comment]
@ahadzhanian, it looks like this issue was resolved. Could you check?
