### ISSUE TITLE
#2185: Fuzzy filter enhancements

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2185]
Possible enhancements:

- [x] Add text highlighting in column for text filter queries
- [x] Add ability for structure filter to filter selected columns and filter visible columns only.
- [x]Add the ability to delete or rename searches
- [x]Implement filtering across the grid no matter the column
- [x] Add three modes for search:        - In one column. The filter header corresponds to the column name.        - Across all columns. The filter header name is "Free-text filter".
- [x] Combine with free-text filter
- [x] Save to layout typical searches / search patterns

- [x] Add ability to filter only selected/visible columns using expression filter

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14590

**Comment by ahadzhanian** [comment]
1.18.0
The first item will be implemented later
