### ISSUE TITLE
Add zoom slider to X axis of Histogram

### ISSUE THREAD

**Issue by DanTkachev** [datagrok-ai/public#2197]
It would be useful if the histogram would show a zoom slider on the X axis, in order to drill down into specific segments of the plotted data.

**Comment by ahadzhanian** [comment]
1.17.0

**Comment by ahadzhanian** [comment]
Zooming is possible by changing a range slider and can be set via new settings:

- Zoom to range
- Bin to range
- Normalize to filter

**Comment by ahadzhanian** [comment]
- [ ] it is possible to drag the zoom slider away from the screen
- [ ] the range slider must remain visible even if its length is zero

**Comment by ahadzhanian** [comment]
1.16.4
