### ISSUE TITLE
Pivot table: editing and saving issues

### ISSUE THREAD

**Issue by DanTkachev** [datagrok-ai/public#2198]
Editing the viewer properties:

- [x] Changes done in the viewer itself and in its properties panel are completely decoupled:
- [x] Columns selected in viewer are not reflected in properties panel
- [x] Columns selected in the panel are not applied to the viewer

<img width="813" alt="screenshot-1 (1)" src="https://github.com/datagrok-ai/public/assets/114074888/089651dc-b761-42da-9e08-dd3c71838ccd">

Properties panel is missing 'Measures' selection:

<img width="301" alt="image-2023-05-05-14-39-27-363" src="https://github.com/datagrok-ai/public/assets/114074888/e0c31d02-fd29-4ea6-8063-b1db0acddf45">

Saving pivot table viewer:

- [x] On applying saved layout with pivot viewer, it is always shown in its default state. Properties set through the panel are saved, but not applied (because of issues mentioned in 'editing the viewer properties').
- [x] Any changes in the resulting pivoted table, e.g. colours, pinned columns, format, show/hide columns, summary etc. are not preserved on saving layout too.

**Comment by ahadzhanian** [comment]
DG 1.17.0
