### ISSUE TITLE
#2208: PowerGrid: SmartForm

### ISSUE THREAD

**Issue by skalkin** [datagrok-ai/public#2208]
A form that shows multiple row values in a single cell

- [x] Picks up cell renderers, such as a molecule renderer
- [x] Picks up grid color-coding
- [x] Adaptive resizing

**Comment by skalkin** [comment]
Some good progress already

![grid-smart-form](https://github.com/datagrok-ai/public/assets/943403/7fd3df10-34d6-4c4d-9629-5425a6e231a0)

**Comment by tcarolan** [comment]
This will be very useful, thank you for developing it. How will regular "Form" multi columns in Powergrid behave after the upgrade to Smart Forms?

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16133
