### ISSUE TITLE
Compute: Heights of dataframes in the script output

### ISSUE THREAD

**Issue by dskatov** [datagrok-ai/public#223]
Currently all heights seems to be fixed-size and exhausts the free area.

![image](https://user-images.githubusercontent.com/67762377/144235171-6421e2a4-53ac-4928-add2-58ebcfa9501c.png)

**Comment by AufarZakiev** [comment]
@adrkn mentioned once that there is no such feature in `DG.Grid`. 
I suggest to add the function called `shrink()` that will decrease size to the minimum size.

![1](https://user-images.githubusercontent.com/5558521/144426225-2b490d6c-ef98-4355-b03d-7ed127259623.png)
![2](https://user-images.githubusercontent.com/5558521/144426229-ca9ca7bc-1527-478e-871a-a81035c8ee8a.png)
