### ISSUE TITLE
#226: Utils: Integrate eigen library to allow for a faster la computations.

### ISSUE THREAD

**Issue by nikolay-alemasov** [datagrok-ai/public#226]
- [ ] Consider existing packages, or
- [ ] Implement from scratch.

**Comment by nikolay-alemasov** [comment]
Consider integration of https://github.com/BertrandBev/eigen-js

**Comment by nikolay-alemasov** [comment]
@skalkin , @StLeonidas , could you, please, review the issue and correct if there is a need?

**Comment by skalkin** [comment]
I suggest to start with the functions we want to expose as Datagrok functions, and work back from there.

**Comment by StLeonidas** [comment]
Suggest to revise the reasonability of the eigen library integration

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14923
