### ISSUE TITLE
#2262: Charts | Sunburst: animation and selection improvements

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2262]
- [x] Turn off animations or make them shorter (especially, remove animation in ctrl + click)
- [x] Fix selection - if selecting from the grid or viewer - select only a segment or part of the chart
- [x] Improve labels display
- [x] add the ability to turn off the color-coding inherited from the grid

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14610

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16134
