### ISSUE TITLE
#2276: #2276: Peptides: UI/UX improvements

### ISSUE THREAD

**Issue by vdyma** [datagrok-ai/public#2276]
- [x] Add Sequence Space viewer.
- [x] Add tooltip for Mutation Cliffs pairs panel.
- [x] Fix Monomer-Position not reacting to selection.
- [ ] Align MacromoleculeDifference renderer.
- [x] Improve Actions panel style to match other similar panels.
- [x] Add icon to show any wide table in full screen (e.g. Mutation Cliffs pairs).
- [x] Reduce histogram height in tooltips and panels. 
- [x] Fix Most Potent Residues interaction.
- [x] Fix Logo Summary Table interaction.
- [x] Fix WebLogo in header interaction.
- [x] Use absolute value of mean difference for size coding.
- [x] Improve tooltips (remove “Statistics:” label and merge count and ratio).
- [x] Highlight rows on mouse-over in all viewers: monomer-position, most potent residues, logo summary table and logo in header.
- [x] Adaptive Monomer column width.
- [x] Remove steps from tutorial. Open analysis instead.
- [x] Align viewer interactions. [ref](https://datagrok.ai/help/visualize/viewers/grid#selection)
- [x] Add tooltips for all inputs.
- [x] Improve Identity and Similarity panel layout.
- [x] Remove the ? in Monomer-Position viewer; show info in tooltip.
- [x] Show context panel even for selection from grids and other viewers.
- [x] Scale coloring in viewer from blue (low values) to red (high values), same as in all other viewers.
- [ ] Add buttons to show and hide viewers in analysis.
- [x] Navigate through grids with keyboard.- [x] Mutation cliffs - size the circles with count of mutation cliffs, color by mean difference. correct tooltips to show appropriate information about the set of sequences in current mutation cliffs.- [x] Context panel - Fix crashing on filtering, add expansion for mutation cliff pairs tables. correct event propagation

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14879

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16135
