### ISSUE TITLE
Certain scenarios make it impossible to move or stack a viewer

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2284]
**Steps to reproduce:**

1. Open a table, e.g. SPGI
2. Add a viewer
3. Undock the viewer
4. Click & drag the top of the viewer to adjust its height out of the page borders.

Sometimes issue is also reproduced on undocking & moving viewer up simultaneously.

**Expected results:**  The viewer should not allow resizing/moving out of the page borders.
**Actual results:**  The header of the viewer can be hidden during resizing. There is no way to move it, stack or resize after this.
![viewer](https://github.com/datagrok-ai/public/assets/15780643/d0fd946e-ebe6-4c9f-97bd-9e34323c291e)

**Comment by ahadzhanian** [comment]
Still reproduce
>Sometimes issue is also reproduced on undocking & moving viewer up simultaneously.


![Image](https://github.com/datagrok-ai/public/assets/111368431/d2cb3d9d-7fa5-4652-bba3-e6b0eca5ba98)

**Comment by ahadzhanian** [comment]
DG 1.17.0
