### ISSUE TITLE
Scatter plot: default marker size is not changed on moving slider

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2285]
**Steps to reproduce:**
1. Open a table
2. Add scatter plot
3. Use context menu or properties panel to change default marker size on the plot

**Expected results:** markers size should be changed.
**Actual results:** nothing happens on moving the slider.
![2023-08-16_17-08-41 (1)](https://github.com/datagrok-ai/public/assets/15780643/5fb1d49f-9c7f-4512-bfc8-8858e22baa4a)

**Comment by ahadzhanian** [comment]
Implement handling marker size analogously to a box plot:

- Auto Layout sets the marker size, whet it is set to -1
- In case of other values, user can adjust the marker size

**Comment by ahadzhanian** [comment]
DG 1.16.4
