### ISSUE TITLE
Box plot: markers overlap with X axis and categories in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2286]
**Steps to reproduce:**
1. Open a table
2. Add a box plot
3. Increase markers size and labels font size

**Expected results:** markers should not overlap with X axis and categories.
**Actual results:** sometimes markers overlap with X axis and categories, especially if box plot is not very high:
<img width="549" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/5e9c3a34-223a-4a5e-b1d4-f5285d363876">

**Comment by ahadzhanian** [comment]
- [ ] The markers must also not intersect with the y-axis
- [ ] If you use the slider and reduce the number of boxes on the plot, you can see that the markers are cut off

![Image](https://github.com/datagrok-ai/public/assets/111368431/29d8bcb5-c749-4c61-b442-1b8708861b25)

**Comment by ahadzhanian** [comment]
DG 1.17.0
