### ISSUE TITLE
Cannot search in 'order and hide columns' if table contains a summary column

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2293]
**Steps to reproduce:**
1. Open some table
2. Add a summary column
3. Open 'order and hide columns' dialog
4. Search for some column

**Expected results:** columns list is filtered on typing.
**Actual results:** columns list is not filtered on typing.
Error:
html_dart2js.dart:3558 NullError: method not found: 'c' on null
	packages/$sdk/lib/_internal/js_runtime/lib/js_string.dart 166:12       bne.
	packages/ddt/src/collections/bit_set.dart 306:11                       cV.MT
	packages/d4/src/common/column_grid.dart 69:5                           mk.GQ
	packages/d4/src/common/column_grid.dart 119:37                         bmN.
	packages/$sdk/lib/async/zone.dart 1128:37                              b.M
	packages/$sdk/lib/async/zone.dart 1012:12                              dfj.AI
	packages/$sdk/lib/async/zone.dart 909:14                               dfj.I0
	packages/$sdk/lib/async/stream_impl.dart 330:5                         deK.aD
	packages/$sdk/lib/async/stream_impl.dart 257:7                         oi.kR
	packages/$sdk/lib/async/broadcast_stream_controller.dart 379:7         x.aD
	packages/$sdk/lib/async/broadcast_stream_controller.dart 254:5         l6.aR3
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2811:12      VN.eval
	packages/$sdk/lib/html/dart2js/html_dart2js.dart 42920:48              dhD.
	packages/$sdk/lib/async/zone.dart 1132:12                              b.M
	packages/$sdk/lib/async/zone.dart 1012:12                              dfj.AI
	packages/$sdk/lib/async/zone.dart 909:14                               dfj.I0
	packages/$sdk/lib/async/zone.dart 936:23                               dfm.
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:48      fQ3.
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 474:16  Ou.Mu
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 59:16   Object.G6
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:14      fQ1
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2476:14      HTMLInputElement.<fn>

**Comment by ahadzhanian** [comment]
Also, there is no summary column in the list

**Comment by ahadzhanian** [comment]
A summary column appears in the list when the dialog opens and disappears when searching

![Image](https://github.com/datagrok-ai/public/assets/111368431/364b5f06-e182-47ee-ba13-1e0bc814ad94)

**Comment by ahadzhanian** [comment]
DG 1.16.4
