### ISSUE TITLE
Histogram: number of bins and selected column is not synched between in-plot controls and properties panel

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2296]
**Steps to reproduce:**
1. Open a table
2. Add a histogram
3. Change number of bins using in-plot slider
4. Change number of bins using properties panel
5. Select another column using in-plot controls

**Expected results:** number of bins and selected column is synchronised between in-plot controls and properties panel. 
**Actual results:** number of bins is not synchronised, selected column is not synchronised if changed using in-plot controls.
<img width="789" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/77aa9008-7c0c-4675-8ed1-2e77c0691222">

**Comment by ahadzhanian** [comment]
Duplicates https://github.com/datagrok-ai/public/issues/2295

**Comment by ahadzhanian** [comment]
DG 1.17.0 (1.16.4)

**Comment by ahadzhanian** [comment]
Select another column using in-plot controls - selected column is not synchronised between in-plot controls and properties panel -this item is moved to the https://github.com/datagrok-ai/public/issues/2472 ticket
