### ISSUE TITLE
#2298: Bar Chart: squeeze the white space around the title

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2298]
There is a lot of white space around the title on the bar chart even though Show Stack Selector is off.
See the other viewers.
![image](https://github.com/datagrok-ai/public/assets/111368431/3b5f7737-e581-4783-89d3-f40d077dbf8e)**Squeeze the white space on the bottom**

**Comment by ahadzhanian** [comment]
DG 1.17.0

**Comment by katerina-stepanova** [comment]
1.17.1

In ID application stack selector overlaps bar chart bars:
<img width="391" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/4aab6aac-b312-4ebb-a547-2d46d750c78e">

**Comment by ahadzhanian** [comment]
DG 1.17.3

**Comment by ahadzhanian** [comment]
Squeeze the white space on the bottom

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14592
