### ISSUE TITLE
#2304: Charts: Reorganize the properties on the Context Panel consistently with the core viewers

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2304]
See [Viewers: Organize properties consistently in the context panel#1778](https://github.com/datagrok-ai/public/issues/1778)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14611

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16138
