### ISSUE TITLE
#2305: Charts: implement structures rendering where feasible

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2305]
- [ ] All viewers that show structures as nodes or on axes should render structures.
- [x] Add a check to see if package Chem is installed

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14613

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16139
