### ISSUE TITLE
Filter's slider can no longer be moved, if one of its ends is out of range of available data

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2307]
**Case 1: set min/max range manually in filter**
1. Open a table with at least one date or numerical column
2. Open filters and add this column to filters
3. Show min/max
4. Enter min or max outside of range of available data
5. Drag the filter slider
![2023-08-22_16-04-55 (1)](https://github.com/datagrok-ai/public/assets/15780643/2542a6a6-7bc8-4bc2-bc9d-0fed165c0f21)

**Case 2: data is changed and saved layout is re-applied**
1. Open a table with at least one date or numerical column
2. Open filters and add this column to filters
3. Filter out some data by moving one of the slider's ends
4. Save layout
5. Change values in the table, so that min or max set on step 3 is out of data range
6. Re-apply saved layout
7. Drag the filter slider
![2023-08-22_16-06-41 (1)](https://github.com/datagrok-ai/public/assets/15780643/175fb20a-4f46-4d47-b2ed-a2a4667064c3)

**Expected results:** Filter's slider can be dragged.
**Actual results:** filter's slider cannot be dragged until range is adjusted by manually entering a value.

**Comment by ahadzhanian** [comment]
DG 1.17.0
