### ISSUE TITLE
Scatter plot: axis height is changing while scrolling or panning if structure column is used

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2313]
1.16.3

**Steps to reproduce:**
1. Open SPGI
2. Add scatter plot
3. Select 'R3' as X axis
4. Pan scatter plot
5. Zoom on X axis
6. Pan scatter plot by dragging X axis (after zooming)

**Expected results:** axis height should not change during zooming/panning.
**Actual results:** X axis height is changed during panning and zooming:
![2023-08-23_13-22-05 (1)](https://github.com/datagrok-ai/public/assets/15780643/97b340e9-701d-4232-a959-130e0a428a04)

**Comment by ahadzhanian** [comment]
DG 1.16.4
