### ISSUE TITLE
Unexpected columns appear in 'Order and hide' columns dialog if scaffold tree viewer or structure filter is added

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2315]
**Steps to reproduce:** 
1. Open a table
2. Add Scaffold Tree as a viewer or add some structure filter to filters panel
3. Open 'Order and hide columns' dialog and scroll to the bottom

**Expected results:** No unexpected columns are added.
**Actual results:** Columns are added:
<img width="316" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/284c4af0-ca3e-44cc-b905-16fdcdca20f2">
These columns are never shown in the actual table which make it more confusing.

**Comment by ahadzhanian** [comment]
DG 1.16.4

**Comment by katerina-stepanova** [comment]
DG 1.16.4

Extra columns are stil present in some places:
1. Column selection for filters:
<img width="543" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/67a11ec6-5cbd-4b01-ad56-a2bab08ffd5d">
2. Column selection dropwdowns for various viewers:
<img width="729" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/5bf64800-1ab4-45e3-8f05-28062bd8aa02">
3. Columns list in properties panel:
<img width="346" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/270612e2-8cd4-4a30-a12a-c08d9cc1a4bf">
<img width="538" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/a53e9117-d6be-421b-a451-f4cdea05c1e6">


**Expected:** remove those columns in all places where they might unexpectedly appear.

**Comment by ahadzhanian** [comment]
1.16.5
