### ISSUE TITLE
Viewer docked at the left or at the top is sometimes unexpectedly hidden

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2328]
**Preconditions:**
Open SPGI table.

**Case 1: docking viewer**
1. Add a viewer
2. Dock it to the left or to the top
**Expected results:** viewer is still visible after docking.
**Actual results:** viewer is hidden.
![2023-09-04_13-10-16 (1)](https://github.com/datagrok-ai/public/assets/15780643/952807f7-bd4d-435e-958e-95b29373b143)
Issue happens more often for docking to the left, but sometimes can be also reproduced for docking to the top of the page.

**Case 2: applying saved layout**
1. Add a viewer to the left side of screen or open filters
2. Save layout
3. Decrease window width in any way (resize browser window, change screen resolution or open browser console at the right)
4. Re-apply saved layout
**Expected results:** All viewers and filters should be visible when layout is re-applied.
**Actual results:** viewer or filters docked to the left are hidden:
![2023-09-04_13-26-14 (1)](https://github.com/datagrok-ai/public/assets/15780643/1de2ac78-25d7-4c1c-940e-164087b61818)
This case is the most likely to happen for filters, because their default position is on the left.

**Comment by ahadzhanian** [comment]
1.16.5
