### ISSUE TITLE
Histogram 'normalise to filter' option: Y axis values are not updated on zooming

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2329]
1.16.4

**Steps to reproduce:**
1. Open a table
2. Add a histogram
3. Make sure 'normalise to filter' option is on (it is on by default)
4. Zoom in using the slider

**Expected results:** values on Y axis should be adjusted on zooming when 'normalise to filter' option is on.
**Actual results:** values on Y axis are not changed when bars are scaled on zooming:
![2023-09-05_12-56-21 (1)](https://github.com/datagrok-ai/public/assets/15780643/d645bf1a-9200-48aa-af4b-7d046c1e5a33)

**Comment by ahadzhanian** [comment]
1.16.5
