### ISSUE TITLE
Scatter plot: has to show empty categories like Box plot and Bar chart do

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2330]
- [x]  Scatterplot has to show empty values like Box plot and Bar chart
- [x] The display of empty categories on the screen should be consistent for all three viewers
![image](https://github.com/datagrok-ai/public/assets/111368431/65855863-732b-4ea0-8b5d-35f070750269)

**Comment by ahadzhanian** [comment]
DG 1.17.0 - the first item
DG 1.18.0 (1.17.1)  - the second item

**Comment by katerina-stepanova** [comment]
DG 1.17.4

Some data is missing on filtering, if scatter plot has "Pack and zoom by filter setting"

**Comment by katerina-stepanova** [comment]
DG 1.17.4

**"No action"** option and row source = **"filtered"**: all data is shown even if there is some filtering:
<img width="1012" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/d4018b1c-ab08-498e-8c9b-183ee684e94c">

**Comment by ahadzhanian** [comment]
1.17.6
