### ISSUE TITLE
Properties panel: property names are hidden if some values are very long

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2341]
**Steps to reproduce**
1. Open a table, e.g. SPGI
2. Add a viewer
3. Open Properties panel
4. Enter a long value into some text input for a property (Filter, Title, Font)
5. Click outside the input to apply

**Expected results:** Property names in the properties panel should always be visible.
**Actual results:** Property names are sometimes hidden if value is long:
<img width="815" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/f75626d3-5f2c-4ac1-8148-30cce89c75a8">

**Comment by alex-aprm** [comment]
Fixed in 1.17.0
