### ISSUE TITLE
'Error loading line chart' on applying layout, if line chart has categorical X axis and row source = Selected

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2350]
DG 1.16.5

**Steps to reproduce:**
1. Open a table
2. Add a line chart
3. Use a categorical columns as X axis
4. Switch row source to 'Selected'
5. Save layout
6. Make sure there are no selected rows
7. Apply layout

**Expected results:** no errors.
**Actual results:** line chart is not loaded, 'Error loading line chart' message is shown.
Error in console that might be related:
html_dart2js.dart:3558 Invalid argument: 0.02
	https://grok.tst.nibr.novartis.net/packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1772:17      Object.u
	https://grok.tst.nibr.novartis.net/packages/$sdk/lib/_internal/js_runtime/lib/js_number.dart 154:42       ax.aM
	https://grok.tst.nibr.novartis.net/packages/d4/src/widgets/filter/slide_filter_core.dart 206:16           aVt.Jr
	https://grok.tst.nibr.novartis.net/packages/d4/src/line_chart/line_chart_core.dart 506:7                  Ap.jg
	https://grok.tst.nibr.novartis.net/packages/d4/src/line_chart/line_chart_core.dart 463:7                  Ap.aL.
	https://grok.tst.nibr.novartis.net/packages/d4/src/line_chart/line_chart_core.dart 205:7                  Ap.dw
	https://grok.tst.nibr.novartis.net/packages/d4/src/viewer_base/viewer_base.dart 107:9                     daU.
	https://grok.tst.nibr.novartis.net/packages/$sdk/lib/async/zone.dart 1132:12                              b.M
	https://grok.tst.nibr.novartis.net/packages/$sdk/lib/async/zone.dart 1309:14                              dmA.I1
	https://grok.tst.nibr.novartis.net/packages/$sdk/lib/async/stream_impl.dart 330:5                         deI.aD
	https://grok.tst.nibr.novartis.net/packages/$sdk/lib/async/stream_impl.dart 257:7                         oi.kR
	https://grok.tst.nibr.novartis.net/packages/$sdk/lib/async/broadcast_stream_controller.dart 387:7         doq.
	https://grok.tst.nibr.novartis.net/packages/$sdk/lib/async/broadcast_stream_controller.dart 328:9         x.a7U
	https://grok.tst.nibr.novartis.net/packages/$sdk/lib/async/broadcast_stream_controller.dart 386:5         x.aD
	https://grok.tst.nibr.novartis.net/packages/$sdk/lib/async/broadcast_stream_controller.dart 254:5         LJ.DA
	https://grok.tst.nibr.novartis.net/packages/prop_gen/property.dart 182:11                                 cD8.
	https://grok.tst.nibr.novartis.net/packages/prop_gen/property.dart 254:7                                  cDg.
	https://grok.tst.nibr.novartis.net/packages/xamgle/src/property_grid/prop_grid.dart 132:22                e92.
	https://grok.tst.nibr.novartis.net/packages/xamgle/src/property_grid/prop_grid.dart 97:16                 e9B.
	https://grok.tst.nibr.novartis.net/packages/property_grid/property_item_controller.dart 91:5              AI.OC
	https://grok.tst.nibr.novartis.net/packages/property_grid/editors/editor_spinner.dart 33:7                cAR.
	https://grok.tst.nibr.novartis.net/packages/$sdk/lib/html/dart2js/html_dart2js.dart 42920:48              dhB.
	https://grok.tst.nibr.novartis.net/packages/$sdk/lib/async/zone.dart 1132:12                              b.M
	https://grok.tst.nibr.novartis.net/packages/$sdk/lib/async/zone.dart 1012:12                              dfh.AI
	https://grok.tst.nibr.novartis.net/packages/$sdk/lib/async/zone.dart 909:14                               dfh.I1
	https://grok.tst.nibr.novartis.net/packages/$sdk/lib/async/zone.dart 936:23                               dfk.
	https://grok.tst.nibr.novartis.net/packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:48      fQ1.
	https://grok.tst.nibr.novartis.net/packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 474:16  Ou.Mv
	https://grok.tst.nibr.novartis.net/packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 59:16   Object.G6
	https://grok.tst.nibr.novartis.net/packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:14      fQ.
	https://grok.tst.nibr.novartis.net/packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2476:14      HTMLSelectElement.<fn>

Issue did not happen on DG 1.15.*

**Comment by ahadzhanian** [comment]
1.16.6
