### ISSUE TITLE
Colour and formatting changes are reset on interacting with filters if group tooltip is set

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2356]
DG 1.15.4, 1.16.6

**Steps to reproduce:** 
1. Open a table, e.g. SPGI
2. Change format for some column
3. Set colouring for some column
4. Right click on the table > tooltip > use as group tooltip
5. Open filters and hover some filter or add a viewer using group tooltip and hover it (e.g. bar chart, histogram)

**Expected results:** interaction with filters or other viewers does not reset colouring or formatting.
**Actual results:** Colouring is removed, formatting is reset to default.
Issue can be reproduced for a newly set colouring/formatting and for colouring /formatting applied with layout.

**Comment by ahadzhanian** [comment]
DG 1.17.0
