### ISSUE TITLE
Line chart: Custom tooltip

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2357]
If the column is not used in Split, an aggregation selector should be next to it in the Tooltip Dialog.
Default aggregations are:

- [x]  for numeric columns - avg
- [x]  after that, implement the feature for all viewers with aggregation
- [x] implement the access to the tooltip via API
- [x] Make the dialog more intuitive - add tooltips
- [x] Add aggregation for strings - concatenation

**Comment by ahadzhanian** [comment]
DG 1.17.0

**Comment by katerina-stepanova** [comment]
v1.17.3

Customised tooltip is not displayed at all:
1. Add line chart
2. Set a column with non-unique values on X axis
3. Configure customised line chart tooltip and make sure it is enabled
4. Hover something on the line chart

**Expected results:** customised tooltip should be shown.
**Actual results:** tooltip is not shown at all.

Default aggregated tooltip is shown until user edits it.

**Comment by ahadzhanian** [comment]
1.17.4
