### ISSUE TITLE
Some rows are still shown if filter's range is set out of data's boundaries

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2364]
1.16.6

**Steps to reproduce:**
1. Open a table
2. Open filters
3. Add some numerical filter
4. Show min/max for the filter
5. Enter range that does not match any data in table

**Expected results:** all rows should be filtered out.
**Actual results:** some rows are still shown:
<img width="558" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/0ba06c4b-dcfe-4736-932e-8c7c7eb68cb9">

Not reproduced in 1.15.4

**Comment by katerina-stepanova** [comment]
Good solution would be to make it clear to the user that min or max value set is out of valid range.

**Comment by dionissqq** [comment]
it is indicated by inputs becoming red, and there is tooltip "Value out of range" if you hover over this input

**Comment by ahadzhanian** [comment]
DG 1.17.0
