### ISSUE TITLE
Structure filter is not reset on clicking 'Clear'

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2365]
1.16.6, chem 1.7.2

**Steps to reproduce:**
1. Open SPGI
2. Open filters
3. Add structure filter
4. Draw/paste some structure > OK > filter is applied
5. Click 'Clear' for the structure filter

**Expected results:** structure is removed, structure filtering is reset.
**Actual results:** structure is removed, but filtering is still applied:
![2023-09-25_14-54-46 (1)](https://github.com/datagrok-ai/public/assets/15780643/0fb46ed5-674e-44ff-a38b-eee8f1ebe9e4)

Workaround: filtering is removed on disabling structure filter and does not reappear when it's re-enabled.

Not reproduced in 1.15.4, chem 1.6.20

**Comment by MariaDolotova** [comment]
@katerina-stepanova, did you check for errors in a developer console? If yes, could you provide a stacktrace, please? That would be very helpful for investigation.

**Comment by katerina-stepanova** [comment]
Issue can be reproduced for Marvin editor, but not for OpenChemLib.

**Comment by MariaDolotova** [comment]
@katerina-stepanova , are you using Marvin version 3.1.3?

**Comment by katerina-stepanova** [comment]
@MariaDolotova yes, we have Marvin 3.1.3

**Comment by ahadzhanian** [comment]
Marvin 1.3.6
