### ISSUE TITLE
#238: Core: dataset doesn't open from property panel Actions

### ISSUE THREAD

**Issue by vdyma** [datagrok-ai/public#238]
On [public](public.datagrok.ai) it's not possible to open a dataset from Actions panel in property panel. The following error appears:
```
error: Operation caused an exception (NoSuchMethodError: The getter 'metaParams' was called on null.
Receiver: null
Tried calling: metaParams)
```
![recording-(2)](https://user-images.githubusercontent.com/25188402/147609211-035fe136-6a83-4324-b792-5c8912a901e7.gif)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16036

**Comment by dnillovna** [comment]
> Andrew Skalkin commented in Jira:

“Actions” panel is no more
