### ISSUE TITLE
Line chart: unaggregated tooltip and hovered row do not match in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2395]
v.1.16.6

**Steps to reproduce:**
1. Open SPGI
2. Add a line chart
3. Set 'Last Published date' or 'Structure' as X axis
4. Hover line chart and see tooltip

**Expected results:** tooltip is shown exactly for the row hovered on the line chart.
**Actual results:** tooltip is shown at the mouse cursor position, but hovered row indicator line is at some other place:
<img width="925" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/b84ac2e1-9479-4226-9e4e-733c8521bd22">
Issue is probably reproduced for categorical columns on X axis mostly.

**Comment by ahadzhanian** [comment]
Can't be reproduced on 1.17 bleeding edge. 
Probably is already fixed in 1.17.0
