### ISSUE TITLE
Line chart: only half of the dot is displayed if it is close to the horizontal axis

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2398]
**Steps to reproduce:** 
1. Open SPGI table
2. Add a line chart with 2-3 columns on Y
3. Set categorical column with not too many values as X (e.g. Chemist521 in SPGI dataset)
4. See how the dots closest to the horizontal axis are displayed

**Expected results:** Each dot on the plot is displayed completely.
**Actual results:** Some dots are cut in half:
![image](https://github.com/datagrok-ai/public/assets/15780643/4db3a936-f989-4f26-93ab-a3233854112b)

**Comment by ahadzhanian** [comment]
Case 2:
X=Chemist521
Y=Competition assay
Split: Core, Series
![image](https://github.com/datagrok-ai/public/assets/111368431/80567174-d257-4be7-9feb-e6a5ffdd0682)

**Comment by ahadzhanian** [comment]
DG 1.17.0
