### ISSUE TITLE
Scaffold tree viewer: coloring can't be saved to the Layout

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2399]

**Comment by ahadzhanian** [comment]
Chem 1.8.1

**Comment by katerina-stepanova** [comment]
Chem 1.8.2:

Scaffold colouring from the layout is not restored after re-loading browser page, re-opening the table and applying layout.
It is only restored if layout was re-applied without re-loading.

**Comment by ahadzhanian** [comment]
Chem 1.8.3
