### ISSUE TITLE
Chem: renderMolecule method

### ISSUE THREAD

**Issue by skalkin** [datagrok-ai/public#240]
- returns DivElement with canvas
- uses package-defined rendering options
- context menu also available from the "dots" mouse-over element: copy smiles, copy molblock, sketch, explore

**Comment by vdyma** [comment]
I just made a commit with mostly implemented `renderMolecule` method [here](https://github.com/datagrok-ai/public/blob/master/packages/Chem/src/package.ts#L124). Could you please clarify what is 'explore' action supposed to do?
