### ISSUE TITLE
Scatter plot: min/max values are not saved/restored in the layout

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2402]
v1.16.7
Also can be reproduced on current public env version.

**Steps to reproduce:**
1. Open a table
2. Add a scatter plot
3. Change a column for one of the scatter plot axes, choose numerical one
4. Set min/max values for this numerical column on scatter plot
5. Save layout
6. Re-apply layout
7. Check min/max values after re-applying layout

**Expected results:** min/max values are saved and restored.
**Actual results:** min/max values are not restored.
![2023-10-12_13-29-16 (1)](https://github.com/datagrok-ai/public/assets/15780643/817787a5-c47c-446e-8461-297cc320917b)

This is a regression, it used to be working correctly in some previous version.

**Comment by ahadzhanian** [comment]
The min and max values are reset on the plot after adding another viewer.

![Image](https://github.com/datagrok-ai/public/assets/111368431/5fed78ac-a0e0-482d-a752-f782e36ee9b0)

**Comment by dionissqq** [comment]
it works correctrly, you see the result of Axes Follow Filter property

**Comment by ahadzhanian** [comment]
1.17.0
