### ISSUE TITLE
Scatter plot: incorrect tooltip for 'zoom and filter'

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2408]
v1.16.7

**Steps to reproduce:**
1. Add a scatter plot
2. Open properties panel
3. Hover 'zoom and filter' option

**Expected results:** rename the last entry into 'pack and zoom by filter' in the tooltip
**Actual results:** two last options have same names in the tooltip:
<img width="711" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/b563ca90-59fb-48af-b7f5-dfca3e30adb5">

**Comment by ahadzhanian** [comment]
1.17.0
