### ISSUE TITLE
#2410: Projects can't be opened after changing the connected data query name

### ISSUE THREAD

**Issue by LaykDimon** [datagrok-ai/public#2410]
After renaming a query name, which is connected to the project, the project can't be opened and throws the following error:

```
Method "METHOD_NAME" not found for object type "Namespace"
      packages/$sdk/lib/_internal/js_runtime/lib/core_patch.dart 680:36      Object.a0m
      packages/grok_shared/src/log.dart 167:40                               aN0.ce
      packages/grok_shared/src/log.dart 120:12                               Eb.ap1
      packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 213:19     e62.a
      packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 237:5      e62.
      packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 187:19     dq2.
      packages/$sdk/lib/async/zone.dart 1371:54                              dmB.AI
      packages/$sdk/lib/async/future_impl.dart 129:12                        diY.
      packages/$sdk/lib/async/future_impl.dart 665:13                        Object.y3
      packages/$sdk/lib/async/future_impl.dart 343:9                         diP.
      packages/$sdk/lib/async/schedule_microtask.dart 41:5                   Object.e34
      packages/$sdk/lib/async/schedule_microtask.dart 50:5                   hbV
      packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 51:9       de3.
      packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:48      fQ2.
      packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 474:16  Ou.Mv
      packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 59:16   Object.G6
      packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:14      fQ0
      packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2476:14      MutationObserver.<fn>
```

Remark: The `METHOD_NAME` can't be replaced with any query name.

Also, any project that uses the broken query will not reload even if created as a new project.

If you need me to give you more details, I can easily screen-share the problem.

The problem appears on the client instance of version 1.16.7.

**Comment by LaykDimon** [comment]
@alex-aprm
We had a working query and a project with this query. Everything worked alright for one day, but then the next day, the query somehow just stopped working (??). After this, the project stopped working, so the new query was created, which worked correctly, and the new project with this query was created as well. So, why can the query break itself, and what actions can lead to this effect?

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14881

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16141
