### ISSUE TITLE
#2424: Charts: handle the invalid input data

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2424]
- [x] For the invalid input data, the viewer should be disabled in the Add Viewer dialog (and show tooltip with explanation)
- [x] Viewers should display a message for the invalid input data, indicating that the dataset can't be processed (in case the viewer is switched to the table with invalid data)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14615
