### ISSUE TITLE
Some structures are displayed incorrectly when highlighted if they are in SMILES format

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2448]
1.16.7, chem 1.8.2

**Steps to reproduce:** 
1. Open a table with SMILES structures having some stereochemistry elements, e.g.
[SMILES_highlighted.csv](https://github.com/datagrok-ai/public/files/13053883/SMILES_highlighted.csv)
2. Make these structures highlighted:
either use scaffold tree to highlight
or use structure filter

**Expected results:** highlighted structure is displayed in the same way as non-highlighted.
**Actual results:** stereochemistry is lost when structure is highlighted:
<img width="720" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/2a81adb3-a57b-47a5-a661-0904aaedc15a">
<img width="748" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/9c6a624d-7552-43e1-8d91-5c324668beee">
Same molecule in MOLfile format is displayed correctly when highlighted.

**Comment by ahadzhanian** [comment]
Chem 1.8.4
