### ISSUE TITLE
#245: ML: Predictive modeling using H2O does not work

### ISSUE THREAD

**Issue by nikolay-alemasov** [datagrok-ai/public#245]
### How to reproduce
1. Open https://dev.datagrok.ai/f/Demo.TestJobs.Files.DemoFiles/demog.csv
2. Select ML | Train Model...
3. Select any columns for Predict & Features
4. Press TRAIN

### Expected behavior
A model is created.

### Observed behavior
Progress indicator is hung. Error "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again" is logged into console.
[dev.datagrok.ai-1641443079773.log](https://github.com/datagrok-ai/public/files/7819462/dev.datagrok.ai-1641443079773.log)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16037
