### ISSUE TITLE
Scaffold tree imported from file is not restored on applying saved layout

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2450]
v1.16.7
chem 1.7.2, 1.8.2

**Steps to reproduce:**
1. Open a table with some molecules
2. Add scaffold tree viewer
3. Upload scaffold tree from file
4. Save layout
5. Refresh browser page
6. Open the same table
7. Re-apply saved layout

**Expected results:** scaffold tree is restored when layout is re-applied.
**Actual results:** scaffold tree is empty when layout is re-applied.

**Comment by ahadzhanian** [comment]
Chem 1.8.3

**Comment by ahadzhanian** [comment]
Incorrect reapplying of the layout on DG 1.17.0
![2450](https://github.com/datagrok-ai/public/assets/111368431/8a7ad21b-5534-46da-894b-99eca2ec47ff)

**Comment by ahadzhanian** [comment]
Chem 1.8.4
