### ISSUE TITLE
Viewers: Add the ability to choose several categories with ctrl click

### ISSUE THREAD

**Issue by dionissqq** [datagrok-ai/public#2455]
- [x] Use Ctrl+click to select/deselect one more category
- [ ] Sync the global filtering
- [x] Add an option for local viewer filtering
- [x] Reset the filter (on the Filter Panel) shouldn’t break the viewer

**Comment by ahadzhanian** [comment]
Check also the **In viewer Filtering** property (Legend tab)

**Comment by ahadzhanian** [comment]
In viewer Filtering is not implemented for the histogram.

![Image](https://github.com/datagrok-ai/public/assets/111368431/dfdabbdb-9e8a-4d81-8646-e027d39ef894)

**Comment by ahadzhanian** [comment]
1.18.0

**Comment by ahadzhanian** [comment]
DG 1.17.6

**Comment by katerina-stepanova** [comment]
1.17.6

A few issues specific to MacOS:
1. When one of several selected categories is de-selected with cmd-click, it is still shown as selected in the legend. Issue can be reproduced for all viewers.
![2023-11-30_11-54-27 (1)](https://github.com/datagrok-ai/public/assets/15780643/b7e39550-06f4-4c3b-9e9a-8d7f1153eea2)
2. Line chart: it's not possible to select multiple categories. Cmd-click does the same as regular click.

**Comment by ahadzhanian** [comment]
1.18.0
