### ISSUE TITLE
Chem: Scaffold Tree: Bugs and improvements (Сhem 1.8.4)

### ISSUE THREAD

**Issue by Aleksashka11** [datagrok-ai/public#2459]
- [x] Add Expand All/Collapse All icons for easy navigation
- [x] Size change doesn't work
- [x] Orphan cards should have the same design and functionality
- [x] Child shouldn't duplicate the parent
- [x] the “trash can” icon is red and stands out from the general style; make a blue one from the same collection
- [x] it would be nice to save the state of the tree (what was selected, what was expanded) when saving

**Comment by ahadzhanian** [comment]
Chem 1.8.4
