### ISSUE TITLE
Allow to set tab label for stacked viewers programmatically

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2467]
DG 1.16.*

Currently it is not possible to set tab label for stacked viewers programmatically. Label will be the the viewer's name.

**Expected:**
Allow to set programmatically custom tab labels for stacked viewers.

**Comment by dionissqq** [comment]
for a viewer add a property named title and set its value before adding to the view:
`this.title = this.string('title', 'RadarTitle', {description: 'Title of the chart'});`
![image](https://github.com/datagrok-ai/public/assets/47571050/f2f381b4-cbf9-49c4-86db-bf5eb9276ed0)

**Comment by ahadzhanian** [comment]
1.17.3

**Comment by nrareoanwts** [comment]
doesn't work properly in some cases:
1) while creating lineChart using following (extend DG.TableView:)
const lc = this.lineChart(lineChartJson1);
grok.shell.tv.dockManager.dock(lc, DG.DOCK_TYPE.RIGHT);
 
2) works only if pass view.**root** property and specify the fourth **title** parameter
const dockNode = tv.dockManager.dock(view1.root, dockType, refNode, 'New title 1);
tv.dockManager.dock(view2.root, DG.DOCK_TYPE.FILL, dockNode, 'New title 2');

**Comment by ahadzhanian** [comment]
1.17.4

**Comment by ahadzhanian** [comment]
DG 1.18.0
