### ISSUE TITLE
Cell values starting with the quote character are parsed incorrectly

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2468]
v1.16.*

**Steps to reproduce and results:**
1. Open a csv file with a cell starting with quote character, correctly escaped, e.g.:
```
id,cat,cor1,cor2,cor3
1,AA,1,2,3
2,AA,4,5,6
3,"""BB"" ccc",7,8,9
4,CC,10,11,12
```
Value is displayed as **""BB"** instead of just "BB":
<img width="291" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/63e2437f-dc0e-4790-905b-f1437995edac">

Exporting this data further corrupts it:
2. Download opened table as CSV, check how it looks
**Results:** Extra pair of quotes is added to the cell:
```
id,cat,cor1,cor2,cor3
1,AA,1,2,3
2,AA,4,5,6
3,"""""BB"" ccc",7,8,9
4,CC,10,11,12
```
3. Open downloaded file in DG again
**Results:** values are not displayed as expected:
<img width="295" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/92b1d434-f8dc-4b85-a12a-1cfdee5f7fd9">

**Expected results:** quotes at the beginning of the cell value should be parsed and displayed correctly. When downloaded file is opened in DG again, table should look the same as original one.

**Comment by skalkin** [comment]
Just a reference to the discussion (obviously exporting/importing should preserve the value so something is wrong)

----
RFC-4180, paragraph "If double-quotes are used to enclose fields, then a double-quote appearing inside a field must be escaped by preceding it with another double quote." – 
[tommed](https://stackoverflow.com/users/127018/tommed)
 [Feb 18, 2015 at 16:35](https://stackoverflow.com/questions/17808511/how-to-properly-escape-a-double-quote-in-csv#comment45484411_17808731)

**Comment by ahadzhanian** [comment]
DG 1.18.0 (1.17.1)
