### ISSUE TITLE
#247: ML: Stochastic Proximity Embedding does not work

### ISSUE THREAD

**Issue by nikolay-alemasov** [datagrok-ai/public#247]
### How to reproduce
1. Open https://dev.datagrok.ai/f/Demo.TestJobs.Files.DemoFiles/demog.csv
2. Select ML | Stochastic Proximity Embedding

### Expected behavior
An embedding is created.

### Observed behavior
Nothing happens. Error "error: NullError: method not found: 'prepare$0' on null" is logged into console.
[dev.datagrok.ai-1641444942676.log](https://github.com/datagrok-ai/public/files/7819547/dev.datagrok.ai-1641444942676.log)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16039
