### ISSUE TITLE
Structure filter: 'current value > use as filter' breaks filtering in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2473]
chem 1.8.3, 1.8.2, 1.8.0

**Steps to reproduce:**
1. Open a table, e.g. SPGI or [PubChem_compound_text_covid-19.csv](https://github.com/datagrok-ai/public/files/13207046/PubChem_compound_text_covid-19.csv)
2. Open filters and make sure some structure column is added to the filter panel
3. Add another view with the same table (e.g. clone current view)
4. Open filters and make sure same structure column is added to the filter panel in the 2nd view
5. Right click some structure > Current value > use as filter

**Expected results:** filter is applied, filters are synchronised in two open views.
**Actual results:** Looks like filtering process never ends, some rows are appearing/disappearing indefinitely:
![2023-10-30_18-17-43 (1)](https://github.com/datagrok-ai/public/assets/15780643/4c411698-16d3-4d90-aacf-ddda340494e1)
In some cases filtering does not start until switching to another view. After that behaviour is the same as described above.

Not reproduced on chem 1.7.2

**Comment by ahadzhanian** [comment]
Chem 1.8.4
