### ISSUE TITLE
Scaffold tree: rows are shown as filtered for a while after applying structure even if checkbox is not selected

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2476]
chem 1.8.3

**Steps to reproduce:**
1. Open a table with structures
2. Add scaffold tree viewer
3. Draw some structure > Add

To reproduce the issue use some larger dataset and structure that will result in long search.

**Expected results:** data is not filtered if checkbox near the structure is not selected.
**Actual results:** After clicking 'Add' structure search is started and 3 dot showing search progress are displayed. At some point table is filtered for a while, then it returns to non-filtered state.
Issue is sporadic, but it may confuse users a lot.

**Comment by ahadzhanian** [comment]
Chem 1.8.4
