### ISSUE TITLE
In-viewer filter: the result depends on the order in which formula parts are written

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2479]
public 1.17.0
Data: SPGI
1.Add a linechart
2. Set Filter to
* ${Series} == "Pyrrolidines" && ${Stereo Category} in ["R_ONE", "S_UNKN"] - works
* ${Stereo Category} in ["R_ONE", "S_UNKN"] && ${Series} == "Pyrrolidines" - `Invalid formula`

![Invalid_formula](https://github.com/datagrok-ai/public/assets/111368431/019b0dd0-4e32-4be6-8627-aaf2de38902b)

**Comment by alex-aprm** [comment]
Fixed in 1.17.1
