### ISSUE TITLE
#2481: BsV: Import ligands from .pdbqt format

### ISSUE THREAD

**Issue by tanas80** [datagrok-ai/public#2481]
- [x] Parse pdbqt file
- [x] import a MODEL per row, 
- [x] other atoms place to dataframe's tag 'pdb' to be read by Biostructure viewer

**Comment by ahadzhanian** [comment]
is blocked by https://reddata.atlassian.net/browse/GROK-14438

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14884
