### ISSUE TITLE
Box plot: no indication what dot is hovered, wrong dot is selected in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2484]
v 1.17.1

**Steps to reproduce:**
1. Open a table
2. Add a box plot
3. Hover a dot and ctrl-click to select it (cmd-click on MacOS)

**Expected results:** hovered dot should be selected.
Nice to have some indication of what dot is hovered, similar to scatter plot.

**Actual results:** no indication what dot is hovered. In some cases wrong dot is selected (i.e. some dot away from the current cursor position):
![2023-11-03_15-56-53 (1)](https://github.com/datagrok-ai/public/assets/15780643/b4d4bcbf-6fca-4ee3-b6c5-6e180e1e1342)

**Comment by ahadzhanian** [comment]
DG 1.17.3
