### ISSUE TITLE
Line chart: too much empty space if Y axis is logarithmic for specific data

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2485]
v1.17.1, not reproduced on same data on v1.16.*

**Steps to reproduce:**
1. Open SPGI
2. Add line chart
3. Set 'Num Heavy Atoms' on X axis
4. Set 'Whole blood assay 1' on Y axis
5. Switch Y axis to logarithmic

**Expected results:**  line chart axes range is adjusted according to the data shown.
**Actual results:** for some data there is too much empty space in the line chart:
<img width="654" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/c55b1ed8-0941-4275-849c-ea3b6726517c">

**Comment by skalkin** [comment]
@dionissqq This is probably due to us adding a small margin in the bottom - it has to be calculated with log scale in mind, like we do in scatter plot

**Comment by ahadzhanian** [comment]
DG 1.17.3
