### ISSUE TITLE
#2487: Scatter plot: datetime columns are not supported when adding formula lines

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2487]
v1.16.8, 1.17.1

**Steps to reproduce:**
1. Open a table that has some datetime columns (e.g. use SPGI and switch 'First Reg Date' to datetime)
2. Add a scatter plot
3. Set up datetime columns for one or both axes
4. Add formula line

**Expected results:** it should be possible to to add formula lines for scatter plots with datetime axes.
**Actual results:** formula line is not displayed:
![2023-11-06_13-22-12 (1)](https://github.com/datagrok-ai/public/assets/15780643/efae0639-8c7e-4163-9478-465cb3f9bc13)
In some cases it is possible to add a line when both axes are datetime, using formula like `${First Reg Date} = date(2017, 1, 1)` but i could not reproduce it myself.

**Comment by ahadzhanian** [comment]
Сan’t set a Date type value in Formula Lines
![image (46)](https://github.com/datagrok-ai/public/assets/111368431/70bde2ea-d658-47da-8624-44bae882ebe8)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14594

**Comment by dnillovna** [comment]
> Olena Ahadzhanian commented in Jira:

Use UnixTimestamp(Date(2011, 1, 1)) to set the date value

DG 1.18.0
