### ISSUE TITLE
Colour selector is missing for formula lines dialog

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2488]
v1.17.1, not reproduced in 1.16.*

**Steps to reproduce:**
1. Open a table
2. Add a scatter plot
3. Open formula lines dialog
4. Add a line
5. Check colour input

**Expected results:** colour selector should be present.
**Actual results:** colour selector is missing, it is only possible to input colour code manually:
<img width="766" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/3a447600-3d3e-4b81-ac73-70130b185382">

**Comment by ahadzhanian** [comment]
PowerPack v1.1.1
