### ISSUE TITLE
Colour selector opened from the 'style' section in properties panel cannot be closed

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2489]
v1.17.1, not reproduced in 1.16.*

**Steps to reproduce:**
1. Open properties panel for any viewer or table itself
2. Scroll to Style section
3. Open colour selector for any property
4. Try to close the colour selector

**Expected results:** it should be possible to close colour selector, e.g. on clicking outside it.
**Actual results:** there is no evident way to close colour selector: click outside, enter, escape, selecting a colour or opening another colour selector does not allow to close it.
Colour selectors are left open even after the table is closed:
<img width="1276" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/eac39c8c-59f4-4e4e-ad07-fd901f791919">

**Comment by ahadzhanian** [comment]
DG 1.17.3
