### ISSUE TITLE
#2491: Docker container for Autodock

### ISSUE THREAD

**Issue by GennadiyZakharov** [datagrok-ai/public#2491]
# Background
This ticket covers the development of the Docker container for the Autodock plugin. See the full description in the parent ticket.

# Scope of work
The Docker container should contain the autogrid4 and Autodock-GPU utilities and all required scripts. Container functions:

## Run grid calculations for macromolecule. 
* Input:
    * Macromolecule pdb/pdbqt file
    * Grid parameters file
* Output: 
    * Calculation log
    * Grid files are stored in the docker container/volume. There is no need to return it to the client
* Cache calculated grids (using Docker volumes or similar):
    * On the first run, save grid files to local storage (suggest Docker volumes)
    * Bypass calculations for the macromolecules that already have the grids.
    * Accept a flag to force grid re-calculation.

## Run the docking calculation for the small molecule and the macromolecule. 
If the macromolecule grids are not available, run grid calculation first. The docking calculations should use the GPU version of Autodock.
* Input
    * small molecule pdb/mol2 file
    * macromolecule file name
* Output
     * Full docking log file
     * molecule conformation in the pdbqt file (extracted from the docker logs)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14886
