### ISSUE TITLE
#2492: Autodock plugin

### ISSUE THREAD

**Issue by GennadiyZakharov** [datagrok-ai/public#2492]
# Background
The epic covers the development of the docking plugin for Datagrok using the Autodock4 engine.
The discussion thread: https://datagrok.slack.com/archives/G01BZ4Y776E/p1698873693338189 

# Use cases
* You have the macromolecule (receptor) PDB file and a dataframe with small molecules.
* You run docking of the molecule set to the macromolecule.
* Autodock returns a set of possible 3D conformations for each small molecule. 
* Datagrok joins all docked conformations in the single dataframe and displays it
* You can explore the docking results using the existing Datagrok docking results viewer.

# Technical realization
We use for the docking the combination of the original Autodock tool (https://autodock.scripps.edu/download-autodock4/) and the GPU-optimized version of Autodock: https://github.com/ccsb-scripps/AutoDock-GPU 

To perform the docking, we need to do the following:
* Specify the dataframe column containing small molecules and choose the pre-configured macromolecule via input UI: https://github.com/datagrok-ai/public/issues/2568
* Perform the docking https://github.com/datagrok-ai/public/issues/2491
    * Calculate atomic grids using the autogrid4 utility. This is a time-consuming step running on a single CPU. We cache the grids in the contained, so subsequent runs with the same macromolecule don't require grids calculation.
    * Convert small molecule to pdbqt format
    * Perform docking using the Autodock-GPU utility
* Visualize results
    * Open the macromolecule on the 3D viewer
    * Parse the Autodock log and extract the pdbqt records for the small molecule (simple shell script implemented): https://github.com/datagrok-ai/public/issues/2481
    * Show the molecule conformation on the 3D viewer. TODO: discuss the way to switch conformations.

# Improvements
* Handle the failures in the docking calculations: https://github.com/datagrok-ai/public/issues/2732
* File preview handler for autogrid configuration files: https://github.com/datagrok-ai/public/issues/2740
* Notification in the "poses" column for the failed run: https://github.com/datagrok-ai/public/issues/2741

**Comment by GennadiyZakharov** [comment]
# Run scripts
[autodock4-run.txt](https://github.com/datagrok-ai/public/files/13267744/autodock4-run.txt)
[autogrid4-run.txt](https://github.com/datagrok-ai/public/files/13267745/autogrid4-run.txt)
[autodock4-set-conda-env.txt](https://github.com/datagrok-ai/public/files/13267761/autodock4-set-conda-env.txt)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14887

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16146

**Comment by GennadiyZakharov** [comment]
The autodock plugin has implemented.
