### ISSUE TITLE
Pivot table: Save coloring and column settings to the layout

### ISSUE THREAD

**Issue by DanTkachev** [datagrok-ai/public#2497]
Currently, if a user defines any coloring settings for the Pivot table (e.g. column coloring), saves the analysis and then reloads the page, the coloring settings are not restored (as it would happen for other viewers, such as scatterplot). It would be good to save the coloring as otherwise, users might lose their work.

The same applies to Grid settings (ordering/hiding columns).

**Comment by ahadzhanian** [comment]
Is already fixed in 1.17
available in 1.17.3
