### ISSUE TITLE
#2500: Sunburst improvements

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2500]
- [x] Sunburst doesn't filter - add an option: selection or implement on-click filtering like in the bar chart
- [x] Add Row Source 
- [x] Hierarchy - provide a dialog like Order and Hide with all/visible/ hidden
- [x] Turn off the ability to drill down on click (ctrl +click or cmd+click)
- [x] Wrap the long labels and show the whole text in the tooltip
- [x] Add a tooltip: label + row count
- [x] Labels are hidden after the structures are added (bug)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14617

**Comment by ahadzhanian** [comment]
Charts > 1.2.2
