### ISSUE TITLE
Filter Panel: buttons on the filter panel appear on hovering only

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2502]
Buttons on the filter panel should not disappear: 
- [x] Set an option from the API to show the buttons on the Filter Panel constantly
- [x] Show them with a very pale grey color - as an option

**Comment by ahadzhanian** [comment]
DG 1.17.6

**Comment by dionissqq** [comment]
use
`grok.shell.settings.showFiltersIconsConstantly = true`
