### ISSUE TITLE
Filter Panel: The question mark hovering doesn’t show the filtering of the scaffold tree viewer 

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2504]
The question mark hovering doesn’t show the filtering of the scaffold viewer as it does for the other filters

**Comment by ahadzhanian** [comment]
Chem 1.8.7 DG 1.17.0

**Comment by ahadzhanian** [comment]
Expected behavior for the Scaffold tree viewer (not only the filter)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14595

**Comment by ahadzhanian** [comment]
DG 1.18.0, Chem 1.9.0
