### ISSUE TITLE
#2505: Scatterplot: If categories are filtered out they shouldn't be shown in the marker legend

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2505]
![image](https://github.com/datagrok-ai/public/assets/111368431/a66670fc-9a89-4baa-851d-56173bc6ac38)

The issue can still be reproduced if the Marker is set before the Filter
 ${Stereo Category} in ["R_ONE", "S_UNKN"]

**Comment by ahadzhanian** [comment]
The issue can still be reproduced if the Marker is set before the Filter


![Image](https://github.com/datagrok-ai/public/assets/111368431/88ee4fbd-d9d3-476a-b64a-2c378723eea4)

**Comment by ahadzhanian** [comment]
The issue can still be reproduced if the Marker is set before the Filter

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-17230

**Comment by dnillovna** [comment]
> Olena Ahadzhanian commented in Jira:

Ok on dev, waiting to test on release 1.23.0

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

works in generalbut a bug found on 1.23.0 release:After manually adjusting the legend's position, filtering by formula stops working, e.g.,${Stereo Category} in ["R_ONE", "S_UNKN"].
[file id="e523e0c2-16f1-44f1-ab71-be35fb874289"]

**Comment by ahadzhanian** [comment]
DG 1.23.0

Changing the legend position doesn’t affect the filtering

**Comment by dnillovna** [comment]
> Olena Ahadzhanian commented in Jira:

DG 1.23.0

changing legend position doesn’t affect filtering
