### ISSUE TITLE
#2509: Pinned columns in multiple views for the same table cause performance issues in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2509]
v1.16.*, 1.17.1

**Steps to reproduce:**
1. Open SPGI
2. Pin Id and Structure
3. Open filters
4. Add 10-15 more views with the same table (e.g. clone current view), each having filters and pinned columns
5. Check performance for one of the following:
- Add one more vew
- Add another table viewer to the current view
- Open 'order and hide columns' or similar dialog
- Open column selection dropdown for some viewer

**Expected results:** Pinned columns should not affect performance significantly.
**Actual results:** The most noticeable thing is that any new table (added to the current view or one more view) is rendered much slower compared to the case when there are no pinned columns in the opened views. Column selection dropdowns and dialogs for various viewers are also rendered slowly.

**Comment by ahadzhanian** [comment]
PowerGrid 1.2.5

**Comment by ahadzhanian** [comment]
PowerGrid 1.3.0 DG 1.18.5
Data: SPGI

1. Pin Id and Structure
2.  Clone current view (View > Layout > Clone) - Id and Structure columns are not shown in the clone

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15375

**Comment by ahadzhanian** [comment]
PowerGrid 1.3.0,  DG 1.18.5
