### ISSUE TITLE
Filtering options (contains, exact, included in etc.) are not synchronised for structure filters on different tabs in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2512]
chem 1.8.4

**Steps to reproduce:**
1. Open a table with structures
2. Add another view for the same table or clone current view
3. Open filters and add structure column in both views
4. Add a structure
5. Switch to another view > filter is synchronised
6. Switch structure filter option
E.g. from 'contains' to 'exact', from 'not included in' to 'included in' etc. Issue can be reproduced for almost any combination of options.

**Expected results:** Filter should be re-applied using newly selected option. Structure filtering options should be always synchronised between vidws.
**Actual results:** Filter is not reapplied. Filtering option in the 2nd view is not changed.

**Comment by ahadzhanian** [comment]
Chem 1.8.5

**Comment by ahadzhanian** [comment]
Add filter options synchronization for scaffold tree filter as well.
