### ISSUE TITLE
#2513: Radar: improvements and bugs

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2513]
- [x] Data section:
- **Values**: add a dialog with all/visible/hidden.
- Add the **Row Source** and **Table** properties.
- [ ] Add the ability to inherit a tooltip from the grid or (and) to set the custom tooltip
- [ ] Show the values of min & max for each category as labels on the plot?

Bugs:
 - [x] **Show all rows** cancels the disabling of the **Show values** checkbox
 - [x] **Values**: click on 'X' in the dialog disables the ability to show radar - `not enough data to produce the result`
 - [x] DateTime is displayed in the list of values but can't be added to the chart
 - [ ] Set **Show min percentile** off, **Show max percentile** - on: the color for max is changed on the chart but not the legend
 - [x] **Show only current row** doesn't work
 
New functionality:
- [ ] Add the ability to set Desired Data Range for each axis
- [ ] Form the axis range as a union of Data Range and Desired Data Range
- [ ] Select Desired Data Range as an area (like for the percentiles)
- [ ] Show the current data with a connected line (as is currently implemented for the current row)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14619

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16149
