### ISSUE TITLE
Columns added after performing structure search cannot be shown again if hidden

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2523]
v1.17.3, chem 1.8.5 and older

**Steps to reproduce:**
1. Open SPGI
2. Open filters
3. Filter by structure (contains, similarity etc.)
4. Add new calculated column
5. Open 'Order and hide columns' dialog
6. Hide newly added column by unchecking it
7. Check it again to show

**Expected results:** columns should be shown when checked.
**Actual results:** column is still hidden:
![2023-11-14_18-31-05 (1)](https://github.com/datagrok-ai/public/assets/15780643/e87c7425-52fd-4136-9e53-dd0b232c03e2)

**Comment by ahadzhanian** [comment]
1.17.4
