### ISSUE TITLE
#2525: Chem (1.8.6, 1.8.7):Scaffold  tree highlighting improvements

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2525]
- [x] More specific fragments should be drawn on top - 1.8.7
- [x] Remove the intermediate dialog before the color picker - 1.9.0
- [x] Add a tooltip for the checkbox - Chem 1.8.6
- [x] Add a tooltip for NOT - Chem 1.8.6

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14621

**Comment by ahadzhanian** [comment]
Remove the intermediate dialog before the color picker - implemented in Chem 1.9.0
