### ISSUE TITLE
Row headers are lost after pinning and un-pinning columns in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2528]
1.17.3, 1.16.3, powergrid 1.2.1, 1.1.33

**Steps to reproduce:**
1. Open a table
2. Pin some column
3. Save layout
4. Reapply saved layout
5. Unpin all columns
6. Save layout again
7. Re-apply layout saved on previous step

**Expected results:** Pinning and un-pinning columns should not unexpectedly hide row headers.
**Actual results:** Row header disappears. Column properties still have 'Show row header' checked.

**Comment by ahadzhanian** [comment]
PowerGrid 1.2.5
