### ISSUE TITLE
Pivot table: non-default aggregations are not saved in layout

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2535]
1.17.3

**Steps to reproduce:**
1. Open a table
2. Add PivotTable viewer
3. Configure pivoted table, using non-default aggregations (med, stdev etc.)
4. Save layout
5. Reapply layout

**Expected results:** all properties should be saved, including non-default aggregations.
**Actual results:** non-default aggregations are not saved, resulting also in loss of any table formatting, hidden columns etc.
![2023-11-17_14-11-28 (1)](https://github.com/datagrok-ai/public/assets/15780643/74c72949-c468-4b60-bc08-b47fcfca5559)

Formatting and hidden/shown columns config is also lost in some cases when all aggregations are default, but i couldn't reproduce it on public data yet.

**Comment by ahadzhanian** [comment]
Layout does not save assigned aggregations if they are assigned to the same column.

![Image](https://github.com/datagrok-ai/public/assets/111368431/2ead79e9-b0c8-4f47-8fd9-0d874850bde6)

**Comment by ahadzhanian** [comment]
DG 1.18.0
