### ISSUE TITLE
Incorrect structure filter results if structure is drawn quickly and Marvin editor closed

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2537]
chem 1.8.6

**Steps to reproduce:**
1. Open SPGI
2. Open filters and make sure structure filter is there
3. Switch structure filter to use Marvin for editing
4. Draw benzene ring and quickly replace two atoms with N to get this structure:
<img width="95" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/92933c65-1791-4b6e-90d4-01b689b8e654">

5. Quickly click OK in editor to close it and apply filter

**Expected results:** Results are filtered by the structure drawn.
**Actual results:** if structure is drawn and editor closed quickly enough, filtering results and structure displayed in filters panel are inconsistent:
<img width="1042" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/3a4ddf97-2160-4895-8a2c-6cea41c5e179">

Issue is sporadic and depends on how quickly structure is drawn and how quickly the results get filtered. So it might be easier to reproduce on some larger dataset.

**Comment by katerina-stepanova** [comment]
It can be also reproduced with chem 1.7.2

**Comment by ahadzhanian** [comment]
Marvin> 3.1.24
