### ISSUE TITLE
#2540: Сhem (>1.9.0): add an option to toggle the realignment of molecules by molecular filter

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2540]
For substructure search, add an option to toggle the realignment of molecules in the grid (false by default)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14622

**Comment by ahadzhanian** [comment]
Chem 1.9.0
