### ISSUE TITLE
#2547: Scaffold tree: add an option to switch between two highlighting modes 

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2547]
![image (38)](https://github.com/datagrok-ai/public/assets/111368431/c0b771c9-7bad-426a-9b30-60d4e8111d50)
![image (39)](https://github.com/datagrok-ai/public/assets/111368431/7c79cc32-3eb5-495f-93ec-dab0c60c3c93)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14623

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16152
