### ISSUE TITLE
#2555: Scaffold tree: synchronization of multiple scaffold viewers in a view

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2555]
- [ ] Set common colors for common structures
 - [ ] Synchronization of highlighting between different scaffold three viewers: the last one added has priority (in case of intersection)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14624

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16154
