### ISSUE TITLE
Trellis plot: cog icon for inner viewer config was not removed

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2560]
v1.17.6

**Steps to reproduce:**
1. Open any table
2. Add trellis plot
3. Hover the viewer and check cog icons

**Expected results:** cog icon for inner viewer config should be removed.
**Actual results:** cog icon for inner viewer config is still present. Nothing happens on clicking it now (previously it used to open inner viewer config)

**Comment by ahadzhanian** [comment]
1.17.7
