### ISSUE TITLE
#2568: Autodock plugin - input UI

### ISSUE THREAD

**Issue by GennadiyZakharov** [datagrok-ai/public#2568]
# Background
This ticket covers the development of the input UI for the Autodock plugin. See the full description in the parent ticket: https://github.com/datagrok-ai/public/issues/2492

# Scope of work
In the discussed scenario, the preparation of the macromolecule (molecule file, config) is performed by a separate specialist using desktop tools. The UI covers only the selection of the pre-configured macromolecule and the small molecules to dock.

We need to implement the input UI allowing the user to specify the following:
* Dataframe column containing molecules 
* Drop-down of the pre-generated macromolecules

# Possible UI:
![Autodock-plugin_UI_choices](https://github.com/datagrok-ai/public/assets/5824560/d733179f-1944-4e4a-8c41-9d28ec3c35dd)

```
#name: Autodock
#description: Autodock plugin UI
#language: python
#tags: template, demo
#input: string macromolecule {choices: ['1pbq - all molecule', '1pbq - ligand-binding pocket']} [To add new macromolecule, create the autogrid config and macromolecule pdbqt and place it to Datagrok data folder ]
#input: dataframe data [Dataframe containing small molecules to dock]
#input: column molecules {semType: Molecule} [Small molecules to dock]
#output: dataframe poses [Docked ligands]
```

# How to create GPF and pdbqt for macromolecule
* The complete tutorial: https://www.chem.uwec.edu/chem491_w01/Chem491-Molecules%20and%20Medicine%202008/AutoDock%20Tutorial.pdf
* Short video: https://drive.google.com/file/d/1DI6TAtNYSwJTTC_h2YB_bLi3eSm8WblX/view?usp=drive_link

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14893

**Comment by GennadiyZakharov** [comment]
Tested - works as expected.
