### ISSUE TITLE
Viewers: legend does not show all categories after filtering in specific cases

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2570]
1.17.8
data: 
[PubChemReduced (1).csv](https://github.com/datagrok-ai/public/files/13613362/PubChemReduced.1.csv)

1. Open a table
2. Add a line chart (bar chart, scatterplot, pie chart, trellis plot)
3. Configure line chart splitting so that legend is shown (i.e. not too many categories)
4. Open filters panel
5. Apply some filtering, so that number of categories in legend is reduced
6. Select one or several categories in line chart's legend
7. Reset filtering

**Expected results:** All categories are shown on the line chart when filtering is reset.
**Actual results:** Only categories that were selected are shown after resetting filtering. Resetting line chart view does not bring back hidden categories. An error occurs
![2023-12-08_12-09-14 (1)](https://github.com/datagrok-ai/public/assets/111368431/20b39aa5-6626-4346-9945-44bd92f13b5a)
```
html_dart2js.dart:3558 2023-12-08 13:25:50.928 NullError: method not found: 'setAllValues$1' on null
	login.dart.js_1.part.js?72350 43913:29   dart.GridFilterBase_onFrameAttached_closure4.call$1
	login.dart.js?72350 8690:18              dart._rootRunUnary
	login.dart.js?72350 12518:41             _CustomZone.runUnary$2
	login.dart.js?72350 12437:21             _CustomZone.runUnaryGuarded$2
	login.dart.js?72350 11381:20             _ForwardingStreamSubscription._sendData$1
	login.dart.js?72350 11331:16             dart._BufferingStreamSubscription._async$_add$1
	login.dart.js?72350 11993:14             _ForwardingStreamSubscription._async$_add$1
	login.dart.js?72350 12068:16             _WhereStream._handleData$2
	login.dart.js?72350 12021:22             dart._ForwardingStreamSubscription._handleData$1
	login.dart.js?72350 5710:14              BoundClosure.eval
	login.dart.js?72350 8690:18              dart._rootRunUnary
	login.dart.js?72350 12518:41             _CustomZone.runUnary$2
	login.dart.js?72350 12437:21             _CustomZone.runUnaryGuarded$2
	login.dart.js?72350 11381:20             _BroadcastSubscription._sendData$1
	login.dart.js?72350 11331:16             dart._BufferingStreamSubscription._async$_add$1
	login.dart.js?72350 9203:22              _SyncBroadcastStreamController__sendData_closure.call$1
	login.dart.js?72350 9142:20              _SyncBroadcastStreamController._forEachListener$1
	login.dart.js?72350 9185:14              _SyncBroadcastStreamController._sendData$1
	login.dart.js?72350 9066:14              dart._BroadcastStreamController.add$1
	login.dart.js?72350 41896:42             J.add$1$ax
	login.dart.js_1.part.js?72350 141358:11  EventBus.fire$3
	login.dart.js_1.part.js?72350 141362:21  EventBus.fire$2
	login.dart.js_1.part.js?72350 8207:41    Object.AppEvents_fire
	login.dart.js_1.part.js?72350 42633:11   FiltersCore__initHeader_closure4.call$0
	login.dart.js_1.part.js?72350 115128:29  icon_closure.call$1
	login.dart.js_1.part.js?72350 98815:29   Icons__bindIcon_closure.call$1
	login.dart.js?72350 29281:28             dart._EventStreamSubscription_closure.call$1
	login.dart.js?72350 8694:16              dart._rootRunUnary
	login.dart.js?72350 12518:41             _CustomZone.runUnary$2
	login.dart.js?72350 12437:21             _CustomZone.runUnaryGuarded$2
	login.dart.js?72350 12601:27             dart._CustomZone_bindUnaryCallback_closure.call$1
	login.dart.js?72350 6926:29              invokeClosure_closure0.call$0
	login.dart.js?72350 4274:25              _IsolateContext.eval$1
	login.dart.js?72350 3852:28              Object._callInIsolate
	login.dart.js?72350 5539:20              dart.invokeClosure
	login.dart.js?72350 5558:18              HTMLElement.<fn>
```

**Comment by katerina-stepanova** [comment]
Another possibly related case:

1. Open a table
2. Add a plot with legend
3. Select several categories in legend (using ctrl-click)
4. Apply some filter, so that data for some of the selected categories is no longer shown

**Expected results:** categories with no data shown should not be shown in the legend.
**Actual results:** all selected categories are still shown in the legend:
<img width="747" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/f3776598-ea36-46c5-bdbc-a1c2d7891709">

**Comment by dionissqq** [comment]
Regarding last case, for now we do not change or hide legend items if we have filtering in it, though yes, we can change it for inViewerFilter to show only the ones that are present in global filter.
Also, i propose to get rid of the case with global filtering in legend(its rarely useful and will stay in way of implemented the legend this new way. Supporting several cases of synchronizing legend and global filters is really not something we want)

**Comment by ahadzhanian** [comment]
Filtering on the legend should only filter the viewer

**Comment by ahadzhanian** [comment]
Case 1: All categories are shown on the line chart when filtering is reset but the error remains

**Comment by ahadzhanian** [comment]
1.18.0
