### ISSUE TITLE
#2573: #2573: RFC: Universal way of performing dimensionality reduction on multiple columns

### ISSUE THREAD

**Issue by drizhina** [datagrok-ai/public#2573]
Purpose:

* To have a unified method for dimensionality reduction that will support multiple columns and would be easily extended with supported column types from different packages.

Problem:

* Datagrok currently can perform dimensionality reduction on biological sequences, molecules or numbers separately. Each of these methods are separately placed in corresponding packages, and there is a lot of code duplication. 
* There is an increased interest in being able to process different columns and produce their embeddings in 2d space. In current realization of code, one would need to duplicate similar code sequence/chem space in order to add support for particular column. 
* We cannot currently do dimensionality reduction for an arbitrary set of columns, including string types (for instance AGE / HEIGHT / SEX)
* We don't have "find similar" functionality based on the arbitrary set of columns. This might be useful as a context panel.

Proposed Solution:

* Create a unified function for performing dimensionality reduction, that would dynamically know which columns are supported and what preprocessing/distance functions they support. these preprocessing functions would be picked up from any installed package, and then called on column before calculating embeddings. For example, when performing sequence space, first step is encoding of sequences and constructing monomer substitution matrix. In proposed solution, in order to add support for macromolecule columns, only thing needed is to expose a preprocessing function in bio that encodes sequences. For aggregating different columns, ui will include items grid editor which will allow to add multiple columns, including its preprocessing function, distance function and weight used for distance aggregation. 

Benefits:

* Much less code, less needed to test and maintain. 
* Easier way of adding new supported function, easier way of extending.
* Support for multiple columns together

![image](https://github.com/datagrok-ai/public/assets/943403/6d9ee9c6-5f06-4e21-8522-b37b32c07f27)

**Comment by skalkin** [comment]
I love the idea.

What's missing in the picture is the way the individual distances would be aggregated (Euclidean / Manhattan).

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14894

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16155

**Comment by drizhina** [comment]
The features described above and more have been implemented. please check out the[ community link](https://community.datagrok.ai/t/dimensionality-reduction/832/3) for more info.
