### ISSUE TITLE
Line chart with splitting: wrong values in custom aggregated tooltip if not all data is shown in the plot

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2575]
1.17.8

**Preconditions:**
1. Open SPGI
2. Add a line chart
3. Select 'Chemist521' column for X axis
4. Select some numerical column for Y axis
5. Split by 'Primary series name'
6. Configure custom aggregated tooltip: 'Primary series name'/'value or unique count'

**Case 1: selecting categories**
1. Select any category in legend except 1st one or last one
2. Hover some dot
**Expected results:** values in the tooltip should match hovered dot.
**Actual results:** values in the tooltip do not match hovered dot:
<img width="568" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/41ed3ea0-2b4f-4930-bb3f-b6c3af27da1f">

**Case 2: filtering**
1. Open filters
2. Filter data using any filter, so that not all categories are shown on the plot
4. Hover some dot
**Expected results:** values in the tooltip should match hovered dot.
**Actual results:** values in the tooltip should match hovered dot.
<img width="1066" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/b45f27e3-e392-4929-9702-8bc825a33347">

**Comment by ahadzhanian** [comment]
1.18.0
