### ISSUE TITLE
Line chart: colours in the legend do not match colour in the plot in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2577]
1.17.8

**Steps to reproduce:**
1. Open SPGI
2. Add a line chart
3. Split by 'Primary series name'

**Expected results:** colours in the legend should match colour in the plot.
**Actual results:** 'no value' is red in the legend, but grey in the plot:
<img width="540" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/1dfa3604-eb4e-45b6-a78d-b681d7cc35fa">

**Comment by ahadzhanian** [comment]
Split= Primary series names, Series
Different categories have the same color 

![Image](https://github.com/datagrok-ai/public/assets/111368431/556a4aef-f316-4422-9bdd-eaa7b9f4fa1c)

**Comment by ahadzhanian** [comment]
When you hover over a category in the legend turn other categories' markers color down

**Comment by ahadzhanian** [comment]
Fix coloring: remove empty categories and then assign the colors

**Comment by ahadzhanian** [comment]
1.18.0
