### ISSUE TITLE
#2578: Queries and Projects: Implement the ability to add tags

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2578]
Plan for 1.19

**Comment by tcarolan** [comment]
This will help organize Projects. Great idea.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14895

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16156

**Comment by LesiaPavlenko** [comment]
works for projects
