### ISSUE TITLE
#2590: Calculated columns dialog: not all functions are available in list, search is not working as expected

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2590]
v 1.17.8

**Steps to reproduce:**
1. Open a table
2. Click 'Add new column' button
3. Scroll through the functions list
**Expected results:** all available functions should be in the list.
**Issue 1:** If, Eq, NotEq are not present in the list
4. Search functions list for 'is' > search results are correct
5. Continue typing, so that 'isn' or 'ise' is searched
**Expected results:** IsNotEmpty or IsEmpty should appear in search results.
**Issue 2:** nothing is found, IsNotEmpty or IsEmpty is not shown:
<img width="235" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/87fccf13-207a-4907-a928-f90e1468d45e">

**Comment by ahadzhanian** [comment]
DG 1.18.0
