### ISSUE TITLE
#2604: Core | Grid: Row tags

### ISSUE THREAD

**Issue by LaykDimon** [datagrok-ai/public#2604]
Implement row tags that will provide capability to tag rows, save the tags to the database and work with it

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14897

**Comment by KiK0S** [comment]
Sticky meta can be used for it https://datagrok.ai/help/govern/catalog/sticky-meta
