### ISSUE TITLE
Pivot table: colours, formatting, shown/hidden columns are reset on filtering

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2606]
v 1.17.10

**Steps to reproduce:**
1. Open a table
2. Add and configure pivot table viewer
3. Apply colouring and format for some columns, hide some columns
4. Do one of the following:
If row source = filtered >>> Filter the main table
If row source = selected >>> Select/deselect some rows.
Or change row source.

**Expected results:** formatting, colours, shown/hidden columns should not be reset.
**Actual results:** formatting, colours, shown/hidden columns are reset for pivot table.

Issue happened once for row source = all for pivot table, but i could not reproduce it anymore.

**Comment by ahadzhanian** [comment]
1.18.0
