### ISSUE TITLE
#2608: Line chart with row source = selected: all rows are deselected on clicking line in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2608]
v.1.17.8, 1.17.10

Steps to reproduce: 
1. Open a table
2. Add a line chart: row source = selected, split on 1 or more columns
3. Select some rows (but not all), so that some lines on line chart are shown: use another viewer for selection, or select directly in the grid
4. Click one of the lines on the line chart

**Expected results:** the line user clicked is shown in the line chart, rows matching this line are selected in the dataframe.
**Actual results:** All rows are de-selected, line chart is empty.
![2023-12-22_18-05-48 (1)](https://github.com/datagrok-ai/public/assets/15780643/b080390d-14fa-49ea-ae0b-b7ad58ded189)
Issue can be reproduced only if not all rows were selected initially.

**Comment by ahadzhanian** [comment]
Consider the following:
- [ ] Put the selected line’s rows in the context panel without deselection of the other lines’ rows (Selected, Selected or current, Filtered Selected)
- [ ] Hide the Delete rows action from the context panel

**Comment by ahadzhanian** [comment]
- Line chart, bar chart, pie chart: put the selected line’s (bar's/section's) rows in the context panel without deselection of the other lines’ (bars', sections') rows (Selected, Selected or current, Filtered Selected)

- Hide the Delete rows action from the Context Panel #2635 

DG 1.18.0

**Comment by ahadzhanian** [comment]
Doesn't work for the bar chart when Row source = SelectedOrCurrent
![2608](https://github.com/datagrok-ai/public/assets/111368431/216954ae-f54c-4c39-97f6-63949a70ac6a)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15071

**Comment by ahadzhanian** [comment]
1.18.0
