### ISSUE TITLE
Scaffold tree: structure part containing H atom is replaced with '?' in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2612]
v1.17.10, chem 1.8.7

**Steps to reproduce:**
1. Open a table containing molecules column (e.g. SPGI)
2. Add a scaffold tree standalone viewer OR add scaffold tree as a filter to filters panel
3. Open editor and draw a structure with H atom added explicitly
4. Add it as a scaffold

**Expected results:** structure is displayed in scaffold tree viewer/filter as drawn in the editor.
**Actual results:** part with H atom is replaced with '?':
<img width="877" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/6b0f8a8e-aa1a-4173-bcf8-87d3e2768748">

**Comment by ahadzhanian** [comment]
Chem 1.8.9
