### ISSUE TITLE
#2625: Charts: Tree Visualization: Color Agg fails on null values

### ISSUE THREAD

**Issue by tcarolan** [datagrok-ai/public#2625]
The Tree does draw sometimes. But it is challenging to get the tree to redraw when properties are changed. Maybe this is due to the Javascript errors output in the console. Below are several stacktraces (different errors) and a screenshot. I'm happy to assist to further diagnose the issue. 

![image](https://github.com/datagrok-ai/public/assets/6126004/b118bf6b-a2d3-4990-8b9f-a945c15c88b6)

html_dart2js.dart:3558 NullError: method not found: 'toString' on null
	packages/d4/src/color.dart 452:9                                                    Color.scaleColor
	packages/xamgle/src/interop/grok_api.dart 1662:90                                   _initJsApi.<anonymous function>
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1539:16                   Primitives.applyFunctionWithPositionalArguments
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1489:11                   Primitives.applyFunction
	packages/$sdk/lib/js/dart2js/js_dart2js.dart 667:13                                 _convertDartFunctionFast
	webpack://datagrok-api/src/widgets.ts 1376:16                                       Color.scaleColor
	webpack://charts/src/viewers/tree/tree-viewer.ts 132:49                             scaleColor
	webpack://charts/src/viewers/tree/tree-viewer.ts 136:42                             setItemStyle
	webpack://charts/src/viewers/tree/tree-viewer.ts 136:23                             forEach
	webpack://charts/src/viewers/tree/tree-viewer.ts 138:5                              setItemStyle
	webpack://charts/src/viewers/tree/tree-viewer.ts 167:12                             colorCodeTree
	webpack://charts/src/viewers/tree/tree-viewer.ts 107:12                             render
	webpack://datagrok-api/src/widgets.ts 274:11                                        p.set
	packages/xamgle/src/property_grid/prop_grid.dart 108:39                             buildPropertyModel.<anonymous function>
	packages/xamgle/src/property_grid/prop_grid.dart 78:16                              buildPropertyModel.reg.<anonymous function>
	packages/xamgle/src/property_grid/editors/property_view_column_selector.dart 21:20  PropertyViewColumnSelector.<anonymous function>
	packages/$sdk/lib/async/zone.dart 1128:37                                           _rootRunUnary
	packages/$sdk/lib/async/zone.dart 1012:12                                           _CustomZone.runUnary
	packages/$sdk/lib/async/zone.dart 909:14                                            _CustomZone.runUnaryGuarded
	packages/$sdk/lib/async/stream_impl.dart 330:5                                      _BufferingStreamSubscription._sendData
	packages/$sdk/lib/async/stream_impl.dart 257:7                                      _BufferingStreamSubscription._add
	packages/$sdk/lib/async/broadcast_stream_controller.dart 387:7                      _SyncBroadcastStreamController._sendData.<anonymous function>
	packages/$sdk/lib/async/broadcast_stream_controller.dart 328:9                      _BroadcastStreamController._forEachListener
	packages/$sdk/lib/async/broadcast_stream_controller.dart 386:5                      _SyncBroadcastStreamController._sendData
	packages/$sdk/lib/async/broadcast_stream_controller.dart 254:5                      _BroadcastStreamController.add
	packages/ddt/src/events/event_bus.dart 72:7                                         EventBus.fire
	packages/d4/src/common/column_combo_box.dart 71:9                                   ColumnComboBox.setColumn
	packages/d4/src/common/column_combo_box.dart 57:36                                  ColumnComboBox.column
	packages/$sdk/lib/async/zone.dart 1116:37                                           _rootRun
	packages/$sdk/lib/async/zone.dart 1001:12                                           _CustomZone.run
	packages/$sdk/lib/async/zone.dart 901:14                                            _CustomZone.runGuarded
	packages/$sdk/lib/async/zone.dart 926:20                                            _CustomZone.bindCallback.<anonymous function>
	packages/$sdk/lib/async/zone.dart 1120:12                                           _rootRun
	packages/$sdk/lib/async/zone.dart 1001:12                                           _CustomZone.run
	packages/$sdk/lib/async/zone.dart 901:14                                            _CustomZone.runGuarded
	packages/$sdk/lib/async/zone.dart 926:20                                            _CustomZone.bindCallback.<anonymous function>
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 1393:9               TimerImpl.internalCallback
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2454:48                   invokeClosure.<anonymous function>
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 474:16               _IsolateContext.eval
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 59:16                _callInIsolate
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2454:14                   invokeClosure
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2476:14                   convertDartClosureToJS

NullError: method not found: 'gPx' on null
	packages/ddt/src/data_frame/tools/pivot.dart 73:46                                  _pivot.addColumn
	packages/ddt/src/data_frame/tools/pivot.dart 87:7                                   _pivot
	packages/ddt/src/data_frame/tools/aggregate.dart 247:7                              GroupByBuilder.aggregate
	packages/xamgle/src/interop/grok_api.dart 741:57                                    _initJsApi.<anonymous function>
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1516:16                   Primitives.applyFunctionWithPositionalArguments
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1489:11                   Primitives.applyFunction
	packages/$sdk/lib/js/dart2js/js_dart2js.dart 667:13                                 _convertDartFunctionFast
	webpack://datagrok-api/src/dataframe.ts 1884:30                                     GroupByBuilder.aggregate
	webpack://charts/src/utils/tree-utils.ts 30:32                                      aggregate
	webpack://charts/src/viewers/tree/tree-viewer.ts 153:23                             toTree
	webpack://charts/src/viewers/tree/tree-viewer.ts 160:39                             getSeriesData
	webpack://charts/src/viewers/tree/tree-viewer.ts 107:12                             render
	webpack://datagrok-api/src/widgets.ts 274:11                                        p.set
	packages/xamgle/src/property_grid/prop_grid.dart 108:39                             buildPropertyModel.<anonymous function>
	packages/xamgle/src/property_grid/prop_grid.dart 78:16                              buildPropertyModel.reg.<anonymous function>
	packages/xamgle/src/property_grid/editors/property_view_column_selector.dart 21:20  PropertyViewColumnSelector.<anonymous function>
	packages/$sdk/lib/async/zone.dart 1128:37                                           _rootRunUnary
	packages/$sdk/lib/async/zone.dart 1012:12                                           _CustomZone.runUnary
	packages/$sdk/lib/async/zone.dart 909:14                                            _CustomZone.runUnaryGuarded
	packages/$sdk/lib/async/stream_impl.dart 330:5                                      _BufferingStreamSubscription._sendData
	packages/$sdk/lib/async/stream_impl.dart 257:7                                      _BufferingStreamSubscription._add
	packages/$sdk/lib/async/broadcast_stream_controller.dart 387:7                      _SyncBroadcastStreamController._sendData.<anonymous function>
	packages/$sdk/lib/async/broadcast_stream_controller.dart 328:9                      _BroadcastStreamController._forEachListener
	packages/$sdk/lib/async/broadcast_stream_controller.dart 386:5                      _SyncBroadcastStreamController._sendData
	packages/$sdk/lib/async/broadcast_stream_controller.dart 254:5                      _BroadcastStreamController.add
	packages/ddt/src/events/event_bus.dart 72:7                                         EventBus.fire
	packages/d4/src/common/column_combo_box.dart 71:9                                   ColumnComboBox.setColumn
	packages/d4/src/common/column_combo_box.dart 57:36                                  ColumnComboBox.column
	packages/$sdk/lib/async/zone.dart 1116:37                                           _rootRun
	packages/$sdk/lib/async/zone.dart 1001:12                                           _CustomZone.run
	packages/$sdk/lib/async/zone.dart 901:14                                            _CustomZone.runGuarded
	packages/$sdk/lib/async/zone.dart 926:20                                            _CustomZone.bindCallback.<anonymous function>
	packages/$sdk/lib/async/zone.dart 1120:12                                           _rootRun
	packages/$sdk/lib/async/zone.dart 1001:12                                           _CustomZone.run
	packages/$sdk/lib/async/zone.dart 901:14                                            _CustomZone.runGuarded
	packages/$sdk/lib/async/zone.dart 926:20                                            _CustomZone.bindCallback.<anonymous function>
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 1393:9               TimerImpl.internalCallback
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2454:48                   invokeClosure.<anonymous function>
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 474:16               _IsolateContext.eval
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 59:16                _callInIsolate
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2454:14                   invokeClosure
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2476:14                   convertDartClosureToJS
	
auE @ html_dart2js.dart:3558
bY @ log.dart:171
dart.EZ.ar3 @ log.dart:131
dart.EZ.ar3 @ login.dart.js_1.part.js?19054:104543
(anonymous) @ login.dart:186
(anonymous) @ async_patch.dart:213
dart.egS.$2 @ async_patch.dart:237
dart.dA9.$1 @ async_patch.dart:187
Bt @ zone.dart:1371
$0 @ future_impl.dart:129
yA @ future_impl.dart:665
dart.dsX.$0 @ future_impl.dart:343
edV @ schedule_microtask.dart:41
dart.hq7 @ schedule_microtask.dart:50
dart.dom.$1 @ async_patch.dart:51
$0 @ js_helper.dart:2456
Nk @ isolate_helper.dart:474
GZ @ isolate_helper.dart:59
dart.h3m @ js_helper.dart:2456
(anonymous) @ js_helper.dart:2476
childList (async)
$1 @ async_patch.dart:67
b2h @ async_patch.dart:28
dart.a54 @ zone.dart:1176
zo @ zone.dart:1391
V2 @ future_impl.dart:342
aaO @ future_impl.dart:251
a4p @ async_patch.dart:206
n @ async_patch.dart:142
dart.h44.$2 @ login.dart:186
dart.b2b @ zone.dart:1144
a59 @ zone.dart:1377
dart.h9Q.$5 @ zone.dart:1443
wl @ zone.dart:981
IL @ zone.dart:911
aC @ stream_impl.dart:330
dart.oG.lt @ stream_impl.dart:257
$1 @ broadcast_stream_controller.dart:387
a9l @ broadcast_stream_controller.dart:328
aC @ broadcast_stream_controller.dart:386
dart.yy.t @ broadcast_stream_controller.dart:254
J.a9 @ login.dart.js?19054:18272
a5 @ event_bus.dart:72
K5 @ column_combo_box.dart:71
hW @ login.dart.js_1.part.js?19054:16368
dart.bqg.$0 @ column_combo_box.dart:57
dart.b2a @ zone.dart:1116
dart.dpB.fL @ zone.dart:1001
IK @ zone.dart:901
dart.dpC.$0 @ zone.dart:926
dart.b2a @ zone.dart:1120
dart.dpB.fL @ zone.dart:1001
IK @ zone.dart:901
dart.dpC.$0 @ zone.dart:926
dart.da_.$0 @ isolate_helper.dart:1393
$0 @ js_helper.dart:2454
Nk @ isolate_helper.dart:474
GZ @ isolate_helper.dart:59
dart.h3m @ js_helper.dart:2454
(anonymous) @ js_helper.dart:2476
setTimeout (async)
aHK @ isolate_helper.dart:1398
d9W @ isolate_helper.dart:1369
a2s @ async_patch.dart:121
dart.hpV @ zone.dart:1184
Dr @ zone.dart:1084
c_ @ timer.dart:51
dart.bqh.$1 @ column_combo_box.dart:367
dart.b2c @ zone.dart:1128
Bt @ zone.dart:1012
IL @ zone.dart:909
aC @ stream_impl.dart:330
dart.oG.lt @ stream_impl.dart:257
$1 @ broadcast_stream_controller.dart:387
a9l @ broadcast_stream_controller.dart:328
aC @ broadcast_stream_controller.dart:386
dart.yy.t @ broadcast_stream_controller.dart:254
J.a9 @ login.dart.js?19054:18272
a5 @ event_bus.dart:72
bC @ login.dart.js_1.part.js?19054:72509
sp5 @ data_frame.dart:117
dart.eG.ald @ data_frame_viewer.dart:123
eval @ VM656:3
dart.b2c @ zone.dart:1128
Bt @ zone.dart:1012
IL @ zone.dart:909
aC @ stream_impl.dart:330
dart.oG.lt @ stream_impl.dart:257
lt @ stream_pipe.dart:132
CK @ stream_pipe.dart:207
dart.Pl.aKW @ stream_pipe.dart:164
eval @ VM515:3
dart.drW.$1 @ html_dart2js.dart:42920
dart.b2c @ zone.dart:1132
Bt @ zone.dart:1012
IL @ zone.dart:909
dart.dpE.$1 @ zone.dart:936
$0 @ js_helper.dart:2456
Nk @ isolate_helper.dart:474
GZ @ isolate_helper.dart:59
dart.h3m @ js_helper.dart:2456
(anonymous) @ js_helper.dart:2476
html_dart2js.dart:3558 NullError: method not found: 'gPx' on null
	packages/ddt/src/data_frame/tools/pivot.dart 73:46                     _pivot.addColumn
	packages/ddt/src/data_frame/tools/pivot.dart 87:7                      _pivot
	packages/ddt/src/data_frame/tools/aggregate.dart 247:7                 GroupByBuilder.aggregate
	packages/xamgle/src/interop/grok_api.dart 741:57                       _initJsApi.<anonymous function>
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1516:16      Primitives.applyFunctionWithPositionalArguments
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1489:11      Primitives.applyFunction
	packages/$sdk/lib/js/dart2js/js_dart2js.dart 667:13                    _convertDartFunctionFast
	webpack://datagrok-api/src/dataframe.ts 1884:30                        GroupByBuilder.aggregate
	webpack://charts/src/utils/tree-utils.ts 30:32                         aggregate
	webpack://charts/src/viewers/tree/tree-viewer.ts 153:23                toTree
	webpack://charts/src/viewers/tree/tree-viewer.ts 160:39                getSeriesData
	webpack://charts/src/viewers/tree/tree-viewer.ts 107:12                render
	webpack://datagrok-api/src/widgets.ts 274:11                           p.set
	packages/xamgle/src/property_grid/prop_grid.dart 113:22                buildPropertyModel.<anonymous function>
	packages/xamgle/src/property_grid/prop_grid.dart 78:16                 buildPropertyModel.reg.<anonymous function>
	packages/property_grid/property_item_controller.dart 109:5             PropertyItemController.finishEditing
	packages/property_grid/editors/editor_spinner.dart 65:7                PropertyEditorSpinner._notifyFinishEditing
	packages/$sdk/lib/html/dart2js/html_dart2js.dart 42920:48              _EventStreamSubscription.<anonymous function>
	packages/$sdk/lib/async/zone.dart 1132:12                              _rootRunUnary
	packages/$sdk/lib/async/zone.dart 1012:12                              _CustomZone.runUnary
	packages/$sdk/lib/async/zone.dart 909:14                               _CustomZone.runUnaryGuarded
	packages/$sdk/lib/async/zone.dart 936:23                               _CustomZone.bindUnaryCallback.<anonymous function>
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:48      invokeClosure.<anonymous function>
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 474:16  _IsolateContext.eval
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 59:16   _callInIsolate
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:14      invokeClosure
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2476:14      convertDartClosureToJS
	
auE @ html_dart2js.dart:3558
bY @ log.dart:171
dart.EZ.ar3 @ log.dart:131
dart.EZ.ar3 @ login.dart.js_1.part.js?19054:104543
(anonymous) @ login.dart:186
(anonymous) @ async_patch.dart:213
dart.egS.$2 @ async_patch.dart:237
dart.dA9.$1 @ async_patch.dart:187
Bt @ zone.dart:1371
$0 @ future_impl.dart:129
yA @ future_impl.dart:665
dart.dsX.$0 @ future_impl.dart:343
edV @ schedule_microtask.dart:41
dart.hq7 @ schedule_microtask.dart:50
dart.dom.$1 @ async_patch.dart:51
$0 @ js_helper.dart:2456
Nk @ isolate_helper.dart:474
GZ @ isolate_helper.dart:59
dart.h3m @ js_helper.dart:2456
(anonymous) @ js_helper.dart:2476
childList (async)
$1 @ async_patch.dart:67
b2h @ async_patch.dart:28
dart.a54 @ zone.dart:1176
zo @ zone.dart:1391
V2 @ future_impl.dart:342
aaO @ future_impl.dart:251
a4p @ async_patch.dart:206
n @ async_patch.dart:142
dart.h44.$2 @ login.dart:186
a59 @ zone.dart:1376
dart.h9Q.$5 @ zone.dart:1443
wl @ zone.dart:981
IL @ zone.dart:911
dart.dpE.$1 @ zone.dart:936
$0 @ js_helper.dart:2456
Nk @ isolate_helper.dart:474
GZ @ isolate_helper.dart:59
dart.h3m @ js_helper.dart:2456
(anonymous) @ js_helper.dart:2476

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14899

**Comment by dnillovna** [comment]
> Olena Ahadzhanian commented in Jira:

A new error appears on some combinations of Size/Color and their aggregation functions:

data: demog

set Color Agr Type to stdev and try to set Color to STARTED
[file id="e1806efc-19e3-4b2b-b091-af745716d128"]



```
logger.ts:94 NullError: method not found: 'gQR' on null
	packages/ddt/src/data_frame/tools/pivot.dart 73:46                     _pivot.addColumn
	packages/ddt/src/data_frame/tools/pivot.dart 87:7                      _pivot
	packages/ddt/src/data_frame/tools/aggregate.dart 247:7                 GroupByBuilder.aggregate
	packages/xamgle/src/interop/grok_api.dart 678:57                       _initJsApi.<anonymous function>
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1516:16      Primitives.applyFunctionWithPositionalArguments
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1489:11      Primitives.applyFunction
	packages/$sdk/lib/js/dart2js/js_dart2js.dart 667:13                    _convertDartFunctionFast
	webpack://datagrok-api/src/dataframe.ts 1906:30                        GroupByBuilder.aggregate
	webpack://charts/src/utils/tree-utils.ts 30:32                         TreeUtils.toTree
	webpack://charts/src/viewers/tree/tree-viewer.ts 198:23                TreeViewer.getSeriesData
	webpack://charts/src/viewers/tree/tree-viewer.ts 205:39                TreeViewer.render
	webpack://charts/src/viewers/tree/tree-viewer.ts 143:12                TreeViewer.onPropertyChanged
	webpack://datagrok-api/src/widgets.ts 285:11                           p.set
	packages/d4/src/js_viewer_host/js_viewer_host_core.dart 58:9           JsViewerHostCore.setJsViewer.<anonymous function>
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1521:16      Primitives.applyFunctionWithPositionalArguments
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1489:11      Primitives.applyFunction
	packages/$sdk/lib/js/dart2js/js_dart2js.dart 667:13                    _convertDartFunctionFast
	packages/xamgle/src/property_grid/prop_grid.dart 113:22                buildPropertyModel.<anonymous function>
	packages/xamgle/src/property_grid/prop_grid.dart 78:16                 buildPropertyModel.reg.<anonymous function>
	packages/property_grid/property_item_controller.dart 91:5              PropertyItemController.requestValueChange
	packages/property_grid/editors/editor_spinner.dart 33:7                PropertyEditorSpinner.<anonymous function>
	packages/$sdk/lib/html/dart2js/html_dart2js.dart 42920:48              _EventStreamSubscription.<anonymous function>
	packages/$sdk/lib/async/zone.dart 1132:12                              _rootRunUnary
	packages/$sdk/lib/async/zone.dart 1012:12                              _CustomZone.runUnary
	packages/$sdk/lib/async/zone.dart 909:14                               _CustomZone.runUnaryGuarded
	packages/$sdk/lib/async/zone.dart 936:23                               _CustomZone.bindUnaryCallback.<anonymous function>
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:48      invokeClosure.<anonymous function>
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 474:16  _IsolateContext.eval
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 59:16   _callInIsolate
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:14      invokeClosure
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2476:14      convertDartClosureToJS
```
