### ISSUE TITLE
Structure filter filters out all molecules in the presence of filter-by-zoom scatterplot and multiple views

### ISSUE THREAD

**Issue by ptosco** [datagrok-ai/public#2629]
This could have the same underlying root cause as #2628.

1. Open `SPGI.csv`
2. Open filter tab
3. Add a scatterplot
4. From the menu, choose View->Layout->Clone
6. In the Structure filter, draw a benzene ring -> filtering works as expected - click Cancel
7. Repeat step (6): all compounds now disappear

Note that the problem only happens when
1. There are multiple views
2. The structure filter is used in combination with a scatterplot configured with "filter by zoom"

![2024-01-12_15-04-42](https://github.com/datagrok-ai/public/assets/5244385/710f2cfd-ca8f-493f-a4c5-d7d31addb47c)

**Comment by ahadzhanian** [comment]
Chem 1.9.0

**Comment by ahadzhanian** [comment]
1.9.0
