### ISSUE TITLE
#2634: Synchronization between Bar chart and Line chart

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2634]
Add dynamic highlighting for bars and lines in case of one-to-one correspondence
#2608

**Comment by ahadzhanian** [comment]
1.18.0

**Comment by ahadzhanian** [comment]
Add highlighting for bar chart subsets

**Comment by dnillovna** [comment]
> Olena Ahadzhanian commented in Jira:

https://github.com/datagrok-ai/public/issues/2696
