### ISSUE TITLE
#2635: Customization of actions on the Context Panel

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2635]
![Image](https://github.com/datagrok-ai/public/assets/111368431/ac16a236-f209-42f0-943e-2172185fae97)

**Comment by ahadzhanian** [comment]
1. Apply Hide to the Save as Column action
2. Go to the Settings - General > Hidden context actions and delete its content
3.  Go back to the grid and select some rows
4. The action is back on the Context Panel
5. Try to apply Hide to Save as Column one more time  - an error occurs, and no actions are mentioned in  Settings - General > Hidden context actions



![Image](https://github.com/datagrok-ai/public/assets/111368431/29b6b7fe-b68d-4ce6-9d75-5a54c10c9acb)


 ```
logging.dart:163 2024-01-23 15:07:40.870 NullError: method not found: 'add$1' on null
	login.dart.js?22149 42009:41             J.add$1$ax
	login.dart.js_1.part.js?22149 40656:11   EntityMeta_renderActionsList___closure.call$0
	login.dart.js_1.part.js?22149 8242:16    Object.AppEvents_contextRun
	login.dart.js_1.part.js?22149 105670:13  MenuItem.click$1
	login.dart.js_1.part.js?22149 105860:27  MenuItem__init_closure.call$1
	login.dart.js?22149 29333:28             dart._EventStreamSubscription_closure.call$1
	login.dart.js?22149 8712:16              dart._rootRunUnary
	login.dart.js?22149 12530:41             _CustomZone.runUnary$2
	login.dart.js?22149 12449:21             _CustomZone.runUnaryGuarded$2
	login.dart.js?22149 12613:27             dart._CustomZone_bindUnaryCallback_closure.call$1
	login.dart.js?22149 6944:29              invokeClosure_closure0.call$0
	login.dart.js?22149 4292:25              _IsolateContext.eval$1
	login.dart.js?22149 3870:28              Object._callInIsolate
	login.dart.js?22149 5557:20              dart.invokeClosure
	login.dart.js?22149 5576:18              HTMLDivElement.<fn>
```

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14627

**Comment by ahadzhanian** [comment]
DG 1.18.0

**Comment by dnillovna** [comment]
> Andrew Skalkin commented in Jira:

Looks like I fixed it a while ago

**Comment by dnillovna** [comment]
> Olena Ahadzhanian commented in Jira:

Closed the issue in Github. It looks like it missed the sync.
