### ISSUE TITLE
Structure in filter is unexpectedly changed when there are two views in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2639]
1.17.8, 1.17.11
chem 1.8.7, 1.8.10

**Steps to reproduce:**
1. Open SPGI
2. Add the 2nd view
3. Open filters in the 2nd view
4. Draw some structure in structure filter >>> table is filtered
5. Go to the 1st view >>> table is filtered
6. Open filters panel >>> structure filter is the same as in the 2nd view
7. Close filters panel
8. Return to the 2nd view and change structure in filters
9. Go to the 1st view and open filters panel again

**Expected results:** filtering does not change. Structure in filters panel is the same as in the 2nd view.
**Actual results:** filtering is changed, structure is reset to one set on step 4.
![2024-01-23_14-16-57 (1)](https://github.com/datagrok-ai/public/assets/15780643/2ab64f6f-f7cd-463c-a76e-1f7160156c04)

**Comment by ahadzhanian** [comment]
DG 1.17.13
