### ISSUE TITLE
Filtering done using viewers is unexpectedly reset on applying other filters in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2642]
v1.17.11 (and earlier)

**Scatter plot, filter by zoom:**
1. Open filters, add a structure column to filters
2. Add scatter plot with 'filter by zoom' option
3. Zoom scatter plot >>> table is filtered
4. Draw some structure in structure filter and apply
**Expected results:** scatter plot zoom is not reset, table is filtered both on structure and range set by scatter plot zoom.
**Actual results:** scatter plot zoom is reset to default (or min/max), table is filtered only on structure drawn in structure filter.
Same issue happens when scaffold tree filter or scaffold tree standalone viewer is used.
This issue does not happen for other filters.

**Bar chart and pie chart, filter on click:**
1. Open filters
2. Add bar chart or pie chart
3. Right click > On click > select 'filter' or set the same option through properties panel
4. Click a bar/pie chart segment >>> table is filtered
5. Apply any filtering in filters panel
**Expected results:** filtering done through bar chart or pie chart should not be reset. It should be combined with filtering done in filters panel.
**Actual results:** filtering set using bar chart or pie chart is reset. Issue does not depend on row source option (filtered, all, selected).

**Comment by ahadzhanian** [comment]
Collaborative filtering for scatterplot is fixed in DG 1.17.13.
Note: for collaborative filtering, the AxesFollowFilter option for scatterplot should be off

**Comment by ahadzhanian** [comment]
DG 1.18.0

**Comment by ahadzhanian** [comment]
Data: SPGI
1. Add a Structure filter
2. Add a bar chart
3. Set On click to filter
4. Click any bar to filter the grid 
Expected: structure filter and bar chart filter is applied
Actual: only the bar chart filter is applied
 
![2642__](https://github.com/datagrok-ai/public/assets/111368431/fabf6183-21cc-4862-80ab-0dbbe95163bb)
