### ISSUE TITLE
#2644: Forms | Next row button: incorrect behavior after sorting the grid

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2644]
When sorting the grid and using the "Next row" function, it uses the old order and skips the rows. There should be a single spreadsheet.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14628

**Comment by ahadzhanian** [comment]
DG 1.19.0
