### ISSUE TITLE
#2645: Support single decimal place for rounding in calculated columns

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2645]
Formatting does not support exactly one decimal digit. Even if you use round to one digit, it comes back to two digits. The problem is in rendering.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14629

**Comment by dnillovna** [comment]
> Andrew Skalkin commented in Jira:

Added “one digit after comma” format

**Comment by ahadzhanian** [comment]
DG 1.18.-
