### ISSUE TITLE
#2646: Structure highlighting is not removed when filters panel is closed

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2646]
v1.17.11, chem 1.8.10

**Steps to reproduce:**
1. Open SPGI
2. Open filters
3. Draw some structure in structure filter, e.g.:
<img width="78" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/3a5fc2e1-ad8a-467b-a0cb-a973d08d72c9">
4. Apply structure filter
5. Close filters panel

**Expected results:** structure highlighting in the table should be removed, when filters are closed.
**Actual results:** structure highlighting is not removed when filters are closed:
<img width="474" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/fc37ecd3-bce4-4756-ab62-0f242f94d84a">

**Comment by MariaDolotova** [comment]
Fixed, will be in Chem 1.8.11

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14630

**Comment by ahadzhanian** [comment]
Chem 1.8.11, DG 1.17.13
