### ISSUE TITLE
#2647: File refresh breaks structure filter

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2647]
Chem 1.8.10 
DG 1.17.11
Data: any table, loaded form the storage (not locally)
**case 1:**
1. Open a table
2. Open the Filter Panel and use the structure filter - the data is filtered
3. go to Tables > File and click Refresh - sometimes filter is cleared and data is not filtered

**case 2:**
1. Open a table
2. Open the Filter Panel
3. Clone the view
4. On the cloned view close the structure filter tab on the Filter Panel
5. Go to the general view and use the structure filter - the data is filtered on both views
6. Switch to the cloned view
7. Go to Tables > File and click Refresh - the cloned view is not filtered, and the general view remains filtered

![refresh](https://github.com/datagrok-ai/public/assets/111368431/0d9d829b-7790-433b-b23c-c8bd2d9f3116)

**Comment by ahadzhanian** [comment]
Also, after the refresh, desynchronization occurs in the Search panel on the toolbox.
![image (84)](https://github.com/datagrok-ai/public/assets/111368431/82083942-c428-4b8a-90a4-da25b0341b07)

**Comment by dnillovna** [comment]
> Olena Ahadzhanian commented in Jira:

duplicateshttps://reddata.atlassian.net/browse/GROK-14612(manual-sync)

**Comment by ahadzhanian** [comment]
DG 1.17.13

**Comment by dnillovna** [comment]
> Olena Ahadzhanian commented in Jira:

@Denis Kryvchukcan reproduce the issue on Release 1.18.0

**Comment by ahadzhanian** [comment]
1.18.0
