### ISSUE TITLE
#2658: Core: Scatter Plot: ColorMin, ColorMax, SizeMin, SizeMax properties

### ISSUE THREAD

**Issue by skalkin** [datagrok-ai/public#2658]
They should default to `null`, and only taken into account when both are set and xxxMin < xxxMax.

-----
From our [community forum](https://community.datagrok.ai/t/visualization-issues-forms-barchart-scatter-plot-correlationplot/836):

> Customizing color schemes for scatter plots: Not good at handling of outliers
> Currently, scatter plots only allow selecting color schemes, which means that it does not reflect colors properly when existing extreme outliers. It would be helpful to have options such as setting Min/Max values or color coding based on ranges when specifying numerical columns for color coding.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14902

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16162
