### ISSUE TITLE
#2663: Grid: Enable easier composition of rows/columns range selections

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2663]
- [x] provide consistent behavior for rows and columns:
Shift+Drag selects rows (columns)
Ctrl+Shift+Drag deselects rows(columns)
Ctrl+Click toggles selected state.
Ctrl+Shift+Home selects rows above the current row,
Ctrl+Shift+End selects rows below the current one (inclusively)
Note: selection can be made by header or by cells
- [x] implement the Excel shortcuts 
For example, CTRL+click on row 2, SHIFT+click on row 4, then CTRL+click on row 8, SHIFT+click on row 10 will lead to the disconnected range 2-4,8-10 selected 
- [x] Skip hidden columns

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14903
