### ISSUE TITLE
#2665: Scatterplot: Ctrl+Shift+Drag doesn't work for deselection

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2665]
- [x] Ctrl+Shift+Drag doesn't work for rectangular deselection 
- [x] Lasso tool doesn't allow the deselection either

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14905

**Comment by ahadzhanian** [comment]
DG 1.18.0
