### ISSUE TITLE
#2676: Multiple activities for sequence generator

### ISSUE THREAD

**Issue by GennadiyZakharov** [datagrok-ai/public#2676]
# Scope of work
Implement the ability for the sequence generator to generate several activity columns with correlated data.
Activities should mock real biological assays used to estimate the product's biological activity.

# Implementation
- Generate Gauss-distributed "real" activity - same for all activity columns
- For each column, generate "noise" - gauss or random-distributed value specific to the particular column.
- Output activity with some level of noise

# Comments
The improvement requested by @asantrosyan

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14911
