### ISSUE TITLE
#2677: Line chart: formula line position is incorrect after switching axis to log scale

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2677]
v1.17.*

**Steps to reproduce:**
1. Open a table
2. Add a line chart
3. Add a formula line to the line chart
4. Switch one or both axes to log scale

**Expected results:** Formula lines should be adjusted accordingly when line chart is switched to the log scale.
**Actual results:** Formula lines position/shape is not adjusted on switching to log scale:
![2024-02-13_13-06-58 (1)](https://github.com/datagrok-ai/public/assets/15780643/70ba93b7-9d7a-4080-b47e-b76781faf042)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14941

**Comment by ahadzhanian** [comment]
Power Pack 1.2.1
