### ISSUE TITLE
#2678: Line chart: formula lines sometimes end abruptly and overlap axes

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2678]
v1.17.*

**Steps to reproduce:**
1. Open a table
2. Add line chart
3. Add a few formula lines

**Expected results:** Formula line position should be adjusted to the current range by default, it should not end abruptly. Formula line should not overlap axes.
**Actual results:** Formula lines do not use all the chart's range, some lines overlap axes.
Even if line's min/max is adjusted manually, it still does not use the right side of the chart.
<img width="676" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/24d759eb-3af6-437f-97c9-f8484b1f25f0">

When line is edited, the preview is shown on a scatter plot instead of line chart. Line range seems to be calculated for this scatter plot, not for the line chart:
<img width="748" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/23170a1c-7650-4853-a42d-3590e3672cb7">

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14942

**Comment by dnillovna** [comment]
> Olena Ahadzhanian commented in Jira:

@Dmytro Kovalyov

Release 1.18.0

There’s an error when adding a formula line


```
Property not found: invertYAxis
	packages/$sdk/lib/_internal/js_runtime/lib/core_patch.dart 680:36  StackTrace.current
	packages/grok_shared/src/log.dart 179:40                           Logger.getCurrentStackTrace
	packages/grok_shared/src/log.dart 132:12                           Logger.log
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1521:16  Primitives.applyFunctionWithPositionalArguments
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1489:11  Primitives.applyFunction
	packages/$sdk/lib/js/dart2js/js_dart2js.dart 667:13                _convertDartFunctionFast
	webpack://datagrok-api/dg.ts 51:21                                 <fn>
```

[file id="8704565f-fdaf-4e0b-8d91-46ac168452c7"]

**Comment by ahadzhanian** [comment]
The second case is not addressed
Power Pack 1.2.1

**Comment by dmytro** [comment]
Wrong Dmytro

**Comment by ahadzhanian** [comment]
Sorry

**Comment by ahadzhanian** [comment]
Power Pack 1.2.1
