### ISSUE TITLE
Implement editing a custom column format

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2679]
![grid-custom-format (1)](https://github.com/datagrok-ai/public/assets/111368431/29006436-dc39-4b73-b2c8-1135dfab51da)
Note: **Set as Default** applies only to numbers received from the database

**Comment by ahadzhanian** [comment]
DG 1.18.0

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14947
