### ISSUE TITLE
#2681: PowerGrid: Tags cell renderer

### ISSUE THREAD

**Issue by skalkin** [datagrok-ai/public#2681]
Efficient color-coded representation of tags (comma-separated strings in a cell). Somewhat similar to #2673. This is how this will look:

![image](https://github.com/datagrok-ai/public/assets/943403/84818704-3988-4c1a-b48f-8373c71bdee0)

**Comment by ahadzhanian** [comment]
PowerGrid 1.3.0

**Comment by ahadzhanian** [comment]
const df = grok.data.demo.demog(100);
grok.shell.addTableView(df);
const dis = df.col('disease');
const site = df.col('site');
dis.set(0, 'Anxiety, Glaucoma');
dis.set(1, 'Hepatitis A, Glaucoma');
dis.setTag(DG.TAGS.CHOICES, JSON.stringify(['Anxiety', 'Hepatitis A', 'Glaucoma']));
dis.setTag(DG.TAGS.CELL_RENDERER, 'MultiChoice');
site.setTag(DG.TAGS.CELL_RENDERER, 'Tags');
