### ISSUE TITLE
#2684: Wrong filters are added if there are two views in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2684]
v1.17.13

**Steps to reproduce:**
1. Open SPGIv2
2. Open filters > filter panel with default filters is opened
3. Open the 2nd view for the same table (not clone)
4. Use console command to add specific filters and open the filter panel:
```
grok.shell.v.filters( {
        columnNames: [
          'Primary Series Name',
        ],
      })
```

**Expected results:** Filter panel is opened, the columns specified in the command are added to filters.
**Actual results:** filter panel with default filters is opened.
![2024-02-14_17-38-26 (1)](https://github.com/datagrok-ai/public/assets/15780643/92dacd25-2853-4cc0-a944-588ca3217086)

Issue cannot be reproduced in v1.17.10

**Comment by ahadzhanian** [comment]
Dg 1.18.0
