### ISSUE TITLE
#2685: Histogram: add stacked view option when split is set 

### ISSUE THREAD

**Issue by dionissqq** [datagrok-ai/public#2685]
Currently, in bar graphs, it is possible to implement coloring for each category based on “stack” setting. Would it be possible to also implement this coloring feature in histograms? Currently, coloring in histograms is only done based on aggregated values of numerical data. Although there is “split” setting for displaying categories, it is shown as a line graph. Line graphs are useful in case of comparing individual categories, but category stack coloring would be suitable in case for viewing both the total of each bin and its constituent elements. It would be a useful feature to have. I hope you feel worth trying.
![2f12f88ea92176ff4594a1352048bf4f99baccd5_2_1035x399](https://github.com/datagrok-ai/public/assets/111368431/cb5b6f7b-e213-4734-b8ac-6af805ea2a01)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14961

**Comment by ahadzhanian** [comment]
The legend is not saved to the layout
![2685](https://github.com/datagrok-ai/public/assets/111368431/8740f3cc-099f-4ace-8ae0-1134b32a491f)

**Comment by ahadzhanian** [comment]
DG 1.18.0
