### ISSUE TITLE
#2686: Forms viewer | Context Panel | Data | Fields: columns order is not preserved

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2686]
It is possible to sort rows, but once you sort them and try to sort again, the previously set order is lost. 
Add the new dialog that saves the fields' order and shows the selected fields at the top of the list.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14962

**Comment by dnillovna** [comment]
> Olena Ahadzhanian commented in Jira:

Add the same dialog to pivot table

**Comment by dnillovna** [comment]
> Andrew Skalkin commented in Jira:

@Denis Kryvchukdid you fix it? Don’t see the associated commit

**Comment by dnillovna** [comment]
> Andrew Skalkin commented in Jira:

This looks very minor to me -  but what is needed is the ability to drag column names to establish order

**Comment by ahadzhanian** [comment]
1.18.0
