### ISSUE TITLE
#2688: Scatterplot | structure labels: improve positions and sizes adjustment

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2688]
https://community.datagrok.ai/t/visualization-issues-forms-barchart-scatter-plot-correlationplot/836/13
Currently, the images can be shown by Labels setting, but their positions and sizes cannot be adjusted. So it would be more user friendly if you could add such options. Besides, if sometimes images are overwrapped so, if possible, clickable function for dragging image to adjust their positions is favorable to have. Or, scattering images function not to stack is another option to achieve.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14970

**Comment by dnillovna** [comment]
> Andrew Skalkin commented in Jira:

This is definitely not for Kostya but for@Denis Kryvchuk

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16165

**Comment by LesiaPavlenko** [comment]
1.21

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

ok on dev 1.22.0


[file id="c3b42f9f-eb96-4244-9065-75ce195b6e27"]
