### ISSUE TITLE
#2696: Bar chart: Add highlighting for bar chart subsets

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2696]
Add dynamic highlighting for bars in case there are subsets in bar chart
- [x] Add an option (**Show Filtered Rows**) for displaying the indication of filtered rows under the bars when the Row Source = All (Off by default)
- [x] Add dynamic highlighting for the mouseoverrows action

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15006

**Comment by ahadzhanian** [comment]
Dynamic highlighting doesn't work in the case of structure and numeric filtering


![Image](https://github.com/datagrok-ai/public/assets/111368431/594e4066-0635-4229-85b9-f1720a1a527a)



![Image](https://github.com/datagrok-ai/public/assets/111368431/cdc0c721-114b-4691-8e27-e87100434e1e)

**Comment by ahadzhanian** [comment]
![Image](https://github.com/datagrok-ai/public/assets/111368431/82210f4a-aad4-43be-a68f-b8ad128fb0b8)

**Comment by ahadzhanian** [comment]
DG 1.19.0
