### ISSUE TITLE
#2708: Formula lines: Preserve scatterplot line configuration upon changing columns on the axis 

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2708]
Additional updates:

- [x] highlight the feature (or add some explanation)
- [x] change "${x}" to "x" on Formula Lines
- [x] restyle Formula Lines for better visibility (let's use a bolder color, and maybe an white opaque rectangle underneath the text)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16214
