### ISSUE TITLE
#2710: Implement export selected dataframe/view as a CSV

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2710]
- [x] Save the order of columns
- [x] Save the order of rows
- [x] Add the ability to export molecules as Smiles
- [ ] Nice to have
            Select which dataframe to export
            Select what (dataframe or view) should be exported
- [ ]  Remove the word “Only” in options
- [ ] Fix tooltips in the Save as CSV dialog
- [x] Add an option to download only visible columns
- [x] Check for the ability to set qualifier as column
- [x] Rename qualifier column as "Qualifier"

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15090

**Comment by katerina-stepanova** [comment]
v1.19 rc

Error on exporting with 'molecule as smiles' option:
`logger.ts:107 
 convertNotation 4 input parameters, 5 passed
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1772:17      wrapException
	packages/ddt/src/func/func_call.dart 808:9                             FuncCall.setValues
	packages/ddt/src/func/func.dart 145:16                                 Func.apply
	packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 213:19     _wrapJsFunctionForAsync
	packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 237:5      _wrapJsFunctionForAsync.<anonymous function>
	packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 187:19     _awaitOnObject.<anonymous function>
	packages/$sdk/lib/async/zone.dart 1128:37                              _rootRunUnary
	packages/$sdk/lib/async/zone.dart 1012:12                              _CustomZone.runUnary
	packages/$sdk/lib/async/future_impl.dart 129:12                        _FutureListener.handleValue
	packages/$sdk/lib/async/future_impl.dart 665:13                        _Future._propagateToListeners
	packages/$sdk/lib/async/future_impl.dart 343:9                         _Future._addListener.<anonymous function>
	packages/$sdk/lib/async/zone.dart 1120:12                              _rootRun
	packages/$sdk/lib/async/zone.dart 1001:12                              _CustomZone.run
	packages/$sdk/lib/async/zone.dart 901:14                               _CustomZone.runGuarded
	packages/$sdk/lib/async/zone.dart 926:20                               _CustomZone.bindCallback.<anonymous function>
	packages/$sdk/lib/async/schedule_microtask.dart 41:5                   _microtaskLoop
	packages/$sdk/lib/async/schedule_microtask.dart 50:5                   _startMicrotaskLoop
	packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 51:9       _AsyncRun._initializeScheduleImmediate.internalCallback
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:48      invokeClosure.<anonymous function>
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 474:16  _IsolateContext.eval
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 59:16   _callInIsolate
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:14      invokeClosure
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2476:14      convertDartClosureToJS`

Issue can be reproduced for SPGIv table

**Comment by katerina-stepanova** [comment]
No error with chem 1.10 on exporting molecules as smiles
