### ISSUE TITLE
#2715: PadLeft and PadRight do not seem to work

### ISSUE THREAD

**Issue by ptosco** [datagrok-ai/public#2715]
I tried to use the `PadLeft` and `PadRight` functions without success.
They do not seem to work either with a `const` string (as in the [example in the JS API documentation](https://datagrok.ai/help/transform/functions/text-functions#padlefts-width-padding)) or with a column string.

![image](https://github.com/datagrok-ai/public/assets/5244385/bd889e30-018a-4dbc-8f4e-6aa092ed2622)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15099

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16170

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

https://reddata.atlassian.net/browse/GROK-15099

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

https://reddata.atlassian.net/browse/GROK-15099

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

duplicatehttps://reddata.atlassian.net/browse/GROK-16170
