### ISSUE TITLE
#2718: Grid Viewer - JS Exception

### ISSUE THREAD

**Issue by tcarolan** [datagrok-ai/public#2718]
To reproduce: Add 2 Datasync tables. Add a 'Grid Viewer' so that both tables are viewed on the same Dashboard.  Upload the Project, close, reopen. Error will occur. 

Stacktrace:

sortByCols.length != orders.length
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1772:17      wrapException
	packages/ddt/src/data_frame/data_frame.dart 285:5                      DataFrame.getSortedOrder
	packages/d4/src/grid/grid_core.dart 466:9                              GridCore._applySortFilter
	packages/d4/src/grid/grid_core.dart 1219:9                             GridCore.refresh
	packages/d4/src/grid/grid_core.dart 509:9                              GridCore.onFrameAttached.refreshRows.<anonymous function>
	packages/$sdk/lib/async/zone.dart 1116:37                              _rootRun
	packages/$sdk/lib/async/zone.dart 1001:12                              _CustomZone.run
	packages/$sdk/lib/async/zone.dart 901:14                               _CustomZone.runGuarded
	packages/$sdk/lib/async/zone.dart 926:20                               _CustomZone.bindCallback.<anonymous function>
	packages/$sdk/lib/async/zone.dart 1120:12                              _rootRun
	packages/$sdk/lib/async/zone.dart 1001:12                              _CustomZone.run
	packages/$sdk/lib/async/zone.dart 901:14                               _CustomZone.runGuarded
	packages/$sdk/lib/async/zone.dart 926:20                               _CustomZone.bindCallback.<anonymous function>
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 1393:9  TimerImpl.internalCallback
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2454:48      invokeClosure.<anonymous function>
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 474:16  _IsolateContext.eval
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 59:16   _callInIsolate
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2454:14      invokeClosure
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2476:14      convertDartClosureToJS

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15108

**Comment by tcarolan** [comment]
Hi Olena,
You can close the issue. I can't reproduce and am running 1.18 now. Likely
this bug was fixed. Thanks,
Tom

**Comment by ahadzhanian** [comment]
Hi Tom,
Thank you kindly for the feedback
