### ISSUE TITLE
#2726: Line chart: implement consistent behavior for aggregated and nonaggregated axes

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2726]
Add an option to show/hide unused categories - hide by default
Consistent behavior for axes is preferable

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15145

**Comment by ahadzhanian** [comment]
To test

1. Open the table from attached file:
2. [PubChem_compound_text_covid-19.csv](https://github.com/datagrok-ai/public/files/12818189/PubChem_compound_text_covid-19.csv)
3. Configure line chart: 'inchi' as X axis, 'heavycnt' as Y axis, split by 'depcatg'
4. Filter the table by 'depcatg' so that only the largest category is shown (630 rows)
5. See the line chart -  no unused categories should be shown

**Comment by ahadzhanian** [comment]
DG 1.19.0
