### ISSUE TITLE
#2739: Core: Grid: Custom column order sorting is not saved in the layout/project

### ISSUE THREAD

**Issue by LaykDimon** [datagrok-ai/public#2739]
Grid doesn't remember the custom order sorting when creating a layout or the project

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15202

**Comment by skalkin** [comment]
Tried to reproduce it but everything works fine now (both layouts and projects), likely we fixed it already so I'm closing the issue - please reopen if you still experience it somewhere
