### ISSUE TITLE
Show placeholder for failed docking rund

### ISSUE THREAD

**Issue by GennadiyZakharov** [datagrok-ai/public#2741]
For the failed docking runs, the "poses" column displays an empty grid cell.
In fact, by clicking on this "empty" cell, we can see the docking log in the properties panel.
![Screenshot 2024-03-19 101417](https://github.com/datagrok-ai/public/assets/5824560/ed2126fd-a7bb-45cd-9355-0104aeee284d)

We need to display in the "poses" column some notification that the error log is available on click.
For example, plain text "Error log". Or something similar.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15221
