### ISSUE TITLE
#2747: Line chart, scatterplot | Formula lines: inconsistent behavior

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2747]
- [x] The preview does not change when selecting a line
- [x] Can't change axes in the Formula lines dialog
Expected: 
When you open the FormulaLines dialog, a list of all specified lines is displayed, and the axes corresponding to the current formula line are displayed in the preview. 
If lines are not specified, then the axes in the preview correspond to the axes on the chart

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15252

**Comment by ahadzhanian** [comment]
release 1.18.5
Data: SPGI
1. Add a Scatterplot
2. Add a vertical formula line. Ok
3. On the scatterplot, change the x-axis
4. Open Formula lines dialog again - Y-axis is changed, and the line is not vertical, it's horizontal

![Image](https://github.com/datagrok-ai/public/assets/111368431/542e4fdd-1088-49f4-92ae-92246b3d01dc)
