### ISSUE TITLE
#2748: Whole table is broken if cell with curves contain specific data

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2748]
v1.18.2, curves 1.2.15

**Steps to reproduce:**
1. Open table: 
[curves zero.csv](https://github.com/datagrok-ai/public/files/14722004/curves.zero.csv)
2. Set tag for 'curve' column:
.fit = {"chartOptions":{"logX":false,"logY":false,"allowXZeroes":true},"seriesOptions":{"fitFunction":"sigmoid","errorModel":"constant","clickToToggle":false,"showFitLine":true,"showPoints":"points","showCurveConfidenceInterval":false,"markerType":"circle","lineStyle":"solid"}}
3. Set semType for this column in the console:
grok.shell.tableByName('curves zero').columns.byName('curve').semType = 'fit';

**Expected results:** Even if one cell cannot be rendered, the rest of the table should be usable.

**Actual results:** Table is completely broken: headers disappear, data is not rendered properly:
![2024-03-22_14-49-39 (1)](https://github.com/datagrok-ai/public/assets/15780643/78c768d4-e631-4762-98d3-b1cc775b2e0b)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15258

**Comment by ahadzhanian** [comment]
Curves > 1.2.16

**Comment by ahadzhanian** [comment]
- [ ] Show the red cross and the exception when we can`t render - add explanation in the property panel 
- [ ] Use generic handler to specify what is missing or what is wrong

**Comment by LesiaPavlenko** [comment]
Curves > 1.2.16
