### ISSUE TITLE
#2749: Line chart and Trellis plot: '+' icon is missing

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2749]
v1.18.2, Edge on MacOS

**Steps to reproduce:**
1. Open SPGI
2. Add Line chart
3. Add Trellis plot
4. Check '+' icons:
- Splits for line chart
- Adding columns for Trellis plot

**Expected results:** '+' icon should be present.
**Actual results:** '+' icon is missing for line chart and trellis plot, but the area where is should be is clickable:
![image](https://github.com/datagrok-ai/public/assets/15780643/edc162f8-73a6-4071-b852-15c109603e47)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15261

**Comment by ahadzhanian** [comment]
DG 1.19.0
