### ISSUE TITLE
#2753: Activating disabled structure filter does not trigger filtering

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2753]
DG 1.17.* and 1.18.2, chem 1.8.13 and 1.9.0

**Steps to reproduce:**
1. Open a table, e.g. SPGI
2. Open filters and make sure structure filter was added
3. Disable all filters or structure filter only
4. Draw some structure in the filter > OK
5. Enable all filters or structure filter only

**Expected results:** Filtering by structure should be triggered when filter is enabled.
**Actual results:** Filtering by structure is not triggered, user needs to open editor > OK to apply this filter:
![2024-03-26_18-21-15 (1)](https://github.com/datagrok-ai/public/assets/15780643/7db2a49d-2895-40e0-9d18-628f36b6ea8f)

**Comment by ahadzhanian** [comment]
See the scaffold tree filter as well

**Comment by LesiaPavlenko** [comment]
Chem 1.9.1
