### ISSUE TITLE
#2755: Viewers | Scatterplot: Hide the zoom slider for making screenshots 

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2755]
- [x] Implement the ability to copy the image to the clipboard without the zoom slider from the context menu 
- [x] Add the shortcut for this action - CTRL+C

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15280

**Comment by LesiaPavlenko** [comment]
Default function "save as PNG" saves without the zoom slider

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16174

**Comment by katerina-stepanova** [comment]
v1.19.2: it works for scatter plot only
