### ISSUE TITLE
#2761: Cancels table name` renaming after opening the project 

### ISSUE THREAD

**Issue by LesiaPavlenko** [datagrok-ai/public#2761]
Cancels table name` renaming after opening the project 

Steps to reproduce: Open dataset > change table name > save project > close all > open this project
Actual result : table name has old name
Expected result: Table name is renamed

- [ ] Fix table name` behavior: Table name should save it's previous renaming after Project opening.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16176
