### ISSUE TITLE
#2762: RoundFolat: incorrect display of the function result due to the default formatting of the new columns

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2762]
![RoundFloat](https://github.com/datagrok-ai/public/assets/111368431/a5f4c5ac-25b3-4c95-9a80-ef113ad7b814)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15339

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16177
