### ISSUE TITLE
#2764: Box plot: wrong area is selected with shift-drag when categories at the left are filtered out

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2764]
v.1.17.*, 1.18.3

**Steps to reproduce:**
1. Open SPGI
2. Add Box Plot: Category = 'Stereo Category', Value = 'Chemical Space X' (default config)
3. Open filters
4. Add 'Stereo Category' to filters
5. Filter data: uncheck a few categories that are shown on the box plot at the left
6. Select some data on the box plot using shift-drag

**Expected results:** Exactly the area outlined by shift-drag should be selected. Selection should work correctly when there is some filtering.
**Actual results:** items to the left of the area outlined by shift-drag are selected. If multiple categories are filtered out, nothing is selected at all on shift-drag:
![2024-04-05_18-11-27 (1)](https://github.com/datagrok-ai/public/assets/15780643/131b6f6f-8734-4532-b1ad-15ff60a283d0)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15352

**Comment by ahadzhanian** [comment]
DG 1.18.5

**Comment by LesiaPavlenko** [comment]
shift+drag on the plot selects the area 
ctrl+shift+drag on the plot deselects the area
