### ISSUE TITLE
#2771: Viewers: filter out legend with empty categories in the legend

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2771]
The pack and zoom option does not filter out the empty categories in the legend.
The color legend could be displayed even if there is no data in it (no filter was applied).

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15379

**Comment by katerina-stepanova** [comment]
1.19.2

Legend is not updated when column on plot axis was changed:
1. Open SPGI
2. Add two columns with formulae:
col1: if(${Stereo Category}!='S_UNKN', null, ${Average Mass})
col2: if(${Stereo Category}=='S_UNKN', null, ${Average Mass})
3. Add a scatter plot and set col1 as X axis
4. Set colour by Stereo Category
5. Change X axis to col2

**Expected:** legend categories should be updated according to the new data on the plot.
**Actual:** legend was not updated and does not match current data on the plot:
<img width="579" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/19fb8627-c77f-4b32-80e8-e15b61a3bfda">
Issue can be reproduced for all filter and zoom options.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16275

**Comment by LesiaPavlenko** [comment]
is not reproducible on 1.20
