### ISSUE TITLE
#2776: Line chart: page is frozen if too many categories are used in split

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2776]
v1.17.*
v.1.18.*

**Steps to reproduce:**
1. Open SPGI
2. Add a line chart
3. Configure a couple of columns for Y axis and switch to log scale
4. Open Split columns selector
5. Add several columns to split

**Expected results:** optimise line chart so that it's possible to add more columns to split. Browser page should not freeze.

**Actual results:** Browser page is freezing for a while when ~5-10 columns are added to split (depending on data in the table and columns selected). When more columns are added, page is frozen permanently.
Issue looks to be reproduced easier when Y is on log scale.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15399

**Comment by katerina-stepanova** [comment]
v1.19.2

Issue can be still easily reproduced for SPGI table and 5-10 columns in split.
Columns used on Y axis during testing: Average mass, TPSA, both in log scale.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16255

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

Found on release 1.20

**Comment by katerina-stepanova** [comment]
Issue can be reproduced with v1.22.
SPGI table and 5-10 columns in split. Columns used on Y axis during testing: Average mass, TPSA, both in log scale.
Page is frozen completely if there are 5-7 columns selected and one of them has several hundred values.
Page is lagging severely if there are 8-10 columns selected, each one under 10 categories.

**Comment by ahadzhanian** [comment]
related ticket 
https://github.com/datagrok-ai/public/issues/3210
