### ISSUE TITLE
#2777: Some csv files are parsed incorrectly: comma is not recognised as delimiter

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2777]
v.1.17, 1.18

**Steps to reproduce:**
Open following csv file:
[parse.csv](https://github.com/datagrok-ai/public/files/14958656/parse.csv)

**Expected results:** this file has comma as delimiter. It should be parsed accordingly.
**Actual results:** file is parsed incorrectly, comma is not recognised as delimiter:
<img width="597" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/431918c2-78f9-481c-899a-b26e5d5d15ed">
Issue looks to be caused by spaces in columns headers: if spaces are removed, file is parsed as expected.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15400
