### ISSUE TITLE
#2782: Line chart : incorrect color-coding while setting filters

### ISSUE THREAD

**Issue by LesiaPavlenko** [datagrok-ai/public#2782]
incorrect color-coding while setting filters when we use two splits or more

![Linechart](https://github.com/datagrok-ai/public/assets/163252049/7a25a2d2-7dd0-42f3-9ebf-1599759ed02b)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15451

**Comment by ahadzhanian** [comment]
DG 1.18.5
