### ISSUE TITLE
#2784: Grid : broken ability to apply color-coding to text instead of background 

### ISSUE THREAD

**Issue by LesiaPavlenko** [datagrok-ai/public#2784]
When applying color-coding with “text,” the background is highlighted in Grid.

https://github.com/datagrok-ai/public/assets/163252049/41df0eaf-170f-4f08-a932-a8edf55b614d

![Screenshot_14](https://github.com/datagrok-ai/public/assets/163252049/20d5b37c-7b36-4c23-97de-8f1561b67400)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15461

**Comment by juliyatroff** [comment]
After saving the table color coding type is not changing to text
