### ISSUE TITLE
#2789: Grid: Ability to display the table name/description

### ISSUE THREAD

**Issue by LesiaPavlenko** [datagrok-ai/public#2789]
to display the table name/description on the Grid

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15465

**Comment by LesiaPavlenko** [comment]
![image - 2024-11-20T102224 318](https://github.com/user-attachments/assets/41543169-331b-45f0-ac30-16422f3f9f1b)
