### ISSUE TITLE
#2791: Fix duplicated table` renaming

### ISSUE THREAD

**Issue by LesiaPavlenko** [datagrok-ai/public#2791]
- [ ] reply when the issue is fixed
https://community.datagrok.ai/t/clone-vs-new-table-view/869/7 

when duplicating using “New Table View”
if rename one table, all the duplicated tables end up having the same name.

![9ec53a963a7458e410c5bb953c63442cfaed9cc9](https://github.com/datagrok-ai/public/assets/163252049/e7d45fbf-1447-4c5a-9294-fd2ab54bbbc0)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15478

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16180

**Comment by LesiaPavlenko** [comment]
https://github.com/user-attachments/assets/b2d2578f-d158-4a1a-9042-2ae4c63be01b

View - Rename - works
Table - Rename - renames all views. should rename only current
