### ISSUE TITLE
#2793: Scatter plot with 'filter by zoom': filtering by scatter plot is shown in filter panel's '?' after resetting in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2793]
v 1.17, 1.18

**Steps to reproduce:**
1. Open a table
2. Open filters
3. Add a scatter plot with 'filter by zoom' option
4. Zoom in the scatter plot > table is filtered
5. Hover '?' icon in the filters panel > filtering by scatter plot is shown (expected)
6. Click reset button in filters panel to reset filters
7. Hover '?' icon in filters panel again

**Expected results:** No filtering should be shown on hovering '?' after resetting filters.
**Actual results:** Filters coming from scatter plot are still shown on hovering '?'
![2024-04-23_17-50-57 (1)](https://github.com/datagrok-ai/public/assets/15780643/fe7063ec-7872-4fdb-8b94-ca187ba2c143)
After this, scatter plots filter are always shown on hovering '?'.

Issue is not reproduced if scatter plot filtering is reset in scatter plot itself (reset view or zoom out).

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15496

**Comment by ahadzhanian** [comment]
@katerina-stepanova can't reproduce on 1.17.13 or 1.18

![2793](https://github.com/datagrok-ai/public/assets/111368431/a113b0ca-4bb4-49f6-a2e5-8ee58b702309)

**Comment by katerina-stepanova** [comment]
@ahadzhanian 
I can reproduce it if I make some changes to the filters configuration first, e.g.
1. Remove a couple of filters from the panel
2. Add scatter plot
3. Zoom in on the scatter plot
4. Reset filters

**Comment by ahadzhanian** [comment]
DG 1.18.5
