### ISSUE TITLE
#2798: Calculated column renaming is not cascaded to the dependent columns for a saved project

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2798]
v1.18.5

**Steps to reproduce:**
1. Open a table
2. Add two calculated columns: column2 depending on column1
3. Save project
4. Refresh browser page or open DG in a new tab and reopen saved project
5. Rename column1

**Expected results:** column2's formula should be updated when column1 is renamed.
**Actual results:** column2's formula is not updated:
![2024-04-26_21-00-12 (1)](https://github.com/datagrok-ai/public/assets/15780643/5ce0a9b9-9df1-47a9-8330-88deaf754c8c)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15545

**Comment by LaykDimon** [comment]
@katerina-stepanova is the project saved with the data-sync project?
for calculated columns to work, the project needs to be saved as a data-sync one, so it will rerun all the functions that were done before (such as adding a calculated column and making subscriptions so they will change the values accordingly)

**Comment by skalkin** [comment]
> for calculated columns to work, the project needs to be saved as a data-sync one, so it will rerun all the functions that were done before (such as adding a calculated column and making subscriptions so they will change the values accordingly)

@LaykDimon Something is wrong here. Obviously calculated columns (and renaming) should work orthogonal to the data-sync. Back to the drawing board I guess?

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16182

**Comment by LesiaPavlenko** [comment]
Will be added to v.1.21
