### ISSUE TITLE
Peptides: Substitution analysis enhancements

### ISSUE THREAD

**Issue by StLeonidas** [datagrok-ai/public#280]
Substitution analysis is now functional but needs polishing
- [x] move sequences visualizations to panel
- [x] Create aligned sequence difference cell renderer

**Comment by nuradilK** [comment]
Moved sequences visualizations to panel in [this comit](https://github.com/datagrok-ai/public/commit/291f6125c474b63ad08c52bc8668947c67f406cd).

**Comment by nuradilK** [comment]
The peptide difference cell renderer is implemented in this [commit](https://github.com/datagrok-ai/public/commit/541c76a9d85f126d665e45aef226cbbd725c5108). 
![image](https://user-images.githubusercontent.com/26120466/151140596-1b9e4292-f713-4d07-86c8-3a54b8b1c94a.png)
