### ISSUE TITLE
#2824: Creating Dataframe from csv loses qnum precision

### ISSUE THREAD

**Issue by denyzhirkov** [datagrok-ai/public#2824]
Here is an example%

`
let a = DG.DataFrame.fromCsv(`Id,Col1,Col2,Col3,Col4,Col5,Col6,
AAO239,0.001415,,,,0.00502,,
BHO269,<0.0009000,,,,,,
CSX801,<0.0009000,,,,,,
DQI713,,,0.002862,,,,
GHN729,,0.0008489,0.009932,2.84E-04,,>100.00,
KCF907,,0.001228,0.0048,,,34.43,
,,,,,,,
`);

grok.shell.addTableView(a);

a.toCsv();
`

After "grok.shell.addTableView" we could see that the "Col1" is shown as "0.00".
But if checked directly by:
`a.columns.byName('Col1').get(0)` > "0.001415"

After ".toCsv()" the result lose the qnum column (Col1) precision, and all the values look like "0.00"

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15586

**Comment by LesiaPavlenko** [comment]
1.18.7
