### ISSUE TITLE
#2828: DataSync option not present after loading table from Data Query

### ISSUE THREAD

**Issue by tcarolan** [datagrok-ai/public#2828]
DataSync option not present when saving a Project after loading table from Data Query.
![chrome_A2taESWTty](https://github.com/datagrok-ai/public/assets/6126004/44238571-0735-46d8-813e-bd9438c3b81c)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15594
