### ISSUE TITLE
#2830: Double clicking in "Recent Projects"

### ISSUE THREAD

**Issue by tcarolan** [datagrok-ai/public#2830]
"Recent Projects" box is convenient but most people double click on the project. This causes the project to open twice - doubling the number of tabs and slowing everything down. 

Please removing double click problem or open the "right click" menu when a user clicks in the "Recent Projects" box.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15596

**Comment by LaykDimon** [comment]
fixed in 1.19 (the package depends on the core changes, unfortunately)
