### ISSUE TITLE
#2831: Default open folders in the Browse Menu

### ISSUE THREAD

**Issue by tcarolan** [datagrok-ai/public#2831]
The default Browse menu always opens "Functions" folder. This is not usually needed by most users. Can it be closed by default or placed under "Platform"? Additionally, "Plugins" and "Namespaces" are not normal user objects that are needed to be prominently visible to users. These also can go under "Platform" folder.
![chrome_Tz5WBRmg0p](https://github.com/datagrok-ai/public/assets/6126004/1d1d2ccb-d9aa-489f-a853-75ae983ff38c)

**Comment by skalkin** [comment]
@alex-aprm - I thought we open Browse on the state it was left previously?
