### ISSUE TITLE
#2832: Tab Name changes when reopening Project

### ISSUE THREAD

**Issue by tcarolan** [datagrok-ai/public#2832]
There is some inconsistency when reopening a Project that causes the tab names to change back to the original data query name (despite the tables not being datasync=true). 

To reproduce, open a dat
![chrome_A1j7Z8Opft](https://github.com/datagrok-ai/public/assets/6126004/9df1f8d9-f529-4b7d-aca4-ab41d49b162b)
a query and add it to the workspace, rename the table, save the project, then reopen - the "tab" name will be the original name but listed as different in the Project view and other places.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15598
