### ISSUE TITLE
#2836: Sticky Meta  - cannot remove values

### ISSUE THREAD

**Issue by tcarolan** [datagrok-ai/public#2836]
Cannot remove string value from sticky meta (see screenshot)
The strings should be trimmed and nulled and sticky meta removed if the user deletes it.
![chrome_pTThAbYCez](https://github.com/datagrok-ai/public/assets/6126004/ec012e3a-4624-49d5-80c7-44b557c6815e)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15602
