### ISSUE TITLE
#2838: Stick Meta circles are difficult to distinguish

### ISSUE THREAD

**Issue by tcarolan** [datagrok-ai/public#2838]
The light blue and dark blue circles that designate if a cell has stick meta values or not is difficult to distinguish. Please consider making the color difference more apparent or changing the shape.

![image](https://github.com/datagrok-ai/public/assets/6126004/77f75e28-7025-4cc4-b1ba-fc4c2a557e92)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15604

**Comment by skalkin** [comment]
Tom is right. @KiK0S , I think we discussed it and decided to indicate the non-existing meta as an outline of a circle? Same color as "meta exists" but hust the outline, white inside

**Comment by KiK0S** [comment]
Sure, we already have it implemented, it will be shipped in 1.19 
![Screenshot from 2024-05-09 10-49-56](https://github.com/datagrok-ai/public/assets/20306967/cf9c80d7-fb5b-4659-b8dd-e743ca592739)
