### ISSUE TITLE
#2845:  Changing the colors of labels in the properties

### ISSUE THREAD

**Issue by LesiaPavlenko** [datagrok-ai/public#2845]
Style change - the colors of labels in properties are too pale

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15624

**Comment by skalkin** [comment]
They seem fine to me (and we are using the color from our standard palette, if this is really too pale we need to change it) - or are you referring to the disabled items ("Invert color scheme" in the bottom)?



![image](https://github.com/datagrok-ai/public/assets/943403/a07c4ef4-9e22-4311-a172-59000d63e532)

**Comment by DanTkachev** [comment]
Hi @skalkin - This is not only about the disabled state, this is about the font color for the active state as well. See how it looks in the old version vs. the new version - it gets less contrasted, hardly readable and looks like inactive so it would be great if you could revert it to a more contrasted color:

![image](https://github.com/datagrok-ai/public/assets/114074888/f4a8eaa9-0a14-423f-8b6a-b2c4d698d44e)
