### ISSUE TITLE
#2846: Add distinguishable color legend for line chart when there are multiple Y axis and split key

### ISSUE THREAD

**Issue by LesiaPavlenko** [datagrok-ai/public#2846]
Add distinguishable color legend for line chart when there are multiple Y axis and split key

In the line chart, when there are multiple Y axis and split key, the line chart color legend is only based on the split key and ignored the Y columns. Users need to distinguish the lines by Y column name and split key combinations.

- [x] relocate the color legend to a more appropriate position, as the current placement is somewhat obstructive

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15625
