### ISSUE TITLE
#2848: Make the Structure filter Marvin JS options same as Structure search

### ISSUE THREAD

**Issue by VimalaSelvaraj** [datagrok-ai/public#2848]
Filter Panel > Structure Search > MarvinJS,  the options on the top menu, particularly Add/Remove hydrogens and couple other options, are not accessible. 

In ID Structure search Marvin JS version has those options in the menu.

Acceptance criteria:

Align the Marvin JS menu same as Structure Search  Marvin JS 

the following property would need to be set:

`sketcherInstance.setDisplaySettings({
                    toolbars: 'markush',
                });
<img width="666" alt="image-2024-04-19-08-18-20-185" src="https://github.com/datagrok-ai/public/assets/110638379/9d796ff3-27e7-49c3-801f-b81c0cfacd6b">

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15631

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16188
