### ISSUE TITLE
#2855: The marker value is ignored when outlier is true

### ISSUE THREAD

**Issue by LesiaPavlenko** [datagrok-ai/public#2855]
The marker value is ignored when outlier is true

- [x] add outlier marker as an option
- [ ] add all options to the package settings editor

 
Json
{
    "series": [
        {
            "fitLineColor": "#E74A21",
            "pointColor": "#E74A21",
            "points": [
                {
                    "x": 0,
                    "y": 2.004321
                },
                {
                    "x": 0.25,
                    "y": 1.8686450348881902
                },
                {
                    "x": 0.55,
                    "y": 1.7201601306327536
                },
                {
                    "x": 1,
                    "y": 1.4771227023655227
                },
                {
                    "x": 2,
                    "y": 0.9684876272345548
                },
                {
                    "x": 4,
                    "y": 0.2787764524701085
                },
                {
                    "x": 8,
                    "y": 0.000043427276862669634,
                    "outlier": true,
                    "marker": "square"
                }
            ]
        }
    ]
}
Collapse

**Comment by LesiaPavlenko** [comment]
![Screenshot_14](https://github.com/datagrok-ai/public/assets/163252049/ce6f9412-1e67-4244-ba08-298f89c7b5d0)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15703

**Comment by LaykDimon** [comment]
- [ ] add all options to the package settings editor

**Comment by LaykDimon** [comment]
To use the new outlier marker feature on the Curves v1.4.2, you will need to change the point structure to the following:
`{"x": 8,"y": 0.000043427276862669634,"outlier": true,"outlierMarker": "square"}`

**Comment by LesiaPavlenko** [comment]
Curves 1.4.2
