### ISSUE TITLE
#2859: Pick Up / Apply Option for grid coloring style

### ISSUE THREAD

**Issue by LesiaPavlenko** [datagrok-ai/public#2859]
Pick Up / Apply Option for grid coloring style. 

- [x] Pick Up should copy style settings
- [x] Apply should paste previously copied settings to new grid

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15707

**Comment by LesiaPavlenko** [comment]
1.19.0
