### ISSUE TITLE
#2867: Scatterplot issue with missing "logarithmic" columns

### ISSUE THREAD

**Issue by gasserandreas** [datagrok-ai/public#2867]
We identified an issue with Scatterplot handling missing logarithmic columns which is a) throwing errors to console and b) failing `view.saveLayout()` function.

**Steps to reproduce in native Datagrok:**
1. add Scatterplot to dataframe and configure logarithmic scale for column x and y
2. create layout from view
3. remove x column from dataframe and create new view from dataframe
4. apply layout to newly created view
5. create new layout from newly created view

**Expected behavior:**
- on step 4: Scatterplot shows error of missing column x
- on step 5: new layout is created

**Actual behavior:**
- on step 4: Scatterplot is failing to initialise, error message: "Scatter plot failed to load."
- on step 5: no layout created but error shown in browser console.

**Browser console error**
TypeError: Cannot read properties of null (reading 'z')....

**Script to reproduce error in native Datagrok**
//name: Scatterplot missing column issue
//description: Hello world script
//language: javascript

const df = grok.data.demo.demog()
const view1 = grok.shell.addTableView(df)

// add scatterplot
view1.scatterPlot({
  xColumnName: "site",
  yColumnName: "age",
  xAxisType: 'logarithmic',
  yAxisType: 'logarithmic',
});

// create and store layout 
const layout = view1.saveLayout();

// remove site column
df.columns.remove('age');

// create new table view
const view2 = grok.shell.addTableView(df);

// apply layout
view2.loadLayout(layout);

// BREAK!! create and store layout
const newLayout = view2.saveLayout();
console.log({ newLayout });

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15736
