### ISSUE TITLE
#2875: Line chart, trellis plot: number of selected columns is not updated in properties panel immediately

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2875]
v1.18.*

- [ ] number of selected columns should be updated in opened column selector 

**Steps to reproduce:**
1. Open a table
2. Line chart:
- add line chart
- open its properties
- add split columns from the line chart itself, or remove some columns from line chart
- check number of columns in properties
3. Trellis plot:
- add trellis plot
- open its properties
- add X or Y column from the plot itself
- check number of X or Y columns in properties

**Expected results:** number of selected columns in properties should be updated immediately on adding or removing a column.
**Actual results:** number of selected columns in properties is not updated immediately:
<img width="731" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/1ede04e1-e01d-40b1-b300-c892423dfe0f">
<img width="690" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/caf672cb-3dd9-440b-8523-bd3f62b5cc1c">
<img width="729" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/8322d0d3-943c-4862-a86b-db8aa547679f">

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15828

**Comment by LesiaPavlenko** [comment]
1.20.0
