### ISSUE TITLE
#2889: Scaffold Tree Javascript Error

### ISSUE THREAD

**Issue by tcarolan** [datagrok-ai/public#2889]
Multiple user reports of scaffold tree exceptions on a dataset of ~500 molecules. I tried to share the error report and send an email but that failed with a different exception. Attached is a screenshot of my browser showing the "Generating tree...30% completed" never moves forward. And it also shows the exception stack trace.  I cannot share this dataset. 
![Untitled](https://github.com/datagrok-ai/public/assets/6126004/9b8b6143-b4df-4a9a-9426-dc7cc30300ac)

**Comment by tcarolan** [comment]
jsonStr in loadTreeStr() is empty string.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15892

**Comment by Aleksashka11** [comment]
Hi!
@tcarolan, can you please tell me which version of Chem package do you use?

**Comment by LaykDimon** [comment]
Datagrok version is 1.18.8, Chem version is 1.9.2
