### ISSUE TITLE
#2894: Column header height and row height is not saved in the layout

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2894]
v1.18.*

**Steps to reproduce:**
1. Open a table
2. Adjust column header height
3. Adjust rows height
4. Save layout
5. Refresh browser page
6. Open the same table
7. Apply saved layout

**Expected results:** row height and columns header height should be saved.
**Actual results:** row height and columns header header height is not saved.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16195

**Comment by LaykDimon** [comment]
works on v1.19 and v1.20
