### ISSUE TITLE
#2901: Core | Grid: Setting grid to heatmap and rolling back corrupts layout

### ISSUE THREAD

**Issue by LaykDimon** [datagrok-ai/public#2901]
have a grid -> change to heatmap -> back -> save layout -> apply -> it breaks because of maxHeatmapColumns property

**Comment by katerina-stepanova** [comment]
Issue can be reproduced for DG 1.18.7 with following steps:
1. Open a table, e.g. SPGI
2. Switch table to heatmap
3. Increase 'Max Heatmap Columns'
4. Switch off 'Id heatmap'
5. Save and re-apply layout

Cannot reproduce the issue with same steps in DG 1.19

**Comment by LesiaPavlenko** [comment]
not reproducible on DG public v.1.19.0

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16196
