### ISSUE TITLE
#2910: Heatmap | Memory issue when heatmap contains molecule columns

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2910]
v1.18, 1.19

**Steps to reproduce:**
1. Open a table with molecules, e.g. SPGI
2. Open filters (not sure if necessary, but it looks to worsen the issue)
3. Add a heatmap
4. Configure heatmap to contain Structure and R groups columns
5. Adjust vertical zoom slider on heatmap, move it up and down OR change heatmap viewer size so that it is re-rendered
6. Monitor memory used by the browser page

**Expected results:** heatmap is re-rendered without issues or warnings. There should be no memory leaks and out of memory crashes.
**Actual results:** Page freezes for a while and multiple warnings appear in the console:
`Molecule not rendered due to width or height less than 1`
Page starts to take more and more memory on re-rendering the heatmap (when vertical zoom is adjusted or viewer size is changed).
For some larger datasets page eventually crashes with 'out of memory' error.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16199

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

fixes in Chem package
