### ISSUE TITLE
#2913: Improve different context menu style / functionality between Scatterplot in Trellis vs native Scatterplot

### ISSUE THREAD

**Issue by LesiaPavlenko** [datagrok-ai/public#2913]
Some updates according DG-NX meeting:
- [x] Add formula lines functionality
- [x] Rename in Trellis plot the "Inner viewer" to the actual name of the current inner viewer. Like "Scatter plot".

![image - 2024-06-04T175307 333 (1)](https://github.com/datagrok-ai/public/assets/163252049/7bb44308-1082-49dd-a34a-5671467b5781)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16200
