### ISSUE TITLE
#2918: Typing $ in the calculated column dialog pops up the available column drop down also within a quoted field

### ISSUE THREAD

**Issue by ptosco** [datagrok-ai/public#2918]
This should not happen when typing something within single or double quotes (e.g., when writing a regex which may include `$` as line termination).
For example, the `$` symbol can be introduced in
`RegExpReplace(${colname}, '(?<=^|\n).+(?=_\d+(\n|$))', 'series')`
only using copy/paste, not by typing `$`.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16202

**Comment by OlesiaPavlenko** [comment]
PowerPack 1.11.12
