### ISSUE TITLE
#2925: Viewer title is not saved in layout if it was edited in viewer's header

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2925]
v 1.18, 1.19

**Steps to reproduce:**
1. Open a table
2. Add some viewer
3. Edit viewer's name in its header
4. Check 'title' in properties
5. Save and re-apply layout 

**Expected results:** updated name should be shown in 'title' in properties. Updated name should be saved in layout.
**Actual results:** updated name is missing in properties and it is not saved in the layout.
<img width="614" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/d76acc04-a809-4261-baf1-d4c15557f502">

Title is saved if it was changed using properties panel.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16235
