### ISSUE TITLE
#2927: Heatmap is in a collapsed state after applying saved layout if it was stacked with another viewer

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2927]
v1.18, 1.19

**Steps to reproduce:**
1. Open a table
2. Open filters panel
3. Add heatmap and some other viewer
4. Stack heatmap over another viewer
5. Use heatmap's horizontal slider to zoom in
6. Download current layout
7. Close the table
8. Re-open the same table again
9. Apply previously downloaded layout
10. See heatmap

**Expected results:** heatmap is not in collapsed state.
**Actual results:** heatmap is collapsed, so that only one column is visible:
<img width="733" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/48629fcb-746a-470b-a3a3-614e033ab12d">

**Comment by katerina-stepanova** [comment]
Same issue can also happen even without stacking heatmap and some other viewer, but i could not reproduce it in native grok without our app so far.

**Comment by LesiaPavlenko** [comment]
fixed in 1.20.1

**Comment by katerina-stepanova** [comment]
v1.20.1

Error on applying layout (same steps as descrived above)
<img width="996" alt="image" src="https://github.com/user-attachments/assets/460e4c57-bc3d-4039-a535-7a633f7381e0">

**Comment by LesiaPavlenko** [comment]
![Screenshot_41](https://github.com/user-attachments/assets/7e136e65-ee32-406d-a108-c379718cdda0)
fixed in 1.20.1
