### ISSUE TITLE
#2934: (Mac OS) Grid: some hotkeys for selection/deselection are not working for columns

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2934]
v1.19.2

Following combinations are not working as expected for columns:
- Cmd-Shift-drag does not deselect columns
- Excel-like hotkeys are not applicable for columns (Shift-click selects a single column only)

**Expected result:** update hotkeys for MAc OS, so that
- Cmd-Shift-drag can be used to deselect columns
- Excel-like hotkeys should be applicable for columns too. E.g. Cmd-click on col1 selects col1, Shift-click on col4 after that selects all columns between col1 and col4, col4 included.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16277
