### ISSUE TITLE
#2943: Categorical filter in column header is broken after removing the same column from filters panel

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2943]
v1.18.7, 1.19.2

**Steps to reproduce:**
1. Open a table
2. Open filters
3. Add some categorical column to filters
4. Find the same column in table and use column header hamburger menu to set up filtering on this column
5. Remove the column from filters panel
6. Try to use columns header for filtering again

**Expected results:** removing column from filters should not break column header filtering.
Filtering should behave consistently for different types of filters (histogram, categorical, categorical with .multi-value-separator tag on the column).

**Actual results:** when column is removed from filters panel, filtering is reset in the table, but not in column header filter. Selecting/deselecting something in column header filter no longer works for this column.
![2024-07-19_14-50-31 (1)](https://github.com/user-attachments/assets/a12ded64-3a72-43b1-9866-d804a2fe73f2)

Behaviour is different for histogram filters: filtering set through header is not reset when column is removed from filters panel.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16366

**Comment by LesiaPavlenko** [comment]
added to 1.20.1
