### ISSUE TITLE
#2944: Line chart: the color of the line and the legend differs when multiple splits are selected

### ISSUE THREAD

**Issue by LesiaPavlenko** [datagrok-ai/public#2944]
When multiple splits are selected, the color of the line and the legend are different.
![3a5d2197098f6fa06b3da09b4c661f73c702597c](https://github.com/user-attachments/assets/b387c4ca-3365-413b-9ec5-19ccb378d12c)

[Community issue](https://community.datagrok.ai/t/line-chart-about-splits-and-color/866/6)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16383

**Comment by LesiaPavlenko** [comment]
1.20.1
