### ISSUE TITLE
#2945: Viewers: Color picker HEX\RGB choice input doesn't fit into dialog

### ISSUE THREAD

**Issue by LaykDimon** [datagrok-ai/public#2945]
![image](https://github.com/user-attachments/assets/2dece1b7-560f-4b65-9c66-e5ce072066eb)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16385

**Comment by LesiaPavlenko** [comment]
also check for LineChart

**Comment by LaykDimon** [comment]
Line chart has no color picker for now

**Comment by LesiaPavlenko** [comment]
Will be added to 1.20.1
