### ISSUE TITLE
#2949: Calculated columns dialog: extra scroll bars

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2949]
v1.20, PowerPack 1.1.8

**Steps to reproduce:**
1. Open a table
2. Open calculated columns dialog

**Expected results:** no double scroll bars, no scroll bar for function types (this section size can be adjusted to fit into dialog without any scrolling). 
**Actual results:** Double scroll bar for columns selection, unnecessary scrolling for function types section. Both extra scroll bars do not disappear when dialog is resized.
<img width="820" alt="image" src="https://github.com/user-attachments/assets/2037c9a5-6c8e-4193-8022-9c6d96ced1d9">
Double scroll bar for columns selection disappears on a huge screen (zoom out to 50% on 13" MacBook screen). Scroll bar for funtion types is present no matter the screen size.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16394
