### ISSUE TITLE
#2950: Line chart with multiple axes: legend is not updated when Y column is changed using in-plot selector

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2950]
v1.20

**Steps to reproduce:**
1. Open a table
2. Add a line chart
3. Configure two Y columns and select "Multi Axis"
4. Add a split column > legend appears on the plot
5. Chamge one of the Y columns using the in-plot column selector

**Expected results:** legend should be updated when the column is changed.
**Actual results:** legend is not updated and still contains an 'old' Y column
![2024-07-25_17-34-33 (1)](https://github.com/user-attachments/assets/05829778-f4e1-456e-ba65-a8da3bf23564)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16398
