### ISSUE TITLE
#2951: Line chart: number of Y columns is not updated immediately in properties panel when columns are removed from the plot

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2951]
v1.20

**Steps to reproduce:**
1. Open a line chart
2. Open properties panel
3. Remove some Y columns from the line chart by clicking 'x' buttons on the plot itself
4. Check the number of Y columns displayed in properties panel

**Expected results:** number of Y columns in the properties panel should be updated when columns are removed from the plot.
**Actual results:** number of Y columns in the properties panel is not updated when columns are removed from the plot:
![2024-07-25_18-17-07 (1)](https://github.com/user-attachments/assets/e4eb44b0-4265-417c-bfcb-600fa53a3904)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16399
