### ISSUE TITLE
#2955: Chem: MMPa - reflect selections in dervied tables to parent table

### ISSUE THREAD

**Issue by StLeonidas** [datagrok-ai/public#2955]
- [ ] Add Indication by color

![image](https://github.com/user-attachments/assets/3da0b7d4-84ba-4ec7-a6b0-9636d184ae7d)

Clicking the entities in parent table affects selection in "Fragments table", clicking "Fragments table" affects "Pairs table".
Reflect the clicking of entities in affects "Pairs table" to parent table.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16411
