### ISSUE TITLE
#2956: Chem: MMPa - enhance the ligics to work with multi component entities

### ISSUE THREAD

**Issue by StLeonidas** [datagrok-ai/public#2956]
![image](https://github.com/user-attachments/assets/e284a387-0fb6-488a-a372-1c2e2a934e9d)
Now it looks like this for salts, make correct depiction, ensure the size of fragments are correct

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16413
