### ISSUE TITLE
#2960: Colour picker in legend: icon does not disappear after closing colour picker

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2960]
1.20.1-rc.8e821e64d7.b8881c3102e9

**Steps to reproduce:**
1. Open a table
2. Configure a viewer with legend (e.g. Bar Chart with stacking)
3. Right click a legend item > colour picker appears
4. Close colour picker (OK or Cancel)

**Expected results:** colour picker icon  <img width="22" alt="image" src="https://github.com/user-attachments/assets/0781da52-951d-4c0d-afbb-c2d2ccb90aed"> should disappear when not hovered.
Opening colour picker dialog on right click the legend item might be not necessary at all.

**Actual results:** colour picker icon is still visible after closing the dialog in this case.
![2024-08-05_12-33-33 (1)](https://github.com/user-attachments/assets/e5600494-268d-45dd-9feb-de4bcb09d3a1)
Not reproduced if colour picker is opened by left click on the icon.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16433
