### ISSUE TITLE
#2964: 'Selection to filter' reset immediately for some data if scaffold tree is present in the view

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2964]
v1.8, 1.19, 1.20
chem 1.9.2, 1.10.0, 1.11.1

**Steps to reproduce:**
1. Open SPGI
2. Open Filters
3. Add Scaffold Tree viewer
4. Add benzene to scaffold tree
5. Select some row
6. Select > Selection to filter

**Expected results:** table is filtered, only selected item is shown.
**Actual results:** table is not filtered (filter seems to be applied briefly, but is reset immediately).
![2024-08-06_11-59-05 (1)](https://github.com/user-attachments/assets/464aae08-f576-46ec-b319-1c0ce257c297)

Issue is not reproduced for some datasets, it looks to be specific rather to the data in the table than specific structure drawn in scaffold tree.

Another example dataset to reproduce: 
[PubChem_compound_text_covid-19.csv](https://github.com/user-attachments/files/16508164/PubChem_compound_text_covid-19.csv)

Issue not reproduced: 
[PubchemNotReproduced.csv](https://github.com/user-attachments/files/16508204/PubchemNotReproduced.csv)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16448

**Comment by LesiaPavlenko** [comment]
tested on attached dataset and SPGI
ok on Chem 1.11.2 and DG v.1.20.1
