### ISSUE TITLE
#2965: Scatter plot: legend colour cannot be edited (no colour picker icon) if both colour and markers use the same column

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2965]
v1.20.1 (rc)

**Steps to reproduce:**
1. Open a table
2. Add a scatter plot
3. Use same categorical column for both colour and markers
4. Hover a category in legend

**Expected results:** colour picker icon should be present, it should be possible to edit colour.
**Actual results:** colour picker icon is not shown, right click also does not open colour picker.
<img width="243" alt="image" src="https://github.com/user-attachments/assets/054b13f4-b3b9-4027-bf5c-e814115548fa">

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16455

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

ok on dev 1.23.0

**Comment by ahadzhanian** [comment]
DG 1.23.0 and 1.22.3
