### ISSUE TITLE
#2966: Box plot: not all data is shown when style is 'violin' (data-specific)

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2966]
v1.20.1

**Steps to reproduce:**
1. Open SPGI
2. Add a box plot
3. Set category: AMES
4. Switch from 'box' to 'violin'

**Expected results:** all data is shown.
**Actual results:** 
![2024-08-06_17-11-06 (1)](https://github.com/user-attachments/assets/ab638522-3a00-4fba-accb-ba864fd10998)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16456
