### ISSUE TITLE
Columns: Implement the functionality to change the style of multiple columns simultaneously

### ISSUE THREAD

**Issue by LaykDimon** [datagrok-ai/public#2968]
https://community.datagrok.ai/t/error-occured-when-dropping-column-with-formating-such-as-change-type/884/6?u=dkovalyov

- [x] reminder: to reply in community when the feature is done

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16461

**Comment by LesiaPavlenko** [comment]
reminder: to reply in community when the feature is done

**Comment by LesiaPavlenko** [comment]
https://community.datagrok.ai/t/error-occured-when-dropping-column-with-formating-such-as-change-type/884/14?u=opavlenko
