### ISSUE TITLE
#2970: Molecule column is missing in exported CSV with options "molecules as smiles" + "selected columns only"

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2970]
v1.20.1 (rc), chem 1.11.1

**Steps to reproduce:**
1. Open SPGI
2. Select a few columns including 'Structure' column
3. Export as CSV with options: "Molecules as SMILES", "Selected columns only"

**Expected results:** all selected columns are exported, 'Structure' column is exported as SMILES.
**Actual results:** 'Structure' column is missing in exported file.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16465

**Comment by LesiaPavlenko** [comment]
fixed. will be included to 1.20.2
