### ISSUE TITLE
#2979: Sunburst is showing default columns instead of selected ones after applying layaout in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2979]
v1.20.1 (rc), charts 1.3.3

**Steps to reproduce:**
1. Open table and apply saved layout from the file: 
[Sunburst example.zip](https://github.com/user-attachments/files/16598961/Sunburst.example.zip)
2. Open properties panel for Sunburst chart

**Expected results:** Sunburst is showing columns selected in its properties panel.
**Actual results:** Sunburst is showing default columns. E.g. on the picture Sunburst is configured with 'heavycnt' and 'hbonddonor', but is showing 'neighbourtype', 'depcatg' and 'annothits' instead.
<img width="878" alt="image" src="https://github.com/user-attachments/assets/be171d9b-dc36-4b67-9750-cdd1e40b8d40">
![2024-08-13_14-51-27 (1)](https://github.com/user-attachments/assets/bb712fdc-e51f-49be-b8e3-8a41af460907)
Issue looks to be data dependant, and usually occurs when Sunburst rendering is very slow. Sometimes correct columns are shown after opening column selector and clicking OK.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16482

**Comment by LesiaPavlenko** [comment]
charts 1.3.4
