### ISSUE TITLE
#2981: Typing calculated formula: input is overwritten unexpectedly in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2981]
v1.20.1, PowerPack 1.1.10

**Case 1: formula input is broken in some cases**
1. Open a table, e.g. SPGI
2. Open calculated columns dialog
3. Type some function with opening bracket, e.g. 'Abs('
4. Enter $ and select a column, e.g. Average Mass
5. Without moving cursor or arrows left/right, continue typing, e.g. -400

**Actual results:** selected column name disappears on typing '-400'. After that typing anything else will just replace the last character in formula string.
![2024-08-13_17-52-57 (1)](https://github.com/user-attachments/assets/9f05804b-0cb2-4b2a-8d26-61b921f516bf)

**Case 2:**
1. Open a table, e.g. SPGI
2. Open calculated columns dialog
3. Type some function and close the brackets, e.g. 'Abs()'
4. Set cursor inside '()', type $ and select a column, e.g. Average Mass
5. Without moving cursor or arrows left/right, continue typing, e.g. 123

**Actual results:** Selected column will be replaced by whatever typed next, if you don't move cursor:
![2024-08-13_17-55-08 (1)](https://github.com/user-attachments/assets/2d6d9d0d-f02e-4619-bb62-2846584cd3cf)

**Expected results:** previous input should not be overwritten unexpectedly. It should be possible to type in a formula by just typing it consecutively.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16483

**Comment by katerina-stepanova** [comment]
v1.20.2, PowerPack 1.1.12

Case 1 is still reproduced on typing e.g. 'Abs(${A' and selecting a column from the dropdown.

**Comment by katerina-stepanova** [comment]
v.1.21.1, PowerPack 1.2.0

Case 2 is still reproduced:
- type Abs()
- put cursor inside brackets
- type '${Av' and select 'Average mass' column
- continue typing without moving the cursor
