### ISSUE TITLE
#2982: Viewers: remove tooltip from the legend

### ISSUE THREAD

**Issue by LesiaPavlenko** [datagrok-ai/public#2982]
- [ ] Viewers: remove tooltip from the legend because it makes it difficult to choose legend and completely covers it in some cases
![Screenshot_79](https://github.com/user-attachments/assets/ba0bc4e6-db71-4ccc-a2d0-0abf82fcac7c)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16484

**Comment by LesiaPavlenko** [comment]
will be added to 1.20.2

**Comment by LesiaPavlenko** [comment]
![Screenshot_80](https://github.com/user-attachments/assets/ba32d6c5-6ece-4232-bb0e-1d0a303aae80)
ok on dev DG

**Comment by LesiaPavlenko** [comment]
1.20.2
