### ISSUE TITLE
#2985: Combined boolean filter cannot be removed from a project

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2985]
v1.20.1

**Steps to reproduce:**
1. Open a table
2. Open filters and add 'combined boolean' filter
3. Save project
4. Open the project again
5. Remove 'combined boolean' filter from the filters
6. Save project
7. Open the project again

**Expected results:** 'combined boolean' filter should not re-appear unexpectedly if it was removed and saved.
**Actual results:** 'combined boolean' filter re-appears. There is no way to remove it from the project once it was added.
![2024-08-14_12-55-08 (2)](https://github.com/user-attachments/assets/88bbd161-bca5-4372-aa4b-2ade35349940)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16488
