### ISSUE TITLE
#2988: Calculated columns dialog: make warnings and error messages more clear and consistent

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2988]
1.20.1, power pack 1.1.10

For example, operations with qnums:
<img width="295" alt="image" src="https://github.com/user-attachments/assets/e78d7858-cbe5-416f-bc9a-5a67532908b1">

It should be clear from the warning message how this issue would affect the calculation result, and how to fix it.

Also, showing warning messages could be more consistent. E.g. if ${Competition assay} *2 is replaced with ${Competition assay} + ${Competition assay} there is no warning, despite the resulting calculated column is exactly same:
<img width="330" alt="image" src="https://github.com/user-attachments/assets/d061c30c-81b4-4f19-b226-207717766d69">

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16494

**Comment by LesiaPavlenko** [comment]
PowerPack v.1.1.13
