### ISSUE TITLE
#2992: Sunburst does not select/filter on empty category

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2992]
v1.20.1, charts 1.3.3

**Steps to reproduce:**
1. Open a table, e.g. SPGI
2. Add Sunburst
3. Configure Sunburst with categorical column, having some nulls, e.g. 'Sampling Time' in SPGI
4. Click empty category on the Sunburst.

**Expected results:** clicking on empty category should behave the same as clicking on any other category: filter or select respective rows (depending on selected setting).
**Actual results:** nothing happens on clicking on empty category.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16499
