### ISSUE TITLE
#2993: Cannot type in any input after adding a calculated column

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2993]
v1.20.1, power pack 1.1.10

**Steps to reproduce:**
1. Open a table
2. Add a calculated column
3. Add one more calculated column
4. Try to type in any input (e.g. search in Order and hide columns, search in proiperties panel, edit a value in the table etc.)

**Expected results:** adding a calculated column should not break typing in other inputs.
**Actual results:** nothing happens on typing in any other input.
![2024-08-20_11-50-55 (1)](https://github.com/user-attachments/assets/c35b3928-c6bf-4f14-96c1-79db4b8009fa)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16500

**Comment by LesiaPavlenko** [comment]
PowerPack v.1.1.11
