### ISSUE TITLE
#2995: Tools: use decorators in typescript template

### ISSUE THREAD

**Issue by santee** [datagrok-ai/public#2995]
Use decorators on create/add actions in datagrok tools instead of comments

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16507

**Comment by santee** [comment]
`grok create` still creates
```typescript
/* Do not change these import lines to match external modules in webpack configuration */
import * as grok from 'datagrok-api/grok';
import * as ui from 'datagrok-api/ui';
import * as DG from 'datagrok-api/dg';

export const _package = new DG.Package();

//name: info
export function info() {
  grok.shell.info(_package.webRoot);
}
```

Besides, please confirm that viewer class disposes of subscriptions created in `onTableAttached`

Things like `grok add function helloworld` do not use decorators.
