### ISSUE TITLE
#2997: Tools: add questionnaire on package creation

### ISSUE THREAD

**Issue by santee** [datagrok-ai/public#2997]
The usual user experience while creating a new package is ask different questions like 'do you want to use eslint?'.

So, we'd want to keep all the existing flags in order not to break things for users, add a --silent flag for people who do not want interactive mode, and ask questions for flags not being specified. So, if one says --eslint - do not ask a question, just use it, otherwise, ask it.

**Comment by santee** [comment]
Also, package/folder name should be a question as well. Option chosen by default should 'create  <package_name> folder'.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16509

**Comment by santee** [comment]
Suggest to use https://www.npmjs.com/package/prompts

**Comment by skalkin** [comment]
I don't think we need these options. Why not just use eslint always?

**Comment by skalkin** [comment]
Closing this as not important. Feel free to reopen
