### ISSUE TITLE
#3002: Tools: local installation behaviour should be preferred and normalized

### ISSUE THREAD

**Issue by santee** [datagrok-ai/public#3002]
Ideally, it should be possible to run `npx datagrok-tools create` instead of installation it globally. This command doesn't work at the moment (one needs to do `npm -p datagrok-tools grok create` because there is no script with 'datagrok-tools' name. Needs to be fixed and help should be updated to give that option by default.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16514
