### ISSUE TITLE
#3004: Two tables with molecules: scaffold tree is based on wrong table by default in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3004]
1.18.+, 1.20.+
chem 1.9.2, 1.11.3

**Steps to reproduce:**
1. Open a table with molecules (table1)
2. Open another table with molecules without closing the 1st one (table2)
3. Open scaffold tree while from table2

**Expected results:** scaffold tree should be based on current table be default, same as for other viewers (i.e. scaffold tree opened from table2 should be based on table2 by default).
**Actual results:** scaffold tree opened from table2 is based on table1 by default:
![2024-08-22_18-30-40 (1)](https://github.com/user-attachments/assets/71e86b0a-74a9-40d8-8348-a8625cbf9fea)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16517
