### ISSUE TITLE
#3006: Calculated columns: changing return type triggers column reordering

### ISSUE THREAD

**Issue by ptosco** [datagrok-ai/public#3006]
To reproduce:

1. Open any CSV in native DG
2. Add a calculated `test` column which simply returns `1`
3. Reorder columns such that the `test` column is on the right of the `Structure` column
4. Open the dev console
5. Update the formula such that it returns `2` as follows:
```
table = grok.shell.tableByName('SPGI_10_rows')
testCol = table.getCol('test')
await testCol.applyFormula('2', 'int')
```
6. The column now shows `2` in all rows and has not moved
7. Update the formula such that it returns `a` as follows:
```
await testCol.applyFormula('a', 'string')
```
8. The column has moved to the bottom of the table: this should not happen

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16521

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

PowerPack > v.1.1.14
