### ISSUE TITLE
#3007: Qualifier function is missing from math functions and from hints

### ISSUE THREAD

**Issue by ptosco** [datagrok-ai/public#3007]
To reproduce:
1. Load the attached [qnum.csv](https://github.com/user-attachments/files/16759605/qnum.csv) into native DG
2. Add New Column
3. Select math functions: `Qualifier` function is missing
4. Type `q` in the calculated column field: `Qualifier` function hint does not show up
5. Type `Qualifier(${IC50 (uM)})`
6. The qualifier shows up as expected, so the function indeed exists.
7. Edit the formula into `Qualifier(${IC50 (uM)}, 2)`: DG actually seems to know about the function, a now it prints a red warning message: `Qualifier 1 input parameters, 2 passed`

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16522

**Comment by MariaDolotova** [comment]
Hi @ptosco ! That's strange that you do not get the Qualifier function in the list. Please see the gif below - it is exists both in the list of math functions and in the autocompletion hints. I guess, I will need more details on that issue. Are you running in native Datagrok? Which version of PowerPack are you using?
![qualifier_function](https://github.com/user-attachments/assets/8f9fbfed-ca1a-4174-a0ea-dd13903e1325)

**Comment by ptosco** [comment]
@MariaDolotova `1.1.12`

**Comment by LesiaPavlenko** [comment]
can`t reproduce on PowerPack > v.1.1.14
