### ISSUE TITLE
#3008: Qnum function is missing from hints

### ISSUE THREAD

**Issue by ptosco** [datagrok-ai/public#3008]
To reproduce:
1. Load [qnum.csv](https://github.com/user-attachments/files/16759797/qnum.csv) into native DG
2. Add New Column
3. Type q: `Qnum` function is missing from hints, though it shows up in the math function help text
4. Type `qnum(1, '>')`: the function exists and it provides expected output
5. Type `qnum(1, '>'), 0`: a warning correctly appears `Qnum 2 input parameters, 3 passed`, so DG actually knows the function signature, but it does not show up in hints

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16524

**Comment by MariaDolotova** [comment]
Fixed, will be in PowerPack version 1.1.14
