### ISSUE TITLE
#3009: Calculated column hints break with round bracket + curly bracket

### ISSUE THREAD

**Issue by ptosco** [datagrok-ai/public#3009]
1. Load [qnum.csv](https://github.com/user-attachments/files/16759988/qnum.csv) into  native DG
2. Open browser dev console
3. From the menu, pick Edit->Add New Column
6. Call the column `test`
7. Start typing `if(${I`, then pick the `Id` hint: the dev console fills with errors:
![image](https://github.com/user-attachments/assets/5c01a134-9ae3-4977-ae9b-0ee21c355a37)
8. Now type comma, and then space: when you hit space, the `${Id}` parameter disappears (see #2981)
9. From this point, it is impossible to type anything unless you reposition the cursor after each keystroke.

The only way to recover is to cancel the dialog and restart from scratch _without_ adding the curly bracket after the `$`.

Note that the trigger of the bug is the presence of an open round bracket _and_ an open curly bracket.
The open round bracket alone does not cause problems if `$` is not followed by open curly bracket.
Similarly, the open curly bracket after `$` does not cause problems unless it is preceded by an open round bracket.

It looks like the problem lies in the bookkeeping of brackets, as in #2981.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16525

**Comment by MariaDolotova** [comment]
Fixed in PowerPack 1.1.13

**Comment by LesiaPavlenko** [comment]
v. 1.21.1
PowerPack v.1.2.0
