### ISSUE TITLE
#3015: Trellis plot is not re-rendered on changing settings when there is no data to display after settings change

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3015]
v1.20.2

**Steps to reproduce:**
1. Open SPGI
2. Add a Trellis plot
3. Remove Y column and set 'Lab notebook' as X
4. Set 'Chemist' as inner Pie chart category and uncheck 'include nulls' >> there is nothing displayed (expected)
5. Switch to some other inner viewer type, e.g. Box plot >> some data is displayed
6. Switch back to Pie chart

**Expected results:** Trellis plot should be re-rendered on switching between inner viewer types or changing some properties.
**Actual results:** Trellis plot is not re-rendered, wrong data is displayed.
Trellis is also not re-rendered when inner Pie charts properties are updated.
![2024-08-29_12-56-15 (1)](https://github.com/user-attachments/assets/ef251a66-3e36-4017-bb59-f7bb6a6b26bf)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16535

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

ok on dev 1.22.0
