### ISSUE TITLE
#3026: Viewers: Scatterplot: label placement improvements

### ISSUE THREAD

**Issue by andrew-golovko-datagrok** [datagrok-ai/public#3026]
#### Provide advanced label placement for scatterplot labels:

+ Use multiple columns as labels
+ **"Show Labels Mode"** **Auto** option:
  + Display only labels that have enough free space around, join each with its marker in case the label is too far
  + Selecting **"Labels"** -> **"Show Marker Labels"**,  place as many labels as possible by default if **"Labels"** -> **"Show Labels For"** property is set as **"all'** or **"filtered"**
  + If **"Show Labels For"** property is set as **selected**, **selected or current**, **filtered selected**:
    + Simple text or image if there's enough space for each label (it doesn't overlap at least one marker)
    + Display text inside block with an outline and background coior otherwise
    + Drag'n'drop ability for labels

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16630
