### ISSUE TITLE
#3027: Cannot copy text from any input in filters panel

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3027]
v1.20.2

**Steps to reproduce:**
1. Open a table
2. Open filters
3. Try to select and copy (Ctrl-C or Cmd-C) text from some input field, e.g. from search input of categorical filter, range inputs of numerical or date filters, value input of expression filter.

**Expected results:** selected text should be copied. Or at least there should be a way to make it work in a custom filter (our use case for copying something from filters inputs).

**Actual results:** selected text is not copied. In some cases png image of filters panel is produced instead.
Issue can be also reproduced for custom filters.
Note: 'cut' (Ctrl-X/Cmd-X) is working as expected for selected text.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16640
