### ISSUE TITLE
#3033: Line chart: viewer has 'Marker size' option, but it cannot be changed

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3033]
- [ ] Make it work same way as in the scatterplot - if value = null (make the field nullable) - allow the autoLayout to calculate the marker size, if not - use the user-defined value

v1.20.2

**Steps to reproduce:**
1. Open a table
2. Add line chart
3. Change marker size: from the context menu or from the properties panel

**Expected results:** all options present in menu (context menu or properties panel) should work as expected. If an option is not supported for this type of viewer, it should be removed.
**Actual results:** Marker size option is present, but adjusting it won't change the actual size of markers.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16647

**Comment by LaykDimon** [comment]
Make it work same way as in the scatterplot - if value = null (make the field nullable) - allow the `autoLayout` to calculate the marker size, if not - use the user-defined value

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

ok on dev 1.23.0
