### ISSUE TITLE
#3034: Trellis plot with scatter plots: marker size is not changed when context menu is used

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3034]
v1.20.2

**Steps to reproduce:**
1. Open a table
2. Add Trellis plot
3. Switch to scatter plots as inner viewers
4. Right click > scatter plot> markers
5. Change markers size

**Expected results:** markers size should be changed.
**Actual results:** markers size is not updated when using the context menu.
Note: markers size can be changed through properties panel.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16648

**Comment by LesiaPavlenko** [comment]
markers size is changing

dev 1.22.0
![Screenshot_31](https://github.com/user-attachments/assets/dece26f9-d6f2-4881-9ea4-ca2ae7644b32)
