### ISSUE TITLE
Scatter plot: labels are not displayed if structure column is used as label

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3041]
v1.21.1

**Steps to reproduce:**
1. Open SPGI
2. Add a scatter plot
3. Set some column with structures as label

E.g. 'Stereo category' on X, 'Chemist521' on Y, 'Core' as label.

**Expected results:** structure labels are displayed.
**Actual results:** no labels displayed:
<img width="807" alt="image" src="https://github.com/user-attachments/assets/d9e060c5-a193-43b8-853b-eb43f140aeac">

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16652
