### ISSUE TITLE
#3043: Adding heatmap resets colour coding previously set in the table

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3043]
v1.20.2, 1.21.1

**Case 1: newly added colouring**
1. Open a table, e.g. SPGI
2. Set up some colouring on a few columns: categorical colouring, conditional colouring, linear colouring
3. Add a heatmap to the current view
**Actual results:** colouring in the table disappears.

**Case 2: saved colouring**
1. Open a table, e.g. SPGI
2. Apply a layout that includes custom colouring for a few columns
3. Add a heatmap
**Actual results:** custom colouring is reset to default linear colouring for numerical columns.

**Expected results:** Adding a heatmap should not alter any colouring previously set in the table (either newly set or loaded with the layout).

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16659

**Comment by dnillovna** [comment]
> Andrew Skalkin commented in Jira:

Fixed it -@Olesia Pavlenko, please double-check how color coding works especially when the heat map is involved

**Comment by LesiaPavlenko** [comment]
1.23.0

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

**Case 1:**dev: coloring in the table is present after adding Heatmap**Case 2**: custom coloring is not resetting to default linear coloring for numerical columnsAdding a heatmap does not alter any coloring previously set in the table (either newly set or loaded with the layout).
