### ISSUE TITLE
#3052: A few seconds delay on creating a screenshot of a viewer

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3052]
- [x] press ctrl c - lets show the balloon with information

v1.20.2, 1.21.1

**Steps to reproduce:**
1. Open a table
2. Add some viewer, e.g. a scatter plot
3. Click the viewer
4. Press Ctrl/Cmd-C

**Expected results:** viewer screenshot should be created almost immediately and green message should appear as soon as screenshot is made.
**Actual results:** There is a few seconds (5-7) delay before the screenshot is created and a message is shown.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16668
