### ISSUE TITLE
#3055: Page is freezing after applying layout with multiple scaffold trees with large number of structures (data-specific)

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3055]
v1.20.2

**Steps to reproduce:**
1. Open a table having some structures
2. Apply a layout with 5-6 scaffold tree viewers with multiple structures
3. Wait until scaffold tree hits start calculating
4. Hover something (e.g. a scatter plot) or scroll the table etc. to check if the page is responding.

Issue is probably data-specific.
I was able to somewhat reproduce the issue in native grok for the following table and layout:
[PubChemMol.zip](https://github.com/user-attachments/files/16995936/PubChemMol.zip)

**Expected results:** page does not freeze and is responsive. No performance issues.
**Actual results:** page is responding at first on applying layout. But after some time page gets frozen for a while. When page is un-frozen, it is still somewhat lagging.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16670
