### ISSUE TITLE
#3059: Filtering is unexpectedly saved in the layout after resetting in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3059]
v.1.20.2, 1.21.1

**Steps to reproduce:**
1. Open a table
2. Open filters
3. Add some categorical column to filters
4. Search in filters for some value and apply filtering
5. Reset all filters
6. Download layout
7. Re-apply layout

**Expected results:** no filtering when layout is re-applied (because filter was reset before downloading it). It might be better to reset search input too on resetting filters.
**Actual results:** table is filtered after reapplying layout.
![2024-09-16_13-40-42 (1)](https://github.com/user-attachments/assets/c8565716-ed35-4531-8e76-e0a258eea1ba)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16677

**Comment by LesiaPavlenko** [comment]
1,22,0
