### ISSUE TITLE
#3063: JS API: Add capability to add color palettes to configs

### ISSUE THREAD

**Issue by LaykDimon** [datagrok-ai/public#3063]

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16686

**Comment by LaykDimon** [comment]
DG.Color.categoricalPalettes['New color palette'] = [DG.Color.black, DG.Color.cyan, DG.Color.currentRow, DG.Color.green, DG.Color.darkGreen, DG.Color.yellow];
