### ISSUE TITLE
#3065: Box plot: colour is changed on highlighting

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3065]
v1.20.2, 1.21.1

**Steps to reproduce:**
1. Open a table
2. Add a box plot
3. Set up box plot colouring
4. Hover some row group (e.g. hover an entry in filters, or bar on a bar chart)
5. Check colours in the box plot

**Expected results:** colours in the box plot are not changed on highlighting.
**Actual results:** colour is changed to default linear for a hovered group on the box plot:
![2024-09-18_10-59-16 (1)](https://github.com/user-attachments/assets/aed00d8b-eb78-4e35-b8cf-2877e9bac94a)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16691
