### ISSUE TITLE
#3066: Box plot: selection is not shown in the box plot when non-default or conditional colouring is applied

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3066]
v1.20.2, 1.21.1

**Steps to reproduce:**
1. Open a table
2. Add a box plot
3. Colour box plot with one of the following options:
- use column with conditional colouring
- use column with non-default linear colouring
- use column with non-default categorical colouring
4. Select some rows
5. Check if selected rows are highlighted on the box plot

**Expected results:** box plot should show which rows are selected.
**Actual results:** selected rows are not highlighted with orange on the box plot.
![2024-09-18_11-32-01 (1)](https://github.com/user-attachments/assets/83b1f7b8-ff4f-481a-a3d5-8b79ff4569d6)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16692
