### ISSUE TITLE
#3067: Trellis plot with scatter plot: dots with empty marker value are not shown

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3067]
v1.20.2,1.21.1

**Steps to reproduce:**
1. Open SPGI
2. Add a Trellis plot
3. Switch it to scatter plot as an inner viewer
4. Trellis: Series as Y, Has unlabeled R-groups as X
5. Inner scatter plot: leave default columns
6. Inner scatter plot: select R101 as Markers

**Expected results:** all dots are shown on the inner plots. Dots with empty R101 value should be visible and should have shape shown in the legend.
**Actual results:** dots with empty R101 value are not shown:
![2024-09-18_13-56-15 (1)](https://github.com/user-attachments/assets/f4c57ff9-7d48-47e6-ae88-b6357b4bf2b8)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16694
