### ISSUE TITLE
#3072: Filter panel does not reflect current filtering after using 'selection to filter' option

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3072]
v1.20.2, 1.21.1

**Steps to reproduce:**
1. Open SPGI
2. Open filters
3. Add 'Stereo category' to filters
4. Select & filter on one of the categories, e.g. R_ONE
5. Select > Invert
6. Select > Selection to filter

**Expected results:** After applying 'Selection to filter' all categories except for R_ONE are shown. This should be reflected in filters panel.
**Actual results:** R_ONE is still selected in filters panel, though it is filtered out completely actually.
![2024-09-20_13-59-07 (1)](https://github.com/user-attachments/assets/fc9cf20a-52f7-49dd-8964-2291c62215c2)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16713

**Comment by LesiaPavlenko** [comment]
is not a bug. the expected result is wrong
