### ISSUE TITLE
#3076: Scatterplot: Add coloring via expressions

### ISSUE THREAD

**Issue by LaykDimon** [datagrok-ai/public#3076]
add a little plus with a tooltip above the color column combo box
here we will call "Add new column", add it, and then use this column in the column combo box with others

- [ ] Add more color customization options for created column data.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16722

**Comment by LesiaPavlenko** [comment]
updated with 

- [ ] Add more color customization options for created column data.

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

[file id="3c49ff6f-9ae8-4590-bbd2-02a9b7373e73"]

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

https://reddata.atlassian.net/browse/GROK-16804

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

ok on 1.22.0+
