### ISSUE TITLE
#3086: Scatter plot: setting structure as label for selected/current/filtered/etc. rows makes all scatter plot markers too large

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3086]
v1.21.1

**Steps to reproduce:**
1. Open SPGI
2. Add a scatter plot
3. Configure labels: use Structure column, show labels: always, show labels for: any option except 'all'
UPD: Show labels for: current row
4. Make sure some of the labels are displayed (e.g. select some rows if labels are shown for selected rows)

**Expected results:** Scatter plot markers that currently do not show structure label should be normal size.
**Actual results:** All scatter plot markers are made large, not only ones with label displayed:
<img width="886" alt="image" src="https://github.com/user-attachments/assets/b6e5e1c2-e21f-4a73-a242-7ffa018909e0">

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16754

**Comment by LesiaPavlenko** [comment]
1.22.0
