### ISSUE TITLE
#3088: Scatter plot: structure in label is not centered (could be specific to MacOS, or some specific screen settings)

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3088]
v1.21.1

**Steps to reproduce:**
1. Open SPGI
2. Add a scatter plot
3. Set structure column as label
4. Check how structure labels are displayed

**Expected results:** structure is centered in the label circle, structure is not cropped
**Actual results:** structure is not displayed in the center of the circle, it is partly cropped:
<img width="443" alt="image" src="https://github.com/user-attachments/assets/0ba4ef22-9bed-4b64-90d2-0bd18df07a15">

This issue could be specific either to MacOS, or specific screen DPI settings.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16755
