### ISSUE TITLE
Chem: Mini research about similarity metrics 

### ISSUE THREAD

**Issue by nuradilK** [datagrok-ai/public#309]
Here are what I found during my research about similarity metrics.

Dice - used in statistics to gauge similarity of two samples doi: 10.1016/S1076-6332(03)00671-8
Cosine - finds cosine angle between two vectors, which is very popular
Kulczynski similarity index - the proposed method support comparison with multiple ground truth segmentations and   takes into account the irregularity of meshes
Asymmetric - asymmetric similarity (aka The Tversky index) measure on sets that compares a variant to a prototype.  The Tversky index can be seen as a generalization of the Dice coefficient and the Tanimoto coefficient (aka Jaccard index).
 
SIde note, RDKIT can calculate the following similarity models: Tanimoto, Dice, Cosine, Sokal, Russel, Kulczynski, McConnaughey, and Tversky. 

In the paper "A comparison of 71 binary similarity coefficients: The effect of base rates" by Brusco. M. et all, the authors clustered binary similarity metrics by how they are affected by the base rates (percentage of ones). 
![journal pone 0247751 t003](https://user-images.githubusercontent.com/26120466/151978782-7b805175-1eb7-4704-8c3c-6eb541a1eaac.PNG)
Source - https://doi.org/10.1371/journal.pone.0247751

In the paper "A generalizable definition of chemical similarity for read-across" by Floris. M. et all, the authors report comparison of multiple combinations of binary fingerprints and similarity metrics for computing the chemical similarity in the context of two different applications of the read-across technique. They came up with the top 10 results for fingerprints/similarity metrics combinations.
![image](https://user-images.githubusercontent.com/26120466/151980423-bdd982a2-2a3c-4c72-8a98-acf95f09ec4d.png)
"The best coefficients found in combination with the fingerprints are 37 (Maxwell-Pilliner), 34 (Cohen), 18 (Rogot-Goldberg), 42 (CT4), 13 (Sokal-Sneath), 1 (simple matching)"
Source - doi:10.1186/s13321-014-0039-1

**Comment by StLeonidas** [comment]
@MariaDolotova , should we consider it closed
