### ISSUE TITLE
Charts: Sunburst usability improvements

### ISSUE THREAD

**Issue by LesiaPavlenko** [datagrok-ai/public#3090]
Sunburst usability improvements:

- [x] reduce free space around (comparing with e.g. Pie Chart)
- [x] sorting is not reflected on the fly
![Screenshot_54](https://github.com/user-attachments/assets/4277b06d-e7c2-4e69-8c6c-a99925cb7d26)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16758
