### ISSUE TITLE
#3091: Scatterplot: show a more detailed message for a missing column

### ISSUE THREAD

**Issue by LesiaPavlenko** [datagrok-ai/public#3091]
- [x] show a more detailed message for a missing column in Scatterplot (like it works for Line charts)

![Screenshot_55](https://github.com/user-attachments/assets/1433fe53-a1d8-4d0c-acd6-9188afac73c9)

**Comment by katerina-stepanova** [comment]
**Steps to reproduce:**
1. Open SPGI
2. Add a scatter plot: CAST Idea ID on X, Chemical space Y on Y axis
3. Switch both axes to log scale (negative values are hidden on Y)
4. Download layout
5. Remove CAST Idea ID column
6. Re-apply downloaded layout

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

ok on dev 1.23.0
