### ISSUE TITLE
#3095: Wrong columns are exported with 'Visible columns only' option if there are multiple views for the table

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3095]
v 1.20.2, 1.21.1

**Steps to reproduce:**
1. Open a table and two views
2. View 1: make only column A visible
3. View 2: make only column B visible
4. While View 2 is open, export table with 'visible columns only' option

**Expected results:** exported file contains only column B
**Actual results:** exported file contains only column A, i.e. visible columns from View 1 (instead of View 2) were exported.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16764
