### ISSUE TITLE
#3101: Shift-click selects unexpected rows in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3101]
v1.20.3, 1.21.1

**Steps to reproduce:**
1. Open a table, e.g. SPGI
2. Enable sorting by one of the columns
3. Ctrl-click a couple of rows > correct rows are selected
4. Press Esc key > selection is removed
5. Shift click some rows

**Expected results:** no unexpected rows selected. Shift click should select rows between the clicked one and current one or previously selected one.
**Actual results:** additional rows in a completely different part of the table are selected unexpectedly:
![2024-10-11_15-01-38 (1)](https://github.com/user-attachments/assets/dec5d945-ae5a-4142-a371-4a76dcc2d7ea)
![2024-10-11_15-03-07 (1)](https://github.com/user-attachments/assets/8e10a6a1-4d31-4b18-93bf-09b6c390d6e0)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16793

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

3887237ba1925f9c4452e8b8870ea93614b24f6e- fixesGROK-16793: Shift-click selects unexpected rows in some cases andGROK-16816: Grid: Incorrect selection on grid with filtering/sorting enabledok on release 1.22.1
