### ISSUE TITLE
#3107: Grid: Incorrect selection on grid with filtering/sorting enabled

### ISSUE THREAD

**Issue by LesiaPavlenko** [datagrok-ai/public#3107]

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16816

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

3887237ba1925f9c4452e8b8870ea93614b24f6e- fixesGROK-16793: Shift-click selects unexpected rows in some cases andGROK-16816: Grid: Incorrect selection on grid with filtering/sorting enabledok on release 1.22.1
