### ISSUE TITLE
Add new columns: formula with multi-argument functions is parsed incorrectly if more than one argument contains a column

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3119]
v1.22.0

**Steps to reproduce:**
1. Open a table
2. Add a calculated column with if function, where 2nd or 3rd argument contains a column name, e.g. if(${Stereo Category}=='R_ONE',43, ${Cellular assay 1})

Same issue can be reproduced with **any** function that has more than one argument when at least two arguments contain columns:
${Chemical Space X} + ${Chemical Space X}
Contains(${Scaffold Names}, ${Primary Scaffold Name})
Div(${Average Mass}, ${Chemical Space X})
etc.

**Expected results:** formula is parsed correctly and values are displayed in a calculated column.
**Actual results:** formula is parsed incorrectly, all values are null:
<img width="673" alt="image" src="https://github.com/user-attachments/assets/2da04150-5288-40dc-ab2d-840f8bdf3b44">

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16942

**Comment by dnillovna** [comment]
> Andrew Skalkin commented in Jira:

Let’s make sure we have tests that cover it. This is a pretty big bug.
