### ISSUE TITLE
#3120: Viewers: Scatter plot: cannot drag label if Mouse Drag = Select

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3120]
v1.22

**Steps to reproduce:**
1. Add a scatter plot
2. Set up showing labels (e.g. for selected rows)
3. Set option Mouse Drag = Select
4. Drag some label

**Expected results:** label should be draggable, Mouse Drag option should not affect this.
**Actual results:** label is not draggable when Mouse Drag = Select.
Label is draggable when Mouse Drag = Pan.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16948

**Comment by katerina-stepanova** [comment]
v1.22.1

Label is not draggable if Show Labels For = Selected, Show labels mode = all.
Also labels are not draggable if Show Labels For = Current row.
