### ISSUE TITLE
#3123: Scatter plot: not all formula lines are shown in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3123]
v1.20, 1.22

**Steps to reproduce:**
1. Add a scatter plot
2. Add 8-10 formula lines or bands
3. Click OK to save
4. Re-open formula lines dialog
5. Uncheck a few lines/bands and click OK to save
6. Re-open formula lines dialog again
7. Check all the checkboxes

**Expected results:** all lines/bands should be shown when all checkboxes are selected.
**Actual results:** some checkboxes are unchecked and respective line is not shown.
![2024-10-29_18-59-39 (1)](https://github.com/user-attachments/assets/c12db186-ef93-407d-8bd8-2a673c9a8275)
Also in some cases a line is selected, but not displayed.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16965

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

ok on dev 1.23.0 + Power Pack 1.2.4
