### ISSUE TITLE
#3125: BiostructureViewer doesn't open files

### ISSUE THREAD

**Issue by tcarolan** [datagrok-ai/public#3125]
BiostructureViewer does not open files after upgrade to 1.21.3, Biostructure plugin 1.2.1. If the structure is embedded into a CSV, it still works. But selecting a random PDB file does not trigger drawing.  Please see screenshot video for behavior. 

![mstsc_eYBUqpC0LY](https://github.com/user-attachments/assets/ca3644ec-cc76-4497-9bf9-435e04cd4581)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16968

**Comment by LaykDimon** [comment]
fixed in BiostructureViewer package version 1.2.2
