### ISSUE TITLE
#3126: URLs don't link correctly

### ISSUE THREAD

**Issue by tcarolan** [datagrok-ai/public#3126]
Depending on the width of a semantic type URL column, the rendered link will change and be incorrect. Please see video screenshot for behavior. 

![mstsc_J46AD8ZfDZ](https://github.com/user-attachments/assets/d1787db5-ab19-45a3-8c38-416ccf3bc81d)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16969

**Comment by LaykDimon** [comment]
fixed in DG v1.22.0 (also in 1.21.4)
