### ISSUE TITLE
#3132: Cannot change more than one colour using the viewer's legend

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3132]
v1.22

**Steps to reproduce:**
1. Open a table
2. Add a viewer with legend that allows to change colour through legend (scatter plot or box plot with colouring, bar chart with stack, pie chart etc.)
3. Change one colour through legend
4. Change another colour through legend

**Expected results:** both colours are changed.
**Actual results:** the first changed colour is reset to default when the second one is changed:
![2024-11-01_12-58-31 (1)](https://github.com/user-attachments/assets/dfbeba29-2ee2-4106-bf0b-25a9512831b1)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16975

**Comment by LesiaPavlenko** [comment]
already fixed in 1.22.1
