### ISSUE TITLE
#3133: Grid: Right arrow on changing column position with drag-and-drop is not working if there is not panel/viewer at the right side

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3133]
v1.20.x, 1.22

**Steps to reproduce:**
1. Open a table
2. Make sure there are no viewers on the right side, close context panel or any other panels if open
3. Drag some column by header to the right
4. Drag it over the right arrow to scroll table horizontally while dragging

**Expected results:** table should be scrolled to the right.
**Actual results:** nothing happens.
![2024-11-01_16-56-09 (1)](https://github.com/user-attachments/assets/0e15844e-2600-43a2-a518-e3ebca14d1f8)

Note: there is no issue with the left arrow, also right arrow is working fine if there is a viewer or panel at the right side.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16980

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

ok on dev 1.23.0+

**Comment by ahadzhanian** [comment]
DG 1.22.3 and 1.23.0
