### ISSUE TITLE
#3142: Viewers: Scatter plot: add ability to define columns for scatter plot whiskers

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3142]
Add ability to define columns for scatter plot whiskers, e.g. to show StdDev

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16994

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

testing data[file id="31e71600-beef-46b3-864d-a6e8abc8fa43"]
[file id="81df9f91-8afa-4f11-8a73-49d8646e5ec5"]

**Comment by andrew-golovko-datagrok** [comment]
After some further discussions priority for range column has been changed so that if at least one (any) min or max column is defined, then a corresponding whiskers side is displayed, In case neither min nor max column is selected, a range whiskers column is applied (if it's defined).

**Comment by andrew-golovko-datagrok** [comment]
Based on newer request (Scatter plot whiskers: enhance auto-populate logic [#3465](https://github.com/datagrok-ai/public/issues/3465)), now it works the way if the table contains columns that are identified as whiskers column by their name - they should be populated in the dropdowns no matter what set of them we have.
