### ISSUE TITLE
#3144: Viewers: Scatterplot: add the ability to defile column

### ISSUE THREAD

**Issue by LesiaPavlenko** [datagrok-ai/public#3144]
![Screenshot_80](https://github.com/user-attachments/assets/803733a6-c458-4c61-ab6e-319e2a6f7453)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16996

**Comment by LesiaPavlenko** [comment]
3142 duplicate

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

Viewers: Scatter plot: add ability to define columns for scatter plot whiskers
