### ISSUE TITLE
#3145: Viewers: Scatter plot: label can be dragged out of scatter plot area and completely hidden

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3145]
v 1.22.1

**Steps to reproduce:**
1. Open a table
2. Add a scatter plot
3. Configure showing labels (e.g. select a couple of columns for label, including some structure)
4. Make sure there is at least one label shown
5. Drag label out of the scatter plot

**Expected results:** it should not be possible to drag label so that it is hidden completely, small part of it should be visible allowing to drag it back.
**Actual results:** label can be dragged out of scatter plot area, so that it is hidden completely and cannot be dragged back. Mouse cursor is in dragging state (shown as hand) when over this scatter plot after this.
![2024-11-06_12-19-00 (1)](https://github.com/user-attachments/assets/7e5fd4ce-2d76-4ba6-a31e-c910b323be9e)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16997

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

ok on dev 1.23.0 and release 1.22.2
