### ISSUE TITLE
#3146: Add new columns: Error on calculated columns validation if a complex formula is pasted

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3146]
v1.22.1, PowerPack 1.2.2

**Steps to reproduce:**
1. Open SPGI
2. Open Add column dialog
3. Paste a complex formula containing multiple columns, e.g.
```if(${Whole blood assay 1} != null, ${Whole blood assay 1}, if(${Route Admin}=="PO", ${Whole blood assay 1} / ${Chemical Space X} * 100 / 6 / ${Average Mass} * 1000000.0,null))/if(Contains(${Species}, 'Rat') || Contains(${Species}, 'Rat Legacy'), 80, if(Contains(${Species}, 'Mouse'), 125, if(${Species}=="Dog", 30.9, if(${Species}=="Monkey", 43.6, if(${Species}=="Minipig", 39, null)))))*100```

**Expected results:** formula should be validated and columns used should be highlighted. Warning message should be shown if there are any errors.
**Actual results:** Formula is not validated. Error:
```
 TypeError: Cannot read properties of undefined (reading 'to')
 Stack trace 69dRe
	webpack://powerpack/src/dialogs/add-new-column.ts 611:67                 to
	webpack://powerpack/src/dialogs/add-new-column.ts 497:47                 getColumnNamesAndSelections
	webpack://powerpack/src/dialogs/add-new-column.ts 477:65                 <fn>
	webpack://powerpack/node_modules/@codemirror/view/dist/index.js 7535:21  listener
	webpack://powerpack/node_modules/@codemirror/view/dist/index.js 7415:28  update
	webpack://powerpack/node_modules/@codemirror/view/dist/index.js 7439:14  dispatchTransactions
	webpack://powerpack/node_modules/@codemirror/view/dist/index.js 4580:10  dispatch
	webpack://powerpack/node_modules/@codemirror/view/dist/index.js 4805:9   doPaste
	webpack://powerpack/node_modules/@codemirror/view/dist/index.js 4208:21  handler
	webpack://powerpack/node_modules/@codemirror/view/dist/index.js 4198:14  runHandlers
	```

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-17004

**Comment by LesiaPavlenko** [comment]
Power Pack 1.2.3

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

formula is validated and columns used are highlighted.
[file id="c8918260-b7a6-4725-a134-5044ef029f1f"]

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

Power Pack 1.2.3
