### ISSUE TITLE
#3147: Add new columns: Columns are not calculated for some formulae inside if clause

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3147]
v1.22.1, PowerPack 1.2.2

**Steps to reproduce:**
1. Open SPGI
2. Add a calculated column with formula like following:
Sigmoid-like: if(${Average Mass} == null, 0.5,(1-0)/(1+Exp(-2.5580*(${Average Mass}-3.100000)))+0)
Or even a simpler one: if(${Average Mass} == null, 0.5,${Average Mass}/4)

**Expected results:** a new column should have values, its type should be double.
**Actual results:** all values are null, error:
`logger.ts:108 
 Unknown column type: 'num'
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1772:17      wrapException
	packages/ddt/src/utils/utils.dart 1086:8                               __col
	packages/ddt/src/data_frame/column.dart 120:70                         Column.fromType
	packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 213:19     _wrapJsFunctionForAsync
	packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 237:5      _wrapJsFunctionForAsync.<anonymous function>
	packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 187:19     _awaitOnObject.<anonymous function>
	packages/$sdk/lib/async/zone.dart 1128:37                              _rootRunUnary
	packages/$sdk/lib/async/zone.dart 1012:12                              _CustomZone.runUnary
	packages/$sdk/lib/async/future_impl.dart 129:12                        _FutureListener.handleValue
	packages/$sdk/lib/async/future_impl.dart 665:13                        _Future._propagateToListeners
	packages/$sdk/lib/async/future_impl.dart 468:7                         _Future._complete
	packages/$sdk/lib/async/future_impl.dart 51:5                          _SyncCompleter.complete
	packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 164:3      _asyncReturn
	packages/ddt/src/func/func_call.dart 323:15                            FuncCall.resolveGenericCallFunctions
	packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 213:19     _wrapJsFunctionForAsync
	packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 237:5      _wrapJsFunctionForAsync.<anonymous function>
	packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 187:19     _awaitOnObject.<anonymous function>
	packages/$sdk/lib/async/zone.dart 1128:37                              _rootRunUnary
	packages/$sdk/lib/async/zone.dart 1012:12                              _CustomZone.runUnary
	packages/$sdk/lib/async/future_impl.dart 129:12                        _FutureListener.handleValue
	packages/$sdk/lib/async/future_impl.dart 665:13                        _Future._propagateToListeners
	packages/$sdk/lib/async/future_impl.dart 468:7                         _Future._complete
	packages/$sdk/lib/async/future_impl.dart 51:5                          _SyncCompleter.complete
	packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 164:3      _asyncReturn
	packages/ddt/src/func/func_call.dart 323:15                            FuncCall.resolveGenericCallFunctions
	packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 213:19     _wrapJsFunctionForAsync
	packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 237:5      _wrapJsFunctionForAsync.<anonymous function>
	packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 187:19     _awaitOnObject.<anonymous function>
	packages/$sdk/lib/async/zone.dart 1128:37                              _rootRunUnary
	packages/$sdk/lib/async/zone.dart 1012:12                              _CustomZone.runUnary
	packages/$sdk/lib/async/future_impl.dart 129:12                        _FutureListener.handleValue
	packages/$sdk/lib/async/future_impl.dart 665:13                        _Future._propagateToListeners
	packages/$sdk/lib/async/future_impl.dart 468:7                         _Future._complete
	packages/$sdk/lib/async/future_impl.dart 51:5                          _SyncCompleter.complete
	packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 164:3      _asyncReturn
	packages/ddt/src/func/func_call.dart 323:15                            FuncCall.resolveGenericCallFunctions
	packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 213:19     _wrapJsFunctionForAsync
	packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 237:5      _wrapJsFunctionForAsync.<anonymous function>
	packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 187:19     _awaitOnObject.<anonymous function>
	packages/$sdk/lib/async/zone.dart 1128:37                              _rootRunUnary
	packages/$sdk/lib/async/zone.dart 1012:12                              _CustomZone.runUnary
	packages/$sdk/lib/async/future_impl.dart 129:12                        _FutureListener.handleValue
	packages/$sdk/lib/async/future_impl.dart 665:13                        _Future._propagateToListeners
	packages/$sdk/lib/async/future_impl.dart 343:9                         _Future._addListener.<anonymous function>
	packages/$sdk/lib/async/zone.dart 1120:12                              _rootRun
	packages/$sdk/lib/async/zone.dart 1001:12                              _CustomZone.run
	packages/$sdk/lib/async/zone.dart 928:20                               _CustomZone.bindCallback.<anonymous function>
	packages/$sdk/lib/async/schedule_microtask.dart 41:5                   _microtaskLoop
	packages/$sdk/lib/async/schedule_microtask.dart 50:5                   _startMicrotaskLoop
	packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 51:9       _AsyncRun._initializeScheduleImmediate.internalCallback
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:48      invokeClosure.<anonymous function>
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 474:16  _IsolateContext.eval
	packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 59:16   _callInIsolate
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:14      invokeClosure
	packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2476:14      convertDartClosureToJS`

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-17005

**Comment by LesiaPavlenko** [comment]
1.22.2 + Power Pack 1.2.3

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

1.22.2 + Power Pack 1.2.3
