### ISSUE TITLE
Box plot: New multi-category Box plot is not compatible with older layouts that have only single category

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3150]
v 1.22.1

**Steps to reproduce:**
1. Open SPGI
2. Apply layout with box plot that was saved with one of the previous versions (e.g. 1.20), when only single category could be selected
[SPGI_v2 - v20.json](https://github.com/user-attachments/files/17675935/SPGI_v2.-.v20.json)
(rename file into .json, github did not allow to attach .layout file)

**Expected results:** older layouts should be applied correctly, i.e. category should be loaded from categoryColumnName property.
**Actual results:** older layout is applied incorrectly: there is no category column selected in box plot.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-17008
