### ISSUE TITLE
#3168: Horizontal scroll bar in table disappears on double clicking it

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3168]
v1.22.2, 1.20

**Steps to reproduce:**
1. Open a table with enough columns ,so that horizontal scroll bar is present
2. Double click the scroll bar

**Expected results:** nothing happens, scroll bar is still present and table is scrollable horizontally.
**Actual results:** scroll bar disappears, table cannot be scrolled horizontally with touchpad.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-17049

**Comment by ahadzhanian** [comment]
1.22.3 and 1.23.0
