### ISSUE TITLE
#3174: Table header tooltip overlaps menus in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3174]
v1.22.2 (RC)

**Steps to reproduce:**
1. Open a table
2. Move mouse cursor in diagonal direction across some cell, column header and to the page header pretty quickly
3. Open some dropdown menu, e.g. export

**Expected results:** tooltip does not overlap any menus, tooltip should disappear when cursor is moved away from column header.
**Actual results:** tooltip does not disappear when cursor is moved away from column header. It is still shown when some dropdown menu is opened and overlaps it.
![2024-11-25_14-26-34 (1)](https://github.com/user-attachments/assets/9efa23c7-0313-4b08-b33b-b649a0e00992)

_Note: in grok tooltip disappears when cursor is moved over the dropdown menu. However in our custom NX application tooltip does not disappear on cursor moving with menu opened, and is even still displayed on switching to our custom page._

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-17057
