### ISSUE TITLE
#3175: Scatter plot with conditionally colored column as color inconsistency: color editor icon is shown, but colors cannot be changed

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3175]
v1.20, 1.22.2

**Steps to reproduce:**
1. Open a table
2. Set up conditional colouring on some numerical column
3. Add a scatter plot
4. Colour by a column from step 2.
5. Hover an item in colouring legend and try to change colour

**Actual results:** 'edit colour' icon is shown on hover, but colour cannot be changed.
1.20: colouring dialog is opened, but applying new colour does not change colouring in the plot or the column colour.
1.22.2: clicking 'edit colour' icon does not open the dialog.

**Expected results:** behaviour should be consistent. Ability to change conditional colour on the scatter plot is nice to have.
However if changing colour through plot is not supported for conditionally coloured columns, 'edit colour' icon should not appear on hover.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-17059

**Comment by ahadzhanian** [comment]
1.22.3 and 1.23.0
