### ISSUE TITLE
#3176: Scatter plot: some labels disappear unexpectedly on zoom in / out

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3176]
v1.22.2

**Steps to reproduce:**
1. Open SPGI
2. Add a scatter plot
3. Set up labels (e.g. with Structure column): show labels for selected, mode = auto
4. Select a few items on scatter plot, so that all labels are displayed for the selected items
5. Zoom in, so that some labels are out of currently displayed plot part
6. Zoom out again

Additional scatter plot settings used when this issue was reproduced: 'pack and zoom by filter', select on mouse drag.

**Expected results:** all labels should be visible again after zooming out.
**Actual results:** some of the labels are not show, but appear only on hovering the dot. However there is enough space for all of them to be displayed.
![2024-11-26_15-12-15 (1)](https://github.com/user-attachments/assets/4ace8dab-4409-4dff-b713-c4bf0682ed1e)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-17061

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

works on dev 1.23.0

**Comment by ahadzhanian** [comment]
DG 1.23.0 and 1.22.3
