### ISSUE TITLE
#3189: Scatter plot labels are shown for filtered out points

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3189]
v1.22.2

**Steps to reproduce:**
1. Open SPGI
2. Add a scatter plot, e.g. 'Whole blood assay 2 Date' on X, 'Stereo category' on Y
3. Set up showing labels for selected items
4. Apply some filtering
5. Select some items that are filtered out

**Expected results:** labels should not be shown for the items that are not visible on the scatter plot.
**Actual results:** labels are shown for the filtered out items.
It can be reproduced for any kind of filter (filter panel, in viewer filter).
<img width="751" alt="image" src="https://github.com/user-attachments/assets/f128a5c3-1fb5-4c28-a4e9-031f4d436111">

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-17176

**Comment by dnillovna** [comment]
> Andrew Golovko commented in Jira:

There can be multiple points at the same coord location (two, or four or more). So if there’s not enough space, then only one or couple will be displayed, and if there’re enough space for many (for example, after zoom in), much more labels can be displayed
[file id="6eaf5541-3a57-4a6f-b037-528259e444f1"][file id="f2f81e25-d9ed-4f91-91b5-ec9e2eeffc4f"][file id="e7a7f970-34ba-48a9-86c3-b5a4434b498e"]

[file id="ea157f17-b001-4ac2-8585-74cff9a29871"]

**Comment by LesiaPavlenko** [comment]
fixed for 1.22.3

**Comment by ahadzhanian** [comment]
DG 1.22.3 and 1.23.0
