### ISSUE TITLE
Disabling/not disabling filtering behaviour on closing filter panel is inconsistent in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#319]
Issue is reproduced on https://dev.datagrok.ai/

**Steps to reproduce:**
1. Open any table (e.g. from file)
2. Open filters panel
3. Apply some filtering (e.g. select some items/change range for the 1st of the default filters)
4. Close filters >> *filtering is un-applied*
5. Open filters again >> *filtering is applied again*
6. Reset filters >> *filtering is un-applied in current view*
7. Clone the current view

**Expected results:** no filters applied in the cloned view. Behaviour on closing filters should be the same as before: filters are un-applied when filters panel is closed.
**Actual results:** filters are applied in the cloned view. Behaviour on closing filters has changed for both views: filtering is not un-applied when filters panel is closed.

**Comment by onuf** [comment]
Reproduced on any table, e.g., https://dev.datagrok.ai/f/System.AppData/Demo/demo/demog.csv. The filter reset seems to not be propagated correctly only when cloning the view from the old (full) menu in the native DG.

**Comment by skalkin** [comment]
@katerina-stepanova, @onuf - thanks for providing the steps to reproduce it! This has been fixed and merged to your branch as well.

**Comment by katerina-stepanova** [comment]
@skalkin @onuf There is stil an issue left.
**Steps to reproduce:**
1. Repeat all steps from original description (open filters > apply something > close/reopen filters > reset > clone view)
2. Apply some filter in the cloned view (can be either the same filter or another one)
3. Close filters panel in the cloned view
**Expected results:** Filters are un-applied when filters panel is closed.
**Actual results:** Filters are not unapplied when filters panel is closed in cloned view.
