### ISSUE TITLE
#3191: Some dots are not shown on scatter plot when labels are enabled

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3191]
v1.22.2

**Steps to reproduce:**
1. Open SPGI
2. Add a scatter plot
3. X axis: Id, Y axis: Whole blood assay 1
4. Pack and zoom by filter
5. Show labels for all or selected
6. Show labels mode auto
7. Select any column(s) for the labels

**Expected results:** all dots on scatter plot are visible.
**Actual results:** some scatter plot dots are hidden and appear only on hover after enabling labels.
![2024-12-06_18-34-04 (1)](https://github.com/user-attachments/assets/042c1228-e981-43bb-ac9a-0253d7e0056b)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-17194

**Comment by LesiaPavlenko** [comment]
![Screenshot_167](https://github.com/user-attachments/assets/2eec90b1-2b6d-48dd-b2d1-b4ee2ebf006f)

fix added to 1.22.3 and 1.23.0
