### ISSUE TITLE
#3196: Sunburst chart causes performance issues

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3196]
charts 1.4.1

**Steps to reproduce:**
1. Open some table (~2-8K rows, ~300-400 columns)
2. Open 6-8 views
3. Add some viewers to the views
4. Add a sunburst and configure two columns: one with 6-10 categories, another one - **structure column** with 80-100 categories
5. Save project, refresh browser page

**Expected results:** Sunburst should not cause any performance issues.
**Actual results:** Performance is slow after adding and configuring sunburst. After saving and re-loading page is frozen for a while.

**Comment by katerina-stepanova** [comment]
Data for reproducing the issue: 
[sunburst.zip](https://github.com/user-attachments/files/18163430/sunburst.zip)

**Comment by LesiaPavlenko** [comment]
Charts 1.4.2
