### ISSUE TITLE
#3203: Legend: Save legend position for viewers in previously saved layout

### ISSUE THREAD

**Issue by LesiaPavlenko** [datagrok-ai/public#3203]
Save legend position for viewers in previously saved layout
Layout template for SPGI dataset:
[SPGI_v2 - legend position old.zip](https://github.com/user-attachments/files/18196527/SPGI_v2.-.legend.position.old.zip)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-17281
