### ISSUE TITLE
Add additional options to configure the view loading behaviour to project.open() method

### ISSUE THREAD

**Issue by gasserandreas** [datagrok-ai/public#332]
It would be great to have an option in the project.concept to control what views / layouts are restored on open. We would propose something like:
- open all: open tableView for every linked table if no other view information is available
- open none: no view is restored on open, table are just added to context but no view change
- only saved: all saved / linked views are restored on open

**Comment by alex-aprm** [comment]
Added:
```
project.open({openViews: 'all' | 'saved' | 'none'})
```
option
