### ISSUE TITLE
Issue with restoring layout containing viewers linked to different table

### ISSUE THREAD

**Issue by gasserandreas** [datagrok-ai/public#338]
We experienced an issue with native Datagrok on restoring layouts containing viewers linked to a different table.

**Steps to reproduce:**
1. add two tables
2. add scatterplot (or any other viewer) to second table
3. in viewer configuration select other table as data source
4. store view layout
5. close table and reopen
6. load previously stored layout

**Expected behaviour:** Layout is restored without any issue
**Actual behaviour:** Layout is restored but red warning messages are shown in grok

<img width="537" alt="Screenshot 2022-02-22 at 16 42 16" src="https://user-images.githubusercontent.com/3170680/155167051-facc2d3b-28a4-4492-b537-43387a939e76.png">

I was also able to catch that behaviour with this Grok script:

```javascript
/name: Layout error messages
//description: Hello world script
//language: javascript

const table2 = grok.data.demo.geo();
const table1 = grok.data.demo.demog();

const view2 = grok.shell.addTableView(table2);
const view1 = grok.shell.addTableView(table1);

// add scatterplot for non-active table
view1.scatterPlot({ table: 'Table' });

ui.dialog({title:'Let\'s break the system...' })
	.add(ui.span(['Click "Ok" to re-open view and apply layout.']))
    .onOK(() => {
  		// create layout
		const layout = view1.saveLayout();
        grok.shell.closeTable(table1);
  		const table3 = grok.data.demo.demog();
  	    const view3 = grok.shell.addTableView(table3);
  		view3.loadLayout(layout);
    })
    .show();
```

**Comment by alex-aprm** [comment]
Fixed in 0.136.0
