### ISSUE TITLE
Allow user to rename the viewers from the arranged tab

### ISSUE THREAD

**Issue by JianmeiFan** [datagrok-ai/public#341]
When a user creates a viewer and arrange it overlaid on other viewer plots, it gives a tab. It just says general plot name for example "Scatter plot". It will be useful to allow the user to rename it so that they can distinguish different plots and navigate to the desired one quickly.
![image](https://user-images.githubusercontent.com/100243033/155233005-d1a119eb-50bd-48a5-8c28-94e0cf928bdc.png)

**Comment by skalkin** [comment]
@alex-aprm , I believe this is closed now

**Comment by RobertStrulak** [comment]
Hi Andrew,
The option to rename doesn't work for the Markup viewer.

**Comment by alex-aprm** [comment]
Markup Viewer fixed in 0.146.0

**Comment by katerina-stepanova** [comment]
Viewer saved in the layout on one of the previous DG versions cannot be renamed.

**Comment by RobertStrulak** [comment]
It looks there is no backward compatibility in place.

**Comment by alex-aprm** [comment]
Fixed in 0.149.0
