### ISSUE TITLE
(Only) show filtered category items on scatterplot axes 

### ISSUE THREAD

**Issue by JianmeiFan** [datagrok-ai/public#342]
**Steps to reproduce:**

Create a scatterplot, make sure at least one of the axes is category (String) type.
Filtered on this category 

**Desired behavior:**

User have the choice to only see the filtered category items: Scatterplot Axes automatically adjust and scale to filtered category items. Categories that were filtered out in the filter panel are not displayed on axes.
Option: distinguish filtered/filtered out category items on this axes.

**Actual behavior:** 

User still see all the category items on this axes including filtered out items
![image](https://user-images.githubusercontent.com/100243033/155237506-fbb97769-99d0-4113-9eb4-4307b27c922a.png)

**Comment by RobertStrulak** [comment]
The goal is to reflect state of filters for categorical columns both on axes and on legends.

**Comment by alex-aprm** [comment]
Estimated fix time: 29.04

**Comment by RobertStrulak** [comment]
@skalkin  - please procced with that
