### ISSUE TITLE
Not able to build Chem package

### ISSUE THREAD

**Issue by gasserandreas** [datagrok-ai/public#343]
Latest chem package version fails on build with following error message
```
ERROR in /Users/user/Documents/Projects/intuence/public/js-api/dg.ts(7,21)
      TS2307: Cannot find module 'wu' or its corresponding type declarations.
```

**Steps to reproduce:**
1. checkout lastest master branch (commit: `38cb6c66534259eef623ebc99c49342955ef0c20`)
2. navigate into `packages/Chem`
3. execute setup script: `. setup.sh`
4. try to build: `npm run build`

Expected behaviour: new build is created
Actual behaviour: Error shown in console (see above) and built failed!

I already tried to manually re-install following package (obviously with no luck):
- wu
- @types/wu

**Comment by alex-aprm** [comment]
Could you try the following:
`npm install`
`npm run build`
?

**Comment by gasserandreas** [comment]
Just got more issues related to `datagrok/ui`

```
ERROR in /Users/userid/Documents/Projects/intuence/public/packages/Chem/src/widgets/toxicity.ts
./src/widgets/toxicity.ts 2:20-37
[tsl] ERROR in /Users/userid/Documents/Projects/intuence/public/packages/Chem/src/widgets/toxicity.ts(2,21)
      TS2307: Cannot find module 'datagrok-api/dg' or its corresponding type declarations.
 @ ./src/package.ts 23:0-52 402:20-34

214 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
```

Also tried to install manually before calling `npm run build` again but this ended again with a lot of issues?

**Comment by alex-aprm** [comment]
OK, it could be that chem is in some kind in the middle of development.

You can:
1. rollback to commit that was published to NPM (https://github.com/datagrok-ai/public/commit/75c9c7976bc6d37b1ea87efb5a26f5f6cb54e502)
2. build everything locally, 
run https://github.com/datagrok-ai/public/blob/master/libraries-build-local.cmd
then use `npm run build-chem-local` in chem package

**Comment by alex-aprm** [comment]
Yes, I know that you can't run cmd scirpts. I was just going to make sh.
The purpose is to go through all the libraries and js-api and run `npm install` and `npm link`, and also build local libraries

**Comment by alex-aprm** [comment]
Also, we have a Package Manager, but, sadly, it has issues with your on-site settings of NPM. May be, it's a good moment for fixing it!

**Comment by gasserandreas** [comment]
Reverting back to commit `75c9c7976bc6d37b1ea87efb5a26f5f6cb54e502` worked, however I also had to delete and install `dayjs` and `wu` manually again for the `js-api`.

**Comment by skalkin** [comment]
This seems to be resolved now; please reopen if needed.
