### ISSUE TITLE
Missing onReset event in DG.Filter class

### ISSUE THREAD

**Issue by dgosi** [datagrok-ai/public#346]
Is there an onReset like event for DG.Filter class raised when the "Reset" button on the Filters panel is pressed? The applyFilter() method doesn't seem to be called in that case.
This event is needed to put UI controls of a custom Filter into the default state. Would it be possible to add this event to the DG.Filter class?

**Comment by skalkin** [comment]
Subscribe to the DataFrame's `d4-reset-filter-request` event.

**Comment by dgosi** [comment]
> Subscribing through _event doesn't trigger the reset event. Is this a new feature not yet  available on DG Dev server or the statement below is wrong?

dataframe._event('d4-reset-filter-request').subscribe((_) => alert('reset-filter'));

**Comment by skalkin** [comment]
Apologies, I was wrong, currently it is a global event, so the following code would work:

```
let t = grok.data.demo.demog();
grok.events.onEvent('d4-reset-filter-request').subscribe((_) => alert('reset-filter'));
grok.shell.addTableView(t);
```

I've just exposed it via the `grok.events.onResetFilterRequest`, and we are thinking about introducing a similar event on a DataFrame level as well.

**Comment by dgosi** [comment]
Awesome, works now. Thanks!
