### ISSUE TITLE
Add option on toCsv() function to always export the Structure as SMILES (even if it's CTab in the dataframe)

### ISSUE THREAD

**Issue by gasserandreas** [datagrok-ai/public#351]

**Comment by skalkin** [comment]
I'm not sure if that should be an API option. It's very easy to write a custom function that would check if a column contains molblocks, and replace them with SMILES using one of the functions available in the Chem package.

I think such an option might belong in the "Save to CSV..." dialog, though.

**Comment by skalkin** [comment]
Closing the issue, as it does not belong to the API. It's easy to convert MOLBLOCKs to SMILES before saving the dataframe if that is needed.
