### ISSUE TITLE
Add "Row Source" option to the configuration of the Grid visualization

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#353]
As I user I'd like to have any option to configure "Row Source" for the Grid visualizations. The expected behavior is as on other visualizations where it is available (Scatter Plot , Line Chart, etc).

Acceptance criteria:

- "Row Source" option is added to the Grid configuration

**Comment by skalkin** [comment]
@dionissqq , this should be part of our bigger effort (introducing Row Source / Filter / Transformation to the DataFrameViewer)

**Comment by ahadzhanian** [comment]
v1.15.0
