### ISSUE TITLE
Free-text filter doesn't work for columns which names contain more than one word

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#357]
I've tried a few options (", ', { }) to use multi-word column name in the free-text filter but unfortunately nothings seems to be working.

![2022-03-17_17-35-29](https://user-images.githubusercontent.com/99964535/158849197-b627ce08-201c-46dc-89b6-fa8b9468569b.png)

**Comment by skalkin** [comment]
Fixed in v0.137

![image](https://user-images.githubusercontent.com/943403/159516526-e794f52f-2ad9-40f6-a8a1-d4b9dfb64d79.png)
