### ISSUE TITLE
Render image data

### ISSUE THREAD

**Issue by kennovation1** [datagrok-ai/public#366]
We'd like to have data values that represent the bytes of an image (e.g., png) automatically render as an image.

Double-clicking on the image should create a popup (like is done with chemical structures) that shows the image and includes an option to download to a file.

**Comment by skalkin** [comment]
Good idea! At the moment, we only support images defined as URLs. It shouldn't be too hard to support binary images saved as part of the data frame by introducing new semantic type `BinaryImage` and the corresponding renderer, like we did for `ImageUrl`:

https://github.com/datagrok-ai/public/blob/master/packages/PowerGrid/src/cell-types/image-cell-renderer.ts

**Comment by skalkin** [comment]
@kennovation1 , this feature is now available as part of the PowerGrid package:

https://github.com/datagrok-ai/public/tree/master/packages/PowerGrid#embedded-images
