### ISSUE TITLE
Grid: rendering dataframe values as HTML

### ISSUE THREAD

**Issue by skalkin** [datagrok-ai/public#374]

**Comment by RobertStrulak** [comment]
@skalkin  - In which version it will be available?

**Comment by skalkin** [comment]
@RobertStrulak - v0.139.
Usage: https://github.com/datagrok-ai/public/blob/master/packages/ApiSamples/scripts/grid/html-cells/html-table-cells.js
See also: https://community.datagrok.ai/t/javascript-api-updates/526/14
