### ISSUE TITLE
Dataframe formula lines are not shown on scatter plot, if scatterplot's table was changed in properties panel

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#375]
**Steps to reproduce**
1. Open two dataframes: dataframe1 - any dataframe, dataframe2 has some dataframe lines defined
2. Add a scatter plot to dataframe1
3. Switch scatterplot to dataframe2 in properties panel > Data > Table
4. Configure scatter plot columns so that dataframe formula lines are expected to be shown

**Expected results:** dataframe formula lines are shown.
**Actual results:** dataframne formula lines are missing.

Note: dataframe formula lines are shown as expected if scatterplot was added from dataframe2 and scatter plot table was never switched.

**Comment by alex-aprm** [comment]
Estimated fix time: 15.04
