### ISSUE TITLE
Zoom sliders are broken on the ScatterPlot when the log scale is applied

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#376]
Zoom sliders are broken on the ScatterPlot when the log scale is applied

**Comment by skalkin** [comment]
Estimate: 1 hour to disable in log mode, 4 hours to implement

**Comment by RobertStrulak** [comment]
We need to fix that, so we need to go with the second option (4 hours)

**Comment by katerina-stepanova** [comment]
Was fixed in some version before 1.13.*
