### ISSUE TITLE
#384: HTML Renderer: ability to control max number of cached elements on a column level

### ISSUE THREAD

**Issue by skalkin** [datagrok-ai/public#384]

**Comment by ahadzhanian** [comment]
@skalkin is this enhancement still of current interest?

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14602

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16045

**Comment by LesiaPavlenko** [comment]
looks too old and no longer relevant
