### ISSUE TITLE
Adjusting axes to the range of visible data (adding zoom to filtered points & zoom to ranges)

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#397]
**Acceptance Criteria:**

Property "Zoom and Filter" is consisted of following values:
- no action (already existing)
- filter by zoom ((already existing)
- zoom by filter (already existing)
- zoom to plotted data **(new one)** 

The screenshot presents the expected behavior of the new option:
![image](https://user-images.githubusercontent.com/99964535/165329517-46b88411-9258-46fb-b410-790ab5166a5e.png)

**Comment by skalkin** [comment]
Estimate: 2 days

**Comment by RobertStrulak** [comment]
@skalkin - let's discuss today this topic once again. I'm not sure if the names of the option are clear enough. What we actually need, apart from the current option (no action, zoom by filter, filter by zoom), is yet another option that could be called "zoom to plotted data". Please take a look at the screenshot:
![image](https://user-images.githubusercontent.com/99964535/165320787-bfa91d49-f55a-4ee1-90cc-f984ca3a32f1.png)
