### ISSUE TITLE
Scatter plot, bar chart, 3d scatter plot viewers are empty or frozen if column with structures is selected for one of the axes

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#398]
DG 0.139.0, 0.140.0

**Steps to reproduce**
1. Open a table
2. Add one of the following viewers: scatter plot, bar chart, 3d scatter plot
3. Change one of the axes to use column with structures (e.g. smiles)

**Expected results:** viewers should support structure columns as axes

**Actual results:** the plot is empty (scatter plot, bar chart) or frozen (3d scatter plot) after switching axis to a structure column.

**Comment by skalkin** [comment]
Fixed in the Chem package; see also #401 (label density is incorrect; fixed in core v144)

![image](https://user-images.githubusercontent.com/943403/160626329-0b6d4507-1f50-4dda-bd95-b7da2c87f060.png)
