### ISSUE TITLE
Scatter plot: wrong category name is shown on highlighting

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#403]
Reproduced in DG 0.140.0, 0.143.0

**Steps to reproduce**
1. Open a table
2. Add scatter plot and make sure that one of the axes is using a categorical column
3. Hover some point on the scatter plot
4. See highlighted category on axis

**Expected results**
Category should be highlighted, highlighted category title should match the hovered point

**Actual results**
Category title is changed on hovering a point and does not correspond to hovered point in some cases.

**Data for reproducing**
Save following as a .csv file and open in DG (use 'cat' as one of the axes in scatter plot):
id,cat,cor1,cor2,cor3
1,AA\nDD\EE,1,2,3
2,AA,4,5,6
3,BB,7,8,9
4,CC,10,11,12
5,BB,13,14,15
6,CC,16,17,18
7,DD,19,20,21
7,EE\nFF\nZZ\nMM,22,23,24

**Comment by RobertStrulak** [comment]
@skalkin - would be great if you could fix that in 1-2 weeks so we can push it to PROD with our next release

**Comment by skalkin** [comment]
Great catch @katerina-stepanova ! Fixed in v0.146
