### ISSUE TITLE
Box plot: axis labels are not updated when axis is inverted or changed to log scale

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#404]
**Steps to reproduce**
1. Open a table
2. Add a box plot
3. Change Y axis to log scale or invert it

**Expected results**
Y axis labels are updated accordingly.

**Actual results**
Box plot itself is re-rendered according to changes made, but Y axis labels are not updated.

**Comment by RobertStrulak** [comment]
@skalkin - would be great if you could fix that in 1-2 weeks so we can push it to PROD with our next release

**Comment by skalkin** [comment]
@RobertStrulak Will do!

**Comment by skalkin** [comment]
Log scale was working fine - but inverted scale indeed did not work

![image](https://user-images.githubusercontent.com/943403/161168467-37ca09b6-13e0-4e03-9099-b8f437e8c4fb.png)

**Comment by skalkin** [comment]
Fixed in v0.146
