### ISSUE TITLE
Switching table for a viewer: column selection dropdown/dialog in properties panel is not updated

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#405]
**Steps to reproduce**
1. Open two different tables
2. Add a viewer to one of them
3. Change Table for the viewer from the default one
4. Open columns selection dropdown/dialog

**Expected results**
Column selection dropdown/dialog is updated with columns corresponding to currently selected table.

**Actual results**
Column selection is not updated.
Workaround: close and re-open properties panel.

**Comment by RobertStrulak** [comment]
@skalkin  - which version does include the fix?

**Comment by katerina-stepanova** [comment]
Column selection dropdown is not updated when table is changed in some cases

1. Open 2 or more tables
2. Add a viewer
3. Open properties panel
4. Change selected column in one of the properties panel dialogs (one of the axes, color etc.)
5. Change table for the viewer
6. Check one of the column selection dropdowns in properties panel
**Expected:** column selection dialogs contents are updated when viewer's table is changed.
**Actual:** column selection dialogs are not updated in case described.
Additionally, after this properties panel is showing wrong contents for other viewers added even after closing /reopening properties panel.
![2022-06-09_18-38-19 (1)](https://user-images.githubusercontent.com/15780643/172887946-88d9bf69-6d86-49a7-a99e-5cf058f135c0.gif)

**Comment by RobertStrulak** [comment]
@skalkin - please take a look at @katerina-stepanova  comment ^^

**Comment by onuf** [comment]
@skalkin according to our [release notes](https://datagrok.ai/help/develop/release-history), version `1.2.0` has the fix. Tried the steps Ekaterina provided above and reproduced the behavior on the latest version, though.

**Comment by skalkin** [comment]
@katerina-stepanova , thanks for reporting it! Indeed, a regression bug was introduced when we fixed the issue with the property panel changing to dataframe whenever a combo box value was changed. This is fixed now in `Datagrok 1.4.2` (it is building at the moment and will be available on dev.datagrok.ai in ~30 minutes)
