### ISSUE TITLE
Compute: Model Catalog app to appear on the Left Panel

### ISSUE THREAD

**Issue by dskatov** [datagrok-ai/public#411]
Model Catalog (App) should stick to the left Panel, so that the user doesn't need to look for it in Apps.

**Comment by AufarZakiev** [comment]
Now we have it this way. If it is OK, I propose to close the issue.
![изображение](https://user-images.githubusercontent.com/5558521/173600568-740145cc-6de1-4a55-aed7-4a7f993c13c0.png)
