### ISSUE TITLE
Blocking option (graying it out) to switch to log scale for columns with negative values 

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#424]
Switching axes to log scale for columns with negative values breaks the plot.
It's reproducible on ScatterPlot, BoxPlot, LineChart and BartChart.

**Expected results:** 
Option to switch to log scale is blocked (grayed out) for columns with negative values 

**Actual results:** 
Option to switch to log scale is available for columns with negative values that results in breaking the plot.
![image](https://user-images.githubusercontent.com/99964535/160862896-5870292e-62cd-4449-b9f5-276c7ae0b37e.png)

**Comment by RobertStrulak** [comment]
@skalkin - option to switch to log scale should be available only for non negative numeric values (no categories,  dates, etc.)

**Comment by skalkin** [comment]
Grayed out the option in the popup menu, however it's a lot harder to do for the property panel

![image](https://user-images.githubusercontent.com/943403/161747155-77f563ce-179a-46f1-beb7-c680bc1f0a70.png)

**Comment by skalkin** [comment]
Also, added a validation:

![image](https://user-images.githubusercontent.com/943403/161748431-54d3199b-4797-4fb0-9efb-702606b053b8.png)

**Comment by skalkin** [comment]
> What options do we have?

Now you can change it, but the viewer will complain (and there will be no error)

**Comment by RobertStrulak** [comment]
What exactly do you mean by writing "but the viewer will complain"? Can you provide some screenshots?

**Comment by skalkin** [comment]
There will be the same validation message as above.

This is fixed in v0.146

**Comment by katerina-stepanova** [comment]
@skalkin 'Logarithmic' option is not disabled for scatter plot X axis with negative values in some cases.
It happens if default Y column when scatter plot is added has no negative or zero values.

Can be reproduced for following table (save it as csv and open in DG):
id,cat,cor1,cor2,cor3
1,AA\nDD\EE,-1,2,-3
2,AA,4,5,6
3,BB,7,8,9
4,CC,-10,11,12
5,BB,13,14,15
6,CC,16,17,-18
7,DD,-19,20,21
7,EE\nFF\nZZ\nMM,22,23,24

**Comment by dionissqq** [comment]
fixed in v1.4.16
