### ISSUE TITLE
Switching axis type (linear / logarithmic) causes the "Formula line.." to disappear from the context menu

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#425]
Switching axis type (linear / logarithmic) causes the "Formula line.." to disappear from the context menu. 
**It happens only when axes are changed in the context menu.** Changing axis in the config panel doesn't cause the issue.

**Expected results:** 
The "Formula lines.." option doesn't disappear from the context menu after changing axis type.

**Actual results:** 
The "Formula lines.." option disappears in an erratic way.

**Comment by alex-aprm** [comment]
Fixed in PowerPack 0.0.7
