### ISSUE TITLE
Structure labels are displayed incorrectly in viewers if window.devicePixelRatio !=1

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#426]
Make sure window.devicePixelRatio !=1 in browser (can be achieved using Chrome's tools to imitate various devices)

**Steps to reproduce**
1. Open a table containing some structure column
2. Add a viewer
3. Select structure column as one of the axes

**Expected results**
All labels should be visible

**Actual results**
Some structure labels are not shown (Y axis), labels are misplaced (X axis).

**Comment by StLeonidas** [comment]
devicePixelRatio was used to recalculate the rendering
