### ISSUE TITLE
Data exported to csv is incorrect in 'sign' columns if there is more than one such column and there are some nulls

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#433]
**Steps to reproduce:**
1. Open a table containing at least 2 qnum columns with some empty and non-empty values in them
2. Export data as CSV with 'Qualifier as column' option
3. Check exported data, see 'sign' columns (e.g. open exported file in Datagrok again)

**Expected results:** Sign column should contain only signs from the column next to it. Data from different columns should not be mixed in one column.

**Actual results:** Data in the 'sign' columns is sometimes mixed with data from the columns next to it. Issue could be caused by null value in the columns containing signs.

**Data for reproducing:**
Save following as csv and open file in Datagrok, change type for columns with signs to 'qnum':
id,cat,col1,col2,col3,withSigns,nextOne,yyyyy,withSigns2,y2
1,AA\nDD\EE,1,2,3,>33,1,0qwe,4,
2,AA,4,5,6,<33,2,9,5,u
3,BB,7,8,9,,3,9,,vbn
4,CC,10,11,12,,4,8rsdvsd,,
5,BB,13,14,15,,5,6,>44,kk
6,CC,16,17,18,,6,0zzzz,0,
7,DD,19,20,21,,7,4,,
7,EE\nFF\nZZ\nMM,22,23,24,,8,3ccc,<35,bbcc

**Comment by skalkin** [comment]
Hi Katerina, I've tried reproducing the issue, but everything seems to work fine for me. Can you please show your screenshot?

![image](https://user-images.githubusercontent.com/943403/161163717-161d477a-fab2-4a3c-9dee-0ddb1492d442.png)

**Comment by katerina-stepanova** [comment]
<img width="882" alt="image" src="https://user-images.githubusercontent.com/15780643/161216977-9554780b-d05f-4031-b287-6d88cb1f52fe.png">

**Comment by RobertStrulak** [comment]
@skalkin - did you manage to reproduce the issue with the example provided by Ekaterina?

**Comment by katerina-stepanova** [comment]
Script for reproducing:
    
    //name: missing-data-qnum-csv-export-problem
    //description: Script to demonstate the QNum issue with toCsv({qualifierAsColumn: true}) when value is missing
    //language: javascript
    
    let idCol = DG.Column.fromList('string', 'Id', ["Compound1", "Compound2", "Compound3", "Compound4"]);
    let strQnumCol1 = DG.Column.fromList('string', 'string1', [null, "4", null, "<3"]);
    let qnumCol1 = strQnumCol1.convertTo(DG.COLUMN_TYPE.QNUM);
    qnumCol1.name = 'qnum1';
    let strQnumCol2 = DG.Column.fromList('string', 'string2', [null, "0.001", ">100", null]);
    let qnumCol2 = strQnumCol2.convertTo(DG.COLUMN_TYPE.QNUM);
    qnumCol2.name = 'qnum2';
    let categoryCol = DG.Column.fromList('string', 'categoryABC', ["A", "B", "B", "C"]);
     
    let t = DG.DataFrame.fromColumns([idCol, strQnumCol1, qnumCol1, strQnumCol2, qnumCol2, categoryCol]);
    grok.shell.addTableView(t); // compare this table view ...
    let csv = t.toCsv({qualifierAsColumn: true});
    grok.shell.addTableView(DG.DataFrame.fromCsv(csv)); // ... to this table view and you see values are now in the wrong column due to missing commas in CSV export

**Comment by skalkin** [comment]
Hi @katerina-stepanova , thank you so much for creating a script that reproduces the issue, it helped a lot! The issue was with the empty fields in the qnum columns when the `qualifierAsColumn` mode is on. This is fixed in v0.150
