### ISSUE TITLE
#452: JS API: DataFrame data full replace method is required

### ISSUE THREAD

**Issue by AufarZakiev** [datagrok-ai/public#452]
### Context

We have multiple viewers that are connected to the dataframes. When we create a new DF and connect it to the existing viewer, we lose the subscription we had on the old DF. 

Manual values setting using `addRow`/`addColumn` or `set` methods are very inconvenient - they require to row/column count to be identical. 

### Problem

```
let t = grok.data.testData('demog', 10);
let v = grok.shell.addTableView(t);

t.onCurrentCellChanged.subscribe((_) => grok.shell.info(`Cell: ${t.currentCell.rowIndex}, ${t.currentCell.column.name}`));

let t2 = grok.data.testData('geo', 20)
v.dataFrame = t2
```
In the script above, we lose the `onCurrentCellChanged` subscription. It would be great not lose it, meaning that there is need to replace all the data in `t` with any data we want.

### Proposal 

Add the API to completely replace the data in DF without changing its subscriptions. Proposed method should fire `onValuesChanged` and `onDataChanged` events.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14788

**Comment by AufarZakiev** [comment]
Won't fix
