### ISSUE TITLE
#453: JS API: userStorage.put returns 404 on any request

### ISSUE THREAD

**Issue by AufarZakiev** [datagrok-ai/public#453]
### Description

"Add new row" button is half-hidden when no row headers are used

### Demo script:
```
//language: javascript
//name: Template
await grok.dapi.userDataStorage.remove('coordinate-storage', 'x');
await grok.dapi.userDataStorage.remove('coordinate-storage', 'y');
await grok.dapi.userDataStorage.remove('coordinate-storage', 'z');

await grok.dapi.userDataStorage.post('coordinate-storage', {x: 1, y: 2, z: 3});
await grok.dapi.userDataStorage.put('coordinate-storage', {x: 10, y: 20, z: 30});

data = await grok.dapi.userDataStorage.get('coordinate-storage');

grok.shell.info(data)
```
### Steps to reproduce

Run the script

### Expected

According to the [docs](https://datagrok.ai/help/develop/how-to/user-data-storage), the retrieved data must be `x: 10, y: 20, z: 30`

### Actual

The retrieved data is `x: 1, y: 2, z: 3`

### Additional info:
The PUT request to storage returns 404

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14789

**Comment by AufarZakiev** [comment]
Fixed
