### ISSUE TITLE
Column selectors: search field is invisible (above the screen) when the number of columns is big

### ISSUE THREAD

**Issue by skalkin** [datagrok-ai/public#465]
The search functionality itself works, but you cannot see what you are typing.

 ![image](https://user-images.githubusercontent.com/943403/162230016-3c5991d0-c452-4ffd-b9f2-9f5efba6ad6d.png)

**Comment by skalkin** [comment]
Fixed in v0.146

**Comment by katerina-stepanova** [comment]
Column selectors search field is not visible in some specific cases:
Pie chart
Line chart: split by
Histogram
Bar chart: stack
Network diagram
Box plot: X axis
Tree map: Color
Density plot: X axis

**Comment by skalkin** [comment]
Indeed it was not fixed completely - but now it should all be working. 
Fixed in v0.152
