### ISSUE TITLE
#466: ComputationView

### ISSUE THREAD

**Issue by skalkin** [datagrok-ai/public#466]
ComputationView is a base class for handling Compute models (see https://github.com/datagrok-ai/public/blob/master/help/compute/compute.md)

- [x] structured way to represent input and output parameters
- [x] generic way to generate UI for inputs, outputs, and interactivity
- [x] export and import to Excel and PDF
- [x] persisting historical runs
- [x] loading of historical runs
- [x] routing
- [x] entering the observed results (as opposed to predicted)
- [x] event notifications

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14790

**Comment by AufarZakiev** [comment]
Initial plan is done. CompView already evolved into RFV and Wizard, so the issue is obsolete
