### ISSUE TITLE
Positioning of Grid cells in HTML rendering mode 

### ISSUE THREAD

**Issue by dgosi** [datagrok-ai/public#488]
I am working on Pinned Column feature for Grid viewer and I stumbled upon a major blocker..

When I insert pinned columns to a Grid, I move the grid’s canvas to the right to accommodate the space. However when the grid’s cells are in HTML rendering mode, their corresponding DIV(s) (those with ‘d4-g-style’) are positioned relatively to the grid’s root and not to the grid’s canvas. Will it be possible to change positioning of the DIV(s) relatively to the grid’s canvas element?

Thanks a lot!

**Comment by skalkin** [comment]
Looks like you've customized the Grid in a way we did not foresee :) 

Done. The fix is available in v0.149
