### ISSUE TITLE
Columns in the column picker are selected without clicking (hovering over changes the plotted data)

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#492]
**Steps to reproduce:**
1. Open any project
2. Add any visualization (e.g. ScatterPlot)
3. Open column picker and move the mouse pointer over columns names

**Expected results:**
Plotted columns are not changed until a new column is directly selected (clicked in the column picker).

**Actual results:**
The column is changed after hovering over columns name in the column picker.

![CD4ECDB4-AA95-4E6E-BB4A-6F18EF89383A](https://user-images.githubusercontent.com/99964535/164024873-ad380840-a8ed-4ad2-83fd-d52e4e3badde.GIF)

**Comment by skalkin** [comment]
Fixed in `Datagrok v1.0` - now when the mouse leaves the drop-down part (without clicking on the item), the selection is reverted to the previously chosen column
