### ISSUE TITLE
[Filter panel - Structures] All structures columns used in the filter panel have the same name "Structure"

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#506]
Any structure column added to the filter panel has the same name "Structure". 
The expected behavior is the the name in the filter panel equals the actual name of the column.

![2022-04-22_14-19-21](https://user-images.githubusercontent.com/99964535/164713878-0ea3396f-b461-4e9c-99f3-ab5cdf7e4a80.gif)

**Comment by skalkin** [comment]
Looks like this has been fixed a while ago
