### ISSUE TITLE
[Filter panel - Structures] Turning on / off doesn't work for structure columns in the filter panel

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#507]
![2022-04-22_14-31-14](https://user-images.githubusercontent.com/99964535/164714997-b95843f2-2683-41fd-a6a4-ac9fa9484eea.gif)

**Comment by skalkin** [comment]
Fixed in v0.152 (requires a minor core change)

**Comment by RobertStrulak** [comment]
Turning off doesn't work on the "all filters" level.
