### ISSUE TITLE
Peptides: wrong color coding in distribution panel

### ISSUE THREAD

**Issue by vdyma** [datagrok-ai/public#509]
After resetting a selection, the color coding for lines in the distribution panel gets broken. Instead of showing orange vs blue line, it shows both lines in different shades of blue

**Comment by vdyma** [comment]
I set `orange` and `blue` colors for categories, but at some point something goes wrong and the colors in histogram are getting messed up. I looked up the categorical color map in the column tag and it looks right — the last color code on the screenshot below represents orange color and yet the distribution gets it wrong.

![image](https://user-images.githubusercontent.com/25188402/164803448-391239e2-cd03-4f69-a063-ec3761c38497.png)

**Comment by StLeonidas** [comment]
Is this relevant?

**Comment by vdyma** [comment]
Yes, it is relevant and help is needed.
