### ISSUE TITLE
[Structure similarity] Min score range adjustment & column picker

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#510]
As a User I'd like to have following options in the Structure Similarity search:

1. **Added Column picker** so I can change the structure column that is being compared
2. **Adjusted Min Score parameter range** so I can define only values from range <0, 1>

![image](https://user-images.githubusercontent.com/99964535/164719114-970891c2-78b8-4797-bab8-7d4600814d25.png)

**Comment by MariaDolotova** [comment]
Hi @RobertStrulak ! Just to confirm - when talking about min score range do you mean that you also need to set some range for search (like from 0.1 to 0.8). Or do you mean that it should not be possible to pick values <0 or >1 for this field?

**Comment by RobertStrulak** [comment]
Hi @MariaDolotova we'd like to be able to pick any value from 0 to 1 range. 
Examples: 0.1, 0.25, 0.8, 0.9, 1

**Comment by MariaDolotova** [comment]
@RobertStrulak , now it is possible to choose required min score by entering a number manually into the field (please see the gif below. MinScore has been also renamed to CutOff). Is this a convenient way for you? Or do you want to use slider appearing when you hover over the score field? Cause indeed the slider is not applicable at the moment. Cause it has step equal to 1.
![cutOff_selection](https://user-images.githubusercontent.com/44060410/165349933-9f149cdf-2d1d-4069-b0ea-0d5524a05180.gif)

**Comment by skalkin** [comment]
Looks good, but it should be "Cutoff" and not "CutOff"

**Comment by katerina-stepanova** [comment]
Remaining issues:
 'Cut Off' slider is from 0 to 100 with step = 1 and is not usable because of this.
 'Limit' slider is also from 1 to 100 no matter how many rows there are in the table.

**Comment by RobertStrulak** [comment]
@skalkin  - please take a look at @katerina-stepanova comment ^^
