### ISSUE TITLE
[LineChart] - axes do not scale to plotted points but to max values of plotted columns

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#526]
Axes on the LineChart do not scale to plotted points but to the maximum values of plotted columns.

**The current behavior:**
![image](https://user-images.githubusercontent.com/99964535/165120913-0400b294-8339-4d9d-9ccb-4dd9e2e832dc.png)

**The expected behavior:**
![image](https://user-images.githubusercontent.com/99964535/165120985-669eb3f6-eca3-47dd-b6d6-a258ca478a6f.png)

**Comment by skalkin** [comment]
Implemented in v150. This likely fixes the other old issue with the trellis plot:

![image](https://user-images.githubusercontent.com/943403/165300683-30173ea1-02e4-4bc0-a464-0844277c6e2d.png)
