### ISSUE TITLE
Grid options don't return default values

### ISSUE THREAD

**Issue by dgosi** [datagrok-ai/public#527]
In the snippet below the grid's row height and column header height are not returned even though the corresponding flag in getOptions(true) is set to true

const view = grok.shell.addTableView(grok.data.demo.molecules());
    const options = view.grid.getOptions(true);
    const nRH =  options.look.rowHeight;
    const nCH = options.look.colHeaderHeight;

Is there an alternative way to retrieve those values?

**Comment by skalkin** [comment]
Fixed in v0.153

**Comment by dgosi** [comment]
Row height is fixed, but colHeaderHeight still returns null
