### ISSUE TITLE
Tutorials package

### ISSUE THREAD

**Issue by skalkin** [datagrok-ai/public#53]
A collection of interactive tutorials 

* Interactive hints
* Tracks (collections of tutorials)
    * Exploratory data analysis
    * Machine learning
    * Cheminformatics
* Badges

**Comment by onuf** [comment]
Tutorials:

- [ ]  Scatter Plot
- [ ] Viewers
- [ ] Filters
- [ ] Data Aggregation
- [ ] Scripting
- [ ] Predictive Modeling
- [ ] Multivariate Analysis
- [ ] Data Connectors
