### ISSUE TITLE
#54: ClinicalCase package

### ISSUE THREAD

**Issue by skalkin** [datagrok-ai/public#54]
Provides support for dealing with clinical data represented in the SDTM format

Sources: https://github.com/datagrok-ai/public/tree/master/packages/ClinicalCase

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14742

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16005
