### ISSUE TITLE
[Formula Lines] Columns with parentheses in its names used in Bands' formulas breaks Formula Lines rendering

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#542]
**Steps to reproduce:** 
1. Add a Scatter Plot
2. Set one of axes to a column with parentheses in its name
3. Try to add Band through the Formula Lines dialog

**Expected results:** 
- Bands and other Lines are rendered correctly

**Actual results:**
- Column with parentheses in its name on Y axis used in Horizontal Band formula breaks entire Formula Line engine (non line is rendered)
- Column with parentheses in its name on X axis used in Vertical Band formula  breaks entire Formula Line engine (non line is rendered)

![6BAAEB4C-2E7F-439B-8579-F0A45BBCC4E4](https://user-images.githubusercontent.com/99964535/166438826-f93b103f-0c99-4522-ba1f-b5913be5574f.GIF)

**Comment by alex-aprm** [comment]
Fixed, version > 0.151.5
