### ISSUE TITLE
Implementing Typed Column classes in DG TS API

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#548]
The ticket is related to the issue with conversion of Date columns SQL response into a dataframe.
The potential solution was investigated by @aparamonov-datagrok that is:

_"We need to implement Typed Column classes in DG TS API to completely solve this.
For now, DG core returns a number as a value of Date Column, and it's nearly unusable on JS side."_

**Comment by onuf** [comment]
@RobertStrulak @skalkin it seems we have a duplicate issue: https://github.com/datagrok-ai/public/issues/588. The changes have been implemented, so this ticket can be closed.
