### ISSUE TITLE
#553: Grid shows names of hidden columns

### ISSUE THREAD

**Issue by tanas80** [datagrok-ai/public#553]
Steps to reproduce:
1. Open MolecularLiabiltyBrowser app.
2. Hide any column (for example 'cdr length').
3. Observe the names of the hidden columns shown centered between remained columns.
![MLB-grid-hidden_columns_names](https://user-images.githubusercontent.com/3798326/166681768-cd652c90-1dd1-46bd-aeb8-a888430f02dc.gif)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14929
