### ISSUE TITLE
No data displayed on a line chart using linked table in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#561]
**Steps to reproduce**
1. Open two tables: table1 and table2 (could have same contents)
2. Link those tables, using SELECTION_TO_FILTER type, e.g.
    let df1 = grok.shell.table('table1');
    let df2 = grok.shell.table('table2');
    grok.data.linkTables(df1, df2, ['id'], ['id'], [DG.SYNC_TYPE.SELECTION_TO_FILTER]);
3. Select one row in the table1 (one row will be displayed in the table2)
4. Add a line chart to the table1 and open its properties
5. Change X axis column from the default one
6. Change 'Row source' to 'Selected', than back to 'Filtered'
7. Change table to table2 > line chart is mostly empty because there is only 1 row
8. Select all rows in table1

**Expected results:** line chart for table2 is updated when more rows are selected in table1, causing more rows shown in table2.
**Actual results:** line chart is still empty.
Workaround: line chart is updated on double click (works for line chart with single column)
Trellis plot with line charts is affected too.

Example data that can be used for table1 and table2 (save as 2 csv files and import both):
id,cat,cor1,cor2,cor3
1,AA\nDD\EE,1,2,3
2,AA,4,5,6
3,BB,7,8,9
4,CC,10,11,12
5,BB,13,14,15
6,CC,16,17,18
7,DD,19,20,21
7,EE\nFF\nZZ\nMM,22,23,24

**Comment by RobertStrulak** [comment]
@skalkin - could take a look at this one? For the time being it's the last one that is still blocking us.

**Comment by skalkin** [comment]
Looking into it, will provide an update later today

**Comment by skalkin** [comment]
This seems to work for me, here's the script I've used and the outcome:

function getT() {
  return DG.DataFrame.fromCsv('id,cat,cor1,cor2,cor3\n2,AA,4,5,6\n3,BB,7,8,9\n4,CC,10,11,12\n5,BB,13,14,15\n6,CC,16,17,18\n7,DD,19,20,21');
}

let df1 = grok.shell.addTableView(getT()).dataFrame;
let df2 = grok.shell.addTableView(getT()).dataFrame;

grok.data.linkTables(df1, df2, ['id'], ['id'], [DG.SYNC_TYPE.SELECTION_TO_FILTER]);

![Animation](https://user-images.githubusercontent.com/943403/167501403-a52cffaa-6adf-463f-b2ac-0cb2d4f3e70c.gif)
