### ISSUE TITLE
Chem: Molecule filter doesn't appear despite column's semantic type

### ISSUE THREAD

**Issue by dskatov** [datagrok-ai/public#568]
Previously, when selecting filter on this specific column, a molecule filter was present first.

Now, no molecule filter is present in the whole set of filters.

![NoLongerAppears](https://user-images.githubusercontent.com/67762377/167127236-040d17c3-a043-435f-98c5-287d0696ac63.gif)

**Comment by skalkin** [comment]
This has been fixed in Datagrok v1.7.0
