### ISSUE TITLE
Compute: "Load file" button

### ISSUE THREAD

**Issue by dskatov** [datagrok-ai/public#570]
External input data often comes in an Excel file with several sheets.

Currently, loading a file from disk or from a separate file storage in Datagrok is only possible with drag-and-drop of the file into the platform, and then matching multiple dataframes extracted from the Excel in input dataframes' dropdowns inside the model's input interface.

There are several drawbacks to this:

1. Requires several actions from the user instead of one focused action, and requires the user to be educated on doing it

2. May introduce an inconsistent state in some of the UIs, where the dataframe selection dropdown is empty, and increases the number of UI states in general

3. Complicates matters when the user works with several input files at once. For example, when consecutively editing the template file on his/her computer and then loading it into the model again and again. In this scenario, several dataframes of identical names, corresponding to sheet names, will appear, even if the entire input file was named distinctively. This makes it hard to orient within these many dataframes

There is a consistent request from the users and stakeholders to cover this scenario via a single button.

We need to come up with an agreed design for such button.

**Comment by AufarZakiev** [comment]
![20 06 2022_10 58 33_REC](https://user-images.githubusercontent.com/5558521/175287999-20af9ba6-2cbe-4578-b102-53904b96100a.png)
Have made it on the top of `ui.stringInput` with Excel file blob returning
