### ISSUE TITLE
Compute: Input validation

### ISSUE THREAD

**Issue by dskatov** [datagrok-ai/public#573]
Generalize input validation (disable "Run" button + hint balloon + markup to specify the hint text).

**Comment by dskatov** [comment]
This has two pieces:

1. A simple validator possible to specify in the calculator markup.
2. A mechanism for simple adding of the validation to the custom-developed apps.

**Comment by AufarZakiev** [comment]
Resolved with adding "valdiatorFunc" tag for inputs
