### ISSUE TITLE
#596: Grid: sidescroll makes a back page move instead of scrolling to the beginning of the spreadsheet

### ISSUE THREAD

**Issue by onuf** [datagrok-ai/public#596]
Sidescroll doesn’t work properly in the table view. Sidescroll (at least on a Macbook) scrolls the panel just a bit and then makes a back page move. Might be browser or OS-related.
![image](https://user-images.githubusercontent.com/56073962/168550526-6ce105b9-47c0-4ee5-b54c-4ab056ab2e7e.png)

**Comment by onuf** [comment]
@skalkin is this ticket assigned to me intentionally? Asking for confirmation because the grid issues are usually assigned to people responsible for viewers in the core 😅

**Comment by skalkin** [comment]
Probably not, thanks for noticing :)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14800

**Comment by dionissqq** [comment]
finally closed it
