### ISSUE TITLE
Extending UNDO mechanism (views closing, axes changes)

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#600]
After reviewing the list of currently supported operations (https://github.com/datagrok-ai/public/blob/master/help/overview/undo.md) we'd like to request for following extensions to the UNDO mechanism:

- Supporting views closing
- Supporting axes changes

**Comment by skalkin** [comment]
> Supporting axes changes

Looks like this one is no longer necessary after we fixed #648

**Comment by skalkin** [comment]
@alex-aprm, we can close this issue if you have implemented undo for closing views
