### ISSUE TITLE
PC plot improvements (interactivity, grouping, axes normalization, log scale changes)

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#601]
PC plot is extended with following options:
- Interactivity 
Possibility to click on the plot to select / highlight rows (the expected behavior similar to the ScatterPlot)

- Grouping 
Adding option to group by a categorical column
Once grouping is applied there should be an option to select aggregator for each plotted column independently
Default aggregator: Average

- Log scale improvements
"Log columns" modal should be consisted only of a subset of columns  (the ones that are currently plotted)

**Comment by katerina-stepanova** [comment]
v1.8.2
PC Plot transformations issues:
1. There is no way to scroll through the columns selection. If table has too many columns, some of them won't be available. For example see SPGI dataset:
<img width="560" alt="image" src="https://user-images.githubusercontent.com/15780643/199493652-7d95b7c4-53a0-42f4-9767-96db447479ff.png">
2. Transformations dialog can become too wide on adding columns in some cases. Tested on SPGI dataset:
![2022-11-02_16-02-57 (1)](https://user-images.githubusercontent.com/15780643/199496858-f93b0c5c-0e1f-44fe-a6e5-8f8a54635dd4.gif)
