### ISSUE TITLE
[Filer panel] Substructure search improvements

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#608]
As a MedChem team member, I would like get the improved version of the Substructure Search in the filter panel, so I can flexibly modify my filtering criteria.

Acceptance criteria:
- Structures are sketched in a modal that gets opened upon clicking on a structure (pencil icon ?)
Important - a modal with sketcher does not block the UI
More than one modal can be opened at the same time

- Substructure filters get disabled upon hitting ESC button (the structure itself does not get removed / cleaned)

- Substructure filters can be added to the filter panel upon right-clicking on the row in a table and selecting "Use as Substructure Filter"
In case it's added from a structure column the respective structure is used to prepopulate the filter
In case it's added from a non-structure column the main structure ("Structure") is used to prepopulate the filter
Selecting a new structure results in replacing a previously selected / sketched one

**Comment by RobertStrulak** [comment]
@RobertStrulak - to confirm "Substructure filters get disabled upon hitting ESC button (the structure itself does not get removed / cleaned)"

**Comment by katerina-stepanova** [comment]
@skalkin Where is this option located:
Substructure filters can be added to the filter panel upon right-clicking on the row in a table and selecting "Use as Substructure Filter"
?
In DG 1.2.1, chem 0.52.12 I could not find it in context menu on clicking a table row (checked sub-menus as well):
<img width="421" alt="image" src="https://user-images.githubusercontent.com/15780643/173047439-610b19ef-a721-41a9-870a-0de9f9dc61ba.png">
