### ISSUE TITLE
Inconsistent rows highlighting after using ctrl + a when some data is filtered out

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#609]
**Steps to reproduce:**
1. Open project
2. Apply some filtering
3. Hit CTRL + A in a table with some data filtered out
4. Hit ESC

**Expected result:**
Only rows that were selected when the table was filtered out are highlighted

**Current result:**
Rows that were selected when the table was filtered out are highlighted, but all others are marked with a slightly different coloring too.

![2022-05-18_11-47-39](https://user-images.githubusercontent.com/99964535/169010993-46473c80-efe2-4bdd-9773-ef9b01077445.gif)

**Comment by ahadzhanian** [comment]
Can't reproduce on 1.15.3
