### ISSUE TITLE
Charts: TreeView

### ISSUE THREAD

**Issue by skalkin** [datagrok-ai/public#619]
Develop a viewer that would visualize a dataframe using a hierarchical tree, which is constructed based on the split columns selected by the user. This would be useful for both understanding a dataset, and navigating in it.

For instance, give the demog dataset and split = [sex, race], we would see the following:

```
> M
  > Asian
  > Caucasian
  > Other
> F
  > Asian
  > Caucasian
  > Other
```

- [ ] interactivity (filter, mouse-over, selection)
- [ ] automatic choosing of the initial split
- [ ] first version: only categorical columns; next: binning of numerical columns
- [ ] indicating the number of rows that fall into each category

**Comment by skalkin** [comment]
@onuf , not sure if we still need it since you've implemented a similar functionality in Charts

**Comment by onuf** [comment]
It seems that `TreeViewer` covers this. Plus, we have `ui.tree` for the standard tree component.
