### ISSUE TITLE
Scaling Structures used on the ScatterPlot axes (X axis Height and Y axis Width parameters)

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#639]
Issues / questions:
-  "Y axis Width" parameters seems to be not working
- There is big difference in the size of structures rendered on X and Y axes
- What is the heuristic that stands behind selecting structures to render?

![F9BBED08-461F-40DB-AFF8-481050CEE361](https://user-images.githubusercontent.com/99964535/169850388-a716383e-b978-4ce1-80ee-ff1328012cd5.GIF)

**Comment by skalkin** [comment]
@dionissqq , did you fix the issue with the structure size as well?

**Comment by katerina-stepanova** [comment]
Structures on X axis are not scaled based on axis height.

**Comment by RobertStrulak** [comment]
Please take a look at Ekaterina's comment ^^

**Comment by dionissqq** [comment]
fixed in v1.5.2

**Comment by dionissqq** [comment]
you will also need the latest version of chem and js-api for this one
