### ISSUE TITLE
#64: ClinicalCase: study summary view

### ISSUE THREAD

**Issue by skalkin** [datagrok-ai/public#64]
* subject enrollment chart
* basic statistics (numbers of subjects, distribution for SEX / RACE / AGE)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14746

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16008
