### ISSUE TITLE
How to switch Structure Search to categorical filter

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#640]
In the past there was an option for structure columns to switch between structure sketcher and categorical filter. Is that still possible?

**Comment by skalkin** [comment]
This feature is brought back. Requires `Datagrok v1.2` and `Chem v0.52`.

To turn it on programmatically, set the following column tag:

```
col.tags['.ignore-custom-filter'] = 'true';
```

![image](https://user-images.githubusercontent.com/943403/170785594-a27f11ca-be88-43f5-a462-9efc732a9f9a.png)
