### ISSUE TITLE
Autodetection of Structure columns imported from external files

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#642]
The semantic detection applied for "molecule column" is based on the column name not on the column values.
Currently only columns with the name "Structure" are detected and properly rendered.
Would it be possible to analyze values instead of columns names?

**Comment by RobertStrulak** [comment]
@skalkin  - which version will include that?

**Comment by onuf** [comment]
@RobertStrulak DG versions `>1.3.1`

**Comment by katerina-stepanova** [comment]
DG 1.3.5, chem 0.52.12
@skalkin Autodetection does not seem to work for imported csv files (both mol blocks and smiles):
<img width="701" alt="image" src="https://user-images.githubusercontent.com/15780643/173865581-d0631966-27d4-420f-9a4d-2636c16b41c9.png">
<img width="585" alt="image" src="https://user-images.githubusercontent.com/15780643/173865746-313e6d2b-9932-4099-a612-621dec1e9112.png">

**Comment by skalkin** [comment]
Will provide the details on the build numbers a bit later

**Comment by katerina-stepanova** [comment]
@skalkin Auto-detection is still not working for R*-family columns in ID.

**Comment by skalkin** [comment]
R-groups are now detected in `Chem 1.0.2`, check it out on https://dev.datagrok.ai

![image](https://user-images.githubusercontent.com/943403/174792314-6e71fda3-9a28-4065-95bd-d0e692ddaf3a.png)
