### ISSUE TITLE
Regression lines are broken after switching axis type to log

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#643]
![CEB1B78F-0640-4828-B2ED-71AC75725989](https://user-images.githubusercontent.com/99964535/169855037-c2999929-12fa-46b7-9e9b-d8e6164f515f.GIF)

Please also verify how switching axes to log works with formula lines

**Comment by RobertStrulak** [comment]
@RobertStrulak  - to provide the expected behavior

**Comment by skalkin** [comment]
@dionissqq , for the time being let's just not show regression line when either of the axes is in log mode. See `regression_line.dart`.

**Comment by JianmeiFan** [comment]
@skalkin As we discussed today, it would be nice to automatically change the axis value to log in the regression line calculation when user change axis to log. This way the line will be still straight.
For example:
![image-2022-05-17-15-06-43-727](https://user-images.githubusercontent.com/100243033/183699392-3cce1fd1-5867-4c9c-b7f8-3bf9ee723d8f.png)
The other frequently asked by user is R2 value, could it be shown with regression line? user need to see it to know the quality of the regression line. Thank you!

**Comment by skalkin** [comment]
@dionissqq , let's see if we can do the same

**Comment by dionissqq** [comment]
Fixed in v1.8.2
r2 values added as well
