### ISSUE TITLE
ChemblApi: integration

### ISSUE THREAD

**Issue by vdyma** [datagrok-ai/public#650]
Implement Chembl Similarity and Substructure search

**Comment by skalkin** [comment]
As a SQL query, right? But doesn't it already exist?

**Comment by vdyma** [comment]
@skalkin It is WIP, there are errors in implementation. I created this issue to assign to the branch [vdyma/#650-chemblapi](https://github.com/datagrok-ai/public/tree/vdyma/%23650-chemblapi).
