### ISSUE TITLE
Grid: No auto new line when editing and '+' available

### ISSUE THREAD

**Issue by dskatov** [datagrok-ai/public#655]
By A.Sharapov:
> A table viewer when there is an option to add rows via '+' should not add rows on editing last row data. Also it will be good to have a possibility to delete rows.

![NoNewRow2](https://user-images.githubusercontent.com/67762377/170474624-9a00d3fc-5a59-4bf1-b295-ca748d2e7182.gif)

**Comment by skalkin** [comment]
Implemented in `Datagrok v1.2.1`.

The following properties control the editing behavior:
```
allowEdit
showAddNewRowIcon (requires allowEdit)
addNewRowOnLastRowEdit (requires allowEdit)
```
