### ISSUE TITLE
#659: Compute: Freely editable models metadata for Model Catalog hierarchy

### ISSUE THREAD

**Issue by dskatov** [datagrok-ai/public#659]
Currently, the only way to edit these metadata is to change the model code and re-deploy.
This is a long round-trip and requires access to models' code.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14930

**Comment by AufarZakiev** [comment]
No changes for this issue for a long time + no requests from users about it. Will close it for now.

Feel free to reopen if needed
