### ISSUE TITLE
Help in dialogs doesn't work

### ISSUE THREAD

**Issue by vdyma** [datagrok-ai/public#66]
When question mark is clicked in a dialog window, it doesn't lead anywhere even if `helpUrl` is set and valid.

Example of such behavior can be found in JS API Examples `ui/dialogs/dialogs.js`.

**Comment by adrkn** [comment]
When you click on the question mark of a dialog box - the help associated with this dialog opens in the bottom right corner of the platform. Datagrok automatically shows the available help for all currently active controls and windows.

Often there is really useful information on the use cases of the objects you are working with.

![tg_image_2543789919](https://user-images.githubusercontent.com/23166434/130044275-93148109-f124-4d19-a34d-3f70678a1a23.jpeg)
