### ISSUE TITLE
Chem: Kekularization in .get_mol

### ISSUE THREAD

**Issue by dskatov** [datagrok-ai/public#664]
Based on the commits from @ptosco in the picture below, it's possible that `.get_mol()` crashes with `kekulize: true`, which also appears to be `on` by default. There are many other places with `.get_mol()` with both default and explicit `kekulize: true`, where such possible crash isn't taken into account.

![image](https://user-images.githubusercontent.com/67762377/170889076-185b9b9c-6ca2-4b37-bbd7-096f008ee8c7.png)

We need to understand a general strategy with this option and if we need to handle it in a special way.

**Comment by skalkin** [comment]
Shouldn't this be fixed in the RDKit? Do we have a corresponding issue in their tracker?

**Comment by ptosco** [comment]
@skalkin I wouldn’t say this is a bug. Attempting to kekulize a molecule that cannot be kekulized is bound to fail. A solution is trying again with kekulization switched off. If also that fails, you try with sanitization switched off. Trying to handle this in the WASM layer given that support for exceptions is switched off is quite difficult without major code refactoring.
You can check the following function for a way to do this efficiently:
https://github.com/rdkit/rdkit-structure-renderer/blob/325eb748b8e25589496bda35951fc20dcf0a36ab/src/StructureRenderer/utils.js#L120
By the way, as soon as I have finished migrating our internal apps to the new renderer my plan is also switch DataGrok to using the new renderer for all renderings, so we do not duplicate code and efforts.
But for the time being feel free to use or take inspiration from that function.
