### ISSUE TITLE
Properties panel is showing data for viewer from another table/view in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#667]
**Steps to reproduce**
1. Open table1 and add a viewer, e.g. scatter plot
2. Open table2 and add a viewer, e.g. a histogram
3. Open properties panel for a viewer in table2 and change something
4. Switch to table1 and click cog icon for a viewer
**Expected results:** properties panel should show properties for selected table1's viewer (selected on step 4).
**Actual results:** properties panel is still showing properties for table2's viewer (selected on step 3). Closing/reopening properties panel or adding other viewers does not change anything, properties panel is still showing properties for table2's viewer.

**Comment by skalkin** [comment]
This issue was fixed sometime in June
