### ISSUE TITLE
#671: 'Formula lines' dialog preview is not updated if scatter plot configuration is changed

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#671]
**Steps to reproduce:**
1. Open a table
2. Add a scatter plot
3. Right click > Tools > Formula lines...
4. Add a formula line
5. Make changes to one of the axes:
change column
OR change from linear to logarithmic
OR invert axis
6. Right click > Tools > Formula lines...

**Expected results:** preview in 'Formula lines' dialog should be updated according to current scatter plot axes configuration.
**Actual results:** preview in 'Formula lines' dialog is not updated when axes are changed:
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/15780643/171618252-103154a8-36ef-46da-a434-2cadf0cb6b26.png">
preview is not updated when axis switched to logarithmic:
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/15780643/171618729-7880f07b-f53c-4df6-98a8-1cf93521ad82.png">
preview is not updated on reverting axis

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14600

**Comment by ahadzhanian** [comment]
DG 1.18.0

**Comment by ahadzhanian** [comment]
When you open the FormulaLines dialog, a list of all specified lines is displayed, and the axes corresponding to the current formula line are displayed in the preview.
If lines are not specified, then the axes in the preview in the dialog correspond to the axes on the plot
![FormulaLInes](https://github.com/datagrok-ai/public/assets/111368431/906f0f14-d18a-4220-ade6-5b7f26a4d2ad)
