### ISSUE TITLE
#689: [Calculated columns] - Min() and Max() are not compatible with date and datetime columns

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#689]
**Acceptance criteria:**

- Min() and Max() functions should be compatible with date / datetime columns

**Comment by alex-aprm** [comment]
Done in 1.4.3 or higher

**Comment by katerina-stepanova** [comment]
DG 1.4.14
@alex-aprm Min/Max does not look compatible with date/datetime columns.
Example to reproduce the issue:
1. Open a table with date or datetime columns, e.g. [DatesSimple.csv](https://github.com/datagrok-ai/public/files/9148575/DatesSimple.csv)
2. Create calculated column with formula using Min/Max and date or datetime columns, e.g. Max([${Date1},${Date2}])

**Expected results:** resulting calculated column should be date or datetime column, its values should be as expected.
**Actual results:** default column type when date/datetime columns are used with Min/Max is not datetime. Values are wrong if column type left as is, nulls if type is changed to datetime manually:
<img width="691" alt="image" src="https://user-images.githubusercontent.com/15780643/179952391-efdfa910-9288-4c49-a784-35e40d16edab.png">
<img width="529" alt="image" src="https://user-images.githubusercontent.com/15780643/179953646-a861b3c3-9e02-483c-b384-15575f4027b6.png">

**Comment by RobertStrulak** [comment]
Reopening the issue given Ekaterina's comment

**Comment by alex-aprm** [comment]
Fixed the issue, in > 1.5.4

**Comment by katerina-stepanova** [comment]
v1.9.2
Issue described in comment above can be still reproduced: default column type when date/datetime columns are used with Min/Max is not datetime. Values are wrong if column type left as is, nulls if type is changed to datetime manually

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14603

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16062
