### ISSUE TITLE
Bio: port Clustal algorithm to TypeScript

### ISSUE THREAD

**Issue by skalkin** [datagrok-ai/public#69]
This will be used for the client-based multiple sequence alignments across our bioinformatics solutions when it's computationally feasible (examples: peptides).

@StLeonidas , which algorithms are we implementing exactly (ClustalV / ClustalW / ClustalOmega / etc)?

**Comment by StLeonidas** [comment]
@skalkin, @sasha-tsepilova, For multi-sequence alignment we are going to use ClustalOmega.

**Comment by sasha-tsepilova** [comment]
> This will be used for the client-based multiple sequence alignments across our bioinformatics solutions when it's computationally feasible (examples: peptides).
> 
> @StLeonidas , which algorithms are we implementing exactly (ClustalV / ClustalW / ClustalOmega / etc)?

Clustal Omega.
