### ISSUE TITLE
Structure filter: clicking 'x' or 'Cancel' on sketcher dialog result in inconsistency between filter applied and structure in filter panel

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#697]
DG 1.2.1, chem 0.52.12
Open a table containing structure columns (e.g. SPGI dataset)
Open filters panel and add a structure column as filter

**Case 1: draw new structure:**
1. Add structure column to filter
2. Open sketcher, draw new and click Cancel
**Expected results:** nothing is filtered after clicking Cancel, no structure shown.
**Actual results:** <img width="548" alt="image" src="https://user-images.githubusercontent.com/15780643/173004156-cdc192d4-70e2-43b0-8a40-9b69182060ee.png">
3. Remove and re-add structure column as filter
4. Open sketcher, draw new structure and click 'x'
**Expected results:** nothing is filtered after clicking Cancel, no structure shown.
**Actual results:** <img width="541" alt="image" src="https://user-images.githubusercontent.com/15780643/173004331-3aefaf83-04ea-4292-acab-dce7c3ff7e82.png">

**Case 2: update structure**
1. Draw some structure and click OK on the sketcher
4. Re-open sketcher and update drawn structure
5. Click 'x' or 'Cancel' on the sketcher
**Expected results:** Clicking 'x' or 'Cancel' should discard the changes to the structure made since dialog was opened. Structure shown in filter panel and actual filtering should be the same.
**Actual results:** Actual filter set and structure shown in panel are different:
![2022-06-10_09-13-32 (1)](https://user-images.githubusercontent.com/15780643/173003494-8a887636-1414-470b-ac0c-0aba84291745.gif)
![2022-06-10_09-23-47 (1)](https://user-images.githubusercontent.com/15780643/173003742-cb9352ad-b28c-4dbb-9d5e-dfc3ae2ee6b9.gif)

Can be reproduced both for MArvinJS and Open Chem Sketcher.

**Comment by skalkin** [comment]
Are you sure you were clicking on CANCEL, and not hitting ESC or the "x" sign? Sorry I no longer have `DG 1.2.1, chem 0.52.12` locally

I was able to reproduce and fix the issue #703, but Cancel worked fine for me. You can test it on our latest dev (fix for #703 is not there yet) .

**Comment by katerina-stepanova** [comment]
@skalkin I can reproduce this issue on 1.2.1 (I'm sure I click Cancel, not ESC or 'x'). I'm on Mac OS, if that matters.
https://dev.datagrok.ai/ has been unavailable for a while, so i cannot verify there.

**Comment by RobertStrulak** [comment]
@skalkin @alex-aprm @katerina-stepanova 
Today we had another discussion on the expected behavior of the dialog for sketcher.

This is what we've decided:

1. "Cancel" button is removed 
2. "OK" is renamed to "CLOSE" - **its behavior stays intact**
3. "X" button behaves exactly as "OK"

**Comment by alex-aprm** [comment]
Both cancel and close buttons should discard changes and revert table filtering.

Now is doesn't discard changes if structure was empty, and doesn't refresh structure thumbnail in filters

**Comment by StLeonidas** [comment]
@RobertStrulak, It now works with 2 buttons (see attached):
CLOSE - the sketched molecule and filter are conserved, all editing modifications are applied
X - last modifications are removed, the molecule presented in sketcher before opening is still there
Does that work for you?

![Sketcher_buttons](https://user-images.githubusercontent.com/57249456/174800678-05274a15-de41-426c-a1ac-a01a91626701.gif)

**Comment by katerina-stepanova** [comment]
Closing sketcher using 'x' button is still inconsistent.
**Case 1: adding new structure**
1. Add structure column to filter panel
2. Open sketcher
3. Draw a structure
4. Click 'x'
**Expected:** structure is discarded, filtering is reset
**Actual:** structure is not discarded, table is still filtered

**Case 2: modifying a structure**
1. Add structure column to filter panel
2. Open sketcher
3. Draw a structure
4. Click 'Close' > table is filtered, drawn structure is shown in filters panel
5. Open sketcher again
6. Change drawn structure
7. Click 'x'
**Expected:** changes done on step 6 are discarded both in table filtering and in structure image on filters panel.
**Actual:** changes done on step 6 are not discarded in structure image on filters panel, resulting in inconsistency between actual table filtering and structure displayed on filter panel:
<img width="564" alt="image" src="https://user-images.githubusercontent.com/15780643/175026671-ce912f29-9445-4905-ace7-f2e868411d24.png">
