### ISSUE TITLE
Valid formula line on scatter plot is not shown if one of the scatter plot lines is invalid

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#699]
DG 1.2.1

**Steps to reproduce:**
1. Open a table, e.g. SPGI dataset
2. Add a scatter plot with numerical columns on both axes
3. Add a valid Viewer formula line, e.g. Axis y = Axis x
4. Add an invalid Viewer formula line, e.g. Axis x + 1
5. Click OK on the dialog
**Expected results:** valid line should be displayed, invalid line should be ignored. Valid line also should be displayed in preview when selected.
**Actual results:** valid line is not displayed.
6. Save layout
7. Re-apply saved layout
8. Open formula lines dialog
9. Remove invalid line and click OK
**Expected results:**  valid line should be displayed.  Valid line also should be displayed in preview when selected.
**Actual results:** valid line is not displayed.

**Comment by skalkin** [comment]
Fixed in `Datagrok v1.4.2`
