### ISSUE TITLE
Compute: DG.Accordion allows panes dragging

### ISSUE THREAD

**Issue by AufarZakiev** [datagrok-ai/public#705]
### Description

DG.Accordion always to drag panes through UI. That is undesirable sometimes since the UI breaks. 

### Snippet
https://public.datagrok.ai/js/samples/ui/components/accordion 

### Video

https://user-images.githubusercontent.com/5558521/173817087-8d993544-1a22-4537-9757-2af005f35ffa.mp4

### Proposed solution
 Add option to DG.PaneControl's constructor. Smth like "allowDragging" with default value of true.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14932

**Comment by AufarZakiev** [comment]
Fixed in https://reddata.atlassian.net/browse/GROK-12304
