### ISSUE TITLE
[PC pot] line breaks on missing value

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#717]
In the current implementation of PC plot lines break on missing values (screenshot).
![image](https://user-images.githubusercontent.com/99964535/174782400-9c9e07cb-e2e6-42f3-8483-95606908e864.png)

Could that be fixed?

**Comment by skalkin** [comment]
The problem is that if we draw a line from column 2 to column 4, that would give an impression that it has a corresponding value in column 3, which is not true.

**Comment by skalkin** [comment]
Closing this issue since it works as intended; in the picture you've attached, just exclude the empty column from the viewer settings ("Column Names").
