### ISSUE TITLE
Grid: Add tooltip for Id column to show full Id names in heatmap.

### ISSUE THREAD

**Issue by Recca-Gottschall** [datagrok-ai/public#732]
Currently, if you zoom into the heatmap to see the values, the id column is too narrow to show the full Id names. A tooltip on hover over the Id cells would help.

Ideally, the Id column header could be resized but it was already mentioned that this might be technically challenging.

**Comment by dionissqq** [comment]
fixed in v1.4.14

**Comment by dionissqq** [comment]
fixed in v1.4.14
