### ISSUE TITLE
#74: Map doesn't show

### ISSUE THREAD

**Issue by vdyma** [datagrok-ai/public#74]
In the [google-map example](https://public.datagrok.ai/js/samples/ui/viewers/types/google-map) map doesn't show.

![Bug](https://user-images.githubusercontent.com/25188402/130062110-ea0b38fc-7026-4aa1-b1b0-1d01bc97ffa7.png)

**Comment by Aleksashka11** [comment]
Google Map viewer was retired. Check [Release Notes](https://github.com/datagrok-ai/public/blob/ee0a676fdca7a4fd9454f3f59f8a28ebd98653ea/help/deploy/releases/release-history.md?plain=1#L1631)

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14751
