### ISSUE TITLE
Changing tooltip is broken after setting tooltip through 'sketch' form

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#746]
Issue can be reproduced with DG 1.4.3 and 0.151.9

**Preconditions:**
1. Open a table
2. Add a scatter plot
3. Right click on table > Tooltip > Set Default Tooltip
4. Click 'Sketch form...'
5. Make some changes and click 'Close and apply'

**Case 1: changing default tooltip**
1. Right click on table > Tooltip > Set Default Tooltip 
2. select tooltip columns in column picker and click OK
**Expected:** default tooltip is updated, selected columns are shown in the tooltip.
**Actual:** tooltip sketched in 'preconditions' is shown.

**Case 2: scatter plot tooltip using column picker**
1. Right click on the Scatter plot > Tooltip > Set Scatter plot Tooltip 
2.  select tooltip columns in column picker and click OK
**Expected:** scatter plot tooltip is updated, selected columns are shown in the tooltip.
**Actual:** tooltip sketched in 'preconditions' is shown as scatter plot tooltip.

**Case 3: scatter plot tooltip using sketch form**
1. Right click on the Scatter plot > Tooltip > Set Scatter plot Tooltip
2. Click 'Sketch form...' > make some changes and click 'Close and apply'
**Expected:** tooltip is changed for scatter plot only.
**Actual:** default tooltip is changed instead of scatter plot tooltip.

**Comment by skalkin** [comment]
@onuf , did you address this one with your latest changes?

**Comment by onuf** [comment]
The cases #2 and #3 should be addressed in the PR with viewer-specific tooltips, and the first case has been fixed recently, I believe. Unfortunately, I can't verify it this week, as I'm on vacation without my laptop.

**Comment by onuf** [comment]
Fixed in DG 1.6.4
