### ISSUE TITLE
Bio: detectors and rendering sequences with HELM WE

### ISSUE THREAD

**Issue by StLeonidas** [datagrok-ai/public#752]
- [x] fasta + aligned sequences  (detector ability)
- [x] separators + aligned sequences (detector ability)
- [x] helm notation (detector ability)
- [x] HELM Web Editor for 'fasta' notation
- [x] HELM Web Editor for 'separator' notation

**Comment by tanas80** [comment]
![Image](https://user-images.githubusercontent.com/3798326/182876824-ee65d401-f0d1-4336-9351-2b48f85ffe00.png)

**Comment by tanas80** [comment]
![Image](https://user-images.githubusercontent.com/3798326/182876877-800e65f0-155c-43fd-bb49-fb666ca28da3.png)
