### ISSUE TITLE
[Bar chart] - issue with using the zoom slider

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#756]
In some cases the zoom slider on Bar chart is hidden and it's hard to get it enabled / visible. 
The issue has been captured on the video:
![F4B23558-7C7C-48B3-B3C5-07F817125899](https://user-images.githubusercontent.com/99964535/177199429-25a4a8a5-6109-475d-bbb3-d6389efcb751.GIF)

**Comment by dionissqq** [comment]
fixed in v1.4.16
