### ISSUE TITLE
[Tooltip] - hiding of the tooltip on the table hides it everywhere

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#757]
It looks like the option to hide a tooltip is binned to the dataframe, not to individual visualizations.

Acceptance criteria:
- The option to hide the tooltip is binned to the visualizations instead of entire dataframe
![3C5165A7-239B-429B-AD04-604BFCDB1B62](https://user-images.githubusercontent.com/99964535/177200119-0b70a2bb-2539-40fe-a708-7b2b38c2c4e8.GIF)

**Comment by onuf** [comment]
Implemented in DG 1.6.4
To hide a tooltip for a table (grid), set the grid property 'Show tooltip' to 'do not show' (it switches the tooltip to custom and hides it). 
![image](https://user-images.githubusercontent.com/56073962/187427941-22c8fbc0-10ab-4820-bf3a-ee95774c1907.png)
It can be done for all grids programmatically (`grok.events.onViewerAdded`), if this is the desired default behaviour for the ID app.

Viewers that use the default tooltip (grid, scatter plot, box plot + PC plot and heatmap in the future) now have two separate tooltip modes (custom and default). Such things as tooltip visibility, form template, selected columns for a tooltip are handled separately. Custom tooltips are set on a viewer instance level (e.g., if you have two grid viewers and want to hide tooltip on both, while using the default tooltip for other viewers, you'll need update properties for both grids).

Can be verified on https://public.datagrok.ai/ [release version 1.6.4]
In addition, you can find some test cases here: https://github.com/datagrok-ai/public/blob/master/help/_internal/tests/tooltip.md
