### ISSUE TITLE
[Tooltip] - using the option to sketch form for the tooltip completely breaks its responsiveness for further modifications 

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#758]
Once the option to sketch form for the tooltip is used there is no way to:
- hide it
- switch over to the default one (list of columns)

https://user-images.githubusercontent.com/99964535/177200997-aacf8d2d-50c5-453e-8a44-c201413ed159.MP4

**Comment by onuf** [comment]
DG version 1.4.12 includes the fix.

**Comment by onuf** [comment]
Thanks @katerina-stepanova I will check these issues and get back to you as soon as they are fixed

**Comment by RobertStrulak** [comment]
Reopening the issue given Ekaterina's comment

**Comment by onuf** [comment]
Fixed in DG 1.6.4
