### ISSUE TITLE
[Legend section] - width of the legend section does not scale to the length of its values

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#759]
When values in the legend sections are long there is no way to see them. One cannot modify the width of the section.
![9919B921-A1B7-41FF-80BD-70C760ACC95B](https://user-images.githubusercontent.com/99964535/177202188-ed1ce3da-3a6f-457d-97d6-eeaa9ac36e23.GIF)

**Comment by dionissqq** [comment]
fixed in v1.4.15

**Comment by katerina-stepanova** [comment]
@dionissqq Legend width can be modified, but values do not use available space:
<img width="714" alt="image" src="https://user-images.githubusercontent.com/15780643/180236289-d0f3b449-f38f-493e-82d9-c3a06d79155d.png">



DG 1.5.1

**Comment by RobertStrulak** [comment]
@dionissqq - please take a look at Ekaterina's comment

**Comment by dionissqq** [comment]
fixed in v1.5.2
