### ISSUE TITLE
Viewer legend is not synchronized with in-viewer filter

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#776]
**Steps to reproduce:**
1. Open a table, e.g. SPGI dataset
2. Add a viewer
3. Configure viewer so that legend is shown, e.g. color scatter plot by a categorical column, stack bar chart by a categorical column
4. Set up in-viewer filtering, so that some categories shown in the legend are filtered out
5. Check viewer's legend

**Expected results:** Viewer's legend should be synchronised with current in-viewer filtering (similar to filtering through filter panel)
**Actual results:** All categories are shown in the viewer's legend, even ones filtered out:
<img width="975" alt="image" src="https://user-images.githubusercontent.com/15780643/178534523-046f306e-8ae1-498e-835f-a8d63a0bb63b.png">

**Comment by skalkin** [comment]
@dionissqq Can we improve it?

**Comment by dionissqq** [comment]
Fixed in v1.8.1
