### ISSUE TITLE
Can not uncheck "Filter out missing values" after saving

### ISSUE THREAD

**Issue by JianmeiFan** [datagrok-ai/public#791]
Steps to reproduce:

Load a table, that has columns with "Filter our missing values" in filter.
Check "Filter out missing values"
Save layout
Open it
Uncheck "Filter out missing values"

Expected results: Unchecked

Actual results: "Filter our missing values" still checked.

https://user-images.githubusercontent.com/100243033/179136395-5760eada-c818-4b84-a65d-9581b4bb4506.MP4

**Comment by dionissqq** [comment]
fixed in v1.6.0
