### ISSUE TITLE
selecting dots in jittered scatterplot

### ISSUE THREAD

**Issue by JianmeiFan** [datagrok-ai/public#798]
When selecting a dot in a jittered scatterplot

1): An additional dot is displayed (likely at the un-jittered position). This is rather confusing.

2): sometimes the tooltip is covering the whole area as soon as the mouse reaches one of the dots and user can't see anymore which dot is selected (likely tooltip position is based on un-jittered position)

https://user-images.githubusercontent.com/100243033/179296962-97f9fba0-fa86-469a-becf-0d75027d827f.mp4

**Comment by dionissqq** [comment]
fixed in v1.5.2
