### ISSUE TITLE
Form does not work when scatter plot is zoomed

### ISSUE THREAD

**Issue by JianmeiFan** [datagrok-ai/public#801]
Steps to reproduce: 

1. open an analysis 2 create scatterplot 3 create a form 4 click any scatter plot data point 5 Form will show corresponding data point 6 zoom in scatterplot and click scatterplot data point

Expected results: 

Form should show corresponding data point

Actual results: 

Sometimes Form will not change based on the clicked date point.

**Comment by dionissqq** [comment]
fixed in v1.5.3
