### ISSUE TITLE
Data table: Change column type - some strange appearance

### ISSUE THREAD

**Issue by ShvyrloM** [datagrok-ai/public#805]
**Subject**: Change column type - some strange appearance
**Steps to reproduce**: In data table, chose “Actions->Change type..”, dialog-box will appear. In this dialog box there are some strange UI features: disabled drop-lists (marked with blue arrows, which as I guess user don’t need have ability to change. The second drop-list with current column type is not filled at all (marked with red arrow). And another one feature: autosizing of “Format” drop-list, it’s width jumping here and there, and for bool type it looks a little bit strange (marked with green arrow).

**Comment by ShvyrloM** [comment]
![Screenshot_ColDataType](https://user-images.githubusercontent.com/64889448/180035029-c383ab39-fbb8-4cb5-9676-602094ce40c4.png)

**Comment by skalkin** [comment]
Thanks for reporting it! This is fixed in Datagrok 1.8.3
