### ISSUE TITLE
Reordered selected columns

### ISSUE THREAD

**Issue by JianmeiFan** [datagrok-ai/public#810]
When selected columns to show, the orders of the columns are not expected. 

For example in this screen record, Billingid is first column to show, when later we add cost columns, these columns should be after Billingid columns instead of before it.

Particularly in ID, user usually like to have ID and structure columns in the front, but when they search and choose other columns later, these columns are put in the front.

**Comment by JianmeiFan** [comment]
https://jirasw.prd.nibr.novartis.net/secure/attachment/368200/Datagrok%20reordered%20columns.mp4

**Comment by JianmeiFan** [comment]
https://user-images.githubusercontent.com/100243033/179788140-66fa047b-8158-4299-a506-ca022d42789a.mp4

**Comment by katerina-stepanova** [comment]
Columns order is messed up after searching and adding a column:
1. Open 'smiles' dataset (present in public datagrok)
2. Open 'Order or hide columns...' dialog
3. Select only a few columns, e.g. 'molregno', 'canonical_smiles' and a couple of 'Num*Something*' columns
4. Open 'Order or hide columns...' dialog again
5. Search for 'Num' > several columns are found
6. Check one of the unchecked columns
7. Close the dialog

**Expected results:** Order of columns should be changed only if user does it explicitly. Searching in 'Order or hide columns...' should not affect columns order.
**Actual results:** All selected columns that were found in 'Order or hide columns...' dialog on searching for 'Num' were moved to the left.
![2022-07-20_11-27-39 (1)](https://user-images.githubusercontent.com/15780643/179936680-7f2a0ae1-2b1b-416d-bbf4-219896901a0e.gif)

**Comment by dionissqq** [comment]
fixed
