### ISSUE TITLE
Filtering set on a column is not saved on saving layout

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#823]
DG 1.4.14, 1.5.1
**Steps to reproduce:**
1. Open a table
2. Set some filtering on a column (e.g. uncheck some values for a categorical column): <img width="368" alt="image" src="https://user-images.githubusercontent.com/15780643/179992528-23277679-c0f2-42df-9820-67481fdc8ad0.png">
3. Save layout
4. Remove filtering on a column
5. Re-apply saved layout

**Expected results:** filtering on a column is saved with layout and is restored when layout is re-applied.
**Actual results:** no filtering on a column when layout is re-applied.

**Comment by skalkin** [comment]
We do not save filter states as part of the layout (otherwise it could be confusing). I'm closing the issue for now, but feel free to bring it up on our weekly meeting :)
