### ISSUE TITLE
Peptides: cache tooltips for barchart

### ISSUE THREAD

**Issue by vdyma** [datagrok-ai/public#844]
Cache barchart tooltips so that data is not recalculated if the mouse points at the same bar

**Comment by skalkin** [comment]
How expensive is the recalculation on a dataset of 1M peptides? Just give a rough estimate please - if it's too much, then likely the calculation itself should be improved

**Comment by vdyma** [comment]
@skalkin what I meant is caching the result that is currently used. Right now the data is recalculated for a single bar for any slightest mouse movement, event if the mouse didn't leave the bar it was pointing at. It results in recalculating the same data over and over when nothing is actually changed. What I want to do is caching result for a single bar that the user is pointing at.
