### ISSUE TITLE
Modal dialog desn't consume mouse events

### ISSUE THREAD

**Issue by dgosi** [datagrok-ai/public#854]
Modal dialog passes mouse events to the dom element located directly under if that element registeres a mouse listener. To reproduce, please register a mouse down listener on the document, open the grid's conditioonal dialog, click on the text area to edit values, The text area cannot obtain focus.

**Comment by skalkin** [comment]
Do you mean a mouse down listener that stops immediate propagation? Can you please share a script sample?

@dionissqq please look at it
