### ISSUE TITLE
#89: Add min, max, step options to viewer's numeric properties

### ISSUE THREAD

**Issue by vdyma** [datagrok-ai/public#89]
Currently it is not possible to set int and float viewer properties to be in specific range and they all default to range from 0 to 100 on a slider.

It would be useful to set `min`, `max` and `step` options for int and float properties like this:
`this.myIntProperty = this.int('myIntProperty', 0, {min: -10, max: 10, step: 2});`
`this.myFloatProperty = this.float('myFloatProperty', 0, {min: -1, max: 1, step: 0.2});`

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14754
