### ISSUE TITLE
Core: Charts: Histogram: reference distributions

### ISSUE THREAD

**Issue by skalkin** [datagrok-ai/public#91]
It is useful to be able to render reference pre-calculated distributions on top of the real, calculated ones. It would make sense to keep them with the dataframe in column tags. This would enable many scenarios, such as constructing a dataframe on a server or in a Python script.

Once a reference distribution is defined for a column, then the histogram (and filter) would automatically pick it up and show. 

I propose the following approach:

```
demog.weight.tags['.ref-distributions'] = `{
  'healthy': [2, 4, 45, 76, 45, 5, 5, 6, 2, 1],
  'sick': [3, 4, 56, 76, 45, 5, 5, 6, 2, 1],
}`;
```

**Comment by adrkn** [comment]
Implemented. Will be available for viewing on dev and public servers shortly.

Any curve can be displayed on top of the histogram. You can use the parameters to set the shape of the curve, its color, and thickness. The example below shows how to do this.

To see example of usage:

1. Open `Demog` dataframe.
2. Add tag `.ref-distributions` to column `AGE` with value:

    > { "healthy": { "values" : [169, 265, 272, 402, 367, 507, 465, 597, 461, 584, 554, 328, 347, 198, 195, 82, 39, 12, 3, 2], "color": "#109731", "width": 1 } }

3. Open Histogram.
4. You can change spline tension by the `Spline Tension` property on PP.
5. Property `Spline Tension` also affects charts displayed in split mode (`Split` property on PP).

**Comment by adrkn** [comment]
Added an **optional** parameter `x` for specifying points along the X axis. If this parameter is specified, the spline is drawn at the specified points of the X axis:

> { "healthy": { "values" : [9, 10, 100, 0, 50, 0, 100, 1, 0], "color": "#109731", "width": 1, "x" : [6, 7, 35, 40, 45, 50, 55, 100, 101] } }

If this parameter is not specified, the X axis is evenly divided by the number of values in the `values` array.

Added correct handling of splines outside the histogram range. The endpoints of the spline take on the correct values at the edges of the histogram.

Fixed a bug in the logic of processing `values` when drawing splines.
