### ISSUE TITLE
#910: GIS: Stress-test of the GIS module 

### ISSUE THREAD

**Issue by ShvyrloM** [datagrok-ai/public#910]
Prepare and perform stress-test of the GIS module to detect restrictions of Openlayers solution used for GIS module

- [ ] layers amount test
- [ ] test of max features (elements) amount

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14817

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16076
