### ISSUE TITLE
Improve contents of viewer context and property menus

### ISSUE THREAD

**Issue by pulveni1** [datagrok-ai/public#928]
The contents of the viewer context and property menus should be improved and cleaned-up, in order to reflect what most of the scientists would expect to find there.
Here is a proposal on how we would suggest the contents to look like by default:

/// document following shortly ///

**Comment by Recca-Gottschall** [comment]
[Property Panel and Context Menu.pdf](https://github.com/datagrok-ai/public/files/9290090/Property.Panel.and.Context.Menu.pdf)

**Comment by DanTkachev** [comment]
Additional improvements for the context menu:
https://github.com/datagrok-ai/public/issues/1375
https://github.com/datagrok-ai/public/issues/1376
https://github.com/datagrok-ai/public/issues/1377
https://github.com/datagrok-ai/public/issues/1378
https://github.com/datagrok-ai/public/issues/1381

**Comment by onuf** [comment]
@AnnaMuza please check if everything corresponds to the new design of viewer property menus (should be on dev tomorrow or earlier).
