### ISSUE TITLE
Peptides: peptide space

### ISSUE THREAD

**Issue by skalkin** [datagrok-ai/public#93]
Visualize a collection of peptides in 2-dimensional space, using [t-SNE](https://en.wikipedia.org/wiki/T-distributed_stochastic_neighbor_embedding) with the [edit distance](https://en.wikipedia.org/wiki/Edit_distance) function. Implement Peptide space feature similar to Chemical space feature in Chem package:

- [x] Implement an algorithm to calculate similarities for a pair of sequences (semtype - alignedSequence)
- [x] Use SPE algorithm to get 2d map of peptide sequences
- [x] Implement a new feature in the property panel of each column with alignedSequence values 
- [x] Implement embedding as a web worker to not slow down the main thread.
- [x] Benchmark UMAP performance on dataset of 40k sequences.

**Comment by StLeonidas** [comment]
Implement Peptide space feature similar to Chemical space feature in Chem package:
- [ ] Implement an algorithm to calculate similarities for a pair of sequences (semtype - alignedSequence)
- [ ] Use SPE algorithm to get 2d map of peptide sequences
- [ ] Implement a new feature in the property panel of each column with alignedSequence values

**Comment by nikolay-alemasov** [comment]
Do we really need to consider only alignedSequence? As I can remember string metrics can work on strings of different length as well.

**Comment by nikolay-alemasov** [comment]
Only this left:

1. Implement a new feature in the property panel of each column with alignedSequence values

**Comment by nikolay-alemasov** [comment]
I would also add the following task:

- [ ] Implement embedding as a web worker to not slow down the main thread.

**Comment by nikolay-alemasov** [comment]
In fact, the Peptide Space could be considered as ready with some minor bugs.

**Comment by nikolay-alemasov** [comment]
- [ ] Benchmark UMAP performance on dataset of 40k sequences.

**Comment by nikolay-alemasov** [comment]
Suggest to close the issue.
