### ISSUE TITLE
Vertical scrollbar is not working in Order or Hide Columns menu

### ISSUE THREAD

**Issue by VimalaSelvaraj** [datagrok-ai/public#932]
**Steps to reproduce:** Open an AC and the table view >Right Click> Open Order or Hide Columns menu > when we are rearranging the columns in the "Order or Hide Columns" menu.

The attached example the last few columns should be moved to the beginning of the table,
In the menu after you have selected the  columns, when you drag those columns the vertical scrollbar does not move, and we need to drop it every time and move the sidebar and then drag it again.  

**Expected results:** When you drag the column upfront and the vertical scrollbar also should move automatically

**Actual results:**  The vertical scrollbar doesn't move automatically

![show or order columns](https://user-images.githubusercontent.com/110638379/183714575-0426442f-d0c4-4d5c-8b9f-7b8f2f0a0dfc.gif)

**Comment by VimalaSelvaraj** [comment]
Thanks and I've tried with the latest version of datagrok and it appears the vertical scroll bar is having some minor glitches and based on up/down arrows the vertical scrollbar is not moving
![Latest version DG](https://user-images.githubusercontent.com/110638379/183772802-f445cf70-4ebd-450b-b1c2-1311ceb415fe.gif)
.

**Comment by dionissqq** [comment]
Done in v1.8.2
