### ISSUE TITLE
A few improvements on Treemap 

### ISSUE THREAD

**Issue by JianmeiFan** [datagrok-ai/public#935]
1. Highlight color should be consistent with others
When you create a Bar Chart, a Pie Chart and a Tree Map for the same categorical column, and click on one slice/bar/rectangle:
Bar Chart: its bar is highlighted in orange
Tree Map: its rectangle is highlighted but in yellow
Pie Chart: its slice is highlighted in orange
Could tree map highlight color be the same as others?
2. Can not select row source
3. Not sure if this is due to row source reason - when a first chart is set to OnClick = Filter, other charts will reflect on the filtering but treemap ignores the filtering

**Comment by dionissqq** [comment]
fixed in v1.6

**Comment by dionissqq** [comment]
Fixed in v.1.6.2
