### ISSUE TITLE
A few improvements on pie chart

### ISSUE THREAD

**Issue by JianmeiFan** [datagrok-ai/public#936]
1. Clicking on the "(no value)" slice doesn't select it
2. Click on slice to select: If you hover over the pie, the slice remains colored in its original color. Also, once colored in orange selection color, the label (category name and % value) is hidden

https://user-images.githubusercontent.com/100243033/184028931-a1044086-a316-4211-ab6e-a1c9b25d34ec.mp4

**Comment by dionissqq** [comment]
Fixed in Datagrok v1.6.0
