### ISSUE TITLE
#939: Ability to stop calculations

### ISSUE THREAD

**Issue by StLeonidas** [datagrok-ai/public#939]
There should be an ability to stop processes:
- [ ] that run in the browser
- [ ] that run on a server

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14822

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16080
