### ISSUE TITLE
Charts: Histogram: mark quartiles range

### ISSUE THREAD

**Issue by adrkn** [datagrok-ai/public#94]
Mark the quartiles Q1 and Q3 on the Histogram axe, highlight the area outside this range with filled rectangles. Set default filter markers to these values.

**Comment by skalkin** [comment]
This is not exactly what we discussed. The idea was to do the following:
- Ability to provide default filter ranges via column tags. When opened, filters would default to these values
- Ability to provide column segments via tags. They would be shown on all viewers that use corresponding columns.

**Comment by adrkn** [comment]
Implemented. Will be available for viewing on dev and public servers shortly.

You can use the parameters to set the size and color of each segment. The example below shows how to do this.
Numeric expressions are used to set the segment size. The example below creates segments showing the q1 and g3 quartiles on the histogram.

To see example of usage:

1. Open `Demog` dataframe.

2. Add tag `.data-band` to column `AGE` with value:

    > { "q1": { "rule" : "< 35", "color": "#aee3a4"}, "q3": { "rule" : "> 56", "color": "#fdf5b6"} }

3. Open Histogram.

**Comment by adrkn** [comment]
To set the initial positions of the sliders on the histogram, add tag `.default-filter` to column with value:

> { "min": 11, "max": 40 }

And then open Filter Panel.

To quickly do it you can execute this script:

```
//language: javascript

let df = DG.DataFrame.fromColumns([
  DG.Column.fromList(DG.TYPE.STRING, 'Let', ['A', 'B', 'C', 'D', 'E', 'F']),
  DG.Column.fromList(DG.TYPE.INT, 'Num', [10, 4, 76, 34, 12, 56]),
  DG.Column.fromList(DG.TYPE.INT, 'Num2', [5, 40, 12, 7, 50, 51]),
]);

df.col('Num').setTag('.default-filter', '{ "min": 50 }');
df.col('Num2').setTag('.default-filter', '{ "min": 11, "max": 40 }');

grok.shell.addTableView(df).addViewer(DG.VIEWER.FILTERS);
```
