### ISSUE TITLE
Form viewer: color does not match color in the table if table was sorted

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#940]
DG 1.5.1
**Steps to reproduce:**
1. Open a table [FormColors.csv](https://github.com/datagrok-ai/public/files/9308704/FormColors.csv)
2. Apply linear coloring to columns 'col2' and 'col4'
3. Sort table by col2
4. Add 'Form' viewer
5. Click through the rows and check data displayed in the Form viewer

**Expected results:** color in the Form viewer should be the same as color in the table.
**Actual results:** colors in the table and Form viewer do not match for some of the rows:
![2022-08-11_15-45-59 (1)](https://user-images.githubusercontent.com/15780643/184136361-7cffa90a-fda6-440b-b3cb-30c39debc894.gif)

**Comment by dionissqq** [comment]
fixed in v1.6
