### ISSUE TITLE
Grid: Frozen columns

### ISSUE THREAD

**Issue by skalkin** [datagrok-ai/public#952]
@dgosi , looks like this feature is implemented already; how do we use it?

**Comment by dgosi** [comment]
This feature is under NX testing. There are a few small issues related restoring pinned columns from view layouts (most likely related to the DG core). I will post the usage instructions here.

**Comment by dgosi** [comment]
To use pinned columns, please add the following to your package

import {PinnedColumn} from '@datagrok-libraries/gridext/src/pinned/PinnedColumn';
import * as PinnedUtils from '@datagrok-libraries/gridext/src/pinned/PinnedUtils';

//tags: app
//name: Demo Pinned Columns
export async function demoPinnedColumns() {
 
  const dframe : DG.DataFrame = grok.data.demo.randomWalk(100, 500);
  const view : DG.TableView = grok.shell.addTableView(dframe);
  view.grid.setOptions({
    colHeaderHeight: 30,
    rowHeight: 25
  });

  grok.events.onContextMenu.subscribe((args) => {
    PinnedUtils.handleContextMenu(args, (menu : DG.Menu, colGridOrPinned : DG.GridColumn | PinnedColumn, grid : DG.Grid) => {

      if(colGridOrPinned instanceof PinnedColumn) {
        const colGrid = colGridOrPinned.getGridColumn();
        if(colGrid !== null && !GridUtils.isRowHeader(colGrid)) {
        menu.item("Unpin Column", () => {
          colGridOrPinned.close();
        });
      }
          menu.item("Unpin All Columns", () => {
          PinnedUtils.closeAllPinnedColumns(grid);
        });
      }
      else {
        menu.item("Pin Column", async() => {
          PinnedUtils.addPinnedColumn(colGridOrPinned);
        });
      }
    });
  });
}

**Comment by skalkin** [comment]
Thanks, @dgosi ! I think it would make sense to move the implementation to the [PowerGrid ](https://github.com/datagrok-ai/public/tree/master/packages/PowerGrid)package; let's discuss it in person.

**Comment by skalkin** [comment]
Implemented as part of the PowerPack package.
