### ISSUE TITLE
Filters turned off status is not saved in layout

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#953]
1.5.1
**Steps to reproduce:**
1. Open a table (e.g. use SPGI dataset)
2. Open filters panel
3. Enable some filtering
4. Turn off either one individual filter or turn off all filters
<img width="206" alt="image" src="https://user-images.githubusercontent.com/15780643/184603664-a82a517b-bf65-4b91-bebf-72ca31d03ee2.png"><img width="220" alt="image" src="https://user-images.githubusercontent.com/15780643/184603708-ff2e9a62-12c5-40d8-b967-ff608ff5183f.png">
5. Save layout
6. Re-apply saved layout

**Expected results:** Filters turned off status is saved for a single filter and for all filters.
**Actual results:** All filters are on after re-applying saved layout.

**Comment by skalkin** [comment]
Fixed in Datagrok v 1.6.7

**Comment by katerina-stepanova** [comment]
@skalkin v 1.6.11 has new issues with filters saved in disabled state.

**1. All filters disabled > cannot be re-enabled after applying saved layout**
Steps:
1. Open a table
2. Open filters, apply some filtering
3. Turn off all filters
4. Save layout
5. Re-apply saved layout
6. Try to re-enable filters

Expected: it should be possible to toggle filters on/off after re-applying saved layout.
Actual: Filters cannot be turned back on: clicking checkbox does nothing.

**2. Single filter disabled: inconsistent checkbox state after re-applying saved layout**
Steps:
1. Open a table
2. Open filters, apply some filtering
3. Turn off single filter
4. Save layout
5. Re-apply saved layout
6. Check disabled filter state

Expected: filter is disabled, on/off checkbox is unchecked.
Actual: filter is disabled, on/off checkbox is checked.

**Comment by katerina-stepanova** [comment]
Reopening because of issues described above.

**Comment by dionissqq** [comment]
fixed in v1.6.12
