### ISSUE TITLE
#96: Core: input focus loses in train model

### ISSUE THREAD

**Issue by vdyma** [datagrok-ai/public#96]
When trying to change string/numeric input value in _ML -> Train model..._ after opening a feature selection menu, focus is lost and the value is not changed. It happens only once exactly after using the feature selection menu, trying to change the value again works as expected.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14755

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16016
