### ISSUE TITLE
Trellis plot cannot be added

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#964]
DG 1.5.1
**Steps to reproduce:**
1. Open a table, e.g. SPGI
2. Add Trellis plot

**Expected results:** Trellis plot viewer is added.
**Actual results:** Trellis plot viewer is not added.
Error:
`after: CmdTrellisPlot
js_primitives.dart:30 error: NoSuchMethodError: method not found: 'gU' (true.gU is not a function)
js_primitives.dart:30 stackTrace: packages/ddt/src/collections/observable_map.dart 27:33                 MP.h2
packages/d4/src/trellis_plot/trellis_plot_core.dart 227:5              MP.agS
packages/d4/src/trellis_plot/trellis_plot_core.dart 132:5              MP.dm
packages/d4/src/trellis_plot/trellis_plot_core.dart 117:5              MP.f5
packages/d4/src/viewer_base/data_frame_viewer.dart 66:9                MP.sai
packages/d4/src/common/viewer_descriptor.dart 61:5                     cQc.am4
packages/xamgle/src/commands/viewer_commands.dart 31:22                dQo.
packages/d4/src/command.dart 192:13                                    <fn>
packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 213:19     dQx.a
packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 237:5      dQx.
packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 187:19     dbF.
packages/$sdk/lib/async/zone.dart 1128:37                              aVb
packages/$sdk/lib/async/zone.dart 1012:12                              d1v.zw
packages/$sdk/lib/async/future_impl.dart 129:12                        d4V.
packages/$sdk/lib/async/future_impl.dart 665:13                        Object.xk
packages/$sdk/lib/async/future_impl.dart 343:9                         d4M.
packages/$sdk/lib/async/zone.dart 1120:12                              aV9
packages/$sdk/lib/async/zone.dart 1001:12                              d1v.fn
packages/$sdk/lib/async/zone.dart 901:14                               d1v.GE
packages/$sdk/lib/async/zone.dart 926:20                               d1w.
packages/$sdk/lib/async/schedule_microtask.dart 41:5                   Object.dNq
packages/$sdk/lib/async/schedule_microtask.dart 50:5                   fNs
packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 51:9       d0h.
packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:48      fpx.
packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 474:16  NC.KC
packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 59:16   Object.FI
packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:14      fpv
packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2476:14      MutationObserver.<fn>`

**Comment by skalkin** [comment]
Fixed in Datagrok v1.6
