### ISSUE TITLE
Deleted column filter should not be filtered on

### ISSUE THREAD

**Issue by JianmeiFan** [datagrok-ai/public#966]
Steps to reproduce: 

1. Open a filter panel 2. Filtered on two columns 3. Delete one of the column from the filter panel

Expected results: 

Filter panel and table should only be filtered by current column filter; when we bring back pervious column again, it should be reset to non-filter stage.

Actual results: 

Filter panel question mark still show 2 column filters
Table is still filtered by both columns
When I bring back the previously deleted column, it isn't totally reset to non-filter stage.  

https://user-images.githubusercontent.com/100243033/185195332-14209b77-2e35-451a-83a8-d6816d9a1d90.mp4

![filter1](https://user-images.githubusercontent.com/100243033/185195354-27527a5e-3065-4227-84c6-60d9185cc515.jpg)
![filter2](https://user-images.githubusercontent.com/100243033/185195380-b8eb2560-3291-434c-9f83-c90e78a17d06.jpg)

**Comment by skalkin** [comment]
Fixed in Datagrok v1.6.7
