### ISSUE TITLE
Sorting grid column 3 times

### ISSUE THREAD

**Issue by dgosi** [datagrok-ai/public#971]
Three consecutive double clicks on a column's header produce 3 different results. Is this the expected behavior? Looks like Ascending, Descending orders first and second and then the column's values are scattered randomly on the third click. Does it mean they are returned to the original order?

**Comment by skalkin** [comment]
Yes. Ascending, then descending, then original. The current sorting order is indicated by an up/down arrow next to the column name, no arrow means original order.

**Comment by dgosi** [comment]
Thank you for the clarification! To set the original row order one should call grid.setRowOrder([0,1,2,3,...])?
Also will it be possible to potentially add an method to Grid to check if a column is currently sorted or has the original order? For example isSorted(bAscending : boolean) or isOriginalRowOrder() or getRowOrder() ?
