### ISSUE TITLE
Filter is unexpectedly reset when column used in histogram is changed, if PC plot is also present

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#972]
1.5.1

**Steps to reproduce:**
1. Open a table, e.g. SPGI
2. Add Histogram and PC plot viewers
3. Open filters panel and enable some filtering
6. Change column selected in histogram

**Expected results:** changing histogram configuration should not affect currently set filters.
**Actual results:** filtering is un-applied when histogram column is changed:
![2022-08-19_14-51-03 (1)](https://user-images.githubusercontent.com/15780643/185612565-ba036e3a-7149-4883-9fc2-d62b74e270ec.gif)
Issue can be reproduced for all kind of filters, including structure filters.

**Comment by skalkin** [comment]
Good catch! Fixed in Datagrok v1.6.2
