### ISSUE TITLE
#98: Core: Dataframe view

### ISSUE THREAD

**Issue by ghost** [datagrok-ai/public#98]
Implement a way to create view of DataFrame. 
View creation function should accept BitSet / list of row indices along with list of column id's.

```javascript
df = DG.FromJson({'a': [1, 2, 3, 4], 'b': [5,6,7,8]})
indices = [0,2,3] 
cols = ['b']
v = df.view(indices ,cols )

v => 'b'
         5
         7
         8
```

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14756
