### ISSUE TITLE
Tooltip for a cell with truncated value is not shown if only 1 character is partly hidden

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#989]
**Steps to reproduce:**
1. Open a table, e.g. SPGI
2. Reduce some column width, so that first or last character of some cell value is partly hidden
3. Hover such cell

**Expected results:** cell value in the tooltip should be shown when one of the characters is partly hidden.
**Actual results:** cell value in the tooltip is not shown if only one character is hidden partly.
It can be unclear what character is partly hidden, for example is it '3' or '8':
<img width="494" alt="image" src="https://user-images.githubusercontent.com/15780643/187177347-9b8746ef-3e96-4885-8aca-cd220940d1f7.png">

**Comment by skalkin** [comment]
Fixed in v1.6.5
