### ISSUE TITLE
Chem: malformed molString 

### ISSUE THREAD

**Issue by iFeofilaktov** [datagrok-ai/public#99]
![сруь](https://user-images.githubusercontent.com/89513337/131456035-826b2be8-eb10-47a4-b452-bb92993ff27e.PNG)

chem_error throws error: malformed molString for arguments that are seemingly good  

`
  Mrv1902 02241904102D          

 11 10  0  0  0  0            999 V2000
    0.9818    0.5834    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
    0.9818   -0.5834    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
    0.3984    0.0000    0.0000 Pt  0  0  0  0  0  0  0  0  0  0  0  0
    0.0286    1.3803    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9818   -0.3699    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9818    0.3698    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0285   -1.3803    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.1849   -0.5834    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3984   -1.3803    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.1849    0.5834    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9818    0.7969    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
  3  1  1  0  0  0  0
  3  2  1  0  0  0  0
  3  8  1  0  0  0  0
  3 10  1  0  0  0  0
 10  6  1  0  0  0  0
 10  4  1  0  0  0  0
  8  5  1  0  0  0  0
  8  7  1  0  0  0  0
  8  9  1  0  0  0  0
 10 11  1  0  0  0  0
M  END
`

**Comment by skalkin** [comment]
MarvinJS also complains about that molfile, not sure what's wrong with it
https://marvinjs-demo.chemaxon.com/latest/editorws.html

**Comment by ptosco** [comment]
The problem with that molblock are the single bonds between the `NH3` groups and the `Pt` atom. Those are not covalent bonds, but coordination bonds, where the nitrogen shares its lone pair with one of the empty _d_ orbitals of platinum. An `NH3` group cannot be covalently bonded to another atom without bearing a positive charge, as that exceeds its valence.

```
from rdkit import Chem

molblock = """
  Mrv1902 02241904102D

 11 10  0  0  0  0            999 V2000
    0.9818    0.5834    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
    0.9818   -0.5834    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
    0.3984    0.0000    0.0000 Pt  0  0  0  0  0  0  0  0  0  0  0  0
    0.0286    1.3803    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9818   -0.3699    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9818    0.3698    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0285   -1.3803    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.1849   -0.5834    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3984   -1.3803    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.1849    0.5834    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9818    0.7969    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
  3  1  1  0  0  0  0
  3  2  1  0  0  0  0
  3  8  1  0  0  0  0
  3 10  1  0  0  0  0
 10  6  1  0  0  0  0
 10  4  1  0  0  0  0
  8  5  1  0  0  0  0
  8  7  1  0  0  0  0
  8  9  1  0  0  0  0
 10 11  1  0  0  0  0
M  END
"""

mol = Chem.MolFromMolBlock(molblock, removeHs=False)
RDKit ERROR: [17:43:40] Explicit valence for atom # 7 N, 4, is greater than permitted
```

Also MarvinJS flags the chemical inconsistency with a red circle:
![image](https://user-images.githubusercontent.com/5244385/132374613-8900b918-12f0-47c7-9200-f6ef3700eb76.png)

The molblock can be fixed either by removing the two single bonds between `Pt` and `NH3`, or by making them `any` bonds (type 8 according to the MDL specs):

```

  Mrv1902 02241904102D

 11 10  0  0  0  0            999 V2000
    0.9818    0.5834    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
    0.9818   -0.5834    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
    0.3984    0.0000    0.0000 Pt  0  0  0  0  0  0  0  0  0  0  0  0
    0.0286    1.3803    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9818   -0.3699    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9818    0.3698    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0285   -1.3803    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.1849   -0.5834    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3984   -1.3803    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.1849    0.5834    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9818    0.7969    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
  3  1  1  0  0  0  0
  3  2  1  0  0  0  0
  3  8  8  0  0  0  0
  3 10  8  0  0  0  0
 10  6  1  0  0  0  0
 10  4  1  0  0  0  0
  8  5  1  0  0  0  0
  8  7  1  0  0  0  0
  8  9  1  0  0  0  0
 10 11  1  0  0  0  0
M  END
```

Both MarvinJS
![image](https://user-images.githubusercontent.com/5244385/132375883-df882fb1-6b35-4510-8762-8b4cb8ff9372.png)

and RDKit
![image](https://user-images.githubusercontent.com/5244385/132375936-70287282-b742-4627-a947-560328f57e0b.png)

will then visualize it correctly without complaining.

**Comment by dskatov** [comment]
@ptosco thank you for a thorough answer!
@StLeonidas @iFeofilaktov @skalkin do you think we need to apply a lightweight fix-on-the-fly for these cases to incoming MolBlocks? I assumed this comes from a public data-source and glitches like that may occur in the future.

**Comment by StLeonidas** [comment]
It is a quite common issue in public datasets, we have an implementation in Chem : Curate to deal with such cases. So there are two possible solutions:
- insist on dataset curation with Chem : Curate before further actions;
- implement fix-on-the-fly, but in this case, should we notify that the dataset was modified?

**Comment by iFeofilaktov** [comment]
I could implement fix-on-the-fly solution.
